### ISSUE TITLE
Couldn't get data from POST

### ISSUE THREAD

**Issue by misterbell4020** [chriskacerguis/codeigniter-restserver#1000]
I used CodeIgniter 3.1.10. Tried to create rest api service with post method. But the post method returns null only.

```
public function users_post(){
$data = array(
            'FIRST_NAME' => $this->post('FIRST_NAME'),
            'LAST_NAME' => $this->post('LAST_NAME'),
);
}
```
![image](https://user-images.githubusercontent.com/50691094/59736204-46046480-9276-11e9-9b36-4c895f7bf694.png)

**Comment by sierrafayad** [comment]
Hey, you are sending the data as GET parameter, the new postman its a little misleading. with the name of that tab "Params" (You can totally send GET params on the URI on a post request).
Any way if you want to send them as POST you should use the "Body" tab.

**Comment by misterbell4020** [comment]
Yes, Its works, Thank you.

**Comment by misterbell4020** [comment]
May I know, why the postman doesn't support for DELETE?

**Comment by sierrafayad** [comment]
Though it is not recommended to have a request body with DELETE, it is not forbidden.

**Comment by impactcolor** [comment]
To get Body from postman (body as indicated in the tab with form-data) I use:
`$this->post('FIRST_NAME'),`
To get parameter as you are indicating here I use:
`$this->input->get('FIRST_NAME')`
