### ISSUE TITLE
Why have different among installation way?

### ISSUE THREAD

**Issue by trantuanngoctn97** [chriskacerguis/codeigniter-restserver#1003]
I don't know the right way to installing this package. Follow the documentation, i use `composer require chriskacerguis/codeigniter-restserver` and then, i coppy some file from `vendor/chriskacerguis/codeigniter-restserver/application`  like `rest.php, Example.php, REST_Controller.php, Format.php,...` in respectively directory in my project. But when i use it, the function `$this->response()` not work prefectly. 

```
public function apiMiddleware() {

    return $this->response(['message' => 'Unauthorized Access'], MY_Controller::HTTP_UNAUTHORIZED);

    return $this->response(['message' => 'No user was found.'], MY_Controller::HTTP_NOT_FOUND);
}
```

Response should be {"message": "Unauthorized Access"} but {"message": "No user was found."} is displayed.

Take a long time for searching, i see my `$this->response()` function don't have three paramater  `@param bool $continue TRUE to flush the response to the client and continue running the script; otherwise, exit.`

Oh gosh. i added it and it work. 

So. Can you tell me the right way to installing this package and why have different among installation way or different between `REST_Controller.php` in repository and in vendor directory when i use composer?

This is REST_Controller i use from `vendor/chriskacerguis/codeigniter-restserver/application`. Its write `abstract class REST_Controller extends \CI_Controller`
![image](https://user-images.githubusercontent.com/33822205/60704689-592e5a00-9f2f-11e9-9171-3ebd4d7cfe1c.png)

But this is REST_Controller i use from repository. Its just write `trait REST_Controller {`
![image](https://user-images.githubusercontent.com/33822205/60704734-77945580-9f2f-11e9-9c5f-35ffdbb1be59.png)

Thank you so much.

**Comment by klynicol** [comment]
I have similar issues. Installation is a bit funky right now it seems.

**Comment by searchy2** [comment]
The installation is definitely "funky" as directly taking the code from this repository or Composer doesn't work. 

I'll diff the file I use and comment with the changes as the default configuration causes CORS errors. 
Maybe there'd be a way to standardize it so contributing and using this library is a bit easier.

**Comment by chriskacerguis** [comment]
The Composer code should now be working.  Please take a look at the latest code and let me know.
