### ISSUE TITLE
Error REST_Controller library import

### ISSUE THREAD

**Issue by danielveraec** [chriskacerguis/codeigniter-restserver#1005]
I followed the instructions on the github page but I have problems importing the library. I presume it's because it's been updated and changed the way it's implemented.

The difference I see is that it's no longer a class but a trait and maybe this changes the way it should be integrated, but I haven't found the way.
![Capture1](https://user-images.githubusercontent.com/8257504/61429682-da50fe00-a8ec-11e9-952a-c7ea272498a0.PNG)

The error is as follows:
![Capture2](https://user-images.githubusercontent.com/8257504/61429700-e3da6600-a8ec-11e9-8b32-1c9ce9e2380f.PNG)

I have tried to follow the instructions of the site where I downloaded it: https://github.com/chriskacerguis/codeigniter-restserver#handling-requests

However, I could not solve the problem.

I have the code of the controller as follows:
![Capture3](https://user-images.githubusercontent.com/8257504/61429719-f3f24580-a8ec-11e9-945a-b5e73ecd5d6e.PNG)

I am very grateful to anyone who can help me.

Greetings,

Daniel Vera

**Comment by hyyoxhk** [comment]
yes, I have the same problem.

**Comment by rps-repo** [comment]
Same problem, examples are not updated so can't figure out how to use this library.

**Comment by hammadrahman** [comment]
Have you resolved this issue?
I am getting the same error. Please help me.

**Comment by chriskacerguis** [comment]
Try using the 4.0 RC

https://github.com/chriskacerguis/ci-restserver
