### ISSUE TITLE
problem with response (). Does not grant an appropriate JSON response

### ISSUE THREAD

**Issue by JorgeMartinSalasAlvarez** [chriskacerguis/codeigniter-restserver#1007]
the following code:

     public function users_get()
     {
         $users = [
             ['id' => 1, 'name' => 'John', 'email' => 'john@example.com', 'fact' => 'Loves coding'],
             ['id' => 2, 'name' => 'Jim', 'email' => 'jim@example.com', 'fact' => 'Developed on CodeIgniter'],
             ['id' => 3, 'name' => 'Jane', 'email' => 'jane@example.com', 'fact' => 'Lives in the USA',
             	['hobbies' => ['guitar', 'cycling']]],];
            $this->response($users); }

provides this output, is it correct?
{
    "0": {
        "hobbies": [
            "guitar",
            "cycling"
        ]
    },
    "id": 3,
    "name": "Jane",
    "email": "jane@example.com",
    "fact": "Lives in the USA"
}

**Comment by chriskacerguis** [comment]
It doesn't appear to be correct, but I don't have enough info to really help.

**Comment by chriskacerguis** [comment]
no response.  Closing stale
