### ISSUE TITLE
Problem with composer install update 

### ISSUE THREAD

**Issue by thecassion** [chriskacerguis/codeigniter-restserver#1008]
I try to make composer install over this library but I can't find the version that We say in the documentation . 
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/12730875/61653278-f0154900-ac87-11e9-9bc1-8bf54e0adf60.png">

**Comment by thecassion** [comment]
My problem is because we put a requirement in  the composer.json saying that codeigniter version must be > 3.0.4 . I use the latest version of codeigniter3 but I didn't install it via composer . How can I solve this  problem?

**Comment by chriskacerguis** [comment]
Try using the 4.0 RC

https://github.com/chriskacerguis/ci-restserver
