### ISSUE TITLE
Not go along with some Auto loaded Libraries

### ISSUE THREAD

**Issue by kelaskakap** [chriskacerguis/codeigniter-restserver#1009]
Hi,

I've some auto loaded libraries in my config/autoload.php
$autoload['packages'] = array(APPPATH.'third_party/ion_auth');
$autoload['libraries'] = array('form_validation', 'ion_auth', 'template', 'common/mobile_detect');

And this is my Controller:

`<?php`

`defined('BASEPATH') OR exit('No direct script access allowed');`

`require APPPATH . 'libraries/REST_Controller_Definitions.php';`
`require APPPATH . 'libraries/REST_Controller.php';`
`require APPPATH . 'libraries/Format.php';`

`use Restserver\Libraries\REST_Controller;`

`class Coba extends CI_Controller {`

   ` use REST_Controller {`
       ` REST_Controller::__construct as private __resTraitConstruct;`
   ` }`

    `public function __construct() {`

     `   parent::__construct();`
        `$this->__resTraitConstruct();`
   ` }`

    `public function index() {`

        `$this->response(['status' => 'ok']);`
   ` }`

`}`

I opened with my browser http://localhost/coba    
And got this response    
Unable to locate the specified class: Ion_auth.php    
I think it got failed when trying parent::__construct()    
I don't want to remove Ion_auth from autoload.php because it's mandatory for my project.    
Does anyone know? please help me,
Thank you.

**Comment by manukieli** [comment]
I have the same issue.
In into the file config->autoload, I load some libraries and the REST_Controller.php to line 263: parent::__construct(); try to load this libraries and not found it and return this error:

> An uncaught Exception was encountered
Type: Error

Message: Class 'CI_Template' not found

Filename: /home/proyecto/system/core/Common.php

Line Number: 196

Backtrace:

File: /home/proyecto/application/libraries/REST_Controller.php
Line: 263
Function: __construct

File: /home/proyecto/application/controllers/api/Loginapp.php
Line: 17
Function: __resTraitConstruct

File: /home/proyecto/index.php
Line: 315
Function: require_once

**Comment by manukieli** [comment]
I've resolve it temporary with this code into the file config->autloload.php
I replace this line:
` $autoload['libraries'] = array('database');`

With this
`if ($_SERVER['REQUEST_URI'] === '/api/loginapp') {
    $autoload['libraries'] = array('database');
} else {
    $autoload['libraries'] = array('template', 'database', 'session');
}`

Where the condition detect from which URL is doing the request.

**Comment by chriskacerguis** [comment]
Try using the 4.0 RC

https://github.com/chriskacerguis/ci-restserver
