### ISSUE TITLE
Use Auth with database instead of array

### ISSUE THREAD

**Issue by free-developers** [chriskacerguis/codeigniter-restserver#1010]
Hi
I try use Auth in this library with config rest_auth = true and allow_auth_and_keys = true and rest_valid_logins is ['admin' => '1234']
But i need to connect to database and check username and password not this array
Also i use below config
auth_library_class
auth_library_method

but in any way,this library use rest_valid_logins for validation

**Comment by chriskacerguis** [comment]
I'm sorry, I'm not understanding.
