### ISSUE TITLE
Auto loading libraries is broken

### ISSUE THREAD

**Issue by rps-repo** [chriskacerguis/codeigniter-restserver#1017]
auto loading some CI libraries causes an error like:

Unable to locate the specified class: Session.php

It also happens on all user created libraries that I have tried.

**Comment by otengkwame** [comment]
I had the same issue, but I fixed it by removing this line from the REST_Controller class 
```php
public function __construct($config = 'rest')
    {
        parent::__construct();  //Remove or comment this line

        $this->preflight_checks();
}
?>
```
The truth is the trait is not extending a class and so it does not need any parent __construct();
I hope this helps anybody facing the same issue

**Comment by chriskacerguis** [comment]
Try using the 4.0 RC

https://github.com/chriskacerguis/ci-restserver
