### ISSUE TITLE
Undefined class constant 'HTTP_OK'

### ISSUE THREAD

**Issue by harshadaR95** [chriskacerguis/codeigniter-restserver#1018]
An uncaught Exception was encountered
Type: Error

Message: Undefined class constant 'HTTP_OK'

Filename: C:\xampp\htdocs\atozpay\application\controllers\api\Example.php

Line Number: 56

Backtrace:

File: C:\xampp\htdocs\atozpay\application\libraries\REST_Controller.php
Line: 653
Function: call_user_func_array

File: C:\xampp\htdocs\atozpay\index.php
Line: 315
Function: require_once

i

**Comment by chriskacerguis** [comment]
This no longer should be an issue in the latest release.  If you are still having issues (once updated to the latest code), can you please open a new issue?
