### ISSUE TITLE
Example Api Usage 

### ISSUE THREAD

**Issue by hussainkhan** [chriskacerguis/codeigniter-restserver#1020]
Though Documentation is well written, but there is need to have more details about installation & to use given example Api.

After composer installation i m not getting which url needs to be called to use example api, or there are some more changes required.

I tried this way http://localhost/demoprojs/ci-rest-server/index.php/api/users
to get list of users but not getting

Thanks

**Comment by luckydonald** [comment]
You have to use the standard routing of codeigniter as usually here.
https://codeigniter.com/user_guide/general/routing.html

The only thing different is that you would use `index` in your URL while the function in your class would be `function index_get(...)`, `index_post`, etc.

**Comment by hussainkhan** [comment]
Thanks
