### ISSUE TITLE
Request Body JSON not getting $this->post('valiable');

### ISSUE THREAD

**Issue by harshalone** [chriskacerguis/codeigniter-restserver#1021]
Hi I am sending json from my request body like this:

```
{
  "groupuid": "USDFSD243",
  "group_host_id": "1234",
  "group_title": "example",
  "group_description": "example"
}
```

but when I request in my controller I can't see any of these values
ex:
$this->post(group_host_id);

shows null

**Comment by impactcolor** [comment]
This works for me: $this->post('group_host_id');
Apostrophe on the name.

**Comment by chriskacerguis** [comment]
what @impactcolor said; you need the quotes.
