### ISSUE TITLE
Unable to implement load trait in API controller.

### ISSUE THREAD

**Issue by hammadrahman** [chriskacerguis/codeigniter-restserver#1025]
I am having problem, in loading the trait REST_Controller. It is saying that class REST_Controller not found.

**Comment by jfrsbg** [comment]
same issue here, i had installed the library with composer, has set $config['composer_autoload'] = FCPATH .'vendor/autoload.php'; and the error still remains. I search across the issues here on github, followed some them but no solution solve my problem. I'm getting "Trait 'REST_Controller' not found in <folder path>" message in my controller class. I followed the docummentation implementing:

`class Books extends CI_Controller
{
   use REST_Controller {
    REST_Controller::__construct as private __resTraitConstruct;
  }
}`

but nothing works

**Comment by jfrsbg** [comment]
same issue here, i had installed the library with composer, has set $config['composer_autoload'] = FCPATH .'vendor/autoload.php'; and the error still remains. I search across the issues here on github, followed some them but no solution solve my problem. I'm getting "Trait 'REST_Controller' not found in " message in my controller class. I followed the docummentation implementing:

class Books extends CI_Controller
{
    use REST_Controller {
    REST_Controller::__construct as private __resTraitConstruct;
  }
}

but nothing works

**Comment by ziaahsan** [comment]
Looking at your code you might be missing some things. Try the following:
```
<?php
/** Importing from namespace 'RestServer\Libraries' **/
use RestServer\Libraries\REST_Controller;

defined('BASEPATH') OR exit('No direct script access allowed');

// Required Libs
require APPPATH . 'libraries/REST_Controller.php';
require APPPATH . 'libraries/Format.php';

/** Books CI **/
class Books extends CI_Controller {
    // REST CI
    use REST_Controller {
        REST_Controller::__construct as private __resTraitConstruct;
    }

    // Constructor
    public function __construct() {
        $this->__resTraitConstruct();
    }
}
```

That should be able to get rid of the problem "REST_Controller not found.". However I have noticed when I set the session in config it causes an issue with "Session.php" file not found. However there is a way around it, but for now hope this helps.

**Comment by jfrsbg** [comment]
@ziaahsan this dont solve the problem because now the REST_Controller are in composer, so, when i load:
require APPPATH . 'libraries/REST_Controller.php';
require APPPATH . 'libraries/Format.php';

i will receive the message that libraries/REST_Controller.php was not found and thats ok because i dont have nothing in libraries directory. So, following the documentation should be the correct way. I can use the namespace but cant require the file with APPPATH and idk how to require in vendor, because the file is there. I`m using an old version of this library that dont implement "trait". If you have any suggestions it will be helpful

**Comment by chriskacerguis** [comment]
This no longer should be an issue in the latest release.  If you are still having issues (once updated to the latest code), can you please open a new issue?
