### ISSUE TITLE
How to get User ID from my key table

### ISSUE THREAD

**Issue by harshalone** [chriskacerguis/codeigniter-restserver#1028]
Hi I was just wondering if there is  a easy way to get user id from my keys table after authenticating.

I understand that I can write a function where I compare the key and get the relevant userid

But as the REST server is already authenticating my KEY with table I am guessing the query is already made. So why to query database twice for the same reason.

if there is a small change in the library or tweak I can use to get userid it will be really helpful

keys table:

 id | user_id |                   key                                                        |  
  1 |       1     | k0wk8g8gg0skocw88o8ok888skws0o08skgss8g8 |   
 
Looking forward to hear from authors: @CaddyDz  and @chriskacerguis

**Comment by JhonGdl** [comment]
using 

$this->_apiuser

**Comment by harshalone** [comment]
@JhonGdl   I tried it but its saying function is not defined? any idea

**Comment by harshalone** [comment]
solved: $this->_apiuser->user_id

**Comment by luckydonald** [comment]
@harshalone Thank you for reporting back your solution.
If you got it working with the above, please mark the issue as resolved by clicking the `Close issue` button then.

**Comment by harshalone** [comment]
thanks
