### ISSUE TITLE
Help Installation failed

### ISSUE THREAD

**Issue by WenHou** [chriskacerguis/codeigniter-restserver#1029]
PHP7.2.9
CI 3.1.10
 composer require chriskacerguis/codeigniter-restserver:dev-master
It`s failed

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for codeigniter/framework No version set (parsed as 1.0.0) -> satisfiable by codeigniter/framework[No version set (parsed as 1.0.0)].
    - chriskacerguis/codeigniter-restserver dev-master requires codeigniter/framework ^3.1.10 -> satisfiable by codeigniter/framework[3.1.10, 3.1.11].
    - Can only install one of: codeigniter/framework[3.1.10, No version set (parsed as 1.0.0)].
    - Can only install one of: codeigniter/framework[3.1.11, No version set (parsed as 1.0.0)].
    - Installation request for chriskacerguis/codeigniter-restserver dev-master -> satisfiable by chriskacerguis/codeigniter-restserver[dev-master].

Installation failed, reverting ./composer.json to its original content

**Comment by chriskacerguis** [comment]
Try using the 4.0 RC

https://github.com/chriskacerguis/ci-restserver
