### ISSUE TITLE
Getting Error Class 'Restserver\Libraries\Format' not found

### ISSUE THREAD

**Issue by sourabhchotia** [chriskacerguis/codeigniter-restserver#1030]
My Controller File is This

`<?php

// namespace Restserver\Libraries;
// use Restserver\Libraries\REST_Controller;

defined('BASEPATH') OR exit('No direct script access allowed');

use Restserver\Libraries\REST_Controller;
require(APPPATH . 'libraries/REST_Controller.php');
class Example extends CI_Controller {

    use REST_Controller {
        REST_Controller::__construct as private __resTraitConstruct;
    }

    function __construct()
    {
        // Construct the parent class
        parent::__construct();
        $this->__resTraitConstruct();

        // Configure limits on our controller methods
        // Ensure you have created the 'limits' table and enabled 'limits' within application/config/rest.php
        $this->methods['users_get']['limit'] = 500; // 500 requests per hour per user/key
        $this->methods['users_post']['limit'] = 100; // 100 requests per hour per user/key
        $this->methods['users_delete']['limit'] = 50; // 50 requests per hour per user/key
    }`

And Rest_Controller File is 

`namespace Restserver\Libraries;
use CI_Controller;
use Exception;
use stdClass;
require APPPATH . 'libraries/Format.php';

defined('BASEPATH') OR exit('No direct script access allowed');

/**
 * CodeIgniter Rest Controller
 * A fully RESTful server implementation for CodeIgniter using one library, one config file and one controller.
 *
 * @package         CodeIgniter
 * @subpackage      Libraries
 * @category        Libraries
 * @author          Phil Sturgeon, Chris Kacerguis
 * @license         MIT
 * @link            https://github.com/chriskacerguis/codeigniter-restserver
 * @version         3.0.0
 */
require APPPATH . 'libraries/REST_Controller_Definitions.php';

trait REST_Controller {`

Please Help

**Comment by chriskacerguis** [comment]
Try using the 4.0 RC

https://github.com/chriskacerguis/ci-restserver

**Comment by melintc** [comment]
page not found

**Comment by QaziAmmar** [comment]
To resolve this Format error you just need to add this line of code into your custom Controller 

require APPPATH.'libraries/Format.php';
![Screenshot 2021-09-07 at 10 40 44 AM](https://user-images.githubusercontent.com/18580340/132290318-c6824b42-81ec-43f4-9b7b-6d948851a96d.png)
