### ISSUE TITLE
Version 3.1 doesn't read user defined rest.php

### ISSUE THREAD

**Issue by nerdv2** [chriskacerguis/codeigniter-restserver#1032]
After updating to the latest build, the rest.php file in the config folder now doesn't work as intended.

The library only read the one in composer vendor folder.

**Comment by chriskacerguis** [comment]
So, the rest.php in the lib takes precedence, but it should be the other way around.  Could you rename that file to rest-test.php and let me know if it "reads" the correct one?  If that works, I'll do a patch.
