### ISSUE TITLE
Codeigniter Restserver Dynamic API Key Config

### ISSUE THREAD

**Issue by harshalone** [chriskacerguis/codeigniter-restserver#1039]
Hi I am using Codeigniter Restserver,
I have few API's where I have to authenticate them with API's keys and Sessions. But I have few open API's which could be accessible by anyone without any authentication.
How can I dynamically set the API key setting with Codeigniter Rest-server Library

**Comment by chriskacerguis** [comment]
Which API key are you referring to?  The settings are just config vars, so I would imagine that you can just change the config setting.
