### ISSUE TITLE
Running example not Working

### ISSUE THREAD

**Issue by AdeSupriyadi** [chriskacerguis/codeigniter-restserver#1040]
I was follow the installation doc:

1. install via composser: 
composer require chriskacerguis/codeigniter-restserver

2. Create Api controller just rename from Example.php to application/controllers/Api.php
![image](https://user-images.githubusercontent.com/14267724/68987984-d4e7ce00-0862-11ea-9844-05d624ecb783.png)

3. try access get api/users via Postman, but response
Message: Class 'REST_Controller' not found
![image](https://user-images.githubusercontent.com/14267724/68988009-2ee89380-0863-11ea-86e1-5fc0707ad886.png)

There is no other instruction in doc instead install via composser,

how to get it work?

**Comment by kushanz** [comment]
try followings

`require FCPATH . 'vendor/autoload.php';
use chriskacerguis\RestServer\RestController;`

`class Api_Controller extends RestController {
    function __construct() {
        parent::__construct();
    }
//do api functions here
}`

**Comment by Weax** [comment]
change REST_Controller to RestController

**Comment by IcarusHU** [comment]
I've got "The configuration file rest.php does not exist."
autoloading is working (having different libraries also)

use chriskacerguis\RestServer\RestController;

class Api_Controller extends RESTController

index.php is in /public folder, composer.json is in docroot, vendor lib is in /vendor

**Comment by chriskacerguis** [comment]
Sorry, the example should be fixed now.  See https://github.com/chriskacerguis/codeigniter-restserver/pull/1046
