### ISSUE TITLE
Getting error for $this->http_status['METHOD_NOT_ALLOWED']

### ISSUE THREAD

**Issue by vasant-hun** [chriskacerguis/codeigniter-restserver#1041]
![image](https://user-images.githubusercontent.com/56741464/68999370-41a3ac80-08e5-11ea-8946-251b87887c7d.png)

**Comment by kushanz** [comment]
this because controller api function method not matched with the request header method.
as example if the function is `users_get()` postman request should be use GET method. otherwise it will gives you above error

**Comment by Weax** [comment]
> this because controller api function method not matched with the request header method.
> as example if the function is `users_get()` postman request should be use GET method. otherwise it will gives you above error

No, it's not working with Postman, gives me the same error
Message: Undefined property: [Your Class Name]::$http_status
Filename: src/RestController.php
Line Number: 542

**Comment by vinando** [comment]
is there anyone here make it works with Post request?
