### ISSUE TITLE
README.md correction

### ISSUE THREAD

**Issue by guilhermeagirardi** [chriskacerguis/codeigniter-restserver#1042]
Hi @chriskacerguis!

I'm just reporting a small error in the example presented in README.md.

In line 6, the class is extending from REST_Controller instead of RestController.

Best Regards,

**Comment by Huji** [comment]
That is correct. However, changing it to RestController would also not fix the problem. I get this error: ` Class 'chriskacerguis\RestServer\RestController' not found`

**Comment by MiguelGonzalezAravena** [comment]
The same issue here...

**Comment by guilhermeagirardi** [comment]
> That is correct. However, changing it to RestController would also not fix the problem. I get this error: ` Class 'chriskacerguis\RestServer\RestController' not found`

@Huji, are you sure you are loading Composer? If it is not loading, the class will not be found.

Check out the value of `$config['composer_autoload']` in application/config/config.php.
