### ISSUE TITLE
auth_override_class_method_http not working with HMVC

### ISSUE THREAD

**Issue by harshalone** [chriskacerguis/codeigniter-restserver#1045]
Hi I have a config setting like below:

`$config['auth_override_class_method_http']['admin']['auth']['post'] = 'none';`

I am using this library for my HMVC: https://bitbucket.org/wiredesignz/codeigniter-modular-extensions-hmvc

But when I checked with error handling on REST_Controller.php

it seems like /admin/auth is not recognised with REST

Although all of my GET/POST requests are working fine as it should be on the endpoint.

Could anyone suggest what I should do in order to get it working i.e., 

I want to use authentication on several API request but not on admin/auth [POST]

**Comment by harshalone** [comment]
@philsturgeon is this something you have faced before?

**Comment by philsturgeon** [comment]
I've not touched a line of CodeIgniter code since 2014 and I don't even mess with PHP anymore. Best of luck!
