### ISSUE TITLE
Doesn't refresh in composer

### ISSUE THREAD

**Issue by IcarusHU** [chriskacerguis/codeigniter-restserver#1051]
Composer doesn't update to 3.1.1

![composer](https://user-images.githubusercontent.com/7024470/69835955-98927580-1245-11ea-90eb-83e7ac798b41.JPG)
![composer-install](https://user-images.githubusercontent.com/7024470/69835956-98927580-1245-11ea-89f5-3f8c6dbc7531.JPG)

**Comment by gravitymedianet** [comment]
Yeah i just downloaded from composer and I got the older version
