### ISSUE TITLE
Use of undefined constant HTTP_METHOD_NOT_ALLOWED - assumed 'HTTP_METHOD_NOT_ALLOWED'

### ISSUE THREAD

**Issue by nplaviola** [chriskacerguis/codeigniter-restserver#1053]
Hi Chris, I am getting the following error when attempting a POST call to my api and I can't figure out what the story is. Any idea?  Below is my full error message:

`<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

	<h4>A PHP Error was encountered</h4>

	<p>Severity: Notice</p>
	<p>Message: Use of undefined constant HTTP_METHOD_NOT_ALLOWED - assumed 'HTTP_METHOD_NOT_ALLOWED'</p>
	<p>Filename: libraries/RestController.php</p>
	<p>Line Number: 543</p>

	<p>Backtrace:</p>

	<p style="margin-left:10px">
		File: /var/www/testing-dev.praevium.net/application/libraries/RestController.php<br />
			Line: 543<br />
			Function: _error_handler			</p>

		<p style="margin-left:10px">
			File: /var/www/testing-dev.praevium.net/htdocs/index.php<br />
			Line: 315<br />
			Function: require_once			</p>

</div>
<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

	<h4>A PHP Error was encountered</h4>

	<p>Severity: Notice</p>
	<p>Message: Use of undefined constant HTTP_OK - assumed 'HTTP_OK'</p>
	<p>Filename: libraries/RestController.php</p>
	<p>Line Number: 660</p>

	<p>Backtrace:</p>

	<p style="margin-left:10px">
		File: /var/www/testing-dev.praevium.net/application/libraries/RestController.php<br />
			Line: 660<br />
			Function: _error_handler			</p>

		<p style="margin-left:10px">
			File: /var/www/testing-dev.praevium.net/application/libraries/RestController.php<br />
			Line: 543<br />
			Function: response			</p>

			<p style="margin-left:10px">
				File: /var/www/testing-dev.praevium.net/htdocs/index.php<br />
			Line: 315<br />
			Function: require_once			</p>

</div>
`

**Comment by jalal** [comment]
This can be avoided by modifying the source code (`libraries/RestController.php`) and changing usage of the constants from `HTTP_OK` to `self::HTTP_OK`. A temporary fix...

**Comment by wandu-ar** [comment]
Solved in #1055 
Wait the update

**Comment by nplaviola** [comment]
Thank you both!
