### ISSUE TITLE
Basic Auth

### ISSUE THREAD

**Issue by rtrujilloatencion** [chriskacerguis/codeigniter-restserver#1054]
Hi, i find an error In the RestController.

In the line 519
```
**$this->response([
                $this->config->item('rest_status_field_name')  => false,
                $this->config->item('rest_message_field_name') => sprintf($this->lang->line('text_rest_invalid_api_key'), $this->rest->key),
            ], HTTP_FORBIDDEN);**
```
The error can be fix change to this

```
**$this->response([
                $this->config->item('rest_status_field_name')  => false,
                $this->config->item('rest_message_field_name') => sprintf($this->lang->line('text_rest_invalid_api_key'), $this->rest->key),
            ], RESTController::HTTP_FORBIDDEN);**
```
That's correct or i have error in implementation?

**Comment by ashvinimarwal** [comment]
I got the same error and later I found that constant declaration was commented due to my sublime auto copyright variables.

**Comment by AlfanMudhofir** [comment]
I change it into this

`            $this->response([
                $this->config->item('rest_status_field_name')  => false,
                $this->config->item('rest_message_field_name') => sprintf($this->lang->line('text_rest_invalid_api_key'), $this->rest->key),
            ], 404);
`
