### ISSUE TITLE
cannot retrieve  value from a DELETE request using  $this->delete('')

### ISSUE THREAD

**Issue by Arunoda1995** [chriskacerguis/codeigniter-restserver#1058]
I'm trying to retrieve value send from delete request using $this->delete('') but it is null. 

Here is my backbone model code:-
     
    var contactModel = Backbone.Model.extend({
                defaults: {
                    contactName: '',
                    contactEmailAddress: '',
                    contactNumber: '',
                    usertags: []

                },
                idAttribute: "contactId",
                urlRoot: "<?php echo base_url(); ?>index.php/Contacts/userContacts",
                initialize: function() {
                    console.log("Inizializing Contact Model");
                }
            });

and when the user clicks the delete button its triggers the "deleteContact" function in backbone view. 

    var contactView = Backbone.View.extend({
                el: '#userContact',
                initialize: function() {

                },
                render: function() {
                    return this;

                },
                events: {
                    "click #deleteContact": 'deleteContact'
                },
                deleteContact: function() {
                    var contactId = $('#contact_id').val();
                    var contact = new contactModel({
                        contactId: contactId
                    });
                    contact.destroy();
                }
            });

and inside the Codeigniter controller method, I'm trying to get contact id using 

$contactId = $this->delete('contactId');

But it returns null. I only have this issue with delete request. I implemented the other request and they work fine.

**Comment by Ayod-A** [comment]
Try json_decode(file_get_contents('php://input'), true);
instead of 
$this->delete();

**Comment by shimbala** [comment]
Same issue. @Ayod-A has solution.

**Comment by rtrujilloatencion** [comment]
I have the same error
