### ISSUE TITLE
First Time Setup Cannot get "Api.php" example working HELP WANTED!

### ISSUE THREAD

**Issue by libanj** [chriskacerguis/codeigniter-restserver#1059]
@chriskacerguis 

Hi, 

I'm wondering if anyone can help me.

This is the first time I'm setting up a RESTful server in my Codeigniter project and I'm having difficulty trying to get the "Api.php" example to work.

<img width="335" alt="Annotation 2019-12-30 172336" src="https://user-images.githubusercontent.com/36715469/71592699-27d2c780-2b29-11ea-89a8-19e7fad786b7.png">

I have placed the "rest.php" file in the config folder (as instructed in the documentation). I placed the "Restcontroller.php" and the "Format.php" files in different locations but I am still getting the same error.

<img width="1080" alt="2019-12-30" src="https://user-images.githubusercontent.com/36715469/71592840-a891c380-2b29-11ea-927d-1dafea6e8b9f.png">

I would like someone to tell me where I'm going wrong with this.

Thank you.

**Comment by libanj** [comment]
I managed to find a fix. I don't know whether this is a permanent fix.

I have put `require FCPATH . 'vendor/autoload.php';` before the `use chriskacerguis\RestServer\RestController;`

**Comment by gravitymedianet** [comment]
You should set the autoload in the config.php file. There is a setting for that.

Line 139
``
$config['composer_autoload'] =  './vendor/autoload.php'; // or wherever it is
``

**Comment by chopperfield** [comment]
This restful CI is very new to me.
I have been struggling it for 1-2 days wondering what went wrong, I did the same step in read.me.

@gravitymedianet this solve the problems, thanks.
