### ISSUE TITLE
Databse Error if $config['rest_enable_keys'] = TRUE; 

### ISSUE THREAD

**Issue by andreaskrisandy** [chriskacerguis/codeigniter-restserver#1062]
Database error if i change a code FALSE to TREU in config/rest.php 
![Database api](https://user-images.githubusercontent.com/29002825/71761576-72c05680-2efe-11ea-83bf-14e266f1c08c.JPG)

**Comment by ChristianBruno** [comment]
Verify that you entered the correct group name for the database.

//line 291 in rest.php
$config['rest_database_group'] = 'default';

**Comment by chriskacerguis** [comment]
This looks to be an issue with your database connection, and nothing with this library.  Going to close this, but if you can provide more information that it shows a bug in the code, please feel free to create a new issue.
