### ISSUE TITLE
Class RestServer not found

### ISSUE THREAD

**Issue by mozikundev** [chriskacerguis/codeigniter-restserver#1064]
I create a new controller like this.
![image](https://user-images.githubusercontent.com/35588124/72414326-885a3980-37a4-11ea-99f1-c77b9985ee1d.png)

And this is what I got.
![image](https://user-images.githubusercontent.com/35588124/72414287-72e50f80-37a4-11ea-87c4-54d9818d4133.png)

**Comment by kgmayani** [comment]
I had same issue, don't mixed up all online examples,

correct your line with this,
require APPPATH . 'libraries/RestController.php';
use chriskacerguis\RestServer\RestController;
require APPPATH . 'libraries/Format.php';
class Api extends RestController

make sure you need to load both files

**Comment by mozikundev** [comment]
Okay got it, thanks
