### ISSUE TITLE
Use of undefined constant HTTP_OK - assumed 'HTTP_OK' (this will throw an Error in a future version of PHP)

### ISSUE THREAD

**Issue by reshaelfianur** [chriskacerguis/codeigniter-restserver#1065]
i change $config['rest_enable_keys'] = true; in src/rest.php 
and i get this error

![Screenshot from 2020-01-23 15-32-26](https://user-images.githubusercontent.com/44496467/72968223-a1429a80-3df5-11ea-9465-7f7edfcbdf16.png)

I used jwt for token authentication but there were no problems there.

if i changing the config file nothing happens, logs and key doesn't working.
im using php version 7.3.1.

![Screenshot from 2020-01-23 15-41-30](https://user-images.githubusercontent.com/44496467/72968805-d7cce500-3df6-11ea-9dd6-4713da17d5fd.png)

in the version that does not use vendor there are no problems

Thanks Sir

**Comment by georgebgr** [comment]
Please use self::HTTP_XXXX in RestController.php.
Chris, could you please merge and upload?

**Comment by IcarusHU** [comment]
He has already uploaded it, only the composer doesn't update to the right version... for months now :|

**Comment by IcarusHU** [comment]
What is pretty annoying, because I have 4 instances in local/dev/stage/master env, so I have to copy this file 16 cases manually on every deployment...

**Comment by joelkennedy** [comment]
@chriskacerguis are you planning to make a release any time soon which will contain this fix?

**Comment by tewfik-dj** [comment]
Thanks for the pointer !

**Comment by nerdv2** [comment]
As a workaround for composer, you could set the value to "dev-master" in composer.json for now until the latest fixes updated to packagist.

**Comment by aderowbotham** [comment]
I get this error after installing this, before making _any_ changes to the config. So basically there's an error out of the box

`Message: Use of undefined constant HTTP_OK - assumed 'HTTP_OK' (this will throw an Error in a future version of PHP)
Filename: src/RestController.php
Line Number: 659`

Changing line 659 as follows...

`$http_code > 0 || $http_code = self::HTTP_OK`

...causes a further error `Undefined property: Status::$http_status` on line 542

**Comment by aderowbotham** [comment]
Thanks @nerdv2 - setting the version to "dev-master" resolves this

**Comment by AlfanMudhofir** [comment]
I have same problem like @aderowbotham. I think there is some issues with some code in RestController.php. Then I try to changes the code at the line 659

From :
**$http_code > 0 || $http_code = HTTP_OK;**

To : 
**$http_code > 0 || $http_code = 200;**

And I do change several code because I think that type of code is no longer supported on PHP 7. Please correct me if I was wrong

**Comment by AlfanMudhofir** [comment]
> i change $config['rest_enable_keys'] = true; in src/rest.php
> and i get this error
> 
> ![Screenshot from 2020-01-23 15-32-26](https://user-images.githubusercontent.com/44496467/72968223-a1429a80-3df5-11ea-9465-7f7edfcbdf16.png)
> 
> I used jwt for token authentication but there were no problems there.
> 
> if i changing the config file nothing happens, logs and key doesn't working.
> im using php version 7.3.1.
> 
> ![Screenshot from 2020-01-23 15-41-30](https://user-images.githubusercontent.com/44496467/72968805-d7cce500-3df6-11ea-9dd6-4713da17d5fd.png)
> 
> in the version that does not use vendor there are no problems
> 
> Thanks Sir

Like in this case, I change it from

>             $this->response([
                $this->config->item('rest_status_field_name')  => false,
                $this->config->item('rest_message_field_name') => sprintf($this->lang->line('text_rest_invalid_api_key'), $this->rest->key),
            ], HTTP_FORBIDDEN);
        }

Into this : 

>             $this->response([
                $this->config->item('rest_status_field_name')  => false,
                $this->config->item('rest_message_field_name') => sprintf($this->lang->line('text_rest_invalid_api_key'), $this->rest->key),
            ], 403);

**Comment by r00ts3ctors** [comment]
@AlfanMudhofir sudah selesai masalahnya

**Comment by r00ts3ctors** [comment]
I get some error lik @AlfanMudhofir  and @aderowbotham 

and i try to chenge config/rest.php $config['rest_enable_keys'] = TRUE; i used PHP 7.2.27

**Comment by r00ts3ctors** [comment]
$this->response([
                $this->config->item('rest_status_field_name')  => false,
                $this->config->item('rest_message_field_name') => sprintf($this->lang->line('text_rest_invalid_api_key'), $this->rest->key),
            ], 403); // 	HTTP_FORBIDDEN
        }

That is i chenge it on RestController

**Comment by chriskacerguis** [comment]
should be fixed now.

**Comment by kwul0208** [comment]
it works, thanks..
