### ISSUE TITLE
First Time Installation

### ISSUE THREAD

**Issue by difesa18** [chriskacerguis/codeigniter-restserver#1066]
Hello, I just learned Restful API and found this library.
in the src folder there is Format.php RestController.php and rest.php.
as I know it, rest.php is moved to the config folder.
Format.php is moved to the Library folder.
but I don't know which RestController.php should be moved to which folder.

can anyone help me please ?
thanks before.

**Comment by riesurya** [comment]
Hi,

are you using composer to install ?
if do, then just move rest.php into config folder.

the other files still there.

for testing, you can copy Api.php ( as on Readme.md )
into controllers folder. and get it run via http://ip_address/api/users

that's all

good luck

**Comment by chiragsahu** [comment]
Is there any other way to install other than composer? 
Please mention.

**Comment by jeanphillippe** [comment]
I would also like to know. In version 3.0 you just needed the controller, now there are a couple more files that dont fit right away on the MVC of Codeigniter (libraries/helpers?)
