### ISSUE TITLE
Message: Class 'chriskacerguis\RestServer\RestController' not found

### ISSUE THREAD

**Issue by hidayatridwan** [chriskacerguis/codeigniter-restserver#1067]
i copy this file
chriskacerguis\codeigniter-restserver\src\rest.php
into folder config
and than create Api.php in folder controller like this:
use chriskacerguis\RestServer\RestController;
class Api extends RestController {
	function __construct()
	{
		parent::__construct();
	}

but erorr

**Comment by hidayatridwan** [comment]
i copy this file
chriskacerguis\codeigniter-restserver\src\rest.php
into folder config
and than create Api.php in folder controller like this:
<?php
defined('BASEPATH') OR exit('No direct script access allowed');

use chriskacerguis\RestServer\RestController;

class Api extends RestController {
	
	function __construct()
	{
		parent::__construct();
	}

but erorr

**Comment by netonevess** [comment]
Me too! same problem:
In routes.php:
`
$route['api/v1/property'] = 'apiv1/Property';
`
In controller/v1api/Property.php
`
use chriskacerguis\RestServer\RestController;
class Property extends RESTController {
/*
...
*/
}
`
In config.php:
`
$config['composer_autoload'] = '/vendor/autoload.php';
`
And the error is:
`
Fatal error: Class 'REST_Controller' not found in {my_codeigniter_dir}/application/controllers/apiv1/Property.php on line 7
`

**Comment by netonevess** [comment]
Solved: 
In config.php:
`
$config['composer_autoload'] = FCPATH.'vendor/autoload.php';
`

folders tree is:
codeigniter/
|    application/
|    system/
|    vendor/
|    index.php

**Comment by hidayatridwan** [comment]
> Solved:
> In config.php:
> `$config['composer_autoload'] = FCPATH.'vendor/autoload.php';`
> 
> folders tree is:
> codeigniter/
> | application/
> | system/
> | vendor/
> | index.php

Thankyou @netonevess ,, you save my day!!!
in config.php find and replace like this:
$config['composer_autoload'] = TRUE;
$config['composer_autoload'] = FCPATH.'vendor/autoload.php';

solved

**Comment by netonevess** [comment]
Yeah! 

so, remove:
> $config['composer_autoload'] = TRUE;

'cause it is overwritten by

> $config['composer_autoload'] = FCPATH.'vendor/autoload.php';
