### ISSUE TITLE
Error implement

### ISSUE THREAD

**Issue by lamqtt** [chriskacerguis/codeigniter-restserver#1070]
Implement fail or not?
[
![Screenshot_65](https://user-images.githubusercontent.com/47980029/74131425-de40c680-4c16-11ea-91de-445019ce86fb.png)
](url)

For some reason when I try to implement in codeigniter the result always the same like that. I move `Format.php` and `RestController.php` to libraries; `rest.php` to config folder; rest_lang.php to language;

I also delete both namespace and use in `Format.php` and `RestController.php`. Then in Api.php I change use to something like that
`use application\Libraries\REST_Controller;     
require APPPATH . 'libraries\RestController.php';
require APPPATH . 'libraries\Format.php';
`
Is this correct or wrong way?

**Comment by MIqbalFadillah** [comment]
sorry I can not understand, how do you put
use the \ Libraries \ REST_Controller application; requires APPPATH. and
'libraries \ RestController.php';
can i see your source code?

**Comment by boyolaliweb** [comment]
bismillahi,

api/users => showing all result
api/users/{key}/{parameter} => showing result based on parameter

uri : api/users/id/1 => showing
{"id":1,"name":"Jim","email":"jim@example.com"}

**Comment by naetastore** [comment]
how to implement the latest version 3.1.1+ to ci version 3

**Comment by MIqbalFadillah** [comment]
have you tried it? what's eror? 
What error happened?

**Comment by naetastore** [comment]
how to use

**Comment by chriskacerguis** [comment]
I'm not following the ask or issue.  This is an old issue, so I'm going to close it, but please feel free to create a new issue if needed.
