### ISSUE TITLE
Error Install RestController not found

### ISSUE THREAD

**Issue by anomsejogati** [chriskacerguis/codeigniter-restserver#1073]
I just add this code _use chriskacerguis\RestServer\RestController;_ in class Api but error message appears _Message: Class 'chriskacerguis\RestServer\RestController' not found_

Then i change the code _use vendor\chriskacerguis\RestServer\src\RestController;_ and there is still error.

Please, anyone can help my problem

**Comment by tewfik-dj** [comment]
Hello, for some reason I couldn't do the same thing as you, while trying to git clone the code into my CodeIgniter 3 project

The way I solved it is this (using composer) :

- go to application/ folder inside CI, and issue ```composer require chriskacerguis/codeigniter-restserver``` (it will install the library and any dependencies into application/vendor)
- make sur that your configuration file from CI enables autoloading composer libs (in config/config.php)
- copy rest.php from the git repo or the vendor/ folder from this library to CI application/config/ folder, make sure to edit the values there
- in your code, use something like this :

```php
?php
defined('BASEPATH') OR exit('No direct script access allowed');

use chriskacerguis\RestServer\RestController;

class Api extends RestController {

    function __construct()
    {
        // Construct the parent class
        parent::__construct();
    }

    public function index()
    {
    // and so on with your code...
```

For some reason, all tutorials online are outdated, and the code refactored in the meanwhile + some strange behaviour with namespacing and stuff

Hope this helps

Regards

**Comment by Unero** [comment]
Wow thx @tewfik-dj , found this lib on some tutorial and all tutorials still use version which still include application folder. That makes me drive crazy before see these issue. Thx again
