### ISSUE TITLE
Authorisation not found || In rest servers 

### ISSUE THREAD

**Issue by chetanalotliker** [chriskacerguis/codeigniter-restserver#1074]
The rest server used is below . 
namespace chriskacerguis\RestServer;

I am getting Authorisation not found issue . 
In my rest.php file which is located in the application/config folder i have made the following changes.

$config['rest_auth'] = 'basic';
$config['auth_source'] = '';

This was not working . 
Then i added the code below in the .htaccess folder . 
*<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php/$1 [L]
</IfModule>
RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]*

This was also not working . 

Need the way to resolve this issue . I tried making the above changes in the rest.php file only from the config folder .It is not working .

**Comment by chriskacerguis** [comment]
This seems to be an issue with your setup and CI.  Going to close this, I would check with the CI team.
