### ISSUE TITLE
No message with 401

### ISSUE THREAD

**Issue by Ihabafia** [chriskacerguis/codeigniter-restserver#1076]
Hi, I am trying to show an output message to the user with the status of 401, but the message doesn't show up:

`$this->response($data, 401);`

so, I am getting the status of 401 Unautherize but without the message.

Is there a way to show the message?

**Comment by vietqmax** [comment]
Find $this->http_status['UNAUTHORIZED'] replace to: self::HTTP_UNAUTHORIZED

**Comment by chriskacerguis** [comment]
this is fixed in the latest version of the code.
