### ISSUE TITLE
A PHP Error was encountered

### ISSUE THREAD

**Issue by asifagaria** [chriskacerguis/codeigniter-restserver#1077]
Message: Class 'chriskacerguis\RestServer\RestController' not found

**Comment by JhonGdl** [comment]
in order to use the class; you need to load from composer autoload on config.

1.- Install by composer on your project

> composer require chriskacerguis/codeigniter-restserver

2.- Load it. You can do it automaticatly on config: 

> on config file change this line from:     
$config['composer_autoload'] = FALSE
to 
$config['composer_autoload'] = 'vendor/autoload.php';

3.- add this line to your controller

> use chriskacerguis\RestServer\RestController;

and dont forget copy the rest.php dile to your config folder.

**Comment by asifagaria** [comment]
same error not working for me

**Comment by taufikanggarawork** [comment]
@JhonGdl i've tried this but dont know why, got a new error "404 Page Not Found"

**Comment by CuteDeng** [comment]
> in order to use the class; you need to load from composer autoload on config.
> 
> 1.- Install by composer on your project
> 
> > composer require chriskacerguis/codeigniter-restserver
> 
> 2.- Load it. You can do it automaticatly on config:
> 
> > on config file change this line from:
> > $config['composer_autoload'] = FALSE
> > to
> > $config['composer_autoload'] = 'vendor/autoload.php';
> 
> 3.- add this line to your controller
> 
> > use chriskacerguis\RestServer\RestController;
> 
> and dont forget copy the rest.php file to your config folder.
not working for me

**Comment by CuteDeng** [comment]
> same error not working for me

@asifagaria have you find the solution?

**Comment by asifagaria** [comment]
> > same error not working for me
> 
> @asifagaria have you find the solution?

Yes I Give You

**Comment by CuteDeng** [comment]
> > > same error not working for me
> > 
> > 
> > @asifagaria have you find the solution?
> > @CuteDeng
> > Yes i solve problem
@asifagaria 
Please point me out,thank you~

**Comment by asifagaria** [comment]
>@asifagaria have you find the solution?
>@CuteDeng
Yes i solve problem
>@asifagaria
Please point me out,thank you~


https://mega.nz/folder/ZRFm2CrL#Z3NGSOJpheemfGgK8Wx2qw

**Comment by CuteDeng** [comment]
> > @asifagaria have you find the solution?
> > @CuteDeng
> > Yes i solve problem
> > @asifagaria
> > Please point me out,thank you~
> 
> Here Is Files
> https://mega.nz/folder/ZRFm2CrL#Z3NGSOJpheemfGgK8Wx2qw

got it ~

**Comment by neerajsinghsonu** [comment]
If anybody facing same issue, please check https://github.com/chriskacerguis/codeigniter-restserver/issues/1089#issuecomment-636444182
