### ISSUE TITLE
Call to undefined function random_string

### ISSUE THREAD

**Issue by gabrielrodrigodesbesell** [chriskacerguis/codeigniter-restserver#1078]
the helper was loaded in two ways, with automatic loading and in its own controller:

1: $autoload['helper'] = array('url','string');
2: $this->load->helper('string');

Unsuccessful to use as helper functions.
Any suggestion?

**Comment by JhonGdl** [comment]
Can you show us the error log?; if the helper is loaded; you should be able to use it.
The helper has probably not been loaded

**Comment by chriskacerguis** [comment]
no response closing.
