### ISSUE TITLE
Missing Authentication mechanism

### ISSUE THREAD

**Issue by atishagrawal** [chriskacerguis/codeigniter-restserver#1080]
I have been trying to use this library for a couple of days. However, there are a lot of missing points in this.

1. Authentication is missing. No use of changing the auth type, or keys, etc.
2. Use of rest_valid_logins is still unclear.
3. Use of X-API-KEY is unclear

**Comment by chriskacerguis** [comment]
I'm not really following what you are looking for.  I'm going to close this issue, but feel free to create a new issue asking specific questions.
