### ISSUE TITLE
Installing the library on Codeigniter 4.0.3

### ISSUE THREAD

**Issue by jobsondev** [chriskacerguis/codeigniter-restserver#1087]
Hi, is there any example of installing the chriskacerguis library in CI 4.0? I tried to do the installation and did not succeed in any way, I would like to know if it is possible.

**Comment by alex-migwi** [comment]
I think RESTful API is what C4 is take care of here by introducing resource controller [https://codeigniter4.github.io/userguide/incoming/restful.html](url)

**Comment by chriskacerguis** [comment]
So, I'm going to update this so it works for CI4 (so people can upgrade), but I agree with @alex-migwi that using the RESTful Resource Handling built in to CI4 is the best path forward.
