### ISSUE TITLE
installing from composer

### ISSUE THREAD

**Issue by Ir001** [chriskacerguis/codeigniter-restserver#1088]
Deprecation warning: require-dev.mikey179/vfsStream is invalid, it should not contain uppercase characters. Please use mikey179/vfsstream instead. Make sure you fix this as Composer 2.0 will error.

**Comment by neerajsinghsonu** [comment]
It happens when you have downloaded CodeIgniter zip folder from site. It's a warning that you can remove by replacing all in lower case -

e.g. /composer.json

```
"require-dev": {
	"mikey179/vfsStream": "1.1.*",
	"phpunit/phpunit": "4.* || 5.*"
}
```
-- to --

```
"require-dev": {
	"mikey179/vfsstream": "1.1.*",
	"phpunit/phpunit": "4.* || 5.*"
}
```

Cheers!!
Neeraj Singh

**Comment by Ir001** [comment]
Thanks
