### ISSUE TITLE
Class 'chriskacerguis\RestServer\RestController'  not found 

### ISSUE THREAD

**Issue by CuteDeng** [chriskacerguis/codeigniter-restserver#1089]
```
I follow the document ,
composer install 
not working
```

**Comment by neerajsinghsonu** [comment]
### Solution for [CodeIgniter Version 3.1.11] with composer

**_Follow same steps as mentioned in document_**

inside your project root folder run,

```composer
composer require chriskacerguis/codeigniter-restserver
```

### Enable Composer in CodeIgniter-

After that you will see a "**/project/vendor**" folder, which holds all the required files, now go inside vendor folder and copy, "**_vendor/chriskacerguis/codeigniter-restserver/src/rest.php to application/config/rest.php_**"

Now, open "**_application/config/config.php_**" and update

```php
$config['composer_autoload'] = FCPATH . 'vendor/autoload.php';
```
Above line tells CodeIgniter that, use '**vendor**' folder which is exists in '**/project**' root folder

If you using below setting, then you are telling CodeIgniter that use '**vendor**' folder which is exists in '**/project/application/**' folder instead of project root folder.

```php
$config['composer_autoload'] = TRUE;
```

### Create new Controller-

Now, add a Controller file named '_project/application/controllers/Api.php_' (example given in main doc file)

### Example .htaccess in case you don't have

```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule .* index.php/$0 [PT,L]
```

**_http://localhost/project/api/users, http://localhost/project/api/users/id/1_**

when you run above controller example you may see below error on screen.

```php
A PHP Error was encountered
Severity: Notice
Message: Undefined property: Api::$http_status
Filename: src/RestController.php
Line Number: 542
```

### EDIT-
 "**_/project/vendor/chriskacerguis/codeigniter-restserver/src/RestController.php_**"
and add below line of code (above "**protected $rest_format = null;**")

```php
/**
 * This defines the http status code
 * Must be overridden it in a controller so that it is set.
 *
 * @var string|null
 */
protected $http_status = null;
```

also if you are getting error like

```php
A PHP Error was encountered
Severity: Warning

Message: Use of undefined constant HTTP_OK - assumed 'HTTP_OK' (this will throw an Error in a future version of PHP)

Filename: controllers/Api.php

Line Number: 30

Backtrace:
```

### EDIT -
 "**_/project/vendor/chriskacerguis/codeigniter-restserver/src/RestController.php_**"
and replace all **HTTP_OK** const usages with '**_Self::HTTP_OK_**' and same for '**HTTP_NOT_FOUND**' as '**_Self:: HTTP_NOT_FOUND_**' and so on

If you do not want to edit file then use '200 or 404' as a numeric value instead of **HTTP_OK** in your controller where you have extended the '**RestController**'.

Hope all fixed now! enjoy the CodeIgniter :)

Best regards,
Neeraj Singh

**Comment by DmitryAdam** [comment]
Hi Thanks for your help,

but maybe some of people will confused when read this parts "Now, open "application/config/config.php" and update".

cmiww:
if your vendor locatead at root folder of your project use this. 
`  $config['composer_autoload'] = FCPATH . 'vendor/autoload.php'; `
but, if your vendor located at 'application' folder, use this
`   $config['composer_autoload'] = TRUE;`

**Comment by neerajsinghsonu** [comment]
Thanks @DmitryAdam , Yes you are correct. I have updated the answer with same.

**Comment by SaeedNikmehr** [comment]
> ### Solution for [CodeIgniter Version 3.1.11] with composer
> **_Follow same steps as mentioned in document_**
> 
> inside your project root folder run,
> 
> ```
> composer require chriskacerguis/codeigniter-restserver
> ```
> 
> ### Enable Composer in CodeIgniter-
> After that you will see a "**/project/vendor**" folder, which holds all the required files, now go inside vendor folder and copy, "**_vendor/chriskacerguis/codeigniter-restserver/src/rest.php to application/config/rest.php_**"
> 
> if your vendor located at root folder of your project use this.
> 
> ```
> $config['composer_autoload'] = FCPATH . 'vendor/autoload.php';
> ```
> 
> but, if your vendor located inside 'application' folder, use this
> 
> ```
> $config['composer_autoload'] = TRUE;
> ```
> 
> ### Create new Controller-
> Now, add a Controller file named '_project/application/controllers/Api.php_' (example given in main doc file)
> 
> ### Example .htaccess in case you don't have
> ```
> RewriteEngine On
> RewriteCond %{REQUEST_FILENAME} !-f
> RewriteCond %{REQUEST_FILENAME} !-d
> RewriteRule .* index.php/$0 [PT,L]
> ```
> 
> **_http://localhost/project/api/users, http://localhost/project/api/users/id/1_**
> 
> when you run above controller example you may see below error on screen.
> 
> ```
> A PHP Error was encountered
> Severity: Notice
> Message: Undefined property: Api::$http_status
> Filename: src/RestController.php
> Line Number: 542
> ```
> 
> ### EDIT-
> "**_/project/vendor/chriskacerguis/codeigniter-restserver/src/RestController.php_**"
> and add below line of code (above "**protected $rest_format = null;**")
> 
> ```
> /**
>  * This defines the http status code
>  * Must be overridden it in a controller so that it is set.
>  *
>  * @var string|null
>  */
> protected $http_status = null;
> ```
> 
> also if you are getting error like
> 
> ```
> A PHP Error was encountered
> Severity: Warning
> 
> Message: Use of undefined constant HTTP_OK - assumed 'HTTP_OK' (this will throw an Error in a future version of PHP)
> 
> Filename: controllers/Api.php
> 
> Line Number: 30
> 
> Backtrace:
> ```
> 
> ### EDIT -
> "**_/project/vendor/chriskacerguis/codeigniter-restserver/src/RestController.php_**"
> and replace all **HTTP_OK** const usages with '**_Self::HTTP_OK_**' and same for '**HTTP_NOT_FOUND**' as '**_Self:: HTTP_NOT_FOUND_**' and so on
> 
> If you do not want to edit file then use '200 or 404' as a numeric value instead of **HTTP_OK** in your controller where you have extended the '**RestController**'.
> 
> Hope all fixed now! enjoy the CodeIgniter :)
> 
> Best regards,
> Neeraj Singh

thank you , i had the  same issue.your solution worked , but now i get the this error :
Message:  trying to access array offset on value of type null
Filename: src/RestController.php
Line Number: 547
so now how i can i fix this?

**Comment by neerajsinghsonu** [comment]
Hello @SaeedNikmehr 

error saying "trying to access array offset on value of type null". That means you are trying get something like array from a null value. You are expecting array but it's null. so check what value is been set and where and why.

Hope this helps!

Regards,
Neeraj Singh
"Keep Social Distancing and Keep wash your hand frequently.
Do not roam without Mask and Sanitizer. Love your people and Family, Love  the whole world"

**Comment by arifin-zaeyn** [comment]
Hai @SaeedNikmehr, can you show me the code on line 547 ?

**Comment by billpebert** [comment]
> ### Solution for [CodeIgniter Version 3.1.11] with composer
> **_Follow same steps as mentioned in document_**
> 
> inside your project root folder run,
> 
> ```
> composer require chriskacerguis/codeigniter-restserver
> ```
> 
> ### Enable Composer in CodeIgniter-
> After that you will see a "**/project/vendor**" folder, which holds all the required files, now go inside vendor folder and copy, "**_vendor/chriskacerguis/codeigniter-restserver/src/rest.php to application/config/rest.php_**"
> 
> if your vendor located at root folder of your project use this.
> 
> ```
> $config['composer_autoload'] = FCPATH . 'vendor/autoload.php';
> ```
> 
> but, if your vendor located inside 'application' folder, use this
> 
> ```
> $config['composer_autoload'] = TRUE;
> ```
> 
> ### Create new Controller-
> Now, add a Controller file named '_project/application/controllers/Api.php_' (example given in main doc file)
> 
> ### Example .htaccess in case you don't have
> ```
> RewriteEngine On
> RewriteCond %{REQUEST_FILENAME} !-f
> RewriteCond %{REQUEST_FILENAME} !-d
> RewriteRule .* index.php/$0 [PT,L]
> ```
> 
> **_http://localhost/project/api/users, http://localhost/project/api/users/id/1_**
> 
> when you run above controller example you may see below error on screen.
> 
> ```
> A PHP Error was encountered
> Severity: Notice
> Message: Undefined property: Api::$http_status
> Filename: src/RestController.php
> Line Number: 542
> ```
> 
> ### EDIT-
> "**_/project/vendor/chriskacerguis/codeigniter-restserver/src/RestController.php_**"
> and add below line of code (above "**protected $rest_format = null;**")
> 
> ```
> /**
>  * This defines the http status code
>  * Must be overridden it in a controller so that it is set.
>  *
>  * @var string|null
>  */
> protected $http_status = null;
> ```
> 
> also if you are getting error like
> 
> ```
> A PHP Error was encountered
> Severity: Warning
> 
> Message: Use of undefined constant HTTP_OK - assumed 'HTTP_OK' (this will throw an Error in a future version of PHP)
> 
> Filename: controllers/Api.php
> 
> Line Number: 30
> 
> Backtrace:
> ```
> 
> ### EDIT -
> "**_/project/vendor/chriskacerguis/codeigniter-restserver/src/RestController.php_**"
> and replace all **HTTP_OK** const usages with '**_Self::HTTP_OK_**' and same for '**HTTP_NOT_FOUND**' as '**_Self:: HTTP_NOT_FOUND_**' and so on
> 
> If you do not want to edit file then use '200 or 404' as a numeric value instead of **HTTP_OK** in your controller where you have extended the '**RestController**'.
> 
> Hope all fixed now! enjoy the CodeIgniter :)
> 
> Best regards,
> Neeraj Singh

**Thanks for your help!**

**Comment by rajsathishcse** [comment]
Hi @chriskacerguis , I am upgrading my app from CodeIgniter 3.x to **4.3.2**. I have downloaded the new Rest Serer from the git, but RestController still extends from CI_contoller. I have updated that as BaseController but still that is not working . Can you confirm whether this library will work with **CodeIgniter 4**, if yes please send me the details to Place the packages and code changes.

![image](https://user-images.githubusercontent.com/3177577/226730289-04dad107-969d-4640-853f-433a63869c59.png)

![image](https://user-images.githubusercontent.com/3177577/226730380-606f1194-38da-4bbc-aa12-0a6a20e30de2.png)

![image](https://user-images.githubusercontent.com/3177577/226730514-525ad549-a7d1-4f15-a07a-a82d9044b61a.png)

Can you please help, I am got stuck on this.
