### ISSUE TITLE
Is this repo is still worthed to try?

### ISSUE THREAD

**Issue by androxxe** [chriskacerguis/codeigniter-restserver#1091]
Is this repo is still worthed to try?

**Comment by phoenixf** [comment]
I still use it on many projects, for my purposes it's very useful

**Comment by phoenixf** [comment]
> Is this repo is still worthed to try?

I still use it on many projects, for my purposes it's very useful

**Comment by androxxe** [comment]
> > Is this repo is still worthed to try?
> 
> I still use it on many projects, for my purposes it's very useful

Thanks bro, i tried codeigniter 4 restful api before, but sometimes there is a bug at the end of json files, missing '}'

**Comment by phoenixf** [comment]
> > > Is this repo is still worthed to try?
> > 
> > 
> > I still use it on many projects, for my purposes it's very useful
> 
> Thanks bro, i tried codeigniter 4 restful api before, but sometimes there is a bug at the end of json files, missing '}'

I've been using for years, never had that problem! But didn't tried with CI 4 yet =/
