### ISSUE TITLE
Notice --> Undefined property: stdClass::$db ..libraries/REST_Controller.php 1293

### ISSUE THREAD

**Issue by vesvello** [chriskacerguis/codeigniter-restserver#1092]
I got this message.

Notice --> Undefined property: stdClass::$db ..libraries/REST_Controller.php 1293

Any advise?

**Comment by chriskacerguis** [comment]
Could you please provide a little more detail?  Based just on the snippet, it looks like you are using an older version.  Could you please update and try again?  I'm going to close this issue, but feel free to open another if it is still an issue.
