### ISSUE TITLE
Undefined class constant 'HTTP_METHOD_NOT_ALLOWED'

### ISSUE THREAD

**Issue by mranisz** [chriskacerguis/codeigniter-restserver#1099]
Type: Error

Message: Undefined class constant 'HTTP_METHOD_NOT_ALLOWED'

Filename: /usr/share/composer/vendor/chriskacerguis/codeigniter-restserver/src/RestController.php

Line Number: 551

**Comment by iamwiqi** [comment]
Added 
`  const HTTP_METHOD_NOT_ALLOWED = 405;`
in RestController.php constants
