### ISSUE TITLE
Where I find the complete documentation

### ISSUE THREAD

**Issue by NathanAllmeida** [chriskacerguis/codeigniter-restserver#1100]
This library is very useful, but I would like to know more about methods, functions and others.
I need more than just the basics informed.

**Comment by chriskacerguis** [comment]
Please feel free to have a look at the code.

**Comment by NathanAllmeida** [comment]
it doesn't make any sense, if i need to use it, do i have to spend absurd time reading code and guessing how it works?
But thanks, I think this library is very good

**Comment by chriskacerguis** [comment]
@natanfelles I'm happy to answer specific questions...but, your original ask is pretty vague/large.
