### ISSUE TITLE
Use of undefined constant HTTP_OK - assumed 'HTTP_OK' (this will throw an Error in a future version of PHP)

### ISSUE THREAD

**Issue by Andrewsuares** [chriskacerguis/codeigniter-restserver#1102]
Hello,

I just downloaded the latest version of restserver. Is there a fix for this? Thanks.

"chriskacerguis/codeigniter-restserver": "^3.1",

Use of undefined constant HTTP_OK - assumed 'HTTP_OK' (this will throw an Error in a future version of PHP)
Filename: src/RestController.php
Line Number: 659

**Comment by shimbala** [comment]
Hi,

use `self::HTTP_OK`

**Comment by Bliksempie** [comment]
Same issue here. using the solution you suggest would mean I need to modify the RestController.php file directly, which I do not want to do, for obvious reasons. When editing the RestController.php file, adding self:: in front of where the code is used, it works fine, but I do not like this approach. Any other ideas?

**Comment by shimbala** [comment]
HI, I think this will be in next release, because it is already in fixed in [file](https://github.com/chriskacerguis/codeigniter-restserver/blob/master/src/RestController.php) .

**Comment by aderowbotham** [comment]
@chriskacerguis How can we install the version with the fix please? 4.0.0 is not available. 3.1.1. still has the incorrect reference of class constants

**Comment by kennydeckers** [comment]
@chriskacerguis any chance a new tag for this fix so we can avoid using dev-master? 👼

**Comment by netonevess** [comment]
> HI, I think this will be in next release, because it is already in fixed in [file](https://github.com/chriskacerguis/codeigniter-restserver/blob/master/src/RestController.php) .

Yeap! I guess.. I did a copy of it and my code works well.

**Comment by jamieburchell** [comment]
> @chriskacerguis any chance a new tag for this fix so we can avoid using dev-master? 👼

+1

**Comment by chriskacerguis** [comment]
@jamieburchell done.
