### ISSUE TITLE
Cannot Get id

### ISSUE THREAD

**Issue by lamboktulus1379** [chriskacerguis/codeigniter-restserver#1104]
I try to find the user with id 1, but get all the users data.

```php
<?php
defined('BASEPATH') or exit('No direct script access allowed');

use chriskacerguis\RestServer\RestController;

class NewApi extends RestController
{

    function __construct()
    {
        // Construct the parent class
        parent::__construct();
    }

    public function users_get()
    {
        // Users from a data store e.g. database
        $users = [
            ['id' => 0, 'name' => 'John', 'email' => 'john@example.com'],
            ['id' => 1, 'name' => 'Jim', 'email' => 'jim@example.com'],
        ];

        $id = $this->get('id');

        if ($id === null) {
            // Check if the users data store contains users
            if ($users) {
                // Set the response and exit
                $this->response($users, 200);
            } else {
                // Set the response and exit
                $this->response([
                    'status' => false,
                    'message' => 'No users were found'
                ], 404);
            }
        } else {
            if (array_key_exists($id, $users)) {
                $this->response($users[$id], 200);
            } else {
                $this->response([
                    'status' => false,
                    'message' => 'No such user found'
                ], 404);
            }
        }
    }
}
```

I want to get user belongs to Id 1

**Screenshots
If applicable, add screenshots and/or error messages to help explain your problem.
![image](https://user-images.githubusercontent.com/42629000/93548873-63047780-f992-11ea-9655-5d287b35bae1.png)

**Environment**
 - PHP Version: 7.4.7
 - CodeIgniter Version 3.1.1

**Additional**
I try to get user with id 1 "https://mydomain.com/api/users/1, but get all the user

**Comment by Bliksempie** [comment]
Had the same problem. Had two attempts:

(1) Tried:

user/id/{id}

This worked for individual users, however, this still fails on getting all users. So, I tried #2, working fine now, by changing my array structure from:

`
$users = [
    ['id' => 0, 'name' => 'John', 'email' => 'john@example.com'],
    ['id' => 1, 'name' => 'Jim', 'email' => 'jim@example.com']
];
`

to:

`
$users = [
    0 => ['id' => 0, 'name' => 'John', 'email' => 'john@example.com'],
    1 => ['id' => 1, 'name' => 'Jim', 'email' => 'jim@example.com']
];
`
Hope it helps.

**Comment by lamboktulus1379** [comment]
Thanks!
