### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by rtrujilloatencion** [chriskacerguis/codeigniter-restserver#1108]
Hi, i'm looking for documentation, some body can help me?

**Comment by alfinforwork** [comment]
In readme

**Comment by DoWebMx** [comment]
> In readme

Thanks man, but the readme file don't content any information about auth method, just include a basic example for use.

**Comment by Kunwark** [comment]
I am reading the readme.md but I can't make sense of how the URLs work and how are they mapped with the functions?

**Comment by Kunwark** [comment]
users_get() function works and it gets me the data as well but even when I change the function name it stops working. How are these functions mapped? I created users_post but that won't work...  How do we get this API to work properly?

**Comment by kunwarkhalid** [comment]
@chriskacerguis Is there a more detailed documentation somewhere?

**Comment by Bliksempie** [comment]
I am willing to make [some] documentation for this (it could definitely be a collaborative issue) - busy with a new project for myself, and having to figure a few things out for myself. What is the preferred documentation platform? Markdown within this repo? Or do you prefer something like Sphynx/readthedocs?

**Comment by Bliksempie** [comment]
> I am reading the readme.md but I can't make sense of how the URLs work and how are they mapped with the functions?

The URLs are standard CodeIgniter URI segments, I think. RestServer does not introduce new things over and above the way CodeIgniter does this.

**Comment by kunwarkhalid** [comment]
I have started to get a hold of this framework. I am willing to contribute to the documentation as well. @Bliksempie let me know if you would like to collaborate on this. I think Chris has used markdown and we can continue improving the same one.

**Comment by josemilioz** [comment]
Hello guys. Just found this old implementation that you can use as an example for a more complete documentation on this version of the rest server: https://github.com/ricsunny/ciAuth. It uses the old version but you'll have the clue. Good luck!
