### ISSUE TITLE
Help needed: POST example

### ISSUE THREAD

**Issue by Bliksempie** [chriskacerguis/codeigniter-restserver#1109]
Hi,

I am managing very well with GET requests, but somehow, my POST requests do not work. My understanding is this:

1. I must name my method like this: function cart_add_post()
2. When I call my method, I call it like this with Postman: cart_add

If I do not pass the header, I get "Invalid API key" (RESTController response)
If I do pass the header, I get "NOT FOUND ><" (my method response)
If I pass the parameter to see why I get "NOT FOUND ><", it does not make any difference in the result of my method (tried both $this->get() and $this->post() just to test, always getting "NOT FOUND ><" output below)

Can someone give me a bit of assistance?

```
    public function cart_add_post()
    {
        $key = $this->post('X-API-KEY');
        if (!empty($key)) {
            $this->response("POST: >" . $key . "<", 200);
        }
        $key = $this->get('X-API-KEY');
        if (!empty($key)) {
            $this->response("GET: >" . $key . "<", 200);
        }

        // The QUERY item was added later, and that does get a response, but feels wrong...?
        $key = $this->query('X-API-KEY');
        if (!empty($key)) {
            $this->response("QUERY: >" . $key . "<", 200);
        }
        $this->response("NOT FOUND: >" . $key . "<", 400);
        // [...code removed for brevity..., tried options, and head as well]
}
```

Tried calling it in Postman like this: 

https://my.domain.com/api_v1/CartAPI/cart_add?X-API-KEY=boguskey
(with header and parameter)

https://my.domain.com/api_v1/CartAPI/cart_add 
(with header and no parameter)

The "boguskey" exists, and works fine with GET requests.

Anybody knows what I am doing wrong?

**EDIT**: I found in the RestController class the method **query()** (called as $this->query('X-API-KEY')) via parameter in Postman, and that returns the correct data, but that seems wrong.

**EDIT2:** I also realize that my code to check the API key is not necessary, because the RestController does the check, but this is just a test - just in case someone asks "why are you validating the key again?" :-) I do want the API Key available for other purposes in my system, hence trying to get the value thereof.

Thanks!

Kobus

![post](https://user-images.githubusercontent.com/677410/96357698-90625380-10ff-11eb-874a-f8e5adc02931.png)

**Comment by gsaraujo** [comment]
Hi, you should pass the X-API-KEY on the body of the request. GET requests do pass the parameter on the url, that is why it is working. But POST requests send it on the body (security reasons). You should leave the header empty and send the request like the image i posted. With that being said, i believe this is not a chriskacerguis/codeigniter-restserver issue. 

![image](https://user-images.githubusercontent.com/7838084/96372097-bf96b600-113b-11eb-9df7-d0e536d3d67d.png)

**Comment by Bliksempie** [comment]
Hi gsaraujo,

Thank you for your response. I am aware of it not being an issue with the project - hence I did mark it as "help needed" and not a bug or something like that.

My issue is resolved by your answer. Thanks!

Kobus
