### ISSUE TITLE
Class 'chriskacerguis\RestServer\RecursiveIteratorIterator' not found

### ISSUE THREAD

**Issue by careybaird** [chriskacerguis/codeigniter-restserver#1111]
**Describe the bug**
Using the post() method with no variables causes fatal error:

Class 'chriskacerguis\RestServer\RecursiveIteratorIterator' not found

**To Reproduce**
Try to access the request post using method post() with no variables:

```
$post = $this->post();
```

Fatal error will show.

**Expected behavior**
Expect to receive a full array of post data.

**Screenshots / Error Messages**
n/a

**Environment (please complete the following information):**
 - PHP Version: 7.4.x
 - CodeIgniter Version: 3
 - Version: dev-master

**Additional context**

This just needs a use statement so PHP is not looking in the local namespace for the class. Add the following to line 7 of RestController.php:

```
use \RecursiveIteratorIterator;
```

**Comment by nullart2** [comment]
Thank you for this.

In my case

`Message: Class 'chriskacerguis\RestServer\RecursiveIteratorIterator' not found`

adding

`use \RecursiveArrayIterator;`

solved my issues.

**Comment by careybaird** [comment]
@chriskacerguis I can submit a pull request for this if you agree?

**Comment by nacho004** [comment]
Anyone could solve this? 
The fix doesn't work for me


> Thank you for this.
> 
> In my case
> 
> `Message: Class 'chriskacerguis\RestServer\RecursiveIteratorIterator' not found`
> 
> adding
> 
> `use \RecursiveArrayIterator;`
> 
> solved my issues.

**Comment by jamieburchell** [comment]
@chriskacerguis Please can you merge this fix?
