### ISSUE TITLE
Undefined property: Users::$http_status

### ISSUE THREAD

**Issue by dulumina** [chriskacerguis/codeigniter-restserver#1117]
**Describe the bug**
an error occurred after running `composer install`
Message: Undefined property: Users::$http_status

**Screenshots / Error Messages**
![image](https://user-images.githubusercontent.com/46472300/109422825-1d0b0f80-7a18-11eb-9d50-a1c488596763.png)

**Environment (please complete the following information):**
 - PHP Version: 5.6 (XAMPP)
 - CodeIgniter Version 3
 - chriskacerguis/codeigniter-restserver: 3.1

**Comment by MuyiwaSaka** [comment]
I added this somewhere in the file since it seems to me a refactoring-in-progress.

`protected $http_status = [
        'HTTP_OK' => 200,
    'HTTP_CREATED' => 201,
    'HTTP_NOT_MODIFIED' => 304,
    'HTTP_BAD_REQUEST' => 400,
    'HTTP_UNAUTHORIZED' => 401,
    'HTTP_FORBIDDEN' => 403,
    'HTTP_NOT_FOUND' => 404,
    'HTTP_NOT_ALLOWED' => 405,
    'HTTP_NOT_ACCEPTABLE' => 406,
    'HTTP_INTERNAL_ERROR' => 500
    ];`

Addresses that. A little refactoring to fit elsewhere in the file to sweeten the stew. Cheers.
