### ISSUE TITLE
How to Generate Key 

### ISSUE THREAD

**Issue by jajasuparja** [chriskacerguis/codeigniter-restserver#1120]
Hi Chris,

I want to generate Key. I tried access this url : https://github.com/philsturgeon/codeigniter-restserver/blob/master/application/controllers/api/key.php

but page not found. 
Many thank in advance

**Comment by livingatrip** [comment]
I had the same doubt. I think this link from previous version (3.0.4) may help.

https://github.com/chriskacerguis/codeigniter-restserver/blob/3.0.4/application/controllers/api/Key.php

**Comment by mariefku** [comment]
Better provide api auth or api secret yourself dude, its not that hard. Dont postpone your work only because this prob.

**Comment by moudarir** [comment]
You can do that with this function helper

```php
if (!function_exists('generate_api_key')) {
    function generate_api_key () {
        $keyLength = 40;
        // Generate a random salt
        $salt = base_convert(bin2hex($this->security->get_random_bytes(64)), 16, 36);
        // If an error occurred, then fall back to the previous method
        if ($salt === false):
            $salt = hash('sha256', time() . mt_rand());
        endif;

        return substr($salt, 0, $keyLength);
    }
}
```
