### ISSUE TITLE
POST request is not working only GET request is working

### ISSUE THREAD

**Issue by dinukakulatunga** [chriskacerguis/codeigniter-restserver#1129]
![image](https://user-images.githubusercontent.com/32608112/121831183-773c9180-cce4-11eb-9c6e-f11f5148f689.png)

This is my code, as you can see I have created both get and post requests.  But the problem is when I try these endpoints using postman, I only get respond from the GET request. When I try POST request in postman, it will give me the same response that I got from GET request. which means "user get" response not "user add" response. I'm a newbie in restservers.  can some one help me to fix this issue.

**Comment by rferreras** [comment]
I have the same problem ! I have Dockerizate the APP all GET method Working, only POST dont work

**Comment by moudarir** [comment]
I recommend to use this bellow config in your **`routes.php`** file
```php
$route['users'] = [
    'get' => 'api/users', // Method: users_get() / All records
    'post' => 'api/users', // Method: users_post()
    'put' => 'api/users', // Method: users_put()
    'delete' => 'api/users', // Method: users_delete()
    'head' => 'api/users', // Method: users_head()
    'options' => 'api/users' // Method: users_options()
];

// Method: users_get() / One record
$route['users/(\.)([a-zA-Z0-9_-]+)(.*)']['get'] = 'api/users/format/$2$3';
$route['users/([0-9]+)']['get'] = 'api/users/index/id/$1';
$route['users/([0-9]+)(\.)([a-zA-Z0-9_-]+)(.*)']['get'] = 'api/users/index/id/$1/format/$3$4';
```

Hope that help someone.
