### ISSUE TITLE
DELETE method & JSON request

### ISSUE THREAD

**Issue by oytuntez** [chriskacerguis/codeigniter-restserver#113]
Hello all,

Thanks for this precious library. It's a very nice one.

I have encountered a problem while trying to use it with DELETE request by EXTJS Rest proxy. Proxy sends a complete JSON object of the record that will be deleted. Like this:

[CODE]
DELETE http://localhost/km1/admin/gateway/index.php/api/tour_gallery/4?_dc=1336230707386 HTTP/1.1
Host: localhost
Connection: keep-alive
Content-Length: 122
Origin: http://localhost
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.168 Safari/535.19
Content-Type: application/json
Accept: _/_
Referer: http://localhost/km1/admin/app.html
Accept-Encoding: gzip,deflate,sdch
Accept-Language: tr-TR,tr;q=0.8,en-US;q=0.6,en;q=0.4
Accept-Charset: ISO-8859-9,utf-8;q=0.7,*;q=0.3
Cookie: wp_gdsr_artthumb=voted_%7C64%7C33%7C30%7C27

{"id":"4","tourid":"3","thumb":"thumb_1aad297d186cfc66dc449b216994a2ec.jpg","full":"1aad297d186cfc66dc449b216994a2ec.jpg"}

[/CODE]

However, the library failed on parsing the DELETE variables. When print_r($this->_delete_args), the result was unusable:

[CODE]
Array
(   [{"id":"2","tourid":"3","thumb":"thumb_b5fbe4efa7467fc7bf19f10b761f6111_png","full":"b5fbe4efa7467fc7bf19f10b761f6111_png"}] => 
)
[/CODE]

The key was filled with the json request with no value corresponding. So, I changed the SWITCH the __CONSTRUCT function in the library like this after trying to succeed with other methods as you can see in comments:

[CODE]
case 'delete':
                // Set up out DELETE variables (which shouldn't really exist, but sssh!)
                //parse_str(file_get_contents('php://input'), $this->_delete_args);
                /_parse_str(file_get_contents('php://input'), $delme);
                $this->_delete_args = array_merge($this->_delete_args, $delme);_/

```
            if (stripos($_SERVER["CONTENT_TYPE"], "application/json")===false) {
                    //$_POST = json_decode(file_get_contents("php://input"));
                parse_str(file_get_contents('php://input'), $this->_delete_args);
                echo "json 0 - ".$_SERVER["CONTENT_TYPE"];
            }
            else
            {
                $this->_delete_args = (array)json_decode(file_get_contents("php://input"));
            }

            break;
```

[/CODE]

Hope this will help others.
If I am doing something wrong or this was an unnecessary change, please let me know.

Thanks for the library again.

**Comment by Ema4rl** [comment]
The solution by @oytuntez is not advised because:
* Prior to PHP 5.6 **"php://input"** could not be read twice.
* In codeigniter, **"php://input"** === **"$this->input->raw_input_stream"** *(when called from a controller that extends CI_Controller)*.

See this [Gist](https://gist.github.com/Ema4rl/aebb63db1c76786c9cba811d69339fd3) for my alternative to the above hack by @oytuntez.

**BTW:** I'll suggest you extend the REST_Controller class and use the extended class instead of editing the REST_Controller class directly. See my [Gist](https://gist.github.com/Ema4rl/aebb63db1c76786c9cba811d69339fd3).

**Comment by Hanisch-IT** [comment]
You are welcome to do a pull request with your changes so everybody has the correct solution
