### ISSUE TITLE
[RuntimeException] when installing library - [mikey179/vfsstream]

### ISSUE THREAD

**Issue by billpebert** [chriskacerguis/codeigniter-restserver#1130]
I got error runtime exception when running installation composer require.

**Here i attach the screenshot**
![image](https://user-images.githubusercontent.com/70867121/126476710-22b3d1aa-a0dd-4187-90d8-84471d5eb940.png)

 - PHP Version: [7.4.10]
 - CodeIgniter Version [3.1.11]

**Comment by martin72gar** [comment]
Just open your composer.json file and change mikey179/vfsStream -> mikey179/vfsstream
