### ISSUE TITLE
CORS Issue

### ISSUE THREAD

**Issue by mdaltaf-tech** [chriskacerguis/codeigniter-restserver#1141]
**Describe the bug**
Getting CORS issue with Rest API.

**To Reproduce**
Please provide either a cleanly formatted code snippet or a link to repo / gist with code that I can use to reproduce:

```php
    $config['check_cors'] = TRUE;
    $config['allow_any_cors_domain'] = TRUE;
```

```js
var settings = {
  "url": "http://localhost:3786/api/authentication/login",
  "method": "POST",
  "timeout": 0,
  "headers": {
    "Content-Type": "application/json",
    "Access-Control-Allow-Credentials": "true"
  },
  "data": JSON.stringify({"email":"test@gmail.com","password":"1234567"}),
};

$.ajax(settings).done(function (response) {
  console.log(response);
});
```

Error
Access to XMLHttpRequest at 'http://localhost:3786/api/authentication/login' from origin 'http://localhost:8580' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by e404r** [comment]
in   CI->  'application/config/config.php'

under  Cross Site Request Forgery 

replace
$config['csrf_exclude_uris'];
with
```
$config['csrf_exclude_uris'] = array(

	'api/authentication/login'
);

```
