### ISSUE TITLE
Cannot send body request from React js app

### ISSUE THREAD

**Issue by Spectrevuln-sketch** [chriskacerguis/codeigniter-restserver#1143]
Please help my react app cannot send request body post request ci return response 
```
<p>Severity: Notice</p>
<p>Message:  Undefined index: raw_input_stream</p>
<p>Filename: core/MY_Input.php</p>
<p>Line Number: 20</p>
```
but if i use postman and try to send my request body at postman its working perfectly,  return response body as i want
can anyone help me
this is my code
```
public function login_seller_post(){
        
        return $this->response([
            'input'=> $this->post()
        ], RestController::HTTP_OK); 
       
        
    } 
```

my react code 

 ```
axios.post(`www.domain.com/auth_api/login_seller`,{
       email,
       password
     }).then(result=>{
      console.log('Data Result ', result)
    }).catch(err=>{
      console.log(err)
    })
```

**Comment by rodmessias** [comment]
in react code:

`const formData = new FormData();
    Object.keys(data).forEach((key) => {
        formData.append(key, data[key]);
    }); 

axios.post(`www.domain.com/auth_api/login_seller`,fromData).then(result=>{
     console.log('Data Result ', result)
   }).catch(err=>{
     console.log(err)
   })
`
