### ISSUE TITLE
Issue with CodeIgniter 4.3.2 version - Rest Server version 3.1.4

### ISSUE THREAD

**Issue by rajsathishcse** [chriskacerguis/codeigniter-restserver#1146]
Hi @chriskacerguis , I am upgrading my app from CodeIgniter 3.x to 4.3.2. I have installed ResetServer from the composer, but RestController still extends from CI_contoller. I am not sure onthis, so I have updated that as BaseController but still that is not working . Can you confirm whether this library will work with CodeIgniter 4, if yes please send me the details to Place the packages and code changes.

![image](https://user-images.githubusercontent.com/3177577/226735316-d5b11401-e62e-4dca-9fa7-6ea46b7c88e8.png)

![image](https://user-images.githubusercontent.com/3177577/226735716-ddad087c-0530-4998-b351-55c83fafe27b.png)

Can you please help, I am got stuck on this.

**Environment (please complete the following information):**
 - PHP Version: [8.2.1]
 - CodeIgniter Version [4.3.2]
 - Version [3.1.4]

**Comment by daveherman71** [comment]
CodeIgniter 4 includes REST support out of the box and therefore does not require the RestServer.
See the documentation here: [RESTful Resource Handling](https://codeigniter.com/user_guide/incoming/restful.html#restful-resource-handling)
