### ISSUE TITLE
about DBAD License on Format.php

### ISSUE THREAD

**Issue by tenzap** [chriskacerguis/codeigniter-restserver#1149]
We've been using your code in [Kalkun](https://github.com/kalkun-sms/Kalkun/). However, I saw that in your latest version, you added a class Format.php licensed under http://www.dbad-license.org/

I'm in the process of adding kalkun to Debian, and we are using/distributing your classes in it. However this file can't be accepted because its license is not [DFSG](https://wiki.debian.org/DebianFreeSoftwareGuidelines) compliant. So this is somewhat a problem.

Is this intended given that the project is licensed under MIT? Could it be relicensed?

**Comment by chriskacerguis** [comment]
Sorry for the delay, it should have been under MIT.  I have updated the code.  Thanks!
