### ISSUE TITLE
Status=0, Error=Unknown Method

### ISSUE THREAD

**Issue by mariostasos** [chriskacerguis/codeigniter-restserver#169]
Hello, i am trying to implement a simple xml output  using your library and I constantly get this as output.

<xml>
<status>0</status>
<error>Unknown method.</error>
</xml>

this my function

public function index_get()
    {
        $this->load->model('records');
        $records = $this->records->get_records();

```
    $this->response($records2);
}
```

**Comment by shahnawaz-root** [comment]
call method without _get instead index_get

correct url : base_url/controller/index
