### ISSUE TITLE
Default format not changing?

### ISSUE THREAD

**Issue by edwardmp** [chriskacerguis/codeigniter-restserver#181]
Hi,

Thanks for this great piece of code!
Having a small problem. I want the JSON format as default output because I don't want to append /format/json/ on every URI.

I changed REST_Controller.php to modify the order.
But it doesn't seem to change anything.

``` /**
     * List all supported methods, the first will be the default format
     *
     * @var array
     */
    protected $_supported_formats = array(
        'json' => 'application/json',
        'xml' => 'application/xml',
        'jsonp' => 'application/javascript',
        'serialized' => 'application/vnd.php.serialized',
        'php' => 'text/plain',
        'html' => 'text/html',
        'csv' => 'application/csv'
    );
```

`

**Comment by brutalcrozt** [comment]
is it possilbe to override the `rest_default_format` in controller?
in this case my default format is `json` , but i want override on runtime when sending html template.
i use `echo` it just fine, but look's so ugly

**Comment by philsturgeon** [comment]
What is the use case here? The point of default is that it's default, right? So ask folks to send different Accept headers if they want different content. Sending different defaults per endpoint is inconsistent and violates the principle of least surprise. 

If it has no JSON to output, you can output a 415 with a body explaining that HTML is available. 

--
Phil Sturgeon

**Comment by brutalcrozt** [comment]
I change default to `json` because i use angular on frontend. But along the way i sent html template also, right before sending the respone (`html template`) i change `$this->response->format = 'jsonp';` i get what i expected. I know it's inconsistent and violates, but any suggestion?
Thanks for your response and also thanks for writing useful lib :smile:
