### ISSUE TITLE
Unable to load the requested class: Security

### ISSUE THREAD

**Issue by bourou01** [chriskacerguis/codeigniter-restserver#225]
I have gotten this issue with the latest Codeigniter version

I got it works commenting the line "//$this->load->library('security');" at line 173

**Comment by nifrasismail** [comment]
load with relative path from library folder it should work
```
$this -> load -> library('../core/security');
```

**Comment by tanero** [comment]
I have such an issue today while trying to upgrade my project from codeigniter 2.x to 3.x. As I understand, codeigniter changed the security library as helper. That is the reason of this message coming.

**Comment by Abdulmanan0315** [comment]
@tanero Thanks for that it is working when used as helper autoload.
