### ISSUE TITLE
Wrong HTTP Method Being Routed

### ISSUE THREAD

**Issue by tomwerneruk** [chriskacerguis/codeigniter-restserver#233]
Hi,

Not sure if this is a bug or config issue. I have the following controller;

``` php
<?php  
require(APPPATH . '/libraries/REST_Controller.php');  
class Api extends REST_Controller {  
    function memberleads_post() {
        $this->response("OK " . $this->post('name') , 200);
    }
    function memberleads_get() {
        $this->response("OK GET" , 200);
    }
}
?>
```

My POST requests (tried jQuery AJAX, curl and Firefox client) all get routed to the get function, if i remove the get, I then get a 404. A POST is definately being sent as I can see it via packet trace. Any suggestions? Do I need  to 'trust' posts in CI anywhere?

Cheers,
Tom

**Comment by glemiere** [comment]
I exactly have the same problem.
Did you fix it ?
