### ISSUE TITLE
Format.php Error Issue

### ISSUE THREAD

**Issue by faisalbasra** [chriskacerguis/codeigniter-restserver#235]
I setup the project, and while request xml its fine. But when requesting JSON, its giving me the following error.

<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>

<p>Message:  Array to string conversion</p>

<p>Filename: libraries/Format.php</p>

<p>Line Number: 203</p>

</div>id,name,email
"1","Some Guy","example1@example.com"
"2","Person Face","example2@example.com"
"3","Scotty","example3@example.com","Array"

**Comment by webalchemist** [comment]
This fix is wrong and should be reversed. It breaks CSV output.

CSV SHOULD be able to handle multi-dimensional arrays (they HAVE to be 2 dimensional).  It works fine without this 'fix' but can't ever work with it.

Just a few lines higher in the same method it checks for multi-dimensional arrays to set the headings correctly. So its obviously intended to handle multi-dimensional arrays.  The docs also say that you can pass in objects or arrays.

The original error report was about the output when a single value was an array - NOT a whole row.

**Comment by webalchemist** [comment]
You have a had a number of other issues reporting CSV output errors.  I believe this may be the root cause  i.e., #278, #360, #375

**Comment by chriskacerguis** [comment]
Hello @webalchemist,

I'm waiting to see what's going on with CI 3.0, but if you would like to submit a fix for this in the meantime, I'm happy to merge.

**Comment by webalchemist** [comment]
I was going to send a pull request, but since I just want 1 change reversed it didn't seem worthwhile.

I've just reversed this change to get it working for me (can't guarantee that it doesn't break it for anyone else)
https://github.com/chriskacerguis/codeigniter-restserver/commit/b7fe4ab7aa0c571ec398c70f9783cc3dfde5ffa8
