### ISSUE TITLE
PUT Requests being incorrectly routed

### ISSUE THREAD

**Issue by AlgyTaylor** [chriskacerguis/codeigniter-restserver#255]
The put requests seem to be going to the wrong place if you give additional variables, for example if I have

class Users extends REST_Controller {
 function index_put($id) {
    // do something
 }
}
and send a put request to "/users/13", it remaps it as
"13_put" and not "index_put(13)" as expected.

In other news, big up to Phil Sturgeon, who is a man I owe several beers to!

**Comment by joskarthic** [comment]
restserver api delete function not working in codeigniter
