### ISSUE TITLE
PUT does not send parameters

### ISSUE THREAD

**Issue by mulama77** [chriskacerguis/codeigniter-restserver#263]
GET, POST and  DELETE are working perfectly but for some reason PUT is not sending parameters.

i came accross this code 

if ($_SERVER["REQUEST_METHOD"] == "PUT") {
    parse_str(file_get_contents("php://input"), $post_vars);
    $arData = json_decode(array_pop(array_keys($post_vars)));
}

http://www.sitepoint.com/goodbye-codeigniter-hello-laravel/

can i use it in the project?

**Comment by valjar** [comment]
HI!

I'm probably facing same issue, but i don't get it how to fix it.

This is my controller function code:
function task_put(){
        // update task
        $id = $this->get('id');
        $data = array(
            'task' => $this->put('task'),
            'active' => $this->put('active'),
            'date_u' => date("Y-m-d h:i:s")
        );
        var_dump($data, $id);
        die();
        $result = $this->tm->update($this->get('id'), $data);
        if($result === FALSE){
            $this->response(array('status' => 'failed'));
        }else{
            $this->response(array('status' => 'success'));
        }
    }

And this is the result of calling this function:
![untitled](https://cloud.githubusercontent.com/assets/8543041/10416606/293e01e6-701d-11e5-8270-a78f1aee46da.png)

All other methods(GET, POST, DELETE) are working.
Can you please help?

**Comment by valjar** [comment]
Ok i found a soultion.
In post man you should switch from form-data to x-www-form-urlencoded and now it's working
