### ISSUE TITLE
RESTSEVER with $config['csrf_protection'] = TRUE;

### ISSUE THREAD

**Issue by mehtatejas** [chriskacerguis/codeigniter-restserver#274]
I am trying to implement client - server app where server also has UI. 
I have implemented $config['csrf_protection'] = TRUE; in server config.
Now I am getting "The action you have requested is not allowed."
Please guide to fix this issue.

Thank you.
Tejas

**Comment by nanachi-code** [comment]
temporarily disable csrf_protection doesn't work for me tho.

**Comment by zomkarm9992** [comment]
add this in config.php
$config['csrf_exclude_uris'] = array('CONTROLLER/FUNCTION_NAME');
it worked for me...!
