### ISSUE TITLE
Digest Library Auth not working

### ISSUE THREAD

**Issue by robinwo** [chriskacerguis/codeigniter-restserver#283]
In config rest.php I enabled digest authentication and defined a custom library for handling it.

```
$config['rest_auth'] = 'digest';
$config['auth_source'] = 'library';
$config['auth_library_class'] = 'Api_auth';
$config['auth_library_function'] = 'login';
```

The library:

```
class Api_auth
{
    public function login($username, $password) {
        if($username == 'hello' && $password == 'world')
        {
            return true;            
        }
        else
        {
            return false;           
        }           
    }
}
```

Now if I use the username 'hello' and password 'hello', the credentials are not accepted. When I do an error_log of $username and $password in the login() function, only $username appears in the logs. Looks like $password is not being passed to the login() function.

When I switch from 'digest' to 'basic' authentication, the credentials are both passed to the login() function (appear in logs), and credentials are accepted.

So something seems to go wrong using digest authentication and a custom authentication library.

**Comment by parmarmayur9090** [comment]
hello  i have also same problem with basic authentication
