### ISSUE TITLE
POST request with AngularJS fails with preflight OPTIONS status code = 404

### ISSUE THREAD

**Issue by edouard-lopez** [chriskacerguis/codeigniter-restserver#313]
My front-end application is running on a `grunt` live server on port `9100`, while my PHP server is on the port `80`. The host is the same, just the port differ.

When I send a `POST` request to `http://dev.site.dev/api/gist` with some `JSON` data, I got an error `404` on the preflight `OPTIONS` request.

I already added the `CORS` headers in apache configuration: 

``` ApacheConf
Header set Access-Control-Allow-Origin "*"
Header set Access-Control-Allow-Headers "X-Requested-With, accept, content-type"
Header set Access-Control-Allow-Methods "PUT, GET, POST, DELETE, OPTIONS"
```

and restart the server but still got the issue.

Should I add an `index_option()` method in my `gist` controller ? Or the problem is somewhere else ?

**P.S.:** also posted on stackoverflow: [POST request with AngularJS fails with preflight OPTION status code = 404 with CodeIgniter ResetServer](http://stackoverflow.com/q/23954433/802365)

**Comment by victorylee** [comment]
now OPTIONS request is true, but the POST request doesn't send, I don't know why

**Comment by hikmat-sijapati** [comment]
Exactly Same problem here.. i search everywhere and spent a lots of hours but problem not solve. @victorylee did you solve this problem?
