### ISSUE TITLE
Can't read $this->post('username'); from rest client form

### ISSUE THREAD

**Issue by januarfonti** [chriskacerguis/codeigniter-restserver#322]
Why $this->post('username') can not read input from rest client ?

In my controller for server : 

```
function login_post(){
    $data['username']=$this->post('username');
    $data['password']=$this->post('password');
if($this->get('cobak')==1){ 
    $cek = $this->model_user->ambilPengguna($data);
    } 
if($cek){$this->response($cek, 200); // 200 being the HTTP response code}
    else{
            $this->response(array('error' => 'User could not be found'), 404);
           } }
```

My models : 

```
public function ambilPengguna($data) {
          $this->db->select('*');
          $this->db->from('tbl_user');
          $this->db->where($data);
          $query = $this->db->get();
          return $query->num_rows();
      }
```

And this is my client controller : 

```
public function proses_login(){ 
    $data = array(  'username' => $this->input->post('username'), 
                    'password' => $this->input->post('password')
                ); 
    $cek = $this->rest->post('login/cobak/1/format/php/'); 
    echo $cek;
}
```

**Comment by gadaica3** [comment]
I solved this:
https://stackoverflow.com/questions/19183311/codeigniter-removing-index-php-from-url

**Comment by gadaica3** [comment]
Good luck all!

**Comment by usamacode** [comment]
Hi,
I'm getting null values, when using $this->post(); 
Here is my method:
`public function users_post()
    {
        var_dump($this->post()); // output here is array(0){}
        $message = [
            'id'        => 100, // Automatically generated by the model
            'name'      => $this->post('name'), // null
            'email'     => $this->post('email'),  // null
            'message'   => 'Added a resource'
        ];
        // var_dump($_REQUEST); // in the request, I'm getting the data perfectly
        $this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
    }`

Can anybody help here, please?
