### ISSUE TITLE
Upload Image

### ISSUE THREAD

**Issue by elsaBl** [chriskacerguis/codeigniter-restserver#324]
Hi,

I can't upload a file on my API. 

I tried this solution : http://stackoverflow.com/questions/7077666/codeigniter-and-restserver-how-to-upload-images/18774050#18774050

And I tried this : https://github.com/philsturgeon/codeigniter-restserver/issues/48

$this->request->body and $this->post() is empty. 
I have no idea, please help me :)

**Comment by bobbysiagian** [comment]
Anyone can answer this question?
I've got same case too.

Need help.

**Comment by Userlocal2** [comment]
I've made some solution
Client side

                $content = file_get_contents($file_path);
                $data_send['image'] = base64_encode($content);

Ther send like a array of params and then on e server

$image_content = base64_decode($image['image']);
        $image_path = $image['name'];

        $info = pathinfo($image_path);
        $image_name = $info['filename'] . '.' . $info['extension'];

file_put_contents($image_path, $image_content);

Somsing like that

P.S. this is the parts of a big code, i used CI libraries adn Drivers? thats why prev. code can not be simply executed, use it as a parts example
