### ISSUE TITLE
JSON Result

### ISSUE THREAD

**Issue by jfgreco** [chriskacerguis/codeigniter-restserver#327]
I am running into an issue returning a result set from the data base. The XML output is perfect but when I change to JSON errors are being raised:

Severity: Warning
Message:  mb_detect_encoding() expects parameter 1 to be string, object given
Filename: libraries/Format.php
Line Number: 233

Severity: Warning
Message:  utf8_encode() expects parameter 1 to be string, object given
Filename: libraries/Format.php
Line Number: 235

The issue is that the $item trying to be encoded is an row object from the result and the function is expecting a string. 

I am just calling the index_get() as follows:

public function index_get()
    {
        $this->response($this->db->get('pending')->result());
    }

Any thoughts?

**Comment by Blasz** [comment]
This is a regression. Array of objects worked with previous versions of REST_Controller like 2.6.0
