### ISSUE TITLE
With HMVC Modular Extension error

### ISSUE THREAD

**Issue by murugavelit10** [chriskacerguis/codeigniter-restserver#341]
Hi, I'm using the modular extension from https://bitbucket.org/wiredesignz/codeigniter-modular-extensions-hmvc. Then i want to make use of your REST Controller all over my project. Integrated your REST_Controller.php into application/libraries, rest.php to application/config.
When i try to auto load REST_Controller i'm getting this following weird error message.

Fatal error: Cannot instantiate abstract class REST_Controller in /Applications/XAMPP/xamppfiles/htdocs/project/system/core/Loader.php on line 1099.

I modified your REST_Controller.php file slightly. Made it to extend from MX_Controller instead of CI_Controller.

No other changes. Please help me to solve this issue.

Thanks,
Murugavel.N

**Comment by jsieler** [comment]
This is still not resolved or??

**Comment by bayurepo** [comment]
the same case, I also use HMVC on my system and it really helps in flexibility. Can this package be integrated with it? Really hope it happens.
Can you help ?

In my case, I had to do it manually by changing the CI_Controller extends to MX_Controller.
