### ISSUE TITLE
Extending Controllers

### ISSUE THREAD

**Issue by orzilca** [chriskacerguis/codeigniter-restserver#358]
Hi,

Is it possible to to that:

Class Foo extends REST_Controller {}
Class Bar extends Foo {}

and then use both http://host.com/foo/method/
and also http://host.com/foo/bar/method/

couldn't get this to work.

I'm asking this because my controllers became to big - each controller file contains around 10-20 methods (some files are ~1000 lines of code) - its very messy...

**Comment by orzilca** [comment]
anyone?

**Comment by chriskacerguis** [comment]
Hello @orzilca 

I guess I'm not understanding what you need.  Per your original ticket, due to limitation of CI, you can't really do that (you could, but you'd need to do a lot of extra work).  I don't recommend that people do that, and I don't have examples either.

**Comment by orzilca** [comment]
If its a CI limitation than I'll pass..

I just wanted to create a proper rest routing and break big controllers into small controllers

meaning that all the stuff related to Account will nest under account
```
Account - account.php
Account/Billing - account/billing.php
Account/Settings/Password - account/settings/password.php
```

instead of account.php with
```
index_get()
billing_get()
settings_get()
```
