### ISSUE TITLE
Using this library with ion_auth

### ISSUE THREAD

**Issue by llKoull** [chriskacerguis/codeigniter-restserver#368]
Good morning!

I'm already using this fantastic library in some projects but now i've got a question.

I'm using code igniter 2.2.0 with ion_auth library to authenticate my users but now I need to create some restful services and i want to use this library. I saw that in rest.php I can change the rest_auth parameter to 'digest' and that I can define the auth_source as a 'library', the problem is that I don't know if I can set ion_auth library as authentication library. Anyone knows how can I use It?

Thanks!

**Comment by priddhi** [comment]
Hi Chris.. m getting an issue in rest config file..
I want to enable logging and digest but cant
If i write $config['rest_auth'] = "digest"; it shows me error
The configuration file ldap.php does not exist.

Please help me with this....
