### ISSUE TITLE
Loading Model in Controller doesn't work

### ISSUE THREAD

**Issue by yves-s** [chriskacerguis/codeigniter-restserver#369]
**If my controller extends the _REST_Controller_ I can't load my model anymore.**

To test the functionality I have a simple class like:
**Controller**

```
class Example extends CI_Controller {
    public function example_get() {
        $this->load->model('example_model');
        $news = $this->example_model->get($this->get('id'));
        print_r($news);
    }
}
```

**Model**

```
class Example_model extends CI_Model {
  public function get($id) {
      $users = array(
        1 => array('id' => 1, 'title' => 'Some Guy'),
        2 => array('id' => 2, 'title' => 'Person Face'),
        3 => array('id' => 3, 'title' => 'Scotty'),
      );
      return $users[$id];
  }
}
```

I get the result printed

If I now change my Controller from `CI_Controller` to `REST_Controller`

```
class Example extends REST_Controller
```

I get nothing

I copied
- REST_Controller.php
- Format.php
  > libraries
- rest.php
  > config

I even tried it with the example project and it doesn't work either.

Is there a different way to load the model with the REST Controller?

**Comment by kalyankumarakula28** [comment]
I am also getting the same problem but model is loading
1.$this->load->model('Admin_db');
 2.$data=$this->Admin_db->getimg($param2,$param3);
if you print any variable that were passed to controller are printing  before second line.
After 2nd line ,variable is not printing.
here is my model
function getimg($vendor_id,$vendor_pid){
$res =$this->db->query(" SELECT  project_gallery FROM projects where vendor_id='$vendor_id' and id='$vendor_pid' ");
	
	if ($res)
		{
            return $res->result_array();
        } 
		else 
		{
            return null;
	    }
}
what might be the error please help
