### ISSUE TITLE
Authentication problem

### ISSUE THREAD

**Issue by Jakezheng** [chriskacerguis/codeigniter-restserver#381]
$config['rest_auth'] = 'basic';
$config['auth_source'] = '';
$config['rest_valid_logins'] = array('admin' => '1234');

The pop up windows seems never pass my input username and password to the back end.

**Comment by fajriroq** [comment]
> Hello,
> 
> I'm sorry, I'm not understanding the problem. You said "I have copy the project to my server and everything works fine, i can't figure out why" Could you please help me understand the problem a bit better?
> 
> Chris

![image](https://user-images.githubusercontent.com/86406309/180663462-56f18018-0e3f-4e0d-b86c-f30af64413ab.png)
>how i set data rest valid logins using from database
>$config['rest_valid_logins'] = ['admin' => '12345'];
