### ISSUE TITLE
rtime bug?

### ISSUE THREAD

**Issue by enlivenapp** [chriskacerguis/codeigniter-restserver#382]
Hi Chris,

I think I may have found a bug.  Still not delved too deep into the code though.  Also I'm incorporating this into PyroCMS 2.2.x, so some things are slightly different.

in the function below:

```
   protected function _log_access_time()
    {
         $payload['rtime'] = $this->_end_rtime - $this->_start_rtime;

        return $this->rest->db->update(config_item('rest_logs_table'), $payload, array('id' => $this-      >_insert_id));
    }
```

Shouldn't this be?:
    ...

```
    $payload['time'] = ...

...
```

**Comment by wbc-mike** [comment]
Hi Chris,

No worries,  I'm very familiar with CI.  I looked into this a bit more and now have it working properly.  PyroCMS 2.2.x (Pro) comes with a REST config file already, but not with the Rest controller or Format and I hadn't realized you/phil had made some changes to the SQL.

My version didn't have the 'rtime' column in the logs SQL.

My Version:

    CREATE TABLE `logs` (
	  `id` int(11) NOT NULL AUTO_INCREMENT,
	  `uri` varchar(255) NOT NULL,
	  `method` varchar(6) NOT NULL,
	  `params` text NOT NULL,
	  `api_key` varchar(40) NOT NULL,
	  `ip_address` varchar(15) NOT NULL,
	  `time` int(11) NOT NULL,
	  `authorized` tinyint(1) NOT NULL,
	  PRIMARY KEY (`id`)
	) ENGINE=MyISAM DEFAULT CHARSET=utf8;


So, for anyone wanting to use the Rest Server on PyroCMS <= 2.2.x:  Either purchase the API (which can deal with the keys for you automagically) or create your own API module. Rest files goes in your module/libraries file

1: replace your /system/cms/config/rest.php file with the one provided here. (Make sure to keep a copy of the old one so you can transfer over the preferences)
2: add rtime to logs table if you've already created it
3: 

    abstract class REST_Controller extends Public_Controller  
    // not CI_Controller

4: Getting a DB connection seems to be fairly impossible with the current code so: (this feels a little clunky, is there a better way Chris/Phil?)

add this after line 235 in Rest_Controller.php

         // punt with CI?
        else
        {
            $this->rest =& get_instance();
        }

5: required include: (assuming in [site_ref]

    require ADDONPATH . 'modules/[your module name]/libraries/REST_Controller.php';

That should get it working.  Again, it's only for PyroCMS
