### ISSUE TITLE
error handling format json/xml

### ISSUE THREAD

**Issue by scarings** [chriskacerguis/codeigniter-restserver#383]
hi,i'm new to use CI,and i'm using your library can you teach me, how handling some error like error 500 to json/xml format?

example:
i'm trying to insert some data to database with duplicate entry,and get some error 500 internal server 
how to change A Database Error Occurred [CI format] to,
 json format {"error":"internal server error 500"}

thank you :)

**Comment by chriskacerguis** [comment]
Hello @scarings,

Here's an article that can point you in the right direction.

http://thecancerus.com/simple-way-to-add-global-exception-handling-in-codeigniter/

I've thought about incorporating something like that into the code, however for sites that aren't just an API doing something like that could cause problems.
