### ISSUE TITLE
How to return Chinese characters in json 

### ISSUE THREAD

**Issue by Jakezheng** [chriskacerguis/codeigniter-restserver#384]
I got something like this [{"ITEM_ID":"1","ITEM_NAME":"\u4e2d\u6587","ITEM_DESCRIPTION":"\u4e2d\u6587","ITEM_LOCATION":"\u5168\u90fd\u662f\u4e2d\u6587","ITEM_PRICE":"\u6211\u53bb\u7e41\u9ad4","ITEM_STATUS":"\u770b\u770b","ITEM_PICTURES":"\u7b80\u4f53"}]

please advise what should I do

Thanks
Jay

**Comment by chriskacerguis** [comment]
Can you confirm that you have the correct values in your database?

**Comment by Jakezheng** [comment]
![capture](https://cloud.githubusercontent.com/assets/10144358/5604056/75a35c44-9372-11e4-8f7d-15e5a0a9c2b4.PNG)


<html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">[{"ITEM_ID":"1","ITEM_NAME":"\u4e2d\u6587","ITEM_DESCRIPTION":"\u4e2d\u6587","ITEM_LOCATION":"\u5168\u90fd\u662f\u4e2d\u6587","ITEM_PRICE":"\u6211\u53bb\u7e41\u9ad4","ITEM_STATUS":"\u770b\u770b","ITEM_PICTURES":"\u7b80\u4f53"}]</pre></body></html>

**Comment by Jakezheng** [comment]
When consume the API using angular JS everything is in Chinese.
Do you know why?

**Comment by Jakezheng** [comment]
I have another question 
How to work with rounting to make the API URL something like this
http://example.com/books
http://example.com/book/id/1

**Comment by Jakezheng** [comment]
Sloved Thanks
