### ISSUE TITLE
Post request

### ISSUE THREAD

**Issue by Jakezheng** [chriskacerguis/codeigniter-restserver#385]
The following is my post request. I dose not working properly, I passed parameter to it and everything becomes false. 

Also, I am not able to make PUT and DELETE call. don;t know why .
The error message is "XMLHttpRequest cannot load www.host.com/api* Invalid HTTP status code 404 "

i am using plunker to test my api

![capture](https://cloud.githubusercontent.com/assets/10144358/5657853/51a285ae-96c4-11e4-92e7-b944dfb339bf.PNG)
![capture1](https://cloud.githubusercontent.com/assets/10144358/5657854/51a54f1e-96c4-11e4-9950-94ccecae9a6c.PNG)

function item_post()
    {
		if($this->post('name')&&$this->post('description')&&$this->post('condition')&&$this->post('location')&&$this->post('price')&&$this->post('pictures')&&$this->post('account_id')&&$this->post('category_id'))
		{
			$this->load->database();
			
				$data = array(
				   'ITEM_NAME' => $this->post('name'),
				   'ITEM_DESCRIPTION' => $this->post('description') ,
				   'ITEM_CONDITION' => $this->post('condition'),
				   'ITEM_LOCATION' => $this->post('location'),
				   'ITEM_PRICE' => $this->post('price'),
				   'ITEM_PICTURES' => $this->post('pictures'),
				   'ACCOUNT_ID' => $this->post('account_id'),
				   'CATEGORY_ID' => $this->post('category_id')
				   );
				$this->db->insert('ITEMS', $data); 
				$insert_id = $this->db->insert_id();     
				$this->db->trans_complete();
		
				if ($this->db->trans_status() === FALSE)
				{
					 $this->response(array('error' => 'query failed '), 400);
				}
				else
				{
				$message = array('ITEM_ID' => $insert_id, 'ITEM_NAME' => $this->post('name'), 'ITEM_DESCRIPTION' => $this->post('description'), 'ITEM_CONDITION' => $this->post('condition'), 'ITEM_LOCATION' => $this->post('location'), 'ITEM_PRICE' => $this->post('price'), 'ITEM_PICTURES' => $this->post('pictures'), 'ACCOUNT_ID' => $this->post('account_id'), 'CATEGORY_ID' => $this->post('category_id'),'message' => ' ITEM ADDED!');
			
				$this->response($message, 200); // 200 being the HTTP response code
				}
		}
		else
		{
			$this->response(array('ITEM_NAME' => $this->post('name'), 'ITEM_DESCRIPTION' => $this->post('description'), 'ITEM_CONDITION' => $this->post('condition'), 'ITEM_LOCATION' => $this->post('location'), 'ITEM_PRICE' => $this->post('price'), 'ITEM_PICTURES' => $this->post('pictures'), 'ACCOUNT_ID' => $this->post('account_id'), 'CATEGORY_ID' => $this->post('category_id'),'message' => 'Something Wrong!'));
		}
    }

**Comment by chriskacerguis** [comment]
Have you setup your routes to handle the additional URI segments?

**Comment by Jakezheng** [comment]
YEAH 
I have added three
the one related to item table is 
$route['items'] = "api/item_class/items";

So i can get all items using url "www.host.com/items";


Thank you

**Comment by chriskacerguis** [comment]
what happens if you just go to that URL in your browser?

**Comment by Jakezheng** [comment]
I use https://www.hurl.it/  to sent post request and everything is fine. When I use javascript, there are problems.  

I am able to use PUT in https://www.hurl.it/.

Do you think there is problem with my request?

**Comment by Jakezheng** [comment]
UPDATE: I think there is something wrong with angularJS 
The POST request works fine with Jquery.

But the PUT and DELETE is still not working.
XMLHttpRequest cannot load http://host.com/index.php/api/item_class/item. Invalid HTTP status code 404

Any idea? 

function item_delete()
    {
		if($this->delete('id'))
		{
			$this->load->database();
			
			$data = array(
				   'ITEM_STATUS' => 'INACTIVE'
				);

			$this->db->where('ITEM_ID', $this->delete('id'));
			$this->db->update('ITEMS', $data); 
			$this->db->trans_complete();
			
			if ($this->db->trans_status() === FALSE)
			{
				 $this->response(array('error' => 'query failed '), 400);
			}
			else
			{
			
			$message = array('id' => $this->delete('id'), 'message' => 'DELETED!');
			$this->response($message, 200); // 200 being the HTTP response code
			}
		}
		$this->response(NULL, 400);
    }

**Comment by chriskacerguis** [comment]
If it is working with jQuery and not AngularJS then seems like the Rest server is working fine.  I'd reach out to the AngularJS folks.

**Comment by grantgeorge** [comment]
@Jakezheng I had to use x-www-form-urlencoded Content-Type for PUT

![image](https://cloud.githubusercontent.com/assets/4458680/5729311/7995293e-9b3f-11e4-8f44-4133e3b2e1ae.png)
