### ISSUE TITLE
customize xml render

### ISSUE THREAD

**Issue by chhumsina** [chriskacerguis/codeigniter-restserver#386]
Dear Mr.,

Could you tell me how to render xml format like the below:

![capture](https://cloud.githubusercontent.com/assets/3894767/5694356/9a07db50-9985-11e4-9a23-99fd0285937b.JPG)

Thanks you so much :)

**Comment by chriskacerguis** [comment]
Hello,

Unfortunately, restserver cannot generate XML like that at this time.  I'm going to leave this issue open as a "todo" item.

**Comment by chhumsina** [comment]
Thanks you I will wait for that :)

**Comment by softwarespot** [comment]
Something like this >> http://www.lalit.org/lab/convert-php-array-to-xml-with-attributes/

**Comment by softwarespot** [comment]
@chriskacerguis,

Are you sure this can't be done with the the XML formatter? As looking at the code (I don't serve XML, only json) if the @chhumsina uses _attributes as the key and then an array of attributes, they would get the desired affect above. Of course I don't blame anyone for not knowing this, lack of documentation from the original developer is to blame for this.

Anyway, http://www.lalit.org/lab/convert-php-array-to-xml-with-attributes/ OR http://www.viper007bond.com/2011/06/29/easily-create-xml-in-php-using-a-data-array/ is perhaps a good basis for a legible re-write.

**Comment by softwarespot** [comment]
This can be closed
