### ISSUE TITLE
Add compatibility with Composer

### ISSUE THREAD

**Issue by NicolasMahe** [chriskacerguis/codeigniter-restserver#387]
Hi. First of all thank you for this module, it's a great job.

I would like to suggest to add the compatibility with [Composer](https://getcomposer.org), a dependency manager for PHP.

#### Add Composer

You just have to add a `composer.json` file in the root directory that could contain :
```javascript
{
	"description" : "A fully RESTful server implementation for CodeIgniter using one library, one config file and one controller",
	"name" : "chriskacerguis/codeigniter-restserver",
	"license": "MIT",
	"require": {
		"php": ">=5.2"
	}
}
```
and submit the package to https://packagist.org.

However, to do it in a clean way, you should keep only the files of RestServer:
```
application/config/rest.php
application/libraries/Format.php
application/libraries/REST_Controller.php
```
and **delete all the files of CodeIgniter**.

Moreover, CodeIgniter is compatible with [third_party packages](http://www.codeigniter.com/userguide3/libraries/loader.html#application-packages) since at least v2.
It allows to include packages that are not necessarily in the `application/third_party` folder and thus to include the folder of RestServer downloaded by Composer.

So, I think the best file organisation for this repository to respect CodeIgniter's third_party package will be:
```
config/rest.php
libraries/Format.php
libraries/REST_Controller.php
composer.json
LICENSE.txt
README.md
```

#### Expected installation
To install RestServer by Composer, you will just have to add this repository to the `composer.json` require field or run `composer require`. Then you need to run `composer install` to download the packages.
It will download RestServer to the vendor folder `vendor/chriskacerguis/codeigniter-restserver`.

To install RestServer in CodeIgniter, you should autoload it by adding its path to the `$autoload['packages']` array in `application/config/autoload.php`:
```php
/*
| -------------------------------------------------------------------
|  Auto-load Packages
| -------------------------------------------------------------------
| Prototype:
|
|  $autoload['packages'] = array(APPPATH.'third_party', '/usr/local/shared');
|
*/

$autoload['packages'] = array(APPPATH.'/../vendor/chriskacerguis/codeigniter-restserver');
```

Then in the controllers that extend `Rest_Controller`, you should set the require to:
```php
require(APPPATH.'../vendor/chriskacerguis/codeigniter-restserver/libraries/REST_Controller.php');

class User extends REST_Controller {
```

If you want to change the config of RestServer, simply copy `vendor/chriskacerguis/codeigniter-restserver/config/rest.php` to your `application/config` folder and start modifying it here.

#### More
I really hope that you add the compatibility with Composer.
I can also send a PR with the modifications described in this issue.

Thank you.

**Comment by chriskacerguis** [comment]
Hi @NicolasMahe 

Thanks for getting in touch.  You bring up a few good thoughts.  

1.  I agree that all "CI core" files, need to be removed and just left with the Restserver files.  I'll take care of that ASAP (it's been on my todo list).

2.  Composer support.  I'm torn on this honestly, I'm a BIG Composer fan, however CI doesn't really support it.  So, I'm not sure it makes sense.  Thoughts?

**Comment by NicolasMahe** [comment]
You are right, CodeIgniter doesn't support Composer's autoload function. So we'll have to manually load the package and require REST_Controller.

But use Composer as a simple dependencies management makes sense. It will automatically download the package from github and keep it update. I think just to have this functionality will be great.

**Comment by chriskacerguis** [comment]
Sure, that makes sense.  Are any other CI "add-ons" (for lack of a better word) doing this?

**Comment by chriskacerguis** [comment]
Ok.  Just to update this ticket.  All non-REST server files have been removed.

**Comment by NicolasMahe** [comment]
Yes, they are other CodeIgniter third parties that use Composer.
After a little search on Packagist, I have find some good examples:
- [codeigniter-forensics](https://github.com/lonnieezell/codeigniter-forensics)
It can be installed by Composer but also by [Sparks](http://getsparks.org/) (a package management system for Codeigniter but I have never heard of it before today) and you load it by `$autoload['packages'] = array(APPPATH.'third_party/codeigniter-forensics');`
- [codeigniter-debugbar](https://github.com/tan5en5/codeigniter-debugbar)
It can be installed by Composer and you load it by `$autoload['packages'] = array(APPPATH.'third_party/codeigniter-debugbar');`

**Comment by NicolasMahe** [comment]
Moreover, Composer is compatible with CodeIgniter third party, library and module.
See [Composer readme](https://github.com/composer/installers/blob/master/README.md) section Current Supported Package Types.
Simply add : `"type": "codeigniter-third-party"` to `composer.json` and it will install it in `application/third_party`

**Comment by elroyjetson** [comment]
Not trying to hijack your thread, but CI 3 includes the ability to use the composer auto-loader.  http://www.codeigniter.com/userguide3/general/autoloader.html

And is currently shipping RC2 so I expect it to ship full release soon.

**Comment by chriskacerguis** [comment]
Hi @NicolasMahe,

Sorry for delay, if you would like to do a pull request, with the mods, I'd be happy to merge.

**Comment by rougin** [comment]
Hello @chriskacerguis! Sorry for digging this but are you still planning to release it using Composer ?

**Comment by chriskacerguis** [comment]
Hello @rougin !

No worries at all.  I would like to, I was waiting on a PR from @NicolasMahe 

Doesn't look like he's going to send one, so it's on my todo list, but making sure that all is working correctly for CI 3.x is the priority right now.

**Comment by rougin** [comment]
Nice! That's good to hear. I will wait for the release. Thanks! :smile: :+1:

**Comment by anthonysomerset** [comment]
I'm working on a PR for this now - i have a vested interest in this being easy to install for me :)

**Comment by softwarespot** [comment]
I use composer all the time, but my concern is CI in general isn't really composer centric. Yes it supports autoloading, but in general third party libraries are added like it was before the likes of a dependency manager existed.

**Comment by anthonysomerset** [comment]
all other discussion happening over on #539 but @softwarespot i agree with you that CI is not Composer Centric and the community tends to not like it or want to use it but that shouldn't exclude those that do use it within CI projects already and ultimately CI won't improve composer support if we don't increase the implementation of composer by getting CI modules and lib's supporting composer natively or near natively
