### ISSUE TITLE
Only variables should be passed by reference error

### ISSUE THREAD

**Issue by Harshdand** [chriskacerguis/codeigniter-restserver#389]
Hi,

I am getting this error when using with Codeigniter 3.0 (dev)
Request :http://localhost/ci/index.php/api/example/user/id/1

<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Runtime Notice</p>
<p>Message:  Only variables should be passed by reference</p>
<p>Filename: libraries/REST_Controller.php</p>
<p>Line Number: 568</p>

	<p>Backtrace:</p>
	
		
	
		
	
		
			<p style="margin-left:10px">
			File: C:\xampp\htdocs\ci\application\libraries\REST_Controller.php<br />
			Line: 568<br />
			Function: _error_handler			</p>

		
	
		
			<p style="margin-left:10px">
			File: C:\xampp\htdocs\ci\application\libraries\REST_Controller.php<br />
			Line: 264<br />
			Function: _detect_output_format			</p>

		
	
		
			<p style="margin-left:10px">
			File: C:\xampp\htdocs\ci\application\controllers\api\example.php<br />
			Line: 24<br />
			Function: __construct			</p>

		
	
		
	
		
			<p style="margin-left:10px">
			File: C:\xampp\htdocs\ci\index.php<br />
			Line: 292<br />
			Function: require_once			</p>

		
	

</div>

But works fine with older version of codeigniter
and the request http://localhost/ci/index.php/api/example/users also works fine with codeigniter 3

**Comment by chriskacerguis** [comment]
Hello,

Thanks for pointing that out, I'll get to working on it.  I haven't tested with the latest CI 3.0-dev.

**Comment by chriskacerguis** [comment]
@Harshdand What version of PHP are you using?

**Comment by chriskacerguis** [comment]
Also, is this with the latest code?

**Comment by Harshdand** [comment]
I am using Php 5.5.15 and codeigniter 3.0 (dev version) http://www.codeigniter.com/download

**Comment by chriskacerguis** [comment]
Sorry, when I said "latest code", I meant is it the latest Rest-server code?

**Comment by Harshdand** [comment]
Yes, it was 340 commit

**Comment by dansanti** [comment]
HI, i've the same issue , ussing get only, but with post an others work fine. I notice that response was found when call $this->response(someArrayAns)   responseText:" error rerported + someArrayAns" ,"status":200.. the error goes on responseText...

**Comment by dansanti** [comment]
Geting back from this commit https://github.com/chriskacerguis/codeigniter-restserver/commit/a1f96644eab251c6098d3cc2ef2ab8290d8d6c24 seems to work, 
changing  line 568

elseif ($this->_get_args and !is_array(end($this->_get_args)) and preg_match($pattern, end(array_keys($this->_get_args)), $matches)) {

by

elseif ($this->_get_args and !is_array(end($this->_get_args)) and preg_match($pattern, end($this->_get_args), $matches)) {

**Comment by BuCeFaL** [comment]
Thanks !
