### ISSUE TITLE
$this->get() returns false on server not on localhost

### ISSUE THREAD

**Issue by eyeway68** [chriskacerguis/codeigniter-restserver#390]
I have this code

      public function get_all_clients( $params )
	{
		//Getting user details from session
		$params['user_company'] = $this->ion_auth->get_user()->company;
		
		$response = $this->rest->get('clients/clients', $params);
		
		return $response;
	}

In the server side the request is captured by this code

    public function clients_get() {

		$params = $this->get();
		
		$clients = $this->get_clients_list($params);
		
		if($clients)
			$this->response($this->_create_client_array($clients), 200);
		else
			$this->response(array('message' => 'Unable to find any clients'), 200);
	}

Although the $params in get_all_clients() method is an array with valid values the $this->get() returns false.

That in my remote server. The same code in my localhost works fine.

Any thoughts?

Thanks!

**Comment by chriskacerguis** [comment]
Just before the $params = $this->get() can you please do a 

var_dump($this->input->post());

and paste the output here?

**Comment by chriskacerguis** [comment]
please do that on the server that it is not working on.

**Comment by eyeway68** [comment]
The output is 
array(0){}

**Comment by chriskacerguis** [comment]
No worries.  Glad you figured it out.
