### ISSUE TITLE
Same method name as the controller name

### ISSUE THREAD

**Issue by thbaymet** [chriskacerguis/codeigniter-restserver#392]
Hi,

When I try to get */api/elements/elements*, then the *index_get()* method invoked and not the *elements_get()*.  Is this a convention ? 

Thanks

**Comment by chriskacerguis** [comment]
So, it would depend on how you have your routes.php file setup.  Without seeing your code, I can't tell you 100% why it's doing what it's doing, but the following routes should get you what you want.

```
// routes.php
$route['api/(:any)']                = 'api/$1';
$route['api/(:any)/(:any)']         = 'api/$1';
```
