### ISSUE TITLE
How to use the API keys

### ISSUE THREAD

**Issue by faidoc** [chriskacerguis/codeigniter-restserver#393]
Hi

I'm a little bit lost.

I'm trying to use the API Keys to talk to the service. I've enabled the api keys in the config and created the keys table in the database.

If I try to make a PUT to domain.com/api/key/index I get Invalid Key, because there's none in the database I can use.

If I disable API keys and make the PUT again I get not response

How do I have to use the feature? Thank you

**Comment by chriskacerguis** [comment]
what is the version of PHP and what is the server you are using (including what OS)?

**Comment by bribar** [comment]
Hi Chris,

I get this same issue, localhost environment, php 5.5.14, CI 3.0.0, MAMP, OSX Yosemite 10.10.5 

PUT http://localhost/gameplan/api/index.php/key/index
or
PUT http://localhost/gameplan/api/index.php/key
=same result

**Comment by shaiman** [comment]
me too
