### ISSUE TITLE
Digest authentication and API keys

### ISSUE THREAD

**Issue by cristiangile** [chriskacerguis/codeigniter-restserver#394]
Hello,
thanks for this great library.
I'm trying to use the digest authentication and the API keys but the condition at line 301 enables the authentication only if the rest api is disabled.

[https://github.com/chriskacerguis/codeigniter-restserver/blob/master/application/libraries/REST_Controller.php#L301](https://github.com/chriskacerguis/codeigniter-restserver/blob/master/application/libraries/REST_Controller.php#L301)

**Comment by c4xp** [comment]
try $config['auth_override_class_method']['api']['xyz'] = ''; in config/rest.php
where xyz is your method..
I know it's kinda'of a hack but it works ;)

**Comment by cristiangile** [comment]
Hello,

thanks for your reply.

I don't want to override the auth method. I need that API keys and Digest
auth coexist.

The condition at line 301

if ($this->auth_override !== true && !(config_item('rest_enable_keys') &&
$this->_allow === true)) {

should be changed to

if(config_item('rest_auth') !== ''){

so we can use API keys + Authentication


Let me know your thoughts.

Thanks
Cristian

2015-01-21 21:04 GMT+01:00 c4 xp <notifications@github.com>:
