### ISSUE TITLE
API limits

### ISSUE THREAD

**Issue by andrefrcastro** [chriskacerguis/codeigniter-restserver#397]
Limits work great if you want to limit per controller/method or if you work with query strings, but if you have an endpoint like this:

http://api.com/method/id/45

... and set a limit of 1000 req/hour for method_get().
If i reach this limit and i request http://api.com/method/46 i have more 1000 req/hour, because the verification is being made by uri and not by api key.

A global limit setting would be great. 
Something like: this key has a limit of 1000 req/hour, regardless the controllers/endpoints.

Folks who use query strings may be ok with this, but if you use segments, limits don't help you much on limiting the access to the application.

Or maybe i just assumed something wrong.

Thanks.

**Comment by andrefrcastro** [comment]
Any thoughts on this?

**Comment by chriskacerguis** [comment]
Hello @andrefrcastro 

I don't have any particular thoughts.  I certainly see where you have a very valid point, the limit section is something that I will be looking as I refactor things for CI 3.0.  

That said, you're welcome to do a PR that would allow that, and we can get that in there.
