### ISSUE TITLE
autoload REST_Controller as library ,but getting 500 Internal Server Error.

### ISSUE THREAD

**Issue by jianzi0307** [chriskacerguis/codeigniter-restserver#398]
```php
// This can be removed if you use __autoload() in config.php OR use Modular Extensions
require APPPATH.'/libraries/REST_Controller.php';
```
I added *$autoload['libraries'] = array('REST_Controller);* in autoload.php.

but getting 500 Internal Server Error.

**Comment by jbraithwaite** [comment]
If you are working in a development environment, changing the environment in [index.php](https://github.com/bcit-ci/CodeIgniter/blob/develop/index.php) causes PHP errors to be displayed. This will help you figure out what exactly is causing the 500 error.

My guess is that you are conflating [__autoload()](http://php.net/manual/en/function.autoload.php) with [CI's autoload](https://github.com/bcit-ci/CodeIgniter/blob/develop/application/config/autoload.php).
