### ISSUE TITLE
Support JSONP

### ISSUE THREAD

**Issue by jzafrilla** [chriskacerguis/codeigniter-restserver#401]
As you can pass "format" paramater, i would like to pass "callback" paramater for JSONP. Example result:

```
jsonCallback(
    {
        "sites":
        [
            {
                "siteName": "SITENAME",
                "domainName": "http://www.domain.com",
                "description": "This is a site description."
            },
            {
                "siteName": "SITENAME",
                "domainName": "http://www.domain.com",
                "description": "This is a site description."
            },
            {
                "siteName": "SITENAME",
                "domainName": "http://www.domain.com",
                "description": "This is a site description."
            },
        ]
    }
);```

**Comment by chriskacerguis** [comment]
I honestly don't know if this was an attempt to put SPAM-like comments out there.  I have edited your issue to remove the obvious SPAM links.  If this is an actual legit issue, please re-create without SPAM links.

**Comment by jzafrilla** [comment]
Chris, this is not a SPAM-like comment. I got this example from a real JSONP response. Sorry for the links. I'm able to use your solution with my requeriments using callback functions as a response without any changes in your code. Thanks.
