### ISSUE TITLE
config rest_auth = session not working

### ISSUE THREAD

**Issue by jpruiz114** [chriskacerguis/codeigniter-restserver#407]
I have debuged the code of the REST_Controller and this feature is not working.

This should be solved to allow the access of the API controllers via a session variable.

**Comment by jpruiz114** [comment]
Thanks @chriskacerguis. Waiting for a reply.

**Comment by chriskacerguis** [comment]
Looks like my response got munged.  Can you please provide me more info?

1.  What behavior are you seeing?

2.  What are you expecting to see?

3.  How are you testing / debugging?

**Comment by jpruiz114** [comment]
Sure @chriskacerguis:

I'm setting up a session variable through another controller. This is the source of the controller where I'm setting up the variable:

https://gist.github.com/jpruiz114/d0d1b672f14bc9069123

The parent class is this one:

https://gist.github.com/jpruiz114/0182e585ff5b45ff7b3e

This controller I'm calling it via CURL like this:

curl --data "username=admin&password=1234567890" http://jeanpaulruizvallejo.com/proyectos/pruebas/ci-rest-a
pi/AuthenticationController/login

The response I get is this:

![image](https://cloud.githubusercontent.com/assets/4614970/6478101/f610ecf6-c1f9-11e4-8961-f1670383b0d0.png)

Then, I call a RestTestController.

My current rest.php file looks like this:

https://gist.github.com/jpruiz114/933fb2e01f5d5ac66ad5

After this I call my RestTestController like this:

curl -X GET http://jeanpaulruizvallejo.com/proyectos/pruebas/ci-rest-api/RestTestController/user/id/1

The response I get is:

{"status":false,"error":"Not Authorized"}

This error comes from line 1343 of the REST_Controller.php file.

I'm not sure if the problem is the CodeIgniter session class that does not handle the PHP native session or if the problem comes from the CI Rest Server but seems like the session variable is not being found.

**Comment by jpruiz114** [comment]
I would expect to be able to access the REST controller (My REST controller) having previously the variable set in session.

**Comment by jpruiz114** [comment]
I believe this is related to the way CodeIgniter handles the session data.
