### ISSUE TITLE
Faill to call ob_start() prior to ob_end_flush()

### ISSUE THREAD

**Issue by rikkouri** [chriskacerguis/codeigniter-restserver#410]
When the `continue` param is set upon calling `$this->request()` method, `REST_Controller.php` will throw the following error:

```php
A PHP Error was encountered

Severity: Notice
Message:  ob_flush(): failed to flush buffer. No buffer to flush
Filename: libraries/REST_Controller.php
Line Number: 509
```
This is caused because the method fails to call `ob_start()` prior to calling `ob_flush()` on line 507. Example of a fix below:

File REST_Controller.php (line 506):
```php
        if($continue){
        	ob_start();
            echo($output);
            ob_end_flush();
            ob_flush();
            flush();
        }else{
            exit($output);
        }
```

**Comment by navotjer** [comment]
Same Notice for me. 
I would recomend using: 
```
if (ob_get_level() == 0) ob_start();
```

So that the ob_start() is not called twice (in case of compression).

**Comment by chriskacerguis** [comment]
Please feel free to do a PR and I'm happy to test/merge.
