### ISSUE TITLE
Included key.php controller example retrieves ignore_limit parameter incorrectly when "0" in put

### ISSUE THREAD

**Issue by JCBuck** [chriskacerguis/codeigniter-restserver#411]
On this line, if a string literal "0" is passed (as is the case if request post body is "ignore_limits=0")
then it would cause the ternary expression to evaluate to false, taking the else expression, numeral 1.

"00" would correctly set $ignore_limits to "00" or 0 into the database.

$ignore_limits = $this->put('ignore_limits') ? $this->put('ignore_limits') : 1;

**Comment by softwarespot** [comment]
Perhaps I misunderstood the problem, but all I did was check if 'ignore_limits' was a digit and then cast as an integer. If not then could someone please clarify the issue. Thanks
