### ISSUE TITLE
Suggestion for logging response_code 

### ISSUE THREAD

**Issue by JCBuck** [chriskacerguis/codeigniter-restserver#412]
I'd like to say thank you for creating such a simple, yet feature-ful REST library for php/Codeigniter!

I am happily utilizing the logging functionality and realized it would be nice to also know the success of the request.  I've duplicated the _log_access_time private method and modified it to update a 'response_code' field in the database.

    protected function _log_response_code($http_code)
    {
        $payload['response_code'] = $http_code;
        return $this->rest->db->update(config_item('rest_logs_table'), $payload, array('id' => $this->_insert_id));
    }

I've added the call in the response() function

    public function response($data = null, $http_code = null, $continue = false)
    {
        //... rest of code
        set_status_header($http_code);
        $this->_log_response_code($http_code);
        //... rest of code
    }

I've appended this for the 'response_code' field in the log schema
```
    `response_code` smallint(3) NOT NULL,
```

I feel this could be something desirable by many, so deciding to drop it in!

**Comment by Tjoosten** [comment]
i would liek to see this. Can u make a pull request?

**Comment by rathodvikas10** [comment]
what if rest_enable_logging is set false? i think this should be checked

**Comment by JCBuck** [comment]
Ahh you're absolutely right, thanks for the catch!
