### ISSUE TITLE
num_rows ins REST_Controller

### ISSUE THREAD

**Issue by csotelo8885** [chriskacerguis/codeigniter-restserver#415]
Hi, I've checked the REST Controller -> _check_access method and I think that it has a small issue on the 1532 line because ($query->num_rows > 0) returns always zero.... actually is ($query->num_rows() > 0)

Regards.

**Comment by likol** [comment]
In my CI 2.2, (num_rows) and (num_rows()) are of equal value :D,I find the code in DB_driver.php, at 387 line, $num_rows got value from num_rows()

**Comment by darkwhispering** [comment]
$query->num_rows() is the documented method and is what should be used. The $query->num_rows property is undocumented and meant for internal use only.

See comment from the main maintainer for CI. http://forum.codeigniter.com/thread-1622-post-7304.html#pid7304

**Comment by chriskacerguis** [comment]
This was fixed in a PR
