### ISSUE TITLE
A PHP Error was encountered

### ISSUE THREAD

**Issue by nesbtesh** [chriskacerguis/codeigniter-restserver#419]
Hi I get the following error:

Parse error: syntax error, unexpected ';', expecting ')' in /Users/*****/repos/******/api/codeigniter/application/libraries/REST_Controller.php on line 1188
A PHP Error was encountered

Severity: Parsing Error

Message: syntax error, unexpected ';', expecting ')'

Filename: libraries/REST_Controller.php

Line Number: 1188

Backtrace:

 I am having a hard time finding the solution any Ideas?

**Comment by nesbtesh** [comment]
<?php defined('BASEPATH') OR exit('No direct script access allowed');

// This can be removed if you use __autoload() in config.php OR use Modular Extensions
require APPPATH.'/libraries/REST_Controller.php';
 
class hello extends REST_Controller
{
	
    function test_get() {
    $data = array();
    $data['name'] = "TESTNAME";
    $this->response($data); 
 }

}

//this si my code

**Comment by infinit89** [comment]
This is fixed in this pull request:

https://github.com/chriskacerguis/codeigniter-restserver/pull/421
