### ISSUE TITLE
API key based authorization

### ISSUE THREAD

**Issue by shivamdixit** [chriskacerguis/codeigniter-restserver#423]
Is it possible to restrict some functions to be accessible only by specific API key? For example, I've 3 methods:
```
foo_post
bar_post
baz_post
```
and two API keys:
```
XYZ
ABC
```

I want `bar_post` *NOT* to be accessible via `XYZ` key.

**Comment by bencagri** [comment]
You want oauth. This library is usefull for rest. Two are kinda diffirent things. Check this link for more clear. https://github.com/bshaffer/oauth2-demo-php

**Comment by shivamdixit** [comment]
Thanks for your response. I don't want OAuth specifically, but only want some level of authorization in REST library.

**Comment by chriskacerguis** [comment]
Hello @shivamdixit 

I'm not sure that's something that I would put into the lib, @bencagri has a point.  That said, the REST server has support for a custom auth lib, so you could use that.
