### ISSUE TITLE
Fatal error: Call to undefined method CI_Input::method() in application/libraries/REST_Controller.php on line 988

### ISSUE THREAD

**Issue by bugyak** [chriskacerguis/codeigniter-restserver#431]
CodeIgniter 2.1.4 
Fatal error: Call to undefined method CI_Input::method() in application/libraries/REST_Controller.php on line 988

**Comment by chriskacerguis** [comment]
https://github.com/chriskacerguis/codeigniter-restserver/blob/master/application/libraries/REST_Controller.php#L988

**Comment by bugyak** [comment]
yes i used latest lib
and i use CodeIgniter 2.1.4 
when i visit /api/example 
error

**Comment by bugyak** [comment]
can you test it in CodeIgniter 2.1.4 with latest lib

**Comment by chriskacerguis** [comment]
So, at the point CI 2.x is no longer supported, and this will be CI 3.x only moving forward.
