### ISSUE TITLE
When i to use PUT method in API i got syntext error 

### ISSUE THREAD

**Issue by cent040** [chriskacerguis/codeigniter-restserver#433]
here is the error detail

<br />
<b>Fatal error</b>:  Call to undefined method CI_Input::method() in <b>F:\xampp\htdocs\restapi\application\libraries\REST_Controller.php</b> on line <b>992</b><br />

**Comment by betoenciel** [comment]
Change

$this->input->method()

by

$this->input->server('REQUEST_METHOD')
