### ISSUE TITLE
Method names should be declared in camelCase. 

### ISSUE THREAD

**Issue by Tjoosten** [chriskacerguis/codeigniter-restserver#436]
Method names should be declared in camelCase. 
You should rename this method to comply with PSR-1.

If you want i can convert this for u in a PR.

**Comment by chriskacerguis** [comment]
Happy to take a PR :)

**Comment by Tjoosten** [comment]
ok i will work a a PR for this then

**Comment by softwarespot** [comment]
According to [CodeIgniter's style guide](http://www.codeigniter.com/user_guide/general/styleguide.html), the function names are just fine
