### ISSUE TITLE
 Support for older Versions of Codeigniter and PHP

### ISSUE THREAD

**Issue by vschaefer** [chriskacerguis/codeigniter-restserver#437]
Hi!

I would like to use your rest server in a project. But on the development server exists only an older Version of the Codeigniter (2.1.3) and PHP (5.3.3) and I'am not authorized to update it.
Is it possible to run your rest server on this machine or is there another Version of the rest server that I can use?

Thanks a lot!
Volker Schaefer

**Comment by Tjoosten** [comment]
@chriskacerguis What u think. Shall i try this out?

**Comment by chriskacerguis** [comment]
You could grab an older version of the library.  I just feel that b/c CI 2.x is so old and bug ridden, that it would be very time consuming to move forward with CI 3.x and still support CI 2.x

**Comment by vschaefer** [comment]
Okay, thanks for your reply.
