### ISSUE TITLE
I loose session with ajax call.

### ISSUE THREAD

**Issue by glemiere** [chriskacerguis/codeigniter-restserver#441]
Hey !

First, thank you, you made a great job ! However, I'm surprised to see that codeIgniter 3.0 didn't solve the problem about loosing session with ajax. Have you got an idea to fix it ? Because an API without ajax authentication is not so useful...

Thank you.

**Comment by chriskacerguis** [comment]
Hi Sorry for the delay.  Could you please post some example code?

**Comment by softwarespot** [comment]
I have tested and can't seem to replicate the problem @glemiere is mentioning. Sorry but I'm afraid without a sufficient reproduce this is a "works for me" resolution.

**Comment by chriskacerguis** [comment]
Closing.  Works for me as well, and no response from the user.
