### ISSUE TITLE
the input includes the extension of the output

### ISSUE THREAD

**Issue by hillchan31** [chriskacerguis/codeigniter-restserver#442]
src:
   /**
     * List all supported methods, the first will be the default format
     *
     * @var array
     */
    protected $_supported_formats = [
        'xml' => 'application/xml',
        'json' => 'application/json',
        'jsonp' => 'application/javascript',
        'serialized' => 'application/vnd.php.serialized',
        'php' => 'text/plain',
        'html' => 'text/html',
        'csv' => 'application/csv'
    ];

 // Remove the extension from arguments too
$this->_get_args[$last_key] = preg_replace($pattern, '', $this->_get_args[$last_key]);
$this->_args[$last_key] = preg_replace($pattern, '', $this->_args[$last_key]);

example:
SERVER/api/example/my?url=www.github.com/xxx.html
function my_get() will deal with the url. 
$this->get('url') will return 0 www.github.com/xxx

in this situation, string ".html" is a part of input, not format of output.

**Comment by ahcheqiu** [comment]
I have the same problem
I think the auto detecting output format should not depend on get argument
Borrowed the example above , SERVER/api/example/my.json?url=www.github.com/xxx.html output as json not html will be great

**Comment by softwarespot** [comment]
I have no clue how to resolve, as this has been in the library for ages. I personally would remove supporting .html, but then this is will be a script breaking change and inconsistency.

Another idea, only support json, xml and csv

**Comment by softwarespot** [comment]
Anyone have any thoughts? Perhaps a script breaking change is required.

**Comment by lagaisse** [comment]
I think `current(explode("?",$this->uri->uri_string())) ` should do the job instead of using `$this->uri->uri_string()` there https://github.com/chriskacerguis/codeigniter-restserver/blob/master/application/libraries/REST_Controller.php#L813

**Comment by softwarespot** [comment]
I just did some testing and conclude $this->uri->uri_string() is fine.

If I use
```
// api => Class
// index => Method
http://localhost/demo/api/index/my.json?url=www.github.com/xxx.html
```
$this->uri->uri_string() returns...
```
api/index/my.json
```
which is what we want, as json is the return type and my the parameter.

The offending code is: https://github.com/chriskacerguis/codeigniter-restserver/blob/master/application/libraries/REST_Controller.php#L819

**Comment by softwarespot** [comment]
These appear to be quite similar? https://github.com/fuel/core/tree/1.8/develop/classes/controller/rest.php

**Comment by softwarespot** [comment]
Please check >> https://github.com/softwarespot/codeigniter-restserver for an up to date version of the library

**Comment by lagaisse** [comment]
I agree. I can't figure out what the elsif block added that is not already managed.

Does the behavior change with a different uri_protocol ?

**Comment by softwarespot** [comment]
No it doesn't. I tested against various forms and concluded the elseif was pointless, since we shouldn't be stripping from the query params.

How I see it, is the format can be stipulated by:
* HTTP_ACCEPT
* method.FORMAT
* Query parameter called format
* Default for the controller, set via $this->_rest_format
* Default for the api, set via the configuration item

Anything else is simply not accepted.
