### ISSUE TITLE
index_delete($id) not working!

### ISSUE THREAD

**Issue by xerron** [chriskacerguis/codeigniter-restserver#443]
Try, and.
"Unknown method."
But:
id_delete($id) work,

Documentation:

The HTTP spec for DELETE requests precludes the use of parameters. For delete requests, you can add items to the URL

public function index_delete($id)
{
  $this->response(array(
    'returned from delete:' => $id,
  ));           
}

**Comment by chriskacerguis** [comment]
Unknown method would indicate that the routes aren't setup correctly
