### ISSUE TITLE
Notice: strlen() expects parameter 1 to be string, array given (libraries/REST_Controller.php:514)

### ISSUE THREAD

**Issue by 3hertz** [chriskacerguis/codeigniter-restserver#444]
A PHP Error was encountered

Severity: Warning

Message: strlen() expects parameter 1 to be string, array given

Filename: libraries/REST_Controller.php

Line Number: 514

Backtrace:

File: /var/www/html/siteroot/application/libraries/REST_Controller.php
Line: 514
Function: strlen

File: /var/www/html/siteroot/application/controllers/Api.php
Line: 39
Function: response

File: /var/www/html/siteroot/application/libraries/REST_Controller.php
Line: 437
Function: call_user_func_array

File: /var/www/html/siteroot/application/libraries/REST_Controller.php
Line: 423
Function: _fire_method

File: /var/www/html/siteroot/index.php
Line: 295
Function: require_once

------------------------------------------------------------------------------------------
When $output variable is filled by array, notice occurs.

"Format" class is not used.

**Comment by chriskacerguis** [comment]
Could you please provide a little more context here?

**Comment by chriskacerguis** [comment]
no response.
