### ISSUE TITLE
Deploying on a redhat linux server returns page not found

### ISSUE THREAD

**Issue by jampst** [chriskacerguis/codeigniter-restserver#446]
I have this setup and working on my local using a xammp environment and everything seems to be working fine. 

I uploaded my code to a development server running php 5.6.8 and a simple get request returns a page not found error. 

Can anyone help me here? Are there any depencies in apache or php needed for this to work? 

I'm not that good with servers and assumed a local xammp environment with the same php version would work ok when uploading to a production server.

**Comment by yimi2013** [comment]
@jampst  Is your problem solved? I've got same situation
