### ISSUE TITLE
OAuth?

### ISSUE THREAD

**Issue by peteclark3** [chriskacerguis/codeigniter-restserver#447]
Has anyone bolted OAuth onto this as an authentication option, e.g. http://blog.cloudfoundry.org/2012/10/09/securing-restful-web-services-with-oauth2/

?  

If not, I may try.  Is this of interest to anyone such that I should try to code it into the codeigniter-restserver library/extension itself?

Pete

**Comment by chriskacerguis** [comment]
I'd love to see OAuth support included.

**Comment by softwarespot** [comment]
What is the status of this? Do you need help?

**Comment by dschallert** [comment]
I'm highly interessted in seeing OAuth with codeigniter-restserver, unfortunately i failed on implementing it for myself a plenty of times so far.

**Comment by alpheustechnologies** [comment]
Just a question here, why OAuth2 and not OpenID?

**Comment by peteclark3** [comment]
@alpheustechnologies - maybe it'd help if you elaborated... why OpenID?

**Comment by peteclark3** [comment]
@dschallert I have three grant types working so far (client_credentials, password, refresh_token).. but we haven't gotten into 3rd party authorization yet, though that is on the horizon.

**Comment by alpheustechnologies** [comment]
@peteclark3, "OpenID connect will give you an access token plus an id token. The id token is a JWT and contains information about the authenticated user. It is signed by the identity provider and can be read and verified without accessing the identity provider.

In addition, OpenID connect standardizes quite a couple things that oauth2 leaves up to choice. for instance scopes, endpoint discovery, and dynamic registration of clients.

This makes it easier to write code that lets the user choose between multiple identity providers."

**Comment by peteclark3** [comment]
@alpheustechnologies - could you cite your source so I can read more?  Would like to know if/how OpenID handles the 3rd party authorization case.  We need to support 3rd party auth as well.

**Comment by disrvptor** [comment]
A point of clarification, @alpheustechnologies references [OpenID Connect](http://openid.net/connect/), which is different from OpenID. Basically OpenID Connect sits on top of OAuth 2.0.
> OpenID Connect 1.0 is a simple identity layer on top of the OAuth 2.0 protocol. It allows Clients to verify the identity of the End-User based on the authentication performed by an Authorization Server, as well as to obtain basic profile information about the End-User in an interoperable and REST-like manner.

Here's how I think of it
* OpenID : Used for authentication (Google tells StackOverflow, yep, that's him)
* OAuth : Used for authorization (StackOverflow posts something to Facebook on my behalf)
* OpenID Connect : Used for both, but provides a subset of authorization that makes using it less murky

**Comment by obaidott** [comment]
So what happened with this? Was this ever integrated?
