### ISSUE TITLE
Unhandled exceptions handling

### ISSUE THREAD

**Issue by danieleteti** [chriskacerguis/codeigniter-restserver#449]
If an exception is thrown inside a controller, the response is not parsable anymore by the client because the PHP standard exception is returned.
I think that should be better to handle exceptions and render them using the selected serialization format, just lite the other responses. You can do this using the following code (or something similar).

At the last line of "public function _remap($object_called, $arguments)" the is the following call
```php
// and...... GO!
$this->_fire_method([$this, $controller_method], $arguments);
```

I changed it in

```php
// and...... GO!
try {
  $this->_fire_method([$this, $controller_method], $arguments);
} 
catch(Exception $ex) {
  $response = [config_item('rest_status_field_name') => FALSE,
       config_item('rest_message_field_name') => ['classname' => get_class($ex), 
              'message' => $ex->getMessage()]];            
       $this->response($response, 500);            
}
```

So that also unhandled exceptions are returned as proper JSON (or XML or whatever)

e.g.
```javascript
{"status":false,"error":{"classname":"EMyException","message":"This is an Exception"}}

```

**Comment by chriskacerguis** [comment]
thanks for the idea!  I've put that in the code.

**Comment by gconst02** [comment]
Great addition. You may as well put that in a protected method so we can customize the response when overridden:

```
try {
  $this->_fire_method([$this, $controller_method], $arguments);
} 
catch(Exception $ex) {
  $this->_server_error_response($ex);
}
```
```
protected function _server_error_response($ex)
    {
    	$response = [
    			config_item('rest_status_field_name') => FALSE,
    			config_item('rest_message_field_name') => [
    					'classname' => get_class($ex), 'message' => $ex->getMessage()
    			]
    	];
        $this->response($response, 500);
    }
```

Now if someone wants to change the default response in case of unhandled exceptions he can just override _server_error_response() when extending REST_Controller.

**Comment by chriskacerguis** [comment]
good idea. thanks for pointing that out.

**Comment by danieleteti** [comment]
You are welcome. Thanks for add it, and thanks for your valuable job.
