### ISSUE TITLE
Call to undefined function is_cli()

### ISSUE THREAD

**Issue by jjmpsp** [chriskacerguis/codeigniter-restserver#451]
When using the library I get the following error:

Fatal error: Call to undefined function is_cli() in ```/Applications/XAMPP/xamppfiles/htdocs/ben/application/libraries/REST_Controller.php on line 978```

I've worked out a fix for this:

On Line 978, change:
```if (is_cli()) {```

To:
```if ($this->input->is_cli_request()) {```

**Comment by chriskacerguis** [comment]
The REST server only support CI 3.x now, take a look here:

http://www.codeigniter.com/userguide3/installation/upgrade_300.html#input-library-method-is-cli-request
