### ISSUE TITLE
Syntax Error on line 32 of REST_Controller

### ISSUE THREAD

**Issue by panvourtsis** [chriskacerguis/codeigniter-restserver#453]
Hi,

I am facing since i've upload my project a problem on the live server a problem.

I am getting

Parse error: syntax error, unexpected '[' in /home2/ineedcar/public_html/quizapp/application/libraries/REST_Controller.php on line 32
A PHP Error was encountered
Severity: Parsing Error
Message: syntax error, unexpected '['
Filename: libraries/REST_Controller.php
Line Number: 32
Backtrace:

Any thoughts?

**Comment by chriskacerguis** [comment]
What is the version of PHP on your server?

**Comment by panvourtsis** [comment]
Hi Chris,

Thank you so much for your quick reply that was the issue. Although i have php 5.4 i runned phpinfo and saw that the server was using 5.2. Now is working perfectly

**Comment by RaruRv** [comment]
Am Having the same problem. 
PHP Version | 5.6.36 on live
