### ISSUE TITLE
JSON_NUMERIC_CHECK breaks phone numbers

### ISSUE THREAD

**Issue by lagaisse** [chriskacerguis/codeigniter-restserver#458]
Hello,

Adding JSON_NUMERIC_CHECK breaks phone numbers that contains leading 0.

**Comment by chriskacerguis** [comment]
Hello,

This is an issue with PHP, not with the REST server.  A quick Google search turned up this:

http://stackoverflow.com/questions/24520950/json-numeric-check-and-phone-numbers

**Comment by lagaisse** [comment]
Hello,
The issue stands with the last commit. It was working fine before. I do not understand why you added a JSON_NUMERIC_CHECK.

My statement : If you don't want to have numerics as string in the output, do not store them in strings.

**Comment by lagaisse** [comment]
@chriskacerguis do you mind if I create a pull request to put JSON output options in the configuration file ?

**Comment by pabloveliz** [comment]
Same here, big problems with ajax calls to retrieve database info about ID numbers starting with 00something

**Comment by lagaisse** [comment]
The workaroud (sic) which is referenced above is to add quotes or I_AM_A_STRING_I_SWEAR_IT in your string value...
```
$my_string_with_numerics = "001001001";
$my_output = "\"". $my_string_with_numerics . ";
```

The output would be : 
```
"\"001001001\""
```

Then you have to handle the quotes or your magic word in your string from client side...

I would add that whereas the json output handles numerics now, the xml output doesn't. It's not homogeneous between outputs anymore.
