### ISSUE TITLE
tohtml() bug

### ISSUE THREAD

**Issue by charyxiao** [chriskacerguis/codeigniter-restserver#462]
/index.php/example/users/format/html
this will raise a php error. 
it easy to fix.

**Comment by chriskacerguis** [comment]
Hello,

What's the error?

**Comment by charyxiao** [comment]
![image](https://cloud.githubusercontent.com/assets/5407327/7938800/f1c57d84-0979-11e5-8ecb-1c55923647fa.png)

**Comment by chriskacerguis** [comment]
Thanks!

The problem is in the libraries/Tables.php file, which is part of CodeIgniter.  I'd check out here

http://forum.codeigniter.com
