### ISSUE TITLE
Unexpected end of input 

### ISSUE THREAD

**Issue by cent040** [chriskacerguis/codeigniter-restserver#463]
i am using rest apis while i am getting this error sometime in result 
Unexpected end of input 

in Last curly brace is missing "}" this one 

can anyone face this type of problem before 

how i can resolve thanks

**Comment by softwarespot** [comment]
No. You need to be more specific. How to reproduce the problem for example?

**Comment by softwarespot** [comment]
I am calling for this ticket to be closed. Thanks
