### ISSUE TITLE
The configuration file ldap.php does not exist.

### ISSUE THREAD

**Issue by abdulmanan7** [chriskacerguis/codeigniter-restserver#466]
i run domain.com/api/key/index_put.php
it gives me The configuration file ldap.php does not exist.
then i added i file Idap.php from a sources somewhere on the internet .
now it giving me this error:

A PHP Error was encountered

Severity: Notice

Message: Undefined variable: ldaphost

Filename: libraries/REST_Controller.php

Line Number: 1269

Backtrace:

File: /home4/shah/public_html/proof/myapi/application/libraries/REST_Controller.php
Line: 1269
Function: _error_handler

File: /home4/shah/public_html/proof/myapi/application/libraries/REST_Controller.php
Line: 1402
Function: _perform_ldap_auth

File: /home4/shah/public_html/proof/myapi/application/libraries/REST_Controller.php
Line: 1463
Function: _check_login

File: /home4/shah/public_html/proof/myapi/application/libraries/REST_Controller.php
Line: 312
Function: _prepare_basic_auth

File: /home4/shah/public_html/proof/myapi/index.php
Line: 293
Function: require_once

Fatal error: Call to undefined function ldap_connect() in /home4/shah/public_html/proof/myapi/application/libraries/REST_Controller.php on line 1274
A PHP Error was encountered

Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /home4/shah/public_html/proof/myapi/system/core/Exceptions.php:272)

Filename: core/Common.php

Line Number: 564

Backtrace:

A PHP Error was encountered

Severity: Error

Message: Call to undefined function ldap_connect()

Filename: libraries/REST_Controller.php

Line Number: 1274

Backtrace:

**Comment by chriskacerguis** [comment]
Based on the error, ldap_connect is not defined, which means that PHP is not complied with LDAP support.

**Comment by abdulmanan7** [comment]
What is the solution ?
i turn off Idap authentication ,now it giving me 
<code>array (
  'status' => false,
  'error' => 'Unknown method.',
)</code>

**Comment by softwarespot** [comment]
The "fix" is to replace the culprit on line 1272 with:

```
log_message('debug', 'LDAP Auth: Connect to ' . (isset($ldaphost) ? $ldaphost : 'undefined'));
```
