### ISSUE TITLE
Auth Override for HTTP Methods types?

### ISSUE THREAD

**Issue by murrple-1** [chriskacerguis/codeigniter-restserver#467]
So, I ran into an issue where specific HTTP methods needed to ignore authentication (in particular, the OPTIONS call via CORS). I am not sure if this is a common use-case, but if it is, I can provide a PR.

Example:
```php
public function deals_get()
{
// snip
}

public function deals_post()
{
// snip
}

/* I want to only disable authentication for this method */
public function deals_options()
{
// snip
}
```

In my extension, I have added the `$config['auth_override_class_method_http']` and `$config['auth_override_class_http']`, but I am thinking these names might be clunky names.

**Comment by softwarespot** [comment]
I am interested to see what you did. Thanks

**Comment by chriskacerguis** [comment]
I'b be interested as well.  Closing this, but feel free to do a PR.
