### ISSUE TITLE
Array to string conversion for html and csv render

### ISSUE THREAD

**Issue by kmakni** [chriskacerguis/codeigniter-restserver#468]
Hi,

I have a problem with format csv and html

My url is: http://172.16.4.240/RestServer/books?format=html
With HTML:
Severity: Notice

Message: Array to string conversion

Filename: libraries/Table.php

Line Number: 380

Backtrace:

File: /var/www/RestServer/app/libraries/Format.php
Line: 207
Function: generate

File: /var/www/RestServer/app/libraries/REST_Controller.php
Line: 509
Function: to_html

File: /var/www/RestServer/app/controllers/Books.php
Line: 31
Function: response

File: /var/www/RestServer/app/libraries/REST_Controller.php
Line: 453
Function: call_user_func_array

File: /var/www/RestServer/app/libraries/REST_Controller.php
Line: 433
Function: _fire_method

File: /var/www/RestServer/index.php
Line: 292
Function: require_once

With csv:
File: /var/www/RestServer/app/libraries/Format.php
Line: 236
Function: implode
.....
![books](https://cloud.githubusercontent.com/assets/7931434/8206680/01a09f94-14fc-11e5-8f62-d7b390388bc6.png)

What is wrong ?

Thanks

**Comment by Tjoosten** [comment]
Can you give me the source code of  libraries/Table.php and your controller?

**Comment by softwarespot** [comment]
Seeing as I am unable to reproduce this error, I am curious as to how you came about it?

**Comment by softwarespot** [comment]
I possibly have fixed this

**Comment by kmakni** [comment]
Thx softwarespot !
In controllers/api, the first letter file names should be capitalized

**Comment by softwarespot** [comment]
You make a good point. I will create  PR for that
