### ISSUE TITLE
Regenerate the documentation

### ISSUE THREAD

**Issue by softwarespot** [chriskacerguis/codeigniter-restserver#475]
Currently the documentation is a little outdated and should be regenerated with APIGen. I am honestly not too familiar with this doc engine and would rather someone with more experience tackle this "issue"

**Comment by Tjoosten** [comment]
I think i tackle the issue

**Comment by softwarespot** [comment]
Awesome @Tjoosten.

**Comment by Tjoosten** [comment]
No problem

**Comment by chriskacerguis** [comment]
Thanks @Tjoosten

**Comment by Tjoosten** [comment]
@chriskacerguis can u merge it?

**Comment by Tjoosten** [comment]
what's the reason for closing this one?

**Comment by softwarespot** [comment]
Because it was merged. Do you feel it should be reopened?

**Comment by Tjoosten** [comment]
Maybe i tell something about documentation in my other PR. maybe we should another documentation system?
