### ISSUE TITLE
i called your user_post method through chrome poster

### ISSUE THREAD

**Issue by mehboobsamnani** [chriskacerguis/codeigniter-restserver#492]
that is the  function 
function user_post()
    {
	

        // $this->some_model->update_user($this->get('id'));
        $message = [
            'id' => $this->post('id'),
            'name' =>$this->post('name') ,
            'email' => $this->post('email'),
            'message' => 'Added a resource'
        ];

        $this->response($message, 201); // 201 being the HTTP response code
    }
i m calling through chrome poster.
![image](https://cloud.githubusercontent.com/assets/13006640/8590551/12937c2c-263b-11e5-9237-54c33a58a727.png)
this is the attached png showing my method.

this is the response i get
Response:
status: 201 Created
Date: Thu, 09 Jul 2015 08:06:17 GMT
Server: Apache/2.4.9 (Win32) PHP/5.5.12
Connection: Keep-Alive
X-Powered-By: PHP/5.5.12
Content-Length: 68
Keep-Alive: timeout=5, max=100
Content-Type: application/json; charset=utf-8

{"id":false,"name":false,"email":false,"message":"Added a resource"}

kindly help me please as soon as possible

**Comment by softwarespot** [comment]
Are they in $_POST or $this->input->raw_input_stream? If not then it's not a problem with the library.

**Comment by chriskacerguis** [comment]
No response from user.  Closing.
