### ISSUE TITLE
GET parameter in URL

### ISSUE THREAD

**Issue by rooferz** [chriskacerguis/codeigniter-restserver#493]
Hello,

I'm developping a rest server and I think there is a missing fonctionnality or I didn't discover it yet :

I'm trying to get this URL : http://example.com/pets/1 but REST_Controller give me an error : 
```
{"status":false,"error":"Unknown method."}
```

In fact, the real URL to achieve this, is : http://example.com/pets/?id=1

I tried different method such as function index_get($id = NULL) or routes configuration but It doesn't care anymore :(

Any suggestions ?
Thanks.

**Comment by softwarespot** [comment]
What does your method look like for pets_get()? Did you try $this->get('id')?

**Comment by kmakni** [comment]
http://example.com/pets/id/1

**Comment by rooferz** [comment]
Thank you for your response.

I miss read the documentatin and indeed the solution is http://example.com/pets/id/1
