### ISSUE TITLE
parameter value bool

### ISSUE THREAD

**Issue by prybus** [chriskacerguis/codeigniter-restserver#494]
hello,
i have parameter 'optin' is bool. if value is false in post or get, this filld is not updated. 

please help :)

**Comment by softwarespot** [comment]
Reproducer?

**Comment by prybus** [comment]
how to do it?

**Comment by softwarespot** [comment]
Can you show us the problem with some code please.

**Comment by prybus** [comment]
i send GET => optin=0
and this code is not execude, beacose $this->get('optin') == false
if($this->get('optin')){
  $this->db->update('list',array('optin' => $this->get('optin'))
 }

**Comment by prybus** [comment]
if http is get or post i make do $_POST or $_GET and isset key. I have a problem in the case of PUT, because this protocol is not supported in CI

**Comment by softwarespot** [comment]
Hmm...works for me

```
    // http://localhost/<YOUR_APP>/api/settings/optin/true
    public function settings_get()
    {
        // Get the passed param called optin
        $optin = $this->get('optin');

        // If FALSE, then an error occurred
        if ($optin === FALSE)
        {
            set_error('optin was not passed. Whoops!');
            return;
        }

        // Set the response
        $this->response(['opt_in' => $this->to_boolean($optin)], 200);
    }

    // Parse to a boolean datatype. Note: If not true or false, the default to false
    private function to_boolean($value)
    {
        return strtolower($value) === 'true';
    }
```
Please learn how to submit sufficient bug reports, otherwise you're wasting not only your time, but others as well. Thanks.

**Comment by prybus** [comment]
oh thanks, I did not think I could simply take advantage of if, else.

**Comment by softwarespot** [comment]
OK. Well you should always be error checking, that's rule number 1.
