### ISSUE TITLE
Proposal for improving efficiency with get, post, patch, delete methods

### ISSUE THREAD

**Issue by softwarespot** [chriskacerguis/codeigniter-restserver#498]
So I was doing some [research](http://juliusbeckmann.de/blog/php-benchmark-isset-or-array_key_exists.html) on what are the implications of using array_key_exists() vs isset()? Turns out quite a big difference when you're talking about continuous polling.

So I was thinking how about swapping out array_key_exists() for isset()? Now before I go ahead and create a PR, it would mean a small script breaking change, as array_key_exists() returns TRUE regardless of whether the value is NULL or not, but isset() will return FALSE if the key exists or the value is NULL. Thus if the value for the key "example" was NULL, currently get() would return NULL, whereas the upgrade would return FALSE. Therefore I propose for changing the default to NULL and not FALSE (which is better as NULL I feel means NO VALUE).

What do people think?

**Comment by softwarespot** [comment]
Should I create a PR? Or is it too much of a script breaking change?

**Comment by ivantcholakov** [comment]
@softwarespot

It is unclear whether it would be an optimization or a convention change. If you make a separate PR on this matter only, I could review and comment.

If it is for the sake of optimization only, I think, it does not worth the efforts. But between CodeIgniter 2 and 3, for many classes and functions there was a convention change FALSE -> NULL of the returned values if there is nothing to return (initiated by Phil Sturgeon). I this light, a revision of the current convention in this project may be reasonable. Personally, I can swallow a BC break for a good reason.

**Comment by softwarespot** [comment]
It's kind of both, as I liked the route the CI team took with having NULL being the return value on "not found" instead of FALSE. I am not aware of the languages I know whereby FALSE is interpreted as being "no value". Anyway, PR created #504

**Comment by ivantcholakov** [comment]
+1, I have left a comment there.

**Comment by softwarespot** [comment]
Great. =)
