### ISSUE TITLE
What needs to be done before the next stable release?

### ISSUE THREAD

**Issue by softwarespot** [chriskacerguis/codeigniter-restserver#507]
Documentation can be regenerated using
```
php apigen.phar generate -s "application" -d "documentation"
```

Presuming apigen.phar is located at the root directory of the REST server and that php is in the %PATH% variable (or such-like)

**Comment by softwarespot** [comment]
Close the following tickets has they have been fixed/implemented/debunked:
* #506
* #502
* #498
* #442
* #397 (not so clear)
* #386

**Comment by softwarespot** [comment]
I am closing even though #386 is outstanding, but I am looking at a re-write of those functions in the next couple of days.

**Comment by ivantcholakov** [comment]
#514

**Comment by ivantcholakov** [comment]
#515 Is closed at the moment, but I have just left a comment there for consideration
https://github.com/chriskacerguis/codeigniter-restserver/issues/515#issuecomment-123910237

**Comment by softwarespot** [comment]
The release log could perhaps be elaborated a little more than what it is now. As bug fixes doesn't quite reflect just how much this library has changed since last years release.

* HTTP status constants have been added e.g. REST_Controller::HTTP_OK
* Performance increase
* New documentation
* Additional doc comments added to functions
* Re-write of examples (thanks @ivantcholakov and @lagaisse)
* Numerous bug fixes

**Comment by lagaisse** [comment]
what I have in mind:
* API calls limit can be based on API key, routed url or method name
* new CSV formatting method

**Comment by softwarespot** [comment]
Oh yeah the CSV formatter =) forgot that one!

**Comment by softwarespot** [comment]
I am closing this, as I can't see anything else that needs to be done anymore.
