### ISSUE TITLE
Request to be added to the team

### ISSUE THREAD

**Issue by softwarespot** [chriskacerguis/codeigniter-restserver#509]
@chriskacerguis, I hope I am not overstepping the mark, as I would like to ask if it's possible to be added to the development team for codeigniter-restserver?

**Comment by chriskacerguis** [comment]
I'm not opposed to it, but I don't even know your name :)

Why don't you DM on Twitter (same username) and introduce yourself ;)

**Comment by softwarespot** [comment]
Understood. I don't have Twitter, so will continue to help out as I have done so far.
