### ISSUE TITLE
More CodeIgniter friendly by changing the name to MY_Controller

### ISSUE THREAD

**Issue by calvintam236** [chriskacerguis/codeigniter-restserver#511]
Is it possible to change the controller name to MY_Controller (extending the native) so users do not need to run require_once at every controller in order to use this REST_controller? If possible, the new controller should put in the application/core/.

Reference:
http://www.codeigniter.com/user_guide/general/core_classes.html?highlight=my_#extending-core-class

**Comment by softwarespot** [comment]
Maybe a note in the documentation would be suffice, because this isn't really a MY_Controller. For example in the CI application I am developing, I have a MY_Controller as well as this REST_Controller, so I would have to rename one of them anyway.

**Comment by ivantcholakov** [comment]
-1

**Comment by Tjoosten** [comment]
-1 the name REST_controller name is clear. If i See that ik know that we are dzaling with some API controller.

**Comment by chriskacerguis** [comment]
Sorry, I'm a -1 as well.
