### ISSUE TITLE
Little problem with argument parsing

### ISSUE THREAD

**Issue by lagaisse** [chriskacerguis/codeigniter-restserver#515]
Commit #9af2361 breaks the example and existing apps by not removing the format extension

`http://localhost/codeignitermaster/api/Example/user/1.json`

Expected
```
{
 id: 1,
 name: "John",
 email: "john@example.com",
 fact: "Loves coding"
}
```

Result :
```
Fatal error: Undefined class constant 'NOT_FOUND' in C:\THISISDATA\www\codeignitermaster2\application\controllers\api\Example.php on line 60
A PHP Error was encountered

Severity: Error

Message: Undefined class constant 'NOT_FOUND'

Filename: api/Example.php

Line Number: 60

Backtrace:
```
By modifying the `Example.php` L60 with `REST_Controller::HTTP_NOT_FOUND` I've got :

```
{
status: false,
error: "User could not be found"
}
```

Those two lines seem to be necessary (after all)
```
$this->_get_args[$last_key] = preg_replace($pattern, '', $this->_get_args[$last_key]);
$this->_args[$last_key] = preg_replace($pattern, '', $this->_args[$last_key]);
```

**Comment by softwarespot** [comment]
I have fixed the undefined constants and will continue to debug your other issue.

**Comment by softwarespot** [comment]
There is no error. I think you've misunderstood the example, as you will notice it gets the id via a query param called 'id'. Here, try this...
```
http://localhost/codeignitermaster/api/Example/user.json?id=1
````

**Comment by softwarespot** [comment]
This is how your user_get() should be...
```
    public function user_get($id = NULL)
    {
        // Strip the output format inc. dot from the id. You could use a regex (which I would do)
        // but this is a simple demo
        $id = str_replace('.' . $this->response->format, '', $id);

        // If an id doesn't exist check the query params
        if (!$id)
        {
            $id = $this->get('id');
        }

        // Oh come on, where is the id???
        if (!$id)
        {
            // Set the response and exit
            $this->response(NULL, REST_Controller::HTTP_BAD_REQUEST); // BAD_REQUEST (400) being the HTTP response code
        }

        // $user = $this->some_model->getSomething($this->get('id'));
        $users = [
            1 => ['id' => 1, 'name' => 'John', 'email' => 'john@example.com', 'fact' => 'Loves coding'],
            2 => ['id' => 2, 'name' => 'Jim', 'email' => 'jim@example.com', 'fact' => 'Developed on CodeIgniter'],
            3 => ['id' => 3, 'name' => 'Jane', 'email' => 'jane@example.com', 'fact' => 'Lives in the USA', ['hobbies' => ['guitar', 'cycling']]],
        ];

        // Get the user from the array, by retrieving the id from the GET request
        $user = isset($users[$id]) ? $users[$id] : NULL;

        if ($user)
        {
            $this->set_response($user, REST_Controller::HTTP_OK); // OK (200) being the HTTP response code
        }
        else
        {
            $this->set_response([
                'status' => FALSE,
                'error' => 'User could not be found'
            ], REST_Controller::HTTP_NOT_FOUND); // NOT_FOUND (404) being the HTTP response code
        }
    }
```

**Comment by lagaisse** [comment]
Sorry to disagree, formats should be in the form of api/v2/resource/{id}.json and not with ?id (which is the search syntax).
The id doesn't include the format.

**Comment by softwarespot** [comment]
I agree, but it's not the library at fault.

**Comment by lagaisse** [comment]
The library was doing it (I mean cleaning the last arg) well before that update. 

I don't understand what is so disturbing ?

**Comment by softwarespot** [comment]
Well reverting back to the old way, still means [this](#442) ticket is broken.

**Comment by lagaisse** [comment]
ok I understand why it's so disturbing :
It should fix #442 (query arguments) but there's a regression for get arguments

**Comment by softwarespot** [comment]
Though I am still confused as to how the example that ships with the library works for you? As your url should have a GET param called id, which it doesn't. Maybe @ivantcholakov knows?

I will come up with a fix though, by stripping .json

**Comment by lagaisse** [comment]
Oh ! ok. I'm just routing users/1.json (normalized format) to users/id/1.json. That's all.

**Comment by ivantcholakov** [comment]
Ok, as I understand there is a problem #442 and a regression, caused by https://github.com/chriskacerguis/codeigniter-restserver/commit/9af236108efe166196353a76ae11982d312010fe

I will test in my place how they both could be resolved.

**Comment by softwarespot** [comment]
I have come up with this...
```
        // Concatenate formats to a regex pattern e.g. \.(csv|json|xml)
        $pattern = '/([^\/]+)\.(' . implode('|', array_keys($this->_supported_formats)) . ')$/';

        // Check if a file extension is used e.g. http://example.com/api/index.json?param1=param2
        // Match[0] = Full match i.e. method.format
        // match[1] = Method
        // Match[2] = Format (with no dot)
        $matches = [];
        if (preg_match($pattern, $this->uri->uri_string(), $matches))
        {
            // If GET params exist
            if ($this->_get_args)
            {
                // Then remove method.format from the get arguments
                unset($this->_get_args[$matches[0]]);
            }

            return $matches[2];
        }
```
Could you please replace and test for me.

**Comment by ivantcholakov** [comment]
Ok

**Comment by softwarespot** [comment]
Forgot $this->_args. Edited post above.

My change is pretty much doing what it did before. Though of course $arguments in _remap() will still contain 1.json. Perhaps it should be stripped there too?

**Comment by lagaisse** [comment]
@softwarespot who writes users/id/1.json ? ;)

**Comment by softwarespot** [comment]
OK.

Did you try the code above. I am more concerned about fixing the bug.

**Comment by lagaisse** [comment]
I am searching what is not working (uri versus ruri ?)

**Comment by softwarespot** [comment]
OK. Let me know what works for you. Thanks.

**Comment by softwarespot** [comment]
One other option too is to strip the format from $arguments in _remap()

**Comment by lagaisse** [comment]
That code is working at home (similar to the original one)

```
        // Concatenate formats to a regex pattern e.g. \.(csv|json|xml)
        $pattern = '/([^\/]+)\.(' . implode('|', array_keys($this->_supported_formats)) . ')$/';

        // Check if a file extension is used e.g. http://example.com/api/resource/1.json?param1=param2 => http://example.com/api/resource/id/1.json?param1=param2
        // Match[0] = Full match i.e. value.format
        // match[1] = value
        // Match[2] = Format (with no dot)
        $matches = [];
        if (preg_match($pattern, $this->uri->uri_string(), $matches)) 
        {
            // If GET params exist
            if ($this->_get_args)
            {
				$only_get_args = array_diff($this->_get_args,$this->_query_args); //array_slice or saving _get_args_only when calling _parse_get ?
				$arg_keys = array_keys($only_get_args);
				$last_key = end($arg_keys);
				$this->_get_args[$last_key] = $matches[1];
				$this->_args[$last_key] = $matches[1];	
            }

            return $matches[2];
        }

        // Get the format via the GET parameter labelled 'format'
```

**Comment by softwarespot** [comment]
Strange how mine didn't work.

**Comment by lagaisse** [comment]
Calling `/api/Example/user/id/1.json?foo=bar`gives with your proposal
```
$this->_get_args[1] = NULL;
```
But I need
```
$this->_get_args['id'] = 1;
```

**Comment by softwarespot** [comment]
Okay point taken. You have more scenarios than I do it seems. I have added to my pre-existing PR.

**Comment by lagaisse** [comment]
What I don't like in my code is this line
`$only_get_args = array_diff($this->_get_args,$this->_query_args);`

Do you think it would be relevant to definitely split _get_args and _query_args ? (I do)

It's only used to get the format from the query (sic) and here

**Comment by softwarespot** [comment]
Yes it's relevant, as this fixed an issue whereby someone was sending a POST request but also using query params. So of course how it used to be before was the query params were only parsed when a GET request was sent, so I split them up.

**Comment by softwarespot** [comment]
>EDIT : You're welcome to add it to your PR. Thanks

Thanks. I hope this goes towards your commits too!?

**Comment by lagaisse** [comment]
If _get_args and _query_args are definitely not mixed, this array_diff should dissapear

**Comment by ivantcholakov** [comment]
https://github.com/chriskacerguis/codeigniter-restserver/commit/9af236108efe166196353a76ae11982d312010fe is correct, it removes garbage. It is not to be reverted.

After that I made modifications for serving the special case users/1.json
https://github.com/ivantcholakov/starter-public-edition-3/commit/2fe4d6b366527ad680dfd0fa9c0067e0fe6a7938

**Comment by ivantcholakov** [comment]
I think, I've got something that works, see the alternative ways for passing the 'format' parameter: http://iridadesign.com/starter-public-edition-3/www/playground/rest/server

**Comment by softwarespot** [comment]
@ivantcholakov, would you like me to add your changes to the PR too? I have manually updated the Example.php though, as it needed to be re-tweaked

**Comment by softwarespot** [comment]
@lagaisse, I contemplated de-merging _get_args and _query_args, but then as you will notice wherever _get_args is, so must _query_args.Therefore it's a lot more code for the sake of a little bit of duplication! =)

**Comment by ivantcholakov** [comment]
@softwarespot

If you find anything useful, take it.

**Comment by ivantcholakov** [comment]
Yes, this is needed, thank you.
https://github.com/ivantcholakov/starter-public-edition-3/commit/3553365e99e37fbe1b2b4f63d89494d9b4d81b4c

**Comment by lagaisse** [comment]
With your code :
```
       if (preg_match($pattern, $this->uri->uri_string(), $matches))
        {
            return $matches[1];
        }
```
returns a match for /api/Example/user/1.json?foo=bar

This code
```
// A special case: users/1.json
elseif (count($this->_get_args) === 1 && reset($this->_get_args) === NULL)
            {
```
is never reached.




Apart from that, I don' t feel confortable with this commit and I'll try to explain why (and try to be clear) :
1- 
In my opinion, you're managing routing in your Example.php file
My route looks like this :
```
$route['api/Example/user/([0-9]+)(.*)'] = 'api/Example/user/id/$1$2'; 
```
It breaks the Example again.
You shouldn't need extra ifs to check where the id comes from. It has to come from the GET params so with `$this->get('blah'); // GET param `.


2- 
Rest_controller should manage and was managing well subressources access. you can use some routing to perform it. For example (Apiv1 been the rest extended class) :
`/api/v1/magazines/1/articles/2.json` is to be routed to `/api/apiv1/magazines_articles/idm/1/ida/2.json`

This portion of code in REST_Controller is skipped `elseif (count($this->_get_args) === 1 ...`

3-
You can use form_validation against the this->_args array which CI allows since version 3.
That's why `_args` & `_get_args` could be cleaned from format if present.

4- (A little off topic but not so off topic I think)
$this->get() should return arguments from GET (only !)
$this->query() should return arguments from the query


I'll understand if you'd keep your commit like this but I would break existing code and complexify things as it has to be managed in the child controller (is it coming from there ? is there an extension ? does the client inverse the params ?...)

**Comment by softwarespot** [comment]
I can answer part 4. If we went with that approach, then it would existing code as get() can get both GET params and query params. I see what you're saying, but I don't think it is viable at this time. As for 1...3 I will wait for @ivantcholakov to see what they say.

**Comment by ivantcholakov** [comment]
@lagaisse
At first glance your opinion has to be taken seriously. I am going to make an additional test and I will answer you point by point.

**Comment by lagaisse** [comment]
@softwarespot I understand for point 4.

To sum up : The REST_Controller was parsing the format extension from the GET arguments and removing it (example : `api/user/id/1.json`, `1.json` was cleaned as `1`).

9af2361 introduced a regression(?)
5b415bc corrected the issue by reimplementing the mecanism
805b82c introduced a portion of code that is never reached (with my tests).

My first conclusion is that there are some (serious) limitations in CodeIgniter that have been managed by the old versions of the Rest_Controller even it's not its purpose (like cleaning the args).

What I can propose is to manage the cleaning of the argument from the route, because it's CodeIgniter's fault in my opinion.

Proposal for _detect_output_format (without the special case) == 0f35025
```
        // Concatenate formats to a regex pattern e.g. \.(csv|json|xml)
        $pattern = '/\.(' . implode('|', array_keys($this->_supported_formats)) . ')($|\/)/';
        $matches = [];

        // Check if a file extension is used e.g. http://example.com/api/index.json?param1=param2
        if (preg_match($pattern, $this->uri->uri_string(), $matches))
        {
            return $matches[1];
        }

        if (empty($this->_get_args) === FALSE)
        {
            // Get the format parameter named as 'format'
            if (isset($this->_get_args['format']) === TRUE)
            {
                $format = strtolower($this->_get_args['format']);

                if (isset($this->_supported_formats[$format]) === TRUE)
                {
                    return $format;
                }
            }
        }

        // Get the HTTP_ACCEPT server variable
```

routes.php:
```
$route['api/Example/user/([0-9]+)(?:(\.)([^.]*)$)?'] = 'api/Example/user/id/$1/format/$3'; 
```
Very crappy to get the format but people who likes well formatted ressources access can bypass CI limitations with something like this.
Nb : user should be plural

Example.php
```
    public function user_get()
    {
        if (!$this->get('id'))
        {
            // Set the response and exit
            $this->response(NULL, REST_Controller::HTTP_BAD_REQUEST); // BAD_REQUEST (400) being the HTTP response code
        }
        // $user = $this->some_model->getSomething($this->get('id'));
```

My other points are still valid

**Comment by ivantcholakov** [comment]
@chriskacerguis

Please, hold making the release, there is a valid objection here (about the hidden routing rule), I need some time for making a test.

**Comment by softwarespot** [comment]
> Nb : user should be plural

Some see it as a preference than convention. I am not one of them =)

As for your proposal, isn't that similar to what we had before, without ($|\/) on the regex? I know @ivantcholakov, but I can have a look this evening as well.

**Comment by lagaisse** [comment]
@softwarespot yes, almost the same. I came to the conclusion that the REST_controller will keep this regression (not cleaning the args). So I did a workaround by creating `a/full/understandable/route/that/codeigniter/cannot/interpret`.

That also means people using it will need to use routes to get clean route if they want to stick with the standard/preference :o) 

And I want it to be resolved too

**Comment by softwarespot** [comment]
So basically these should be passing  as well?

```
Doesn't work
api/Example/users/id/1.json (id = 1 and format is json)
api/Example/users/id/1/format/xml (id = 1 and format is xml)
api/Example/users/format/json (all users and format is json)

Works
api/Example/users?format=json (format is json)
api/Example/users?id=1&format=json (id = 1 and format is json)
api/Example/users/1.json?url=example.com/help.html (id = 1 and format is json)
```

Note: I changed the example in my latest PR, hence why it's users and not user. I also merged users_get() and users_get() together.

**Comment by softwarespot** [comment]
See the PR with the new example. Thanks

**Comment by ivantcholakov** [comment]
https://github.com/ivantcholakov/codeigniter-restserver-test
I am making a repository with CodeIgniter 3.0.1-dev and the REST server. I'll test the examples and then I'll answer on the issues here.

**Comment by ivantcholakov** [comment]
https://github.com/ivantcholakov/codeigniter-restserver-test - my corrected proposal, testable on clean CodeIgniter 3
http://iridadesign.com/codeigniter-restserver-test/rest-server - a live demo

-------------------------------------------------------------------------------------

@lagaisse

1-
You are absolutely right. What I proposed before is a ugly, hackish method with side-effects. I removed the corresponding bad fragment of code. Using routing rules is the natural way. During my testing I came to these ones, they are optional:

```php
$route['api/example/users/(:num)'] = 'api/example/users/id/$1'; // Example 4
$route['api/example/users/(:num)(\.)([a-zA-Z0-9_-]+)(.*)'] = 'api/example/users/id/$1/format/$3$4'; // Example 8
```

2-
Check my code for that, you understand better what you are looking for. I removed the hard-coded, the hidden routing, so you can define your routing rules freely.

3-
At the moment I am against about _args & _get_args to be cleaned from format. I don't see how the format parameter would obstruct form_validation against the this->_args. I suppose, most people would ask why 'format' is missing.

----------------------------------------------------------

@softwarespot

The testing repository has the best code I can make at the moment. Please, have a look at it.

**Comment by softwarespot** [comment]
Thanks for that. I have tested your development environment  examples and agree that going back to the original idea (with the amended regexof course) is the best course of action. I was thinking about this the morning and wondered what I was thinking when I suggested internally "cleaning" the arguments. I agree it's not a good idea either.

I guess what could be done is add to the README.md something along the lines of "hey if you want this URL format, then add this to your route file etc... etc... etc..." Then there won't be any confusion and simply covering ourselves with people saying it's a bug or regression.

I know @ivantcholakov agrees with me, that going back to the old approach is moving backwards, not forwards.

Good work all.

**Comment by lagaisse** [comment]
@ivantcholakov thanks for your answers. We all came to the same conclusion that the requested URL must be segmented so that the controller doesn't get muddled up in the future.

@softwarespot good idea to put a little something in the readme because if you are planning to remove patches that were implemented in the past in the controller, People will need explanations/workarounds.
