### ISSUE TITLE
Update the library to meet the guidelines of CI3

### ISSUE THREAD

**Issue by softwarespot** [chriskacerguis/codeigniter-restserver#516]
[Style Guide](http://www.codeigniter.com/user_guide/general/styleguide.html)

One section that needs to be looked at is Logical Operators, especially with the preferred choice of OR over ||. I personally prefer ||, but am willing to go with the style guide's choice =)

**Comment by ivantcholakov** [comment]
Please, don't follow all the CodeIgniter's rules. Some of them are stupid, like this one. :-)

**Comment by softwarespot** [comment]
OK, I have reverted back in my pull request for now. I did however change some variable names which were camel-case to snake-case, as this seems to be the popular style for this library.

**Comment by ivantcholakov** [comment]
snake_case for CI3.

In CI4... who knows. There are PSR-1 and PSR-2 standards, maybe the CodeIgniter's council would consider them. I will ask a question at their forum, nobody talked about that.

**Comment by softwarespot** [comment]
I would prefer sticking to those standards, but PSR-1 states that 'properties' can be whatever, so long as the standard is maintained. Unless I read it wrong?

**Comment by ivantcholakov** [comment]
No, it is early for PSR-x, we are to be close to CodeIgniter's rules. But not too close.
For example, they use tabs instead spaces, we may not go this way. At the moment the library is just fine.

About || OR - they are not identical operators http://php.net/manual/en/language.operators.precedence.php Just swapping them without checking the logic might cause breaks, there is some probability.

---------------------------------------

Offtopic: I asked the question about what to expect in the future: http://forum.codeigniter.com/thread-62492.html

**Comment by softwarespot** [comment]
Yeh that order precedence would trip me up sometimes. Best I stick to what I know. Thanks for asking. I should really create an account over there too.

**Comment by softwarespot** [comment]
Apart from some syntax features being for 5.4 only, the big change to meet the style guide would be ... http://www.codeigniter.com/user_guide/general/styleguide.html#localized-text

**Comment by softwarespot** [comment]
>Offtopic: I asked the question about what to expect in the future: http://forum.codeigniter.com/thread-62492.html

Just saw the response from @narf. Lets leave as is I guess?!

**Comment by ivantcholakov** [comment]
Yes, focus on testing before this release would be better. Further style polishing may be postponed for next minor releases.

**Comment by Tjoosten** [comment]
- 1

**Comment by softwarespot** [comment]
I wonder why some JS and PHP developers use == instead of ===? Better to be explicit than implicit in my opinion.

**Comment by ivantcholakov** [comment]
Using == or === is not a matter of generalized rules (or coding style rules). These two operators have their own meanings. so, their usage should match to the sense of the particular code fragments.

**Comment by ivantcholakov** [comment]
Hmm...

Look at this code fragment:

```php
            isset($row->user_id) && $this->rest->user_id = $row->user_id;
            isset($row->level) && $this->rest->level = $row->level;
            isset($row->ignore_limits) && $this->rest->ignore_limits = $row->ignore_limits;
```

I think it is broken. http://php.net/manual/en/language.operators.precedence.php

**Comment by ivantcholakov** [comment]
I did a quick test, the original statements work actually. Sorry, false alarm.

**Comment by softwarespot** [comment]
I do prefer the ternary operator in cases like this, as something like this is something I have only seen in PHP.
```php
    $test >= 0 || $test = 0;
```

As for your other post, you're right, but I prefer to be in control, rather than relying on the interpreter e.g.

```php
$age = 20;
if ($age == '20') // I would do $age === (int) '20'
{
    // ...
}

**Comment by ivantcholakov** [comment]
Beware when $age comes from a database table. With one driver it could come as string '20', with another driver it could come as integer 20. http://stackoverflow.com/questions/5323146/mysql-integer-field-is-returned-as-string-in-php

**Comment by Tjoosten** [comment]
Alright. Thx for the research

**Comment by softwarespot** [comment]
This is why I use Eloquent or create some sort of DAO.
