### ISSUE TITLE
lacking of a symbol...

### ISSUE THREAD

**Issue by wangyun122** [chriskacerguis/codeigniter-restserver#517]
lacking of a symbol ";" at the end of the line 972 of the file "Rest_Controller.php".
sry for duplicate the issue...

**Comment by softwarespot** [comment]
This has been fixed in my PR

**Comment by softwarespot** [comment]
This can be closed as PR #510 fixed this.

**Comment by Tjoosten** [comment]
PR is merged so @chriskacerguis close this issue plz.
