### ISSUE TITLE
Browser hangs on server response

### ISSUE THREAD

**Issue by lagaisse** [chriskacerguis/codeigniter-restserver#521]
I'm using Apache compression capabilities to compress the output of the web server.

The browser hangs on response when the compression isn't activated in the REST_Controller too because the content-length is wrong.

If I activate the compression in the REST_Controller, the browser doesn't hang but the Apache compression is bypassed which is not what I'll need.

I removed the content-length header to solve the issue in my tests as it's needed only if content-length is 0.

EDIT: Oh wait a minute. That was removed too ?

**Comment by lagaisse** [comment]
ok seem to be solved with b4686c9 2 days ago ! Good !

**Comment by softwarespot** [comment]
Phew! Great =)

**Comment by lagaisse** [comment]
@softwarespot The problem is still there but in codeigniter's side `output()`
