### ISSUE TITLE
"Strange" RESTful implementation in _remap method

### ISSUE THREAD

**Issue by danieleteti** [chriskacerguis/codeigniter-restserver#522]
Hi, 
in the _remap method, all the exception thrown by the controller method is returned as HTTP error code 500. While this is "formally" correct (that's it, it is an error on the server), it limits the use of the exceptions. What about a "Not Found" exception? The http status code should be 404, What about a "Bad Request"? The status code should be 400. While in these case the status code is always 500.
I other words, in the current implementation, exceptions cannot be used for "functional exception" but only for "technical exceptions" (which is not RESTful IMHO).
What do you think about it?

This is the questioned code:

```
        // Call the controller method and passed arguments
        try
        {
            call_user_func_array([$this, $controller_method], $arguments);
        }
        catch (Exception $ex)
        {
            // If the method doesn't exist, then the error will be caught and an error response shown
            $this->response([
                    $this->config->item('rest_status_field_name') => FALSE,
                    $this->config->item('rest_message_field_name') => [
                        'classname' => get_class($ex),
                        'message' => $ex->getMessage()
                    ]
                ], self::INTERNAL_SERVER_ERROR); //always 500
        }
```

**Comment by softwarespot** [comment]
The reason it's 500, is because if we get to this point in execution then something has happened which we didn't expect to happen. A check is made prior as to whether the method exists, which if it doesn't then the response is set to 404 (I don't like that, as in my custom REST server I use HTTP_NOT_IMPLEMENTED (501)). So I think 500 is a good choice. I would like to hear from other people too.

**Comment by lagaisse** [comment]
@softwarespot +1 

@danieleteti do you mean something like this ?


The exception class in REST_Controller (much difficult)
```
 class RestException extends Exception {}
```

Modified REST_Controller

```
        // Call the controller method and passed arguments
        try
        {
            call_user_func_array([$this, $controller_method], $arguments);
        }
		catch (RestException $ex)
        {
            // If the method doesn't exist, then the error will be caught and an error response shown
            $this->response([$this->config->item('rest_status_field_name') => FALSE,
							 $this->config->item('rest_message_field_name') => $ex->getMessage()
							], $ex->getCode());
        }
        catch (Exception $ex)
        {
            // If the method doesn't exist, then the error will be caught and an error response shown
            $this->response([
                    $this->config->item('rest_status_field_name') => FALSE,
                    $this->config->item('rest_message_field_name') => [
                        'classname' => get_class($ex),
                        'message' => $ex->getMessage()
                    ]
                ], self::HTTP_INTERNAL_SERVER_ERROR);
        }
```


The controller method
```
	function cheese_get()
	{
		//do things to escape cheese 
		//...
		throw new RestException('dont like cheese', self::HTTP_FORBIDDEN);
	}
```
and the result
```
{
  status: false,
  error: "dont like cheese"
}
```

**Comment by softwarespot** [comment]
Using the exception code as a status code doesn't sit well with me =)

**Comment by lagaisse** [comment]
>Oh nooo, RestException was so complex to write !

I agree with you, something can be done with the code.

But... does it answer the question?

**Comment by chriskacerguis** [comment]
I'm at @softwarespot using the exception code as the status code goes against being a REST interface.

**Comment by danieleteti** [comment]
@chriskacerguis I dont told this. Exception code and status code are differenti things. But you can check for ERESTException in the catch and then use the httpstatus property to automatically set the status code. It is a normal thing in other restful environments.
My 2 cents
