### ISSUE TITLE
Class 'CI_Format' not found 

### ISSUE THREAD

**Issue by aseolin** [chriskacerguis/codeigniter-restserver#529]
On my WAMP environment, I downloaded the CodeIgnoter 3.0, put the REST files in the corresponding folders and change the configurations. When I try to access the service (http://localhost/test/index.php/example), it asks me for an username and password. So far, everything works well. When I provide the correct credentials, a warning shows:

( ! ) Fatal error: Class 'CI_Format' not found in C:\wamp\www\test\system\core\Common.php on line 196
Call Stack
#	Time	Memory	Function	Location
1	0.0010	267232	{main}( )	..\index.php:0
2	0.0020	339312	require_once( 'C:\wamp\www\test\system\core\CodeIgniter.php' )	..\index.php:292
3	0.0440	1811344	Alerta->__construct( )	..\CodeIgniter.php:500
4	0.0440	1813400	REST_Controller->__construct( )	..\Example.php:24
5	0.0780	3123864	REST_Controller->_prepare_digest_auth( )	..\REST_Controller.php:528
6	0.0790	3129728	REST_Controller->_check_login( )	..\REST_Controller.php:1940
7	0.0790	3130048	REST_Controller->_perform_library_auth( )	..\REST_Controller.php:1824
8	0.0790	3130424	CI_Loader->library( )	..\REST_Controller.php:1777
9	0.0790	3130520	CI_Loader->_ci_load_library( )	..\Loader.php:218
10	0.0790	3138040	CI_Loader->_ci_init_library( )	..\Loader.php:1028
11	0.0790	3138488	CI_Controller->__construct( )	..\Loader.php:1233
12	0.0790	3140000	load_class( )	..\Controller.php:75

I'm stuck.

**Comment by softwarespot** [comment]
The class is called Format. Now clue why your setup is prefixing CI_, as this is for official libraries in CI.

**Comment by softwarespot** [comment]
Did you find the issue with your setup?

**Comment by aseolin** [comment]
The problemas occours when I set to diggest. I dont know why the CI_ is
being attached by codeigniter before the Format string
Em 01/08/2015 02:13, "SoftwareSpot Apps" <notifications@github.com>
escreveu:

**Comment by softwarespot** [comment]
Unfortunately I can't help you with the information you have provided. Sorry. It works for me is all I can say.

**Comment by aseolin** [comment]
I fresh installed and reconfigured. Its working now. Thank you
Em 01/08/2015 14:50, "Chris Kacerguis" <notifications@github.com> escreveu:

**Comment by dechosenuchenna** [comment]
Everything is fine, Just ensure that your models extends CI_Model and Controllers extends CI_Controller
