### ISSUE TITLE
routes starting with param

### ISSUE THREAD

**Issue by alzalabany** [chriskacerguis/codeigniter-restserver#533]
its not possible to map to urls like
`/resource/:id/users` OR `/posts/:id/comments` for getting a specific post comments.

i think maybe we can use
`GET_comments($id){}` to match such routes -reversing the position of the `http verb` to identify that this route will match parameter

**Comment by alzalabany** [comment]
as a quick fix also for not matching routes like `resource/:id` adding this block inside _remap will remove need to include /index/ in the url
e.g : url will be `api/books/1` which is better than `api/books/index/1`
<pre>
       //if object getting called is a number e.g example/12 then put 12 in arguments and map to index_get(); since its not logic having to force /index/ in the url !
        if(is_numeric($object_called)){
			$arguments = [$object_called] + $arguments;
			$object_called = 'index';
		}
</pre>

**Comment by alzalabany** [comment]
Expanding my temp. solution

Replacing first part of _remap function in rest_server with this 
<pre>
public function _remap($object_called, $arguments)
    {
        // Should we answer if not over SSL?
        if ($this->config->item('force_https') && $this->request->ssl === FALSE)
        {
            $this->response([
                    $this->config->item('rest_status_field_name') => FALSE,
                    $this->config->item('rest_message_field_name') => $this->lang->line('text_rest_unsupported')
                ], self::HTTP_FORBIDDEN);
        }

        // Remove the supported format from the function name e.g. index.json => index
        $object_called = preg_replace('/^(.*)\.(?:' . implode('|', array_keys($this->_supported_formats)) . ')$/', '$1', $object_called);
        //if object called is numric e.g example/12 then put 12 in arguments and map to index_get();
        //if object is numric/string/numric then these 2 ids are going o args;
        $new_name = null;
        if(is_numeric($object_called)){
        	if(key_exists(0,$arguments) AND !is_numeric($arguments[0])){
				//ITS and /:id/STRING/
				$new_name = "index_{$this->request->method}_{$arguments[0]}";
				if( method_exists($this, $new_name) === TRUE){
					$new_name = "index_{$this->request->method}_".array_shift($arguments);
					$arguments = [$object_called] + $arguments;
				}else{
					$new_name = null;
				}
			}else{
				//its /:id/:id
				$arguments = [$object_called] + $arguments;
				$object_called = 'index';
			}
		}
		
		if($new_name){
			$controller_method = $new_name;
		}else{
			$controller_method = $object_called . '_' . $this->request->method;	
		}
</pre>

and you will be able to route
 `/books/:id`  to ---> `function index_get(){}`    and `books/:id/chapter/:id` to ---> `index_get_chapter($id1,$id2)`

**Comment by softwarespot** [comment]
What about /books/:id/chapters/:2/pages/:3. Could your code do that? Have you read how to use routes in CI3? I honestly don't feel comfortable doing something like this in the _remap function.

**Comment by lagaisse** [comment]
Hello,

I'm able to access subresources and implicit IDs with this library using routes.

Imo it's not a limitation of the library.

Subresources are resources. If you need to access pages, use pages_get, chapters, use chapters_get etc... The routes will do the mapping
