### ISSUE TITLE
_log_request() fails if Date Helper not auto loaded

### ISSUE THREAD

**Issue by dap6000** [chriskacerguis/codeigniter-restserver#536]
At the time of writing line number 971 of REST_Controller.php looks like this:

`'time' => now(), // Used to be: function_exists('now') ? now() : time()`

The reason for the function_exists() check that has recently been removed is the now() function is part of the CodeIgniter Date Helper which, while available as part of the CI core, may not be loaded for any particular project.

If usage is going to be standardized to one or the other I think either of the native mktime() /  time()  functions would be preferable to the helper function. Or the Date Helper should be listed as a requirement to use this library. Or the Date Helper should be explicitly loaded by this library. Or the version of this line using function_exists() should be used.

**Comment by softwarespot** [comment]
I will revert back and submit a PR. Thanks

**Comment by softwarespot** [comment]
@chriskacerguis, this can be closed

**Comment by dap6000** [comment]
Thanks @softwarespot :)

**Comment by softwarespot** [comment]
Or you can too @dap6000
