### ISSUE TITLE
Issues with accented characters

### ISSUE THREAD

**Issue by Lvkz** [chriskacerguis/codeigniter-restserver#538]
Hi, 

I have this database in latin9 (not my choice and I can't change it), but I've noticed that when I have word with accents or special characters. (i.e. teléfono, Sánchez) I got nothing if I return JSON, and if return XML I got and empty tag. Is that a proper behaviour? How can I fix this?

**Comment by softwarespot** [comment]
Are you sure this is related to our library?

**Comment by Lvkz** [comment]
If I do a var_dump() or even an echo, I got the words right... 

![image](https://cloud.githubusercontent.com/assets/2721391/9335840/70b60cc4-45a4-11e5-9e0c-7abfe5a3771b.png)

**Comment by softwarespot** [comment]
Maybe this is a CI issue?

**Comment by Lvkz** [comment]
I dont think so... I use the exact same model to retieve data for a webapp, and IT works perfectly... :/

**Comment by softwarespot** [comment]
Perhaps provide a small reproducer?

**Comment by softwarespot** [comment]
The following...
```php
$demo = ['id' => 1, 'description' => 'Teléfono'];
$this->response($demo);
```
...produced...
```json
{"id":1,"description":"Tel\u00e9fono"}
```

**Comment by Lvkz** [comment]
Maybe I have an outdated, version... Is the actual versión compatible with CI2?

**Comment by softwarespot** [comment]
No it's not as we use some new features from CI3. If for some bizarre reason it is working with CI2 (which it shouldn't be) then I highly suspect that the output library is at fault. Though CI2 is not receiving updates anymore, only security.

**Comment by Lvkz** [comment]
Uff... Ok... Then I'm going to update both CI and the Restful Library and after making some tests get back at you... Thanks!

**Comment by Lvkz** [comment]
Turns out that you were right. I started all from scratch and just copy the classes and models that I had into a new installation of CI3 and the latest version of codeigniter-restserver, and it worked. :) Now I need to figure out to convert the JSON accents into Swift (iOS), but thats another history. :) Thanks!

**Comment by softwarespot** [comment]
Great. Thought so.
