### ISSUE TITLE
display error for $time_limit for enable REST Enable Limits in REST_Controller.php (Line No: 1128)

### ISSUE THREAD

**Issue by shofik-shoaib** [chriskacerguis/codeigniter-restserver#543]
In the library/REST_Controller.php:

In line No: 1106  you use $timelimit  but in line no 1128 you use $time_limit.
For this error "Limit" doesn't work properly in REST api.

**Comment by softwarespot** [comment]
Please update your library as this was fixed ages ago >> https://github.com/chriskacerguis/codeigniter-restserver/commit/7c1c7ba64d45f024f8b85655b0c29cbda9964cac#diff-7d748d7e419940392ec500f54eab66f2

**Comment by softwarespot** [comment]
@chriskacerguis, maybe a new release is on the cards? As I suspect the @shofik-shoaib  downloaded the release version and not from master.

**Comment by softwarespot** [comment]
@chriskacerguis, this can be closed
