### ISSUE TITLE
Why don't you use CI Input class to get query string?

### ISSUE THREAD

**Issue by kenjis** [chriskacerguis/codeigniter-restserver#544]
This is simple question.

https://github.com/chriskacerguis/codeigniter-restserver/blob/master/application/libraries/REST_Controller.php#L1436

http://www.codeigniter.com/user_guide/libraries/input.html#CI_Input::get

**Comment by softwarespot** [comment]
Good point. I just took the old code and didn't think about refactoring it. Though the function is still needed if using the likes of a POST request with query params.

**Comment by kenjis** [comment]
If you POST (or PUT or DELETE or anything else) request with query string, PHP parses query string and sets `$_GET`.
So you don't have to parse `REQUEST_URI` by yourself.

It seems we can refactor the function like below:
~~~php
    protected function _parse_query()
    {
        $this->_query_args = $this->input->get();
    }
~~~

**Comment by softwarespot** [comment]
I understood. It's a good change :+1:

**Comment by kenjis** [comment]
I sent PR.

I wrote functional tests: https://github.com/kenjis/ci-app-for-ci-phpunit-test/commit/fda2365f7887daefc1122a9bd11980c9d86b05e7
And okay with 2.7.2.

**Comment by chriskacerguis** [comment]
Merged PR.
