### ISSUE TITLE
REST API Access on controller methods. 

### ISSUE THREAD

**Issue by AdnanNuruddin** [chriskacerguis/codeigniter-restserver#545]
REST API checks the access table to see if certain API key can access certain controllers. Is there a way to bind the access to controller methods?
 For example I have 3 methods inside 'user' controller. add_user, view_user, delete_user. I want to give someone access to add_user and view_user but not delete_user. 
Thank you.

**Comment by chriskacerguis** [comment]
Hello,

Sorry for the delay getting back to you, please see line 129 ("Override auth types for specific class/method") in application/config/rest.php
