### ISSUE TITLE
Fatal Error with $config['rest_enable_logging'] = TRUE;

### ISSUE THREAD

**Issue by bribar** [chriskacerguis/codeigniter-restserver#548]
<b>Fatal error</b>:  Call to undefined function now() in 
<b>/Users/brian/Dropbox/work/GamePlan/api/application/libraries/REST_Controller.php</b> on line 
<b>1040</b>
<br />
<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">
    <h4>A PHP Error was encountered</h4>
    <p>Severity: Warning</p>
    <p>Message:  Cannot modify header information - headers already sent by (output started at /Users/brian/Dropbox/work/GamePlan/api/application/libraries/REST_Controller.php:1040)</p>
    <p>Filename: core/Common.php</p>
    <p>Line Number: 569</p>
    <p>Backtrace:</p>
</div>
<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">
    <h4>A PHP Error was encountered</h4>
    <p>Severity: Error</p>
    <p>Message:  Call to undefined function now()</p>
    <p>Filename: libraries/REST_Controller.php</p>
    <p>Line Number: 1040</p>
    <p>Backtrace:</p>
</div>

**Comment by bribar** [comment]
If I uncomment the "// Used to be: function_exists('now') ? now() : time() on line 1040 of the REST_Controller.php it works

**Comment by chriskacerguis** [comment]
So, I must have missed that in a PR.  It should actually be the SQL function "now()" not a PHP function.  That said, give me a minute for a fix.

**Comment by softwarespot** [comment]
now() is a CodeIgniter helper function. The issue was the date helper has to be loaded. The fix was just to revert the commit back.
