### ISSUE TITLE
JSON filtering

### ISSUE THREAD

**Issue by mojidabckuu** [chriskacerguis/codeigniter-restserver#560]
Hi,
Using `restserver` I faced with some problem.
This lib gives us possibility directly transfer model to `response` and convert to json, but what if I need to filter my json before sending it back, what should I do?
Example:
I performed `SELECT * FROM users` and perform `if` statements on some properties then I want to send back only `first_name` and `last_name` not all columns...

**Comment by Rafeethu** [comment]
you can use `unset()` to unset other properties or create a new array with only `first_name` and `last_name`, use that array in response.
