### ISSUE TITLE
Unable to locate Session.php

### ISSUE THREAD

**Issue by fcarentz** [chriskacerguis/codeigniter-restserver#562]
Once implemented navigating to the controller path returns the following error.

rest_controller unable to locate the specified class: session.php

**Comment by chriskacerguis** [comment]
Are you autoloading the session class?

**Comment by fcarentz** [comment]
Yes. Using the same set up I have for another integration that is working.

**Comment by fcarentz** [comment]
Any word on this issue?

**Comment by fcarentz** [comment]
Sorry for the old posts. I removed them. Yes I am autoloading the session class.

**Comment by chriskacerguis** [comment]
Hmm...I can't reproduce the error.  What version of CI are you using?

**Comment by fcarentz** [comment]
The latest. But I am also using the Modular Extensions - HMVC by WireDesignz version 5.5

**Comment by ivantcholakov** [comment]
Try the following: Extend REST_Controller from MX_Controller or from higher base controller if you have such.

**Comment by ivantcholakov** [comment]
Like here: https://github.com/ivantcholakov/starter-public-edition-3/blob/v3.0.80/platform/application/libraries/REST_Controller.php#L19

See also: https://github.com/ivantcholakov/starter-public-edition-3/blob/v3.0.80/platform/application/core/MY_Controller.php#L7

**Comment by itischarles** [comment]
i had the same issue and i followed the suggestion from @ivantcholakov . I have core/MY_Controller.php. so extended like this: REST_Controller extends MY_Controller .
just a thought though, you could told the restserver into a module of its own.

**Comment by rwaddin** [comment]
i am use HMVC WireDesignz too,  change `vendor/chriskacerguis/codeigniter-restserver/src/RestController.php` to extend `class RestController extends \MX_Controller{`
