### ISSUE TITLE
Question with API Routes

### ISSUE THREAD

**Issue by 50l3r** [chriskacerguis/codeigniter-restserver#565]
I need routes like this:

    /api/application/cars GET
    /api/application/cars POST
    /api/application/cars/23 PUT
    /api/application/cars/23 DELETE

I try naming methods like this:

    index_get
    index_post
    index_put
    index_delete

or without index, buy dont works.

There is a way to do this ?

**Comment by softwarespot** [comment]
application is the class name and then use cars_get etc...

**Comment by 50l3r** [comment]
i working on a crud api. The applications names are dynamic.

**Comment by ivantcholakov** [comment]
/api/cars GET

**Comment by 50l3r** [comment]
Cars cant be the name of the class or method. "Cars" is a dynamic variable. Example:

    public function index_get($AplicacionPermalink, $Pagina = 0){}
    public function index_post($AplicacionPermalink){}
    public function index_put($AplicacionPermalink, $EntityId){}

$AplicacionPermalink is "Cars"

**Comment by 50l3r** [comment]
anyone can solve this question? Thanks :p

**Comment by chriskacerguis** [comment]
if I understand correctly, you will need to setup your routes.php to accommodate what you are trying to do.
