### ISSUE TITLE
Question about POST request

### ISSUE THREAD

**Issue by Guicai-Li** [chriskacerguis/codeigniter-restserver#566]
hi：

	public function today_post() {
        
        $start = $this->input->post('start');
        $limit = $this->input->post('limit');

        $client = $this->input->post('client');
        $deviceid = $this->input->post('deviceid');
        $version = $this->input->post('version');

        $this->response(array('start' => $start), REST_Controller::HTTP_OK);
    }
I got the start is NULL.

Then I did a test with the Example,and I found the name'value was NULL.

**Comment by softwarespot** [comment]
Are you sure your post request is correct?

**Comment by Guicai-Li** [comment]
I got it.
content-type should be changed.
