### ISSUE TITLE
Error in  __destruct() line number 562 in Rest_Controller.php

### ISSUE THREAD

**Issue by pradeepch** [chriskacerguis/codeigniter-restserver#567]
Hi, 
I am facing following issue when trying OPTIONS call from DHC:

A PHP Error was encountered
Severity: Notice
Message: Undefined property: Tickets::$config
Filename: libraries/REST_Controller.php
Line Number: 562

Backtrace:
File: /opt/lampp/htdocs/embassyApi/application/libraries/REST_Controller.php
Line: 562
Function: _error_handler

does anyone faced this issue? please help.

**Comment by chriskacerguis** [comment]
There is no reference to Tickets in the code, this appears to be an issue on your end.

**Comment by ahmedfathi1** [comment]
I have the same error
Severity: Notice

Message: Undefined property: Test::$config

Filename: libraries/REST_Controller.php

Line Number: 596

**Comment by awalls** [comment]
Anyone get an answer to this as I have the same issue with relating to the controller name. Obviously something I have missed in the setup but just can't pin it down.

**Comment by awalls** [comment]
Ensure your class constructor calls the parent constructor in REST_Controller.
