### ISSUE TITLE
Unable to load the requested language

### ISSUE THREAD

**Issue by ahmadsobri** [chriskacerguis/codeigniter-restserver#568]
Hi, when I try run example to get user data from my url http://localhost/sia/index.php/api/example/users I have an error like this: Unable to load the requested language file: language/english/rest_controller_lang.php 

how to fix it, please help me

**Comment by mesaugat** [comment]
Download this file: https://raw.githubusercontent.com/chriskacerguis/codeigniter-restserver/master/application/language/english/rest_controller_lang.php and put it in this path: `application/language/english`
