### ISSUE TITLE
How to do token based authorization

### ISSUE THREAD

**Issue by gchokeen** [chriskacerguis/codeigniter-restserver#571]
Hi,

I am writing to write api with authentication token. I don't know how to do the token based authorization with this lib. 

What I want to do is, when user login in at first time I want to create the ```Authorization token``` then I want to reuse that token at consecutive api requests as Authorization header in request.

I am not getting the work flow currently, is this library supporting to do this inbuilt?  If yes how to define the general function to authorize the token, if so I can reuse it in all my reset controller.

Thanks
Gowri

**Comment by fred9176** [comment]
+1

**Comment by RafaMedina** [comment]
+1

**Comment by nuryagdym** [comment]
+1
