### ISSUE TITLE
A feature request: Configurable allowed formats

### ISSUE THREAD

**Issue by ivantcholakov** [chriskacerguis/codeigniter-restserver#573]
We have this maximal set of supported response formats within REST_Controller:

```php
    /**
     * List all supported methods, the first will be the default format
     *
     * @var array
     */
    protected $_supported_formats = [
            'json' => 'application/json',
            'array' => 'application/json',
            'csv' => 'application/csv',
            'html' => 'text/html',
            'jsonp' => 'application/javascript',
            'php' => 'text/plain',
            'serialized' => 'application/vnd.php.serialized',
            'xml' => 'application/xml'
        ];
```
Maybe somebody will want to restrict this set by using a configuration option. I am proposing within the configuration file rest.php the following setting to be added:

```php
// You may remove those formats that you don't want to use.
$config['rest_supported_formats'] = [
    'json',
    'array',
    'csv',
    'html',
    'jsonp',
    'php',
    'serialized',
    'xml'
];
```
During the initialization of REST_Controller this new setting is to modify $_supported_formats accordingly.

Edit: To be placed after $config['rest_default_format'] = 'json';
If the default format is missing in $config['rest_supported_formats'] - add it silently during REST_Controller initialization.

**Comment by chriskacerguis** [comment]
I think that makes a lot of sense.  Could you do a PR?

**Comment by ivantcholakov** [comment]
Ok, I'll find time for this.

**Comment by ivantcholakov** [comment]
Done.

**Comment by softwarespot** [comment]
:+1:

**Comment by chriskacerguis** [comment]
merged.
