### ISSUE TITLE
Digest authentication example

### ISSUE THREAD

**Issue by PureTryOut** [chriskacerguis/codeigniter-restserver#575]
Does anyone have an example of digest authentication? I got basic authentication to work fine, with both config based users and a custom library (after I figured out the library just had to return TRUE or FALSE), but digest is refusing for some reason.

In `config/rest.php`:
```php
$config['rest_auth'] = 'digest';
$config['auth_source'] = 'library';
$config['auth_library_class'] = 'authentication';
$config['auth_library_function'] = 'authenticate';
```

Although the library returns TRUE, or if the user is in the config authorized users, I always get "Unauthorized" back.

EDIT: I call the REST server with curl, and I use this to authenticate:
```
curl_setopt($curl_handle, CURLOPT_USERPWD, $email . ':' . $password);
```
Where email and password are of course filled correctly.

**Comment by rfulcher** [comment]
I am having an issue with Digest also.  I am not using a library.  I setup basic and it works but switch to digest and I get a 'Unauthorized'.  Any help would be great.  I am using the same curl call.

$config['rest_auth'] = 'digest';  (Change to basic and it works fine)
$config['auth_source'] = '';
$config['auth_library_class'] = '';
$config['auth_library_function'] = '';
$config['rest_valid_logins'] = ['admin' => '1234'];

Thanks

**Comment by byronwat** [comment]
hello
i have the same issue
maybe i don t understand normal behaviour of rest.
is it possible to use digest, api key, and library ?
my auth library is returning md5(login:restrealm:password) of database infos depending on login.
i have a C curl programm for test with 
CURLOPT_URL    URL?X-API-KEY=gskw0s4cs8ccg8ck4wgc4o08k0wcgcogooocw4go
and CURLOPT_USERPWD login:password
digest will always return Unauthorized and basic will return result but don t care about password at all, just api key and login.

thanks

**Comment by byronwat** [comment]
ok sorry changed my C curl program hadded :
curl_easy_setopt(curl, CURLOPT_HTTPAUTH, CURLAUTH_DIGEST);
and it worked.
