### ISSUE TITLE
Example's POST method is not working

### ISSUE THREAD

**Issue by iamchathu** [chriskacerguis/codeigniter-restserver#578]
I tried to send POST data using Exmple users post endpoint but i get 403 response with

An Error Was Encountered.

**Comment by iamchathu** [comment]
I tried with fresh codeigniter 3.0.2 files. It works but it doesn't works in my current project which is 3.0.1. I have custom .htaccess and removed index.php from config. user_get methods in working put user_post gives me 403 Forbidden.

**Comment by iamchathu** [comment]
Found the error. It was because i had enabled csrf_protection TRUE in config. Any work around for this please ?

**Comment by chriskacerguis** [comment]
Hello,

you would need to send the csrf token in order to have that (or don't use the CSRF token)
