### ISSUE TITLE
Fatal error: Call to undefined function ldap_connect()

### ISSUE THREAD

**Issue by JoCodes** [chriskacerguis/codeigniter-restserver#582]
Hi , 

First of all thanks for a wonderful library. 
After integration I m facing a few issues. 
Initially the error thrown was 
"Unable to load the requested class: Security". So I have tried replacing 
$this->load->library('security'); to 
$this->load->helper('security'); and then removed both without any success. 
Now, the error popping up is 
"Fatal error: Call to undefined function ldap_connect()". 
Stuck around with this . Would be great if can shed some light on what have to be done to overcome the same . 

Thanks in advance, 
Joe

**Comment by chriskacerguis** [comment]
Hello,

Looks like you need to compile PHP with LDAP support.

Chris

**Comment by aniket-magadum** [comment]
I am getting a error like 
<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Warning</p>
<p>Message:  ldap_connect(): invalid port number: 0</p>
<p>Filename: libraries/REST_Controller.php</p>
<p>Line Number: 1840</p>
