### ISSUE TITLE
login page authentication with REST api

### ISSUE THREAD

**Issue by jgudavalli** [chriskacerguis/codeigniter-restserver#583]
Hello Chris,
I have done a login page with basic code-ignitor3.0+ . I am also able to do get methods using your REST library. I have a login page and register page in my web application. In the login page, the user enters the email and password. I am not able to write the REST api for this. Should I use a post for this? and return user object? Please suggest.

Regards,
Jyothi

**Comment by chriskacerguis** [comment]
Hello,

I can't really comment on your code specifically, but a quick Google search turned up this: http://www.ondeweb.in/ajax-login-form-with-jquery-and-php/

**Comment by jgudavalli** [comment]
Hello Chris,
Thank you for replying to my request. I have a login page , controller for session management and DB implemented. However, I want to have REST api so hat I can build a mobile app.
I could not understand how to write the REST api for login. I was able to get it working for other services.
Below is my code for the login using REST Controller.  The problem is I cannot send the password on url and hence I need to figure out some way. Any idea about this are appreciated.

Regards,
Jyothi

<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

require APPPATH . '/libraries/REST_Controller.php';

class Physiohome_Rest extends REST_Controller {

        public function __construct()// constuctor
        {
                parent::__construct();
                $this->load->model('user_model','',TRUE);

        }

        function index_get($email='', $password='' )
        {

                        $result = $this->user_model->login($email, $password);

                        if($result){
                                $this->response($result, 200); // 200 being the HTTP response code
                        }else{
                                $this->response(array('error' => 'invalid'), 404);
                        }

        }

}
?>

**Comment by zionnite** [comment]
@jgudavalli , where you able to get it work, pls i really need your assistance with the code?
