### ISSUE TITLE
my server is based on php version 5.2 and i update the version to 5.3 codeigniterstop working

### ISSUE THREAD

**Issue by kumarsharmaatul** [chriskacerguis/codeigniter-restserver#585]
my server is based on php version 5.2 and i update the version to 5.3 codeigniterstop working

**Comment by ivantcholakov** [comment]
https://github.com/ivantcholakov/codeigniter-restserver-test - I support downgraded files, take them.

**Comment by chriskacerguis** [comment]
Nothing really to add here.  CI dropped 5.2 support, and so we did as well with this lib.
