### ISSUE TITLE
Page not Found

### ISSUE THREAD

**Issue by francisalfanta** [chriskacerguis/codeigniter-restserver#587]
I can access the api within my localhost. Means I am getting result from GET, POST, PUT, DELETE method.
    'localhost/mycontroller/unit'

The api call is also working in POSTMAN chrome extension.

When I transfer the code to pre-live server with domain name, I have a response '**Page Not Found**'.

Any thoughts where's the problem?

**Settings**
*config/rest.php *

    $config['force_https'] = FALSE;
    $config['rest_default_format'] = 'json';
    $config['rest_status_field_name'] = 'status';
    $config['rest_message_field_name'] = 'error';
    $config['enable_emulate_request'] = TRUE;
    $config['rest_realm'] = 'REST API';
    $config['rest_auth'] = FALSE;
    $config['auth_source'] = '';//'ldap';
    $config['auth_library_class'] = '';
    $config['auth_library_function'] = '';
    $config['rest_valid_logins'] = ['admin' => '1234'];
    $config['rest_ip_whitelist_enabled'] = FALSE;
    $config['rest_ip_whitelist'] = '192.168.10.250';
    $config['rest_ip_blacklist_enabled'] = FALSE;
    $config['rest_ip_blacklist'] = '';
    $config['rest_database_group'] = 'default';
    $config['rest_keys_table'] = 'tb_aqary_api_keys';
    $config['rest_enable_keys'] = TRUE;
    $config['rest_key_column'] = 'key';
    $config['rest_limits_method'] = 'ROUTED_URL';
    $config['rest_key_length'] = 40;
    $config['rest_key_name'] = 'X-API-KEY';
    $config['rest_ignore_http_accept'] = FALSE;
    $config['rest_ajax_only'] = FALSE;
    $config['rest_language'] = 'english';

**Comment by Turaylon** [comment]
Hi, i have the same problem. 
Found any solution so far?

**Comment by jafukaka** [comment]
I am realy searching for the solution for a long time. it would be appreciated if any one helps. Realkly struggling with this issue
