### ISSUE TITLE
Login Authentication Workflow

### ISSUE THREAD

**Issue by dchankhour2** [chriskacerguis/codeigniter-restserver#588]
Hi,

I'm trying to build an authentication workflow where the users need to login first, and if authenticated then on the client i will need to store a session that will then be used to further authenticate additional api calls.  Preferably i would need the user id to be returned from the login function so i can further make calls to the api with the user id.  I currently have a users table that is stored on the API server which have a list of users.

Can you please guid me on how to do this with this library.

Thanks.

**Comment by rohinmittal** [comment]
Hi,

You can use CI's session library for the same. In your login controller class, after validating the user details, you can do something as follows:

$data=array(
'username'=>$this->input->post('username'),
);
$this->session->set_userdata($data);

The above call will add the username to user's cookie. Later on, to fetch the username, use can use:
$this->session->userdata('username')

Let me know if it works for you.

Thanks,
Rohin

**Comment by dchankhour2** [comment]
Thanks.  However, this will not resolve my issue. I have already implemented session on the client after the user is authenticated so i know the user is logged in and i can then have the reset server return the user id so i can store that in a session as well.  then i can start sending that in each request.  However, the issue here is that with the digest authentication it requires you send a username/password with each request which i'm trying to avoid as i don't want to store the password in the session.  Instead i need the Login Function to be able to authenticate the user then generate an Id that i can then pass with each request with out having to send the username/password.  And from that Id i'm able to get the User Id as well so this way i don't need to send the user id as an additional field with request as well.

Looking at the library, im not seeing that flexibility and the closest thing that i could do is utilize api keys but it seems that is an overkill to generate an api key for each user.

**Comment by devcenter** [comment]
I'm having the same issue and pondering the following issue as well (access control per method) 
https://github.com/chriskacerguis/codeigniter-restserver/issues/584

Here are some of my thoughts 
1. How about using the session_id from the CI session as the API keys
- will need to change from using api key table to ci session 
2. After we got to use the api key which is the same as session id then for managing the access control per method can be done outside of the REST library, like in the controller's method, using the existing access control mechanism 

I'm working on this, anyone has a better idea?

**Comment by devcenter** [comment]
sorry I didn't look at the latest code and still using the code from years ago, 
I see the access control is already solved (using the api key and access table) 

For the session id issue that you asked 
1. Current authentication method: login and api key, you can choose one of them 
- change it to login or api key, if login failed then check also api key 
2. API key as session id: 
- Server: after successfull login, generate session id and store it as an api key 
- Server: On returning the result after first client call, include also session id generated 
- Client: when receiving session id from server, put it in cookies or other sesssion 
- Client: when sending rest request, check in cookies / session and send out api key instead of username and password 
* The problem with this is api key became like session_id, you will have a lot of them (unless you're periodically cleaning them up / expiration).

**Comment by devcenter** [comment]
You might want to consider using JWT which I 've customised the library
with

   1. Login to /auth webservice which will return token (encrypted by
   server using a key), token will be saved in client local storage
   2. Client include Authorization header which contain the token in every
   request
   3. Server: check whether token exist and can be decrypted by the key
   - if token cannot be decrypted then failed
   - if token can be decrypted then the token contain user_id, name, other
   session data and can be used for further process
   4. Client: logout by deleting the token

Token functioned as replacement for the session table that we usually use,
this make REST server become stateless (doesnt' have to check to a
centralized session database and can receive any request with token that
can be decrypted using the key). Checkout slideshare on JWT for further
info


On Sun, Jan 3, 2016 at 2:18 AM, dchankhour2 <notifications@github.com>
wrote:

> Using a session will only solve it if you are on the same domain. What if
> you are calling the Rest API from a different domain.
>
> I still feel there is a missing link where a user first needs to get
> authenticated and then on subsequent calls, either the api has to know
> which user it is to be able to fetch information only for that user or the
> client needs to send that information, but i feel sending the user id for
> each api call is unsecured.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chriskacerguis/codeigniter-restserver/issues/588#issuecomment-168418330>
> .
>



-- 
Chenri J
Mobile Phone: (62) (813) 152 05 949

**Comment by dchankhour2** [comment]
I was able to resolve the issue by setting a session when a user is authenticated and store the user id in the session and use that in all future requests.
