### ISSUE TITLE
How $config['rest_auth'] = 'session' works?

### ISSUE THREAD

**Issue by YuvPrime** [chriskacerguis/codeigniter-restserver#594]
According to the documentation, I've set 

##### $config['rest_auth'] = 'session'; and $config['auth_source'] = 'logged_in';

to achieve the REST authorization based on session. Here `logged_in` is a session variable.

In one my function, i.e during login if its success, then i set 
       `$this->session->set_userdata('logged_in', TRUE);`

Now, if he wants to access the lists function with GET request, then it needs to check whether he is authorized and should show the response.

    function lists_get()
    {   
      $users = [
            ['id' => 1, 'name' => 'John', 'email' => 'john@example.com', 'fact' => 'Loves coding'],
            ['id' => 2, 'name' => 'Jim', 'email' => 'jim@example.com', 'fact' => 'Developed on CodeIgniter'],
            ['id' => 3, 'name' => 'Jane', 'email' => 'jane@example.com', 'fact' => 'Lives in the USA', ['hobbies' => ['guitar', 'cycling']]],
        ];
      $this->response($users);
      }

##### Currrently it gives me this response 

    {
       status: false
       error: "Unauthorized"
     }

Now, my questions are

1. how server knows I am the one who authorized as many people call the same service?
2. Do I need to send any additional headers or parameters when making a request? (I use Advanced REST Client chrome extension to check)
3. how the REST call URI looks when authorized and unauthorized user raise? (example pls)

**Comment by kabeza** [comment]
@YuvPrime did you solve this?

**Comment by isatrio** [comment]
Have same problem,

It just need to load session library on autoload. I think you'll can answer by yourself about the question after the session worked.

**Comment by nicolaib** [comment]
Did anyone have a solution to this? I have loaded the session library, but that's not the solution to me.
I have the following settings:
config/config.php
$config['sess_driver']  = 'database';
$config['sess_cookie_name'] 	= 'session_';
$config['sess_save_path']  = 'ci_sessions'; // Which is also correct database name

config/rest.php
$config['rest_auth'] = 'session';
$config['auth_source'] = 'session_'; // I've understood that this should be identical to sess_cookie_name.

The auth in my REST controller still doesn't work, no matter if I set 'files' or 'database' in config.php
Any suggestions?

**Comment by janakamarasena** [comment]
In case some still has this issue, this fix worked for me;

adding `exit();` at the end of the if condition in ` _check_php_session()` in the **REST_Controller.php**. What I found was that the response doesn't end the communication (i.e. like a return statement) any code lines after it will also execute. 
 ```
protected function _check_php_session()
    {
        // Get the auth_source config item
        $key = $this->config->item('auth_source');

        // If false, then the user isn't logged in
        if ( ! $this->session->userdata($key))
        {
            // Display an error response
            $this->response([
                    $this->config->item('rest_status_field_name') => FALSE,
                    $this->config->item('rest_message_field_name') => $this->lang->line('text_rest_unauthorized')
                ], self::HTTP_UNAUTHORIZED);
            exit();
        }
    }
```
PS. this might not be the ideal solution but it worked for me.

**Comment by SpringsTea** [comment]
Also wondering how this is supposed to be setup...

**Comment by gravitymedianet** [comment]
I also have the same issue. I can log in, set session variables and can even send them back. But the minute I do a new AJAX call, the session variables no longer exist and so I get Unauthorized 401 error.
