### ISSUE TITLE
Using post_controller hook..?

### ISSUE THREAD

**Issue by andreipetcu** [chriskacerguis/codeigniter-restserver#595]
I'm trying to use a hook to log db queries (http://jigarjain.com/blog/saving-all-db-queries-in-codeigniter/), but can't seem to make it work since the response() method ends with exit().
Any suggestions?

**Comment by vijatov** [comment]
+1

**Comment by onlytiancai** [comment]
我也遇到这个问题

**Comment by andreipetcu** [comment]
没有狗屎。
