### ISSUE TITLE
how to check custom header is set or not when it sent

### ISSUE THREAD

**Issue by circuitmamu** [chriskacerguis/codeigniter-restserver#598]
just like below example
$this->get('blah'); // GET param
$this->post('blah'); // POST param
$this->put('blah'); // PUT param

it is to check that what is the blah value is set with respective method.

So I'm asking is their any metohd to check the header something like
$this->header('custom_heder_key'); // custom header

Thanks is advance if you give me the resolution.

**Comment by ajay-qburst** [comment]
Try CodeIgniter function $this->input->get_request_header('custom_heder_key')
