### ISSUE TITLE
is their any version control system

### ISSUE THREAD

**Issue by circuitmamu** [chriskacerguis/codeigniter-restserver#599]
http://example.com/books.json
http://example.com/books?format=json

I want to know that is this class support version control

http://example.com/v1/books.json
http://example.com/v2/books?format=json

**Comment by softwarespot** [comment]
No there isn't. Maybe submit a PR?

**Comment by circuitmamu** [comment]
@softwarespot but if this api by default internally support with some route method then it will be better for user

**Comment by softwarespot** [comment]
Please submit a PR with your proposal and then we can see.

**Comment by haribkurup** [comment]
Yes, it can be done by making folders for respective version and using routing along with it.

Paths for versioned APIs:
```
ci_root/application/controller/books/v1_0
ci_root/application/controller/books/v1_1
ci_root/application/controller/books/v2_0

```

And in `ci_root/application/config/routes.php` (change dots in URL to underscore):

```
$route['books/(v[\d]+\.[\d]+)/(.*)'] = function($version, $rest_of_the_url)
{
    return 'books/' . str_replace('.', '_', $version) . '/' . $rest_of_the_url;
};

```

Hope that helps!

**Comment by chriskacerguis** [comment]
I'd love to see a PR for this, but generally I just do this via routes and dir structure.
