### ISSUE TITLE
Postman POST request and Format variable

### ISSUE THREAD

**Issue by maridansoft** [chriskacerguis/codeigniter-restserver#600]
I try to send a format=xml to a post request via postman, but still get default json format back. why?

**Comment by sierrafayad** [comment]
You have 2 ways to request a different format.
using:
HTTP Headers "Accept=xml"
if the request is GET using ?format=xml

**Comment by sierrafayad** [comment]
i forgot. you can use .extension as fotmat
this is a comment from the RESTClient
//Check if a file extension is used e.g. http://example.com/api/index.json?param1=param2

**Comment by maridansoft** [comment]
I see, thank you!
