### ISSUE TITLE
HTTP_RAW_POST_DATA

### ISSUE THREAD

**Issue by tru3d3v** [chriskacerguis/codeigniter-restserver#602]
Hi

I found error when API post body json to controller Post.

error message :
Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

my php info 5.6.5

**Comment by softwarespot** [comment]
Doesn't look like our problem

**Comment by chriskacerguis** [comment]
Agree with @softwarespot seems like an issue with CI
