### ISSUE TITLE
Error logs are not working. 

### ISSUE THREAD

**Issue by mahendravikhar** [chriskacerguis/codeigniter-restserver#604]
As instructed we extend our library from REST_Controller but after this codeigniter normal logs are not working we have given write permission to the folder also we checked with different type of log mode but nothing is working.

We have set the error logs enable from config.php file with log_threshold = 1. Can you please suggest how the error logs works with the API.

Thanks in advance.

**Comment by chriskacerguis** [comment]
We are just using the CI logging system.  Are you seeing any CI logs?
