### ISSUE TITLE
Send an md5 variable as header in each api request

### ISSUE THREAD

**Issue by kabeza** [chriskacerguis/codeigniter-restserver#605]
Hi
I'd like to know if there's a way to access these protected arrays 
_args
_get_args
so I can get a custom header value from each api request

I wanna identify userid in each request without sending it in the url for all the methods that require it.
I'm not sure if storing as session variable because it is being accessed from other domain, android app, etc. and don't know how I should work with that

http://i.imgur.com/WZgkKEk.jpg

Thanks a lot in advance

**Comment by kabeza** [comment]
If you see the image url referenced, I've tried all the following sentences to get the userid value from headers

    	$x1 = $this->get(NULL);
    	$x2 = $this->options(NULL);
    	$x3 = $this->head(NULL);
    	$x4 = $this->query(NULL);
    	print_r($x1);
    	print_r($x2);
    	print_r($x3);
    	print_r($x4);

But output is always empty array. The apikey is correct, auth is ok, etc.

**Comment by ivantcholakov** [comment]
It is not clear where you want to read the header value - on the client or on the server. Anyway, let me guess:

```php
$userid = $this->input->get_request_header('userid');
```

Is this what you want? It is a CodeIgniter's feature.

**Comment by kabeza** [comment]
Wow, that worked Ivan.

However, I thought I could read those header values with the same Rest
Server library

I thought one of these methods was for that... am I wrong?

$x1 = $this->get(NULL);
$x2 = $this->options(NULL);
$x3 = $this->head(NULL);
$x7 = $this->query(NULL);

Thanks a lot in advance!



Saludos,
______________________

Enrique Becerra
Freelancer Web Application developer
http://www.freelancer.com/u/kabeza.html
San Juan // Argentina

**Comment by ivantcholakov** [comment]
Yes, you are wrong, none of these methods serve this purpose.


На 19.01.2016 в 22:20, kabeza написа:

**Comment by kabeza** [comment]
I thought the head method was for that, as stated in the docs

/*
* Retrieve a value from a HEAD request
*
* @access public
* @param NULL $key Key to retrieve from the HEAD request
* If NULL an array of arguments is returned
* @param NULL $xss_clean Whether to apply XSS filtering
* @return array|string|NULL Value from the HEAD request; otherwise, NULL
*/
public function head($key = NULL, $xss_clean = NULL)
{
    if ($key === NULL)
    {
        return $this->head_args;
    }
    return isset($this->head_args[$key]) ? $this->_xss_clean($this->head_args[$key], $xss_clean) : NULL;
}

**Comment by yahyaerturan** [comment]
https://github.com/chriskacerguis/codeigniter-restserver/issues/605#issuecomment-172973284  solved my curiosity completely. Thanks. And one more thing, I am accessing the post values like `$post = json_decode($this->input->raw_input_stream, true);`  as `$post = $this->input->post('post_key');` returns `null`. Is there any way to access posted value easier?

**Comment by ivantcholakov** [comment]
@yahyaerturan

https://github.com/chriskacerguis/codeigniter-restserver/blob/2.7.2/application/controllers/api/Example.php#L109

http://iridadesign.com/codeigniter-restserver-test/post-test
