### ISSUE TITLE
when new version is launched or released

### ISSUE THREAD

**Issue by circuitmamu** [chriskacerguis/codeigniter-restserver#609]
@chriskacerguis
Hi when your next release is deployed??

**Comment by softwarespot** [comment]
Maybe the documentation should be updated. I will do a PR request now

**Comment by circuitmamu** [comment]
@softwarespot @chriskacerguis I think new version will come soon this month....

**Comment by softwarespot** [comment]
I don't know if it will be updated this month.

**Comment by circuitmamu** [comment]
@chriskacerguis new version will be launched or not?

**Comment by chriskacerguis** [comment]
@circuitmamu to answer your rather rude sounding comment (I don't know if that was your intent). I will do a new release once we have unit testing in the code. When will that be?  I don't I know. Is it a WIP right now (PR's are always welcome).

There were 2 big slowdowns for development; (1) I wanted to wait until CI was finally release and (2) right around the time it was release my wife and I had a baby. Things are gettin back to normal so development should move forwards much faster.
