### ISSUE TITLE
How to set content type of response

### ISSUE THREAD

**Issue by cmanish049** [chriskacerguis/codeigniter-restserver#621]
Can any one tell me is there any method in rest controller to set content type of response?

**Comment by harrykrupp** [comment]
In your `application/config/rest.php` look for these:

`$config['rest_default_format'] = 'json';`
Here you can change the default format for response.

`$config['rest_supported_formats'] = [
    'json',
    'array',
    'csv',
    'html',
    'jsonp',
    'php',
    'serialized',
    'xml',
];`

**Comment by cmanish049** [comment]
I have set the $config['rest_default_format'] = 'json'
But when I output the response using print_r(json_encode($result_array))
The response is of type text/html
So hou can I fix it

**Comment by harrykrupp** [comment]
What is $result_array? 
Output you intend to send OR output you get from your REST API?
Can you please post a snippet of what you are trying to achieve, your question isn't clear to me.

**Comment by cmanish049** [comment]
$ result_array is the output I get from REST API
Below is the code snippet
function user_history_get()
 {
                $service_no_ip = $this->input->get('consumer',TRUE);
		if (strlen($service_no_ip) < 7 || !($service_no_ip >= 0 || $service_no_ip < 0)) 
		{ 
			// check 7 coz that is the minimum length needed
			$error_result['status'] = "error";
			$error_result['data'] = "Input Service no. is not valid!";
			print_r(json_encode($error_result)); exit;	
		} 
}

**Comment by harrykrupp** [comment]
You don't have to do json_encode, based on output format `$this->response()` function will do it for you. Just pass output to it. Try the code below:  
    
```
    function user_history_get()
    {
        $service_no_ip = $this->input->get('consumer', TRUE);
        if(strlen($service_no_ip) < 7 || !($service_no_ip >= 0 || $service_no_ip < 0))
        {
            // check 7 coz that is the minimum length needed
            $error_result['status'] = "error";
            $error_result['data'] = "Input Service no. is not valid!";
            $this->response($error_result);
        }
    }
```

Hope this works for you.

**Comment by cmanish049** [comment]
Thanks harrykrupp for your help
