### ISSUE TITLE
How to disable access from http?

### ISSUE THREAD

**Issue by s26** [chriskacerguis/codeigniter-restserver#623]
I have few questions regarding using http or https. We have created Web+mobile application. Web application has https. Currently, our APIs can be accessed via http and https both.

I have updated rest.php as following:
```
$config['force_https'] = TRUE;
$config['rest_ignore_http_accept'] = TRUE;
```
However, I can access APIs via http using postman client

1) Should I keep http or restrict to only https?
2) How to configure it to use only https?

**Comment by songwritersg** [comment]
I use this code on controller

`
 function __construct()
 {
        parent::__construct();

        if($_SERVER['SERVER_PORT'] !== 443)
        {
                  $this->response(NULL, REST_Controller::HTTP_BAD_REQUEST);
        }      
        $this->methods['user_get']['limit'] = 500; // 500 requests per hour per user/key
        $this->methods['user_post']['limit'] = 100; // 100 requests per hour per user/key
        $this->methods['user_delete']['limit'] = 50; // 50 requests per hour per user/key
}
