### ISSUE TITLE
PHPSESSID

### ISSUE THREAD

**Issue by artgrosvil** [chriskacerguis/codeigniter-restserver#624]
Hi, when you create a session in codeigniter v.3, a session is created, but a PHPSESSID is also created. That starts to produce files of the sessions and prevents you from working yourself to the sessions in codeigniter. It's also strange that session are created, even if you don't visit the website.

**Comment by chriskacerguis** [comment]
Does this behavior happen without the rest server installed?  REST server uses the CI Session, so my first thought is the problem exists in CI
