### ISSUE TITLE
Limit's not updating in DB table

### ISSUE THREAD

**Issue by ecowed** [chriskacerguis/codeigniter-restserver#625]
I have set limits using `$this->methods['index_put']['limit'] = 500;` but when I make a call to this URI I don't see any rows added to the limits table.

Config for limits is on, table name is correct and created using the SQL in the config file. Using API_KEY as limits method.

Any clues or ideas to get this working?

**Comment by Broekhuis** [comment]
Same here.

**Comment by ecowed** [comment]
For the above to work, you need to have the limits method as ROUTED_URL. If you want to use API_KEY, you have to specify the API key in the `$this->methods` call. 

My (as yet untested) resolution is as follows - this is taken from line 1118 of REST_Controller.php:

`switch ($this->config->item('rest_limits_method'))
        {
          case 'API_KEY':
            $limited_uri = 'api-key:' . (isset($this->rest->key) ? $this->rest->key : '');
            $limited_method_name = isset($this->rest->key) ? $this->rest->key : '';
            // How many times can you get to this method in a defined time_limit (default: 1 hour)?
            $limit = $this->config->item('rest_limits_api_key');
            break;

          case 'METHOD_NAME':
            $limited_uri = 'method-name:' . $controller_method;
            $limited_method_name =  $controller_method;
            // How many times can you get to this method in a defined time_limit (default: 1 hour)?
            $limit = $this->methods[$limited_method_name]['limit'];
            break;

          case 'ROUTED_URL':
          default:
            $limited_uri = $this->uri->ruri_string();
            if (strpos(strrev($limited_uri), strrev($this->response->format)) === 0)
            {
                $limited_uri = substr($limited_uri,0, -strlen($this->response->format) - 1);
            }
            $limited_uri = 'uri:' . $limited_uri . ':' . $this->request->method; // It's good to differentiate GET from PUT
            $limited_method_name = $controller_method;
            // How many times can you get to this method in a defined time_limit (default: 1 hour)?
            $limit = $this->methods[$limited_method_name]['limit'];
            break;
        }

        if (isset($this->methods[$limited_method_name]['limit']) === FALSE )
        {
            // Everything is fine
            return TRUE;
        `

I will then add `$config['rest_limits_api_key'] = 200` to my rest.php config file and then I hopefully have a global limit on how many calls each API key can make per hour.
