### ISSUE TITLE
Not populating db with limits data.

### ISSUE THREAD

**Issue by prudhvi85** [chriskacerguis/codeigniter-restserver#627]
In REST_controller there an bug on line 1108. It should be
$limited_method_name = $controller_method;

**Comment by Broekhuis** [comment]
My limits-table is also not populated. 

However I don't have that ($limited_method_name) on line 1108. Can you specify more precisely what should be changed by indicating:

_[old code]_

should be:

_[new code]_

Thanks & regards,

Erik

**Comment by prudhvi85** [comment]
Now the code is on line 1121.

**Comment by edwade3** [comment]
See my issue #625 for info on this too - my issue was it not updating when using API_KEY as the limit method
