### ISSUE TITLE
api/v1/controller is different of api/v1/controller/

### ISSUE THREAD

**Issue by BugsBunnyBR** [chriskacerguis/codeigniter-restserver#628]
If I add an slash in the end of a `post` request it is handled as a different the `get` endpoint.
If you have index_get() and index_post(), the request will be handled as get even if you are using `post` http verb.
I am using code igniter 3.0.5 with PHP 5.6.

**Comment by chriskacerguis** [comment]
That would be an issue with your routes.php file (not this lib).
