### ISSUE TITLE
Installation: Language file is also required

### ISSUE THREAD

**Issue by luciodiri** [chriskacerguis/codeigniter-restserver#629]
3.0.6 Installation specifies adding the files:
REST_Controller.php , Format.php & rest.php
But the lib also may requires the language file. in my case:
application/language/english/rest_controller_lang.php

**Comment by russ-ab** [comment]
Use [released versions](https://github.com/chriskacerguis/codeigniter-restserver/releases)  instead of downloading separeted files. :smiley:

**Comment by luciodiri** [comment]
Thanks @russ-ab :) ,
In my case I just added the missing file.
Since the installation instructions name the minimal package files, I suggest adding this note.

**Comment by softwarespot** [comment]
Please close this issue
