### ISSUE TITLE
$this->response causes error

### ISSUE THREAD

**Issue by Broekhuis** [chriskacerguis/codeigniter-restserver#630]
I hope someone can help me with this. I have:
 
        $news = $this->news_model->get_news( $this->get('id') );

This succesfully queries my database and returns a news-item into the array $news  ( I checked that with print_r($news) )

However when I try:

  $this->response($news, REST_Controller::HTTP_OK);

I keep getting this error:

  ==============================
  A PHP Error was encountered
  Severity: Error
  Message: Call to a member function factory() on null
  Filename: libraries/REST_Controller.php
  Line Number: 766
  Backtrace:
  ==============================

I hope someone can help..

**Comment by Broekhuis** [comment]
Well, that was on Xampp.. I copied everything to my server and there it works. No idea what caused the error..

**Comment by softwarespot** [comment]
Please close the issue.
