### ISSUE TITLE
Error 500 with codeigniter 2.2.0

### ISSUE THREAD

**Issue by sandeeppujare** [chriskacerguis/codeigniter-restserver#634]
application/controllers/api/Example.php---This is my controller path in codeigniter 2.2.0 but everytime i try to run any method from it it show 500 configuration error. I am not even autoloading the REST_Controller library.

**Comment by fernandodeveloper** [comment]
Requirements

PHP 5.4 or greater
CodeIgniter 3.0+

**Comment by chriskacerguis** [comment]
What error do your logs show?

**Comment by chriskacerguis** [comment]
Also, we no longer support CI 2.x
