### ISSUE TITLE
Call other function in controller class instead of index_get / index_post

### ISSUE THREAD

**Issue by ketavc** [chriskacerguis/codeigniter-restserver#639]
I want to call other method instead of index method. But it will always call index method.

Following is my code : 

> 

     require(DOCROOT . "libraries/REST_Controller.php");

     class Users extends REST_Controller {

    function __construct() {
        header('Access-Control-Allow-Origin: *');
        header("Access-Control-Allow-Headers: X-API-KEY, Origin, X-Requested-With, Content-Type, Accept, Access-Control-Request-Method");
        header("Access-Control-Allow-Methods: GET, POST, PUT, DELETE");
        $method = $_SERVER['REQUEST_METHOD'];
        if ($method == "OPTIONS") {
            die();
        }
        parent::__construct();
        //echo uri_string();exit;
        $requestData = serialize($this->input->post());
        $this->common_model->addApiLog(uri_string(), $requestData);
    }

    public $true = true;
    public $false = false;

    /**
     * This function is used for perform login.
     *
     * 
     * @return userData
     */
    public function index_get(){
        echo "index_get";
    }
    public function index_post() {
    // Code
    }
    public function user_post() {
    // Code
   }
    public function user_get() {
     // Code
    }

I'm calling this Controller like this : 

http://localhost/sovoteit/api/v1/index.php/Users#index_get

http://localhost/sovoteit/api/v1/index.php/Users#index_post

http://localhost/sovoteit/api/v1/index.php/Users#user_post

It is work fine in index methods but when i call user_post method, it will by default call index_post.

How can i call user_post method?

**Comment by chriskacerguis** [comment]
Short version is that you cannot.  I'm not sure i understand the case use of your example, 

http://localhost/sovoteit/api/v1/index.php/Users#index_post and http://localhost/sovoteit/api/v1/index.php/Users#user_post are the same thing (at least from a REST endpoint perspective).
