### ISSUE TITLE
Not getting data in PUT method

### ISSUE THREAD

**Issue by ketavc** [chriskacerguis/codeigniter-restserver#641]
I'm trying to update data using PUT method.
I am using $this->put('UsreId'); But I'm not getting Data.
Below is my code
`public function update_put(){
 echo $this->put('userId); 
}`

Result is blank.

How can I receive PUT data?

**Comment by spreaderman** [comment]
Wow, all day trying to figure out the problem.  Just found you comment @ketavc  have the same issue!

**Comment by ketavc** [comment]
Hello @spreaderman 
I've checked REST_Controller.php file and "PUT" function is already there. But Still I'm not getting data.
Please provide solution.

**Comment by spreaderman** [comment]
@ketavc  No solution yet.  Hoping someone can take a look soon.  Have asked also in stackoverflow but no good hints/suggestions yet.

**Comment by spreaderman** [comment]
@ketavc  Are you using POSTMAN?  What is the STATUS CODE you are receiving?  200?  400?

**Comment by ketavc** [comment]
Yes, I'm using POSTMAN and getting status code 200.

**Comment by datnq201088** [comment]
I have the same problem :(

**Comment by spreaderman** [comment]
Requesting some help with this from anyone!  Just cannot get any data out of print_r($this->put());  It simply returns Array();  Sorry, don't know enough to debug the source code :-(

**Comment by datnq201088** [comment]
Solution: if you used POST MAN, please choose: `x-www-form-urlencoded` instead of `form-data`

**Comment by spreaderman** [comment]
@datnq201088 Thank you. Tried that but same issue.

**Comment by datnq201088** [comment]
@spreaderman : you tried to  use curl testing ?

**Comment by spreaderman** [comment]
For GET, no problems:  curl -H "X-API-KEY: 123456" http://localhost:8000/api/student/1
{"status":"success","message":{"student_id":"1","email_address":"jim@example.com","first_name":"Jim","last_name":"Test","phone_number":"0123456789","status":"active","created_timestamp":"2016-04-09 18:48:32","updated_timestamp":null}}

For PUT, same issue: curl -X PUT -H "X-API-KEY: 123456" http://localhost:8000/api/student/
{"status":"failure","message":[]}

**Comment by spreaderman** [comment]
Here is the code essentially:  github.com/alexmarton/RControl  GET localhost:8000/api/student/1 works well.  PUT should return error messages but doesnt.

**Comment by datnq201088** [comment]
``` javascript
For PUT, same issue: curl -X PUT -H "X-API-KEY: 123456" http://localhost:8000/api/student/
{"status":"failure","message":[]}

``` 
I don't realize your userId on the url? what are the parameters that you want to change?

**Comment by spreaderman** [comment]
Can you please show a screenshot of your HEADER tab and BODY tab in POSTMAN?

**Comment by datnq201088** [comment]
@spreaderman : 
![post-man](https://cloud.githubusercontent.com/assets/7147240/14944282/c569398c-1018-11e6-95df-f18788748c70.png)

**Comment by spreaderman** [comment]
FYI, for me, I have solved the problem.  I made a stupid mistake with POSTman and was send body data through the headers.
