### ISSUE TITLE
Unable to load library in if I use model

### ISSUE THREAD

**Issue by circuitmamu** [chriskacerguis/codeigniter-restserver#646]
I have created a controller in api folder

**application/controller/api/Webservice_1_1.php**
In controller constructor I call the model for it
require APPPATH . '/libraries/REST_Controller.php';
class Webservice_1_1 extends REST_Controller{
function __construct() {
	// Construct the parent class
	parent::__construct();
	$this->load->model('webservice_1_1_model');
}

function test_post(){
$testCheck['status'] = 'success';
$testCheck['response'] = $this->webservice_1_1_model->test();
$this->response($testCheck);
}
}

But when load any custom library that follow the syntax of codeigniter it doesn't load properly
**application/model/Webservice_1_1_model.php**
class Webservice_1_1_model extends CI_Model
{
function __construct() {
        parent::__construct();
		$this->load->library('custom_library');
    }
function test(){
$response = $this->custom_library->custom_function(25,30);
return $response;
}
}

<?php defined('BASEPATH') OR exit('No direct script access allowed');

class Custom_library {
	private $CI;
	
	public function __construct(){
		$this->CI =& get_instance();
	}
	
	public function custom_function($a, $b) {return $a+$b;}

It gives me an error like below
Fatal error: Call to a member function custom_function() on a non-object in D:\wamp\www\ci-demo\application\models\Webservice_1_1_model.php on line 25

**Comment by fernandodeveloper** [comment]
The class name is starting with a capital letter and you're calling tiny. Try  $this->**C**ustom_library->custom_function(25,30);
