### ISSUE TITLE
Basic rest_auth not working in my server

### ISSUE THREAD

**Issue by abneralvarado** [chriskacerguis/codeigniter-restserver#648]
When I try my settings in localhost everything works fine.

When I try to use basic authentication in my server the Authentication Required prompt doesn't recognize  the username and password. I think is an .htaccess issue.

When calling the method i get the dialog that prompts for username and password even if i write in the correct username and password it wont accept it.

**Comment by chriskacerguis** [comment]
You didn't really provide enough info for me to troubleshoot.
