### ISSUE TITLE
Auth session

### ISSUE THREAD

**Issue by sergomet** [chriskacerguis/codeigniter-restserver#651]
If i set:
$config['rest_auth'] = 'session';

I cannot access public function login_post(), because it is "Unauthorized". 
I can find a config for skipping methods authorizations.

**Comment by cwchong** [comment]
I have not tried it, but the documentation in config/rest.php suggests overriding via:

`$config['auth_override_class_method']['deals']['view'] = 'none';`

so you can just replace 'deals' and 'view' with your controller name and 'login' to make it non-protected.
