### ISSUE TITLE
404 error not returned properly when rest_enable_logging is TRUE

### ISSUE THREAD

**Issue by surajsingh-itian** [chriskacerguis/codeigniter-restserver#655]
codeigniter with postgres, when configured rest_enable_logging = TRUE

For 404, the response not as expected, also status & error field are not preset, as soon as rest_enable_logging = FALSE response is proper

**Comment by chriskacerguis** [comment]
I'm sorry, I'm not sure I follow.

**Comment by surajsingh-itian** [comment]
When rest_enable_logging = TRUE and URL not in routes is requested, instead of JSON response with error, PHP error is given.
But when rest_enable_logging = FALSE, response in JSON containing proper error code

**Comment by chriskacerguis** [comment]
No response.  Closing.

**Comment by surajsingh-itian** [comment]
Hello Chris,
I wasn't available for couple of days,
The problem is when config property **rest_enable_logging = TRUE** and URL not in **routes** is invoked/called on server, instead of JSON failure response, I'm getting PHP error.
