### ISSUE TITLE
PHP Fatal error after migration to codeigniter 3

### ISSUE THREAD

**Issue by marwagamal** [chriskacerguis/codeigniter-restserver#658]
Recently i migrated from v2.4 to v4 .. on development server i didn't have any issues but when i deploy on production the following error appears

PHP Fatal error:  Call to a member function item() on a non-object in //application/libraries/REST_Controller.php on line 597
Line 597 >>  {if ($this->config->item('rest_ip_whitelist_enabled') === TRUE)}

when i change that line to {if (config_item('rest_enable_logging'))} it worked fine without errors

**Comment by chriskacerguis** [comment]
Hello,

Can you please provide a bit more context?

**Comment by marwagamal** [comment]
i updated the description, 

I'm using PHP5.6 with apache2 on Centos 6 .. both development and production servers.

**Comment by chriskacerguis** [comment]
When you updated did you update config/rest.php to the latest version?

**Comment by marwagamal** [comment]
Yes I did

**Comment by chriskacerguis** [comment]
They error indicates that the problem is with code igniter...Also, not sure what you meant by v4, there is no CI v4
