### ISSUE TITLE
Controller in sub folder showing 404

### ISSUE THREAD

**Issue by devkiran** [chriskacerguis/codeigniter-restserver#661]
I have a controller in the path /application/api/v1/contacts.php - showing 404
But if i change the path to /application/api/contacts.php - Its working fine. 

CI version - 2.1.3

What is the latest version of this library which support controller access inside sub folders for CI version 2.1.3.

Thanks

**Comment by chriskacerguis** [comment]
I'm sorry, this library doesn't support CI 2.x series anymore.
