### ISSUE TITLE
Custom exception handler with REST_Controller

### ISSUE THREAD

**Issue by scion4581** [chriskacerguis/codeigniter-restserver#667]
Hello. I am facing with some problem using REST_Controller, maybe somebody point me in right direction

So problem - I cant set method for handle exception in my controller using set_exception_handler
cause in REST_Controller _remap function catching all exceptions :(

I always have to catch all exception in controller or model methods 
otherwise _remap will catch them

**Comment by AmitMY** [comment]
The trivial solution is to remove the try/catch, in method `_remap` calling for `call_user_func_array`

What's wrong with it?
