### ISSUE TITLE
Catching constructor exceptions

### ISSUE THREAD

**Issue by AmitMY** [chriskacerguis/codeigniter-restserver#668]
I changed the _remap function a bit, by adding response code support from exceptions
```
if($ex instanceof ResourceException) $response_code = $ex->getCode();
else $response_code = self::HTTP_INTERNAL_SERVER_ERROR;
```
Then I added some exceptions, for example:
```
class UnauthorisedException extends ResourceException {
	function __construct(string $message) {
		parent::__construct($message, REST_Controller::HTTP_UNAUTHORIZED, null);
	}
}
```

If I call it from a method, it is properly catched, and handled into a nice response.

If I call it from the constructor, it becomes a PHP error.

Is there a way to add support for the constructor of a controller, not just the method?

It forces me to use a custom errors handler, and I would like to stick to one function for responses handling.

**Comment by chriskacerguis** [comment]
Sure, we can add support.  I'll add it to my todo list.  PR's are welcome :)

**Comment by chriskacerguis** [comment]
This will be in the the next major release.
