### ISSUE TITLE
Limits not working? 

### ISSUE THREAD

**Issue by ralphioooo** [chriskacerguis/codeigniter-restserver#672]
Hi there, Great Lib!

I found an issue with the limits function. In the example:
$this->methods['user_get']['limit'] = 500; // 500 requests per hour per user/key
needs to be:
$this->methods['**users**_get']['limit'] = 500; // 500 requests per hour per user/key

And in the REST_Controller.php line 1137 needs to change from:
$limited_method_name = isset($this->rest->key) ? $this->rest->key : '';
to
$limited_method_name =  $controller_method;

Otherwise it can not get the method type.

**Comment by gotphp** [comment]
I confirmed this to be true.

**Comment by teabrg** [comment]
Hi i have made the changes that you say but for some reason it does not update the limits table with the count it just adds a new row every time

**Comment by chriskacerguis** [comment]
This should be fixed via https://github.com/chriskacerguis/codeigniter-restserver/pull/702
