### ISSUE TITLE
Problems with UTF-8 characters.

### ISSUE THREAD

**Issue by nim118** [chriskacerguis/codeigniter-restserver#675]
$this->response($result, 200);

My result variable is having UTF-8 characters in it. And to use the option 'JSON_UNESCAPED_UNICODE'

I am not able to use response function. 

Thanks in advance.

**Comment by chriskacerguis** [comment]
Im not sure what your question is. Can you please restate it?

**Comment by nim118** [comment]
Using this response function I was not able to give UTF-8 characters in response. 

So I found that in json_encode function if we pass this option 'JSON_UNESCAPED_UNICODE' it was passing UTF-8 chars correctly. 

And to have my thing working I changed in the core file of your REST controller in the response function.  

I made this change 

return json_encode($data, JSON_NUMERIC_CHECK|JSON_UNESCAPED_UNICODE);

And it worked for me.
