### ISSUE TITLE
Use API Keys

### ISSUE THREAD

**Issue by Usman-Asghar** [chriskacerguis/codeigniter-restserver#676]
Hi Chris
I want your help regarding using Rest server with my Angular Application. Please guide me how i can login without API key and after login create a new API key for every unique user and after that i can use that key for further http requests. Please respond me back as soon as possible

Looking for your cooperation. Thanks

**Comment by chriskacerguis** [comment]
I'm sorry, but I cannot provide help on specific end-user applications. That said, if you find a bug or think of a feature that would be helpful please let me know and I can address it quickly.

**Comment by Usman-Asghar** [comment]
So you can give me any docs related my question?

**Comment by shaiman** [comment]
I want to know how can  craet key without key
