### ISSUE TITLE
Only second HTTP request returns correct userID with BASIC authentication and Codeigniter 2

### ISSUE THREAD

**Issue by arnisjuraga** [chriskacerguis/codeigniter-restserver#678]
Hi!

Restserver version: 3.0.0-pre

We have `/api/login/auth` method, accessible via:
http://server/api/login/auth/format/json

Rest is configured to use 'basic' authentication. 

We have added "sql select" for authenticating with users from DB.

**The problem:** `$this->acl->userID` method, if put it in `auth_get`, will **always** return "0" on first exec, even with successful authorization.

And only on repeated request it will return correct userID.

We did a small workaround - after successful authorization, we redirect request to dummy `result` method, (`/api/login/result`), creating a new HTTP request and, as described before, being a second request after first authorization already - it works correctly and returns `userID`.

Is there something we are doing wrong, or this is by design?

Login Controller:
~~~php
<?php
require (APPPATH.'/libraries/REST_Controller.php');
class Login extends REST_Controller {
 	function __construct(){
        parent::__construct();
	}
    function auth_get()
    {
		header("Location: /api/login/result/format/json");
    }
    function result_get(){
		$result['userID'] = $this->acl->userID;
		if($result['userID']) {
			$result['auth'] = 'Success';
		} else {
			$result['auth'] = 'fail';
		}
		$this->response($result, 200);
    }
}
~~~

**Comment by chriskacerguis** [comment]
Sorry, this doesn't appear to be an issue with the library (and I can't reproduce it)

**Comment by arnisjuraga** [comment]
Ok, the issue still appears in our 2 different environments, but lets's say - if someone can it reproduce, then investigate it further.
Still, this is for quite an old version, may be this has been fized with other changes.
