### ISSUE TITLE
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by kpradeep09** [chriskacerguis/codeigniter-restserver#680]
I am Using Your Library for Rest Api
 I am Getting Error:-
 " Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access."

My Ajax Request is-:"
$.ajax({
			url:"http://domain_name/index.php/login/authenticate",
			crossOrigin : true,
			data: params,
			type: "POST",
			dataType: "json",
			headers: {
						'Authorization': "basic ",
						"Access-Control-Allow-Origin": "*"
							                                    
            },
 
      contentType: "application/json",
            error: function(){
				console.log(' Error in processing!');
			},
            success: function(data) {
				console.log('success');
				console.log(JSON.stringify(data));
			}
        }); 

I also Added the following  header in Construct part of  Rest_controller Librabry

header('Access-Control-Allow-Origin: *');
header("Access-Control-Allow-Headers: X-API-KEY, Origin, X-Requested-With, Content-Type, Accept, Access-Control-Request-Method");
header("Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE");
$method = $_SERVER['REQUEST_METHOD'];

$respon='';

if($method == "OPTIONS") {

}
 plz help me out

**Comment by MathieuNls** [comment]
Hey, I am not from the dev team but I went around this problem by adding an index_options in my controller.

`  public function index_options(){
     $this->response(null, REST_Controller::HTTP_OK);
  }`

**Comment by chriskacerguis** [comment]
Thanks for responding @MathieuNls yes, you are correct adding an OPTIONS is best.

**Comment by vinayindvg** [comment]
@MathieuNls i too got the same error but still i'm unable to reslove it
and i added that index_options() in my controller 
is that rite or any ways..?

**Comment by MathieuNls** [comment]
@vinayindvg 

Do you use API key ? If so, you'll need to exclude index_options from the key protection/limitation:

```
class Users_api extends REST_Controller {

    protected $methods = [
      'index_get' => ['key' => true, 'limit' => 60],
      'index_put' => ['key' => false, 'limit' => 20],
      'index_post' => ['key' => false, 'limit' => 20],
      'index_delete' => ['key' => true, 'limit' => 20],
      'index_options' => ['key' => false],
     ];

    public function __construct(){
      parent::__construct();
    }
    public function index_options(){
        $this->response(null, REST_Controller::HTTP_OK);
    }

   public function index_get(){}

   public function index_put(){}

   public function index_post(){}

   public function index_delete(){}
}
```

**Comment by Neetesh1** [comment]
Thank you so much @MathieuNls  below function work like a charm.
```
public function index_options(){
        $this->response(null, REST_Controller::HTTP_OK);
    }
```
