### ISSUE TITLE
Error 404 Page not Found codeigniter 3 

### ISSUE THREAD

**Issue by lunkadbhushan** [chriskacerguis/codeigniter-restserver#682]
I am facing Error 404 Page not found on codeigniter3. I am using Apache2/PHP7.0 on Ubuntu machine.

**Comment by chriskacerguis** [comment]
Could you please provide more info?  There's nothing here that I can help with.  What are you doing?  What are you expecting?  What does your code look like?

**Comment by diegodeveloper** [comment]
@lunkadbhushan Check the routes in the application / config / routes.php, or application / config / config.php
If the problem is not there, I mean, if the default URL is correct then the config.php file is probably a problem with .htaccess you wrote ...

**Comment by lunkadbhushan** [comment]
@chriskacerguis @diegodeveloper Thanks. Issue has been resolved. :+1:
