### ISSUE TITLE
Giving HTML response from my server 

### ISSUE THREAD

**Issue by nim118** [chriskacerguis/codeigniter-restserver#683]
My local and server code base is same but local works fine with post man and returns json data but on my server it returns HTML. Do I need to  change anything on my server !!!!

**Comment by chriskacerguis** [comment]
Sounds like PHP is not enabled on your server.

**Comment by topsnimesh** [comment]
Look like a made fun of my self. It was my bad sorry :P. I was passing extra space with response. 

Thank You

**Comment by chriskacerguis** [comment]
No worries, glad it was something easy.
