### ISSUE TITLE
Automatically array_walk_recursive output arrays with htmlentities, or provide a flag to do so?

### ISSUE THREAD

**Issue by ilikenwf** [chriskacerguis/codeigniter-restserver#684]
I ended up fixing it locally but didn't want to pull request without some discussion - I ran into an issue where the output I'm pulling from a DB2 server (long story) includes some characters that aren't JSON friendly - to the point json_encode chokes on them.

Recursively encoding the array fixed the issue, but should we automatically encode these since, I believe, that is the standard thing to do? If not automatically, perhaps add a configuration option to enable such a thing?

**Comment by chriskacerguis** [comment]
It's an interesting problem, but not something that I would think that the library would do.  It seems that you would want to encode/sanitize before outputting.  Something like this...

```php
function index_get() {
     $unencoded_data = $this->some_method();
     $encoded_data = encode_my_data($unencoded_data)
     return $this->result($encoded_data)
```
