### ISSUE TITLE
DELETE parameters

### ISSUE THREAD

**Issue by pawelduszczak** [chriskacerguis/codeigniter-restserver#688]
Hi.

I've been testing this library and I have one issue with DELETE.

I'm sending simple request:
`DELETE http://site.com/api/user/id/0`

I was expecting parameter `id` to be returned by the method `$this->delete('id')` and that did not happened. Parameter was instead reachable by `$this->get('id')`.

I did some simple modification to combine `_delete_args` with URI params:
`protected function _parse_delete()
    {
        // These should exist if a DELETE request
        if ($this->input->method() === 'delete')
        {
            $this->_delete_args = array_merge($this->input->input_stream(), $this->uri->uri_to_assoc());
        }
    }`

But i'm not sure that this solution is proper. Can You tell me what can be the problem i can't get params with `$this->delete('param_name')`?

Here is also raw request - response data from my tests before modification, where "error" is returned due to lack of "id" in "delete" method:

DELETE http://site.com/api/user/id/0

 -- response --
400 Bad Request
Server:  nginx/1.6.2
Date:  Fri, 12 Aug 2016 07:00:11 GMT
Content-Type:  application/json; charset=utf-8
Connection:  keep-alive
Set-Cookie:  csrf_cookie_aw_cms=84a3044ab615870d6f71c13b2bb8a9ab; expires=Fri, 12-Aug-2016 09:00:11 GMT; Max-Age=7200; path=/ cisession=562b51a6ad0f8feef0c2b8a414ce5afa255be2b0; expires=Fri, 12-Aug-2016 09:00:11 GMT; Max-Age=7200; path=/; HttpOnly
Expires:  Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control:  no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma:  no-cache
Vary:  Accept-Encoding
Transfer-Encoding:  chunked

$this->delete()
array(0) {
}
$this->get()
array(1) {
  ["id"]=>
  string(1) "0"
}
$this->post()
array(0) {
}
$this->put()
array(0) {
}
{"message":"Method delete ERROR","id":0}

**Comment by chriskacerguis** [comment]
Hello @pawelduszczak Could you please provide info on the server are you using (Linux / Windows, Apache / NginX, etc)?

**Comment by pawelduszczak** [comment]
I use apache basicly plus nginx as proxy, all os linux os.

**Comment by chriskacerguis** [comment]
Have you tried to reproduce this problem without the proxy part?

**Comment by pawelduszczak** [comment]
Unfortynetly no. Problem occured on remote server and provider propably won't do such reconfiguration for tests.

**Comment by supimpa** [comment]
@pawelduszczak any solution? I got the same problem here.. Running on apache server without proxy and using Ubuntu.

**Comment by pawelduszczak** [comment]
@supimpa nope, and still no official soluton as well.

**Comment by erayakartuna** [comment]
I thinks its not a problem.When you want to reach parameters with delete method it uses [codeigniter input_stream]( https://www.codeigniter.com/user_guide/libraries/input.html#using-the-php-input-stream) method.But you are sending id parameter with url.So you can reach it only get method.If you want to reach that with delete method your url should be "api/example/users/" and you send to param with application/x-www-form-urlencoded.

I wrote an example to show differences between get parameter and application/x-www-form-urlencoded parameter. https://gist.github.com/erayakartuna/8cd859ab815ab293b21fa6bdc6d0027a

**Comment by pawelduszczak** [comment]
Yeah, it's not a big deal but also it doesn't work as expected in my opinion. Lack of any explenation or solution also is not a good sign. Chaging headers for delete method do not seems to be the right way. I expected to reach all variables by using method for specific action and that is just not the case here and exaclty this is the issue.

**Comment by barayuda** [comment]
@pawelduszczak agreed with you, tested without proxy, and appeared same error message

**Comment by nicolaib** [comment]
I don't see that there is a problem here: The documentation states
"The HTTP spec for DELETE requests precludes the use of parameters. For delete requests, you can add items to the URL

```
public function index_delete($id)
{
    $this->response([
        'returned from delete:' => $id,
    ]);
}
```
If query parameters are passed via the URL, regardless of whether it's a GET request, can be obtained by the query method:

`$this->query('blah'); // Query param`

So the implementation follows the HTTP spec and has it described in the documentation.

**Comment by chriskacerguis** [comment]
Basically what @nicolaib said (and thanks for helping out @nicolaib, I really appreciate it).
