### ISSUE TITLE
Conflict when using together with Rest-Client library

### ISSUE THREAD

**Issue by luoihoc** [chriskacerguis/codeigniter-restserver#69]
I installed rest-client library using sparks command line. When i try to load the rest-client library in a Rest Controller, i have the following error

```
PHP Fatal error:  Cannot access protected property Example::$rest in /home/tran/public_html/peacemoon/system/core/Loader.php on line 1095
```

This is the code in my Rest Controller

```
public function test_get() {
    $this->load->spark('restclient/2.0.0');

    // Load the library
    $this->load->library('rest');

    $this->response('hello', 200);
}
```

**Comment by ngplus** [comment]
hey, the final fixed is still not pulled to the latest Rest Server library ?

**Comment by ivantcholakov** [comment]
REST_Controller is to be extended, I prefer its properties to be protected, not private.

**Comment by softwarespot** [comment]
Agreed

**Comment by ngplus** [comment]
then what should be the correct approach if we want to use the same class as a Rest server and Client together ?

**Comment by softwarespot** [comment]
That isn't maintained by us is it?

**Comment by ivantcholakov** [comment]
First thoughts:
1. The REST library to be "adopted" by this project. :-)
2. It to be renamed as Rest_client.
3. A test showing them working simultaneously to be prepared.

**Comment by ivantcholakov** [comment]
Meanwhile...
$this->load->library('rest', $config, 'rest_client');

**Comment by softwarespot** [comment]
I will confess I have never used Rest_client nor probably will I ever. But I am game if everyone else is =)

**Comment by ivantcholakov** [comment]
In my demo with the Rest Client library I did not extent the controller class from REST_Controller, but at least the following commit show how can the name conflict be resolved:
https://github.com/ivantcholakov/starter-public-edition-3/commit/0030a94d3c20e853c3baf823312eee9ae4db9389

**Comment by ivantcholakov** [comment]
Also, the REST client library should be renamed, because the configuration file is named as rest.php. This is a second name conflict.

With a renamed client library, if we want to define some configuration options, its configuration file will be named as rest_client.php.

**Comment by ivantcholakov** [comment]
@chriskacerguis

What do you think about putting the REST client library an the Curl library in this project? I can make the initial commits and put some tests. Then (@softwarespot) conversion to PHP 5.4 follows and some polishing.

**Comment by softwarespot** [comment]
If I have time =)

**Comment by ivantcholakov** [comment]
No problem, I can cover the whole thing.

**Comment by ivantcholakov** [comment]
http://forum.codeigniter.com/thread-62631-post-321417.html
