### ISSUE TITLE
REST limits

### ISSUE THREAD

**Issue by garenk02** [chriskacerguis/codeigniter-restserver#690]
How to configure & test the limits api-key function?
I already set up all the tables, but when I test to call the API using the loop that more than limits it's still working, not limited.

Hopefully can get fast respond.

Many thank's

Best regards

**Comment by Deku** [comment]
I would recommend reading about "scopes" in OAuth 2.0, or simply use OAuth in your project

**Comment by gotphp** [comment]
See: https://github.com/chriskacerguis/codeigniter-restserver/issues/672
