### ISSUE TITLE
Rest Server post method response null 

### ISSUE THREAD

**Issue by jaleelpoonath** [chriskacerguis/codeigniter-restserver#691]
Hi,
I'm learning to build rest api and now i got stuck here.Kindly help me to solve it. Thanks in advance

Using POSTMAN  JSON(application/json) it works fine.

My rest client code :
public function update_degree($id,$status){

       if (!$this->session->userdata('admin_logged_in')) {

            redirect('', 'refresh');

        }else{

            $this->rest->format('application/json');

            $params =array(
                'id' => $id,
                'status'   => $status,
                'where' => "Degree_Id = $id",
                );
            //print_r($params);
            $data['result'] = $this->rest->post('admin/index.php/api/update_record', $params);

            $this->rest->debug();
  
        }

    } 

And rest server

 public function update_record_post($params=array()){
        var_dump($params);
        $data = array(
            'status' => $this->post('status'),
            'id' => $this->post('id'),
            'where' => $this->post('where'),
            );
       /* $status = $this->input->post('status');
        $id = $this->input->post('id');
        $where = $this->input->post('where');*/

       // $this->action_model->update_record('degreelist',$id,$status,$where);

        //$message = [ 'message' => 'Updated Status'];

        $this->set_response($data, REST_Controller::HTTP_CREATED);
       
     }
  
}

RESPONSE ;
array(0) {
}
{"status":null,"id":null,"where":null}

I tried with put method too, but not worked.

**Comment by chriskacerguis** [comment]
I'm really sorry, but I'm unable to assist with personal projects.  I can only help with bugs and issues with the library itself.
