### ISSUE TITLE
POST request not working

### ISSUE THREAD

**Issue by lunkadbhushan** [chriskacerguis/codeigniter-restserver#693]
Hi,
When I am using GET request, it's working fine. But when I am using POST request, I am getting an below error:
{
"status": false,
"error": "Unknown method"
}

**Comment by bobbysiagian** [comment]
Hi,

Have you check your method before?
pls use POST method from your postman or other apps.

**Comment by lunkadbhushan** [comment]
Yes, I have checked it. And it is POST method.

**Comment by lunkadbhushan** [comment]
I have face this issue on server. If I am on localhost, it is working fine for me but when I am deploying the code on server, I am facing the issue. Please let me know how can I get rid of this issue.

Thanks!
