### ISSUE TITLE
database error while trying to enable key

### ISSUE THREAD

**Issue by lokenthapa** [chriskacerguis/codeigniter-restserver#694]
I have setup keys table in my database 
CREATE TABLE `keys` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
       `user_id` INT(11) NOT NULL,
       `key` VARCHAR(40) NOT NULL,
      `level` INT(2) NOT NULL,
       `ignore_limits` TINYINT(1) NOT NULL DEFAULT '0',
       `is_private_key` TINYINT(1)  NOT NULL DEFAULT '0',
       `ip_addresses` TEXT NULL DEFAULT NULL,
       `date_created` INT(11) NOT NULL,
      PRIMARY KEY (`id`)
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
and make this TRUE
**$config['rest_enable_keys'] = TRUE;**
while setup key in postman for result, showing following error .please help me to fix this
<h1>A Database Error Occurred</h1>
            <p>Error Number: 1146</p>
            <p>Table 'testapi.api_keys' doesn't exist</p>
            <p>SELECT api_key_activated FROM api_keys WHERE api_key = '123456' </p>
            <p>Filename: E:/xampp/htdocs/apitest/system/database/DB_driver.php</p>
            <p>Line Number: 691</p>

**Comment by teabrg** [comment]
You have to do this:

CREATE TABLE api_keys (
id INT(11) NOT NULL AUTO_INCREMENT,
user_id INT(11) NOT NULL,
key VARCHAR(40) NOT NULL,
level INT(2) NOT NULL,
ignore_limits TINYINT(1) NOT NULL DEFAULT '0',
is_private_key TINYINT(1) NOT NULL DEFAULT '0',
ip_addresses TEXT NULL DEFAULT NULL,
date_created INT(11) NOT NULL,
PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

Recreate the table with the code above and recreate a key

**Comment by ndstyle** [comment]
Hi.

I changed the table name, but I get this error:

```
<p>Error Number: 1054</p>
<p>Unknown column 'api_key_activated' in 'field list'</p>
<p>SELECT api_key_activated FROM api_keys WHERE api_key = '123456' </p>
<p>Filename: libraries/REST_Controller.php</p>
<p>Line Number: 1006</p>
```

How can I fix this error?

Kind Regards
Danilo

**Comment by unlangchan** [comment]
your config  and table are inconsistent
```php
/* -------------controller--------*/
private function _get_key($key)
{       
	return $this->db
		->where(config_item('rest_key_column'), $key)
		->get(config_item('rest_keys_table'))
		->row();
}
/*----------config-------------*/
|--------------------------------------------------------------------------
| REST Enable Keys
|--------------------------------------------------------------------------
|
| When set to TRUE, the REST API will look for a column name called 'key'.
| If no key is provided, the request will result in an error. To override the
| column name see 'rest_key_column'
|
| Default table schema:
|   CREATE TABLE `keys` (
|       `id` INT(11) NOT NULL AUTO_INCREMENT,
|       `user_id` INT(11) NOT NULL,
|       `key` VARCHAR(40) NOT NULL,
|       `level` INT(2) NOT NULL,
|       `ignore_limits` TINYINT(1) NOT NULL DEFAULT '0',
|       `is_private_key` TINYINT(1)  NOT NULL DEFAULT '0',
|       `ip_addresses` TEXT NULL DEFAULT NULL,
|       `date_created` INT(11) NOT NULL,
|       PRIMARY KEY (`id`)
|   ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
|
*/
```

**Comment by ndstyle** [comment]
Hi @unlangchan 

Thanks for reply.

Here my config file:

```
/*
|--------------------------------------------------------------------------
| REST API Keys Table Name
|--------------------------------------------------------------------------
|
| The table name in your database that stores API keys
|
*/
$config['rest_keys_table'] = 'api_keys';

/*
|--------------------------------------------------------------------------
| REST Enable Keys
|--------------------------------------------------------------------------
|
| When set to TRUE, the REST API will look for a column name called 'key'.
| If no key is provided, the request will result in an error. To override the
| column name see 'rest_key_column'
|
| Default table schema:
|   CREATE TABLE `keys` (
|       `id` INT(11) NOT NULL AUTO_INCREMENT,
|       `user_id` INT(11) NOT NULL,
|       `key` VARCHAR(40) NOT NULL,
|       `level` INT(2) NOT NULL,
|       `ignore_limits` TINYINT(1) NOT NULL DEFAULT '0',
|       `is_private_key` TINYINT(1)  NOT NULL DEFAULT '0',
|       `ip_addresses` TEXT NULL DEFAULT NULL,
|       `date_created` INT(11) NOT NULL,
|       PRIMARY KEY (`id`)
|   ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
|
*/
$config['rest_enable_keys'] = TRUE;

/*
|--------------------------------------------------------------------------
| REST Table Key Column Name
|--------------------------------------------------------------------------
|
| If not using the default table schema in 'rest_enable_keys', specify the
| column name to match e.g. my_key
|
*/
$config['rest_key_column'] = 'key';
```

**Comment by teabrg** [comment]
Add this field "api_key_activated" as ENUM in your table structure with values 0,1

I should suggest to seriously read SQL Queries and debugging.

**Comment by ndstyle** [comment]
Hi @teabrg 

Thanks for reply.

I deleted everything and reconfigured codeigniter.

I loaded the library.

I created the table in the database by following the instructions.

```
CREATE TABLE `keys` (
      `id` INT(11) NOT NULL AUTO_INCREMENT,
      `user_id` INT(11) NOT NULL,
      `key` VARCHAR(40) NOT NULL,
       `level` INT(2) NOT NULL,
       `ignore_limits` TINYINT(1) NOT NULL DEFAULT '0',
      `is_private_key` TINYINT(1)  NOT NULL DEFAULT '0',
       `ip_addresses` TEXT NULL DEFAULT NULL,
     `date_created` INT(11) NOT NULL,
       PRIMARY KEY (`id`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

I activated the keys and created a new key.

Here my config file:

```
/*
|--------------------------------------------------------------------------
| REST API Keys Table Name
|--------------------------------------------------------------------------
|
| The table name in your database that stores API keys
|
*/
$config['rest_keys_table'] = 'keys';

/*
|--------------------------------------------------------------------------
| REST Enable Keys
|--------------------------------------------------------------------------
|
| When set to TRUE, the REST API will look for a column name called 'key'.
| If no key is provided, the request will result in an error. To override the
| column name see 'rest_key_column'
|
| Default table schema:
|   CREATE TABLE `keys` (
|       `id` INT(11) NOT NULL AUTO_INCREMENT,
|       `user_id` INT(11) NOT NULL,
|       `key` VARCHAR(40) NOT NULL,
|       `level` INT(2) NOT NULL,
|       `ignore_limits` TINYINT(1) NOT NULL DEFAULT '0',
|       `is_private_key` TINYINT(1)  NOT NULL DEFAULT '0',
|       `ip_addresses` TEXT NULL DEFAULT NULL,
|       `date_created` INT(11) NOT NULL,
|       PRIMARY KEY (`id`)
|   ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
|
*/
$config['rest_enable_keys'] = TRUE;

/*
|--------------------------------------------------------------------------
| REST Table Key Column Name
|--------------------------------------------------------------------------
|
| If not using the default table schema in 'rest_enable_keys', specify the
| column name to match e.g. my_key
|
*/
$config['rest_key_column'] = 'key';
```
When I try with postman is the result: 

```
<h1>A Database Error Occurred</h1>
<p>Error Number: 1146</p>
<p>Table 'myapi.api_keys' doesn't exist</p>
 <p>SELECT api_key_activated FROM api_keys WHERE api_key = '123456' </p>
<p>Filename: libraries/REST_Controller.php</p>
<p>Line Number: 1006</p>
```

I edit the table name with 'api_keys' and i try again with postman. 

```
<h1>A Database Error Occurred</h1>
 <p>Error Number: 1054</p>
<p>Unknown column 'api_key_activated' in 'field list'</p>
<p>SELECT api_key_activated FROM api_keys WHERE api_key = '123456' </p>
<p>Filename: libraries/REST_Controller.php</p>
<p>Line Number: 1006</p>
```

I add this field 'api_key_activated' as ENUM with values 0,1 and i try again with postman. 

```
<h1>A Database Error Occurred</h1>
<p>Error Number: 1054</p>
<p>Unknown column 'api_key' in 'where clause'</p>
<p>SELECT api_key_activated FROM api_keys WHERE api_key = '123456' </p>
<p>Filename: libraries/REST_Controller.php</p>
<p>Line Number: 1006</p>
```

I change field 'key' with 'api_key':

```
<h1>A Database Error Occurred</h1>
            <p>Error Number: 1146</p>
            <p>Table 'myapi.activated' doesn't exist</p>
            <p>SELECT *
FROM `activated`
WHERE `key` = '123456'</p>
            <p>Filename: libraries/REST_Controller.php</p>
            <p>Line Number: 1009</p>
```

Any suggest?

**Comment by teabrg** [comment]
Ok here is a working implementation. There is nothing wrong with your code its just that you miss some configurations. It is very easy to implement. Follow my steps.

`Step 1:`

Drop the table in your database and create again the table like this:

```
CREATE TABLE `keys` (
  `id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `api_key` varchar(255) NOT NULL,
  `level` int(2) NOT NULL,
  `ignore_limits` tinyint(1) NOT NULL DEFAULT '0',
  `is_private_key` tinyint(1) NOT NULL DEFAULT '0',
  `ip_addresses` text,
  `date_created` int(11) NOT NULL,
  `api_key_activated` enum('yes','no') NOT NULL DEFAULT 'no'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `keys` (`id`, `user_id`, `api_key`, `level`, `ignore_limits`, `is_private_key`, `ip_addresses`, `date_created`, `api_key_activated`) VALUES
(1, 1, '1234', 10, 0, 0, NULL, 0, 'no'), (1, 1, '12345', 10, 0, 0, NULL, 0, 'yes')
```

**Step 2:**

Change the rest.php file like this:

$config['rest_keys_table'] = 'keys';
$config['rest_key_column'] = 'api_key';

**Step 3:**

Keep only these lines in your REST_Controller.php

```
$existsactive = $this->db->query("SELECT api_key_activated FROM keys WHERE api_key = '".$key."' ");

$isactive = $existsactive->result();
            if ( ! ($row = $this->rest->db->where($this->config->item('rest_key_column'), $key)->get($this->config->item('rest_keys_table'))->row() ) || $isactive[0]->api_key_activated == 'no' )
            {
                return FALSE;
            }
```

Step 4:

Try to make a request with API KEy = 1234 and another with API Key = 12345.

Hope it helps!!!

**Comment by unlangchan** [comment]
look the Notes ； it tell you Proper operation；
if you set "$config['rest_enable_keys'] = TRUE;"
you must rewrite config for all column；

```php
/*
|--------------------------------------------------------------------------
| REST Enable Keys
|--------------------------------------------------------------------------
|
| When set to TRUE, the REST API will look for a column name called 'key'.
| If no key is provided, the request will result in an error. To override the
| column name see 'rest_key_column'
|
| Default table schema:
|   CREATE TABLE `keys` (
|       `id` INT(11) NOT NULL AUTO_INCREMENT,
|       `user_id` INT(11) NOT NULL,
|       `key` VARCHAR(40) NOT NULL,
|       `level` INT(2) NOT NULL,
|       `ignore_limits` TINYINT(1) NOT NULL DEFAULT '0',
|       `is_private_key` TINYINT(1)  NOT NULL DEFAULT '0',
|       `ip_addresses` TEXT NULL DEFAULT NULL,
|       `date_created` INT(11) NOT NULL,
|       PRIMARY KEY (`id`)
|   ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
|
*/
$config['rest_enable_keys'] = TRUE;
```

**Comment by ndstyle** [comment]
Hi @teabrg 

Thanks for your help.

I made the changes as you wrote to me but now I get this error:

```
<h1>A Database Error Occurred</h1>
            <p>Error Number: 1064</p>
            <p>You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'keys WHERE api_key = '1234'' at line 1</p>
            <p>SELECT api_key_activated FROM keys WHERE api_key = '1234' </p>
            <p>Filename: libraries/REST_Controller.php</p>
            <p>Line Number: 1006</p>
```

**Comment by ndstyle** [comment]
Hi @teabrg.

I found an error: The table can not call keys! I change the name with 'rest_keys'. Now response with both keys  is:

```
{
  "status": false,
  "error": "Invalid API key "
}
```

I still debugging

**Comment by lokenthapa** [comment]
you need to fix this line <p>SELECT **api_key_activated** FROM keys WHERE api_key = '1234' </p>
to       
<p>SELECT api_key FROM keys WHERE api_key = '1234' </p>
this will fix your error...

**Comment by ndstyle** [comment]
Hi @lokenthapa 

I had already fixed the bug. In my case the table can not call '**keys**'! I change the name with '**rest_keys**'. Now the query is executed, but I always get this error with both keys is:

```
{
  "status": false,
  "error": "Invalid API key "
}
```

**Comment by shyambabu2109** [comment]
Comment the line from REST_Controller.php
            //$existsactive = $this->db->query("SELECT api_key_activated FROM api_keys WHERE api_key = '".$key."' ");
            // Using the Query builder method. This will only work if you have a column named activated in the api_key table.
            //If you also want to add this as a config item replace the get('activated') with $this->config->item('rest_key_activated_column').
            //$existsactive = $this->rest->db->where($this->config->item('rest_key_column'), $key)->get('activated')->result();
            //$isactive = $existsactive->result();

**Comment by lokenthapa** [comment]
fix the X-API-KEY value correctly
![capture](https://cloud.githubusercontent.com/assets/11645169/18348998/7c3b25ea-75ee-11e6-8f22-dce5d5da341f.PNG)

**Comment by ndstyle** [comment]
Hi @shyambabu2109.

I commented on the lines that you have indicated to me but still I get the same result with both keys.

Code for '**_detect_api_key**'

```
protected function _detect_api_key()
    {
        // Get the api key name variable set in the rest config file
        $api_key_variable = $this->config->item('rest_key_name');

        // Work out the name of the SERVER entry based on config
        $key_name = 'HTTP_' . strtoupper(str_replace('-', '_', $api_key_variable));

        $this->rest->key = NULL;
        $this->rest->level = NULL;
        $this->rest->user_id = NULL;
        $this->rest->ignore_limits = FALSE;

        // Find the key from server or arguments
        if (($key = isset($this->_args[$api_key_variable]) ? $this->_args[$api_key_variable] : $this->input->server($key_name)))
        {
            //if you have a field to check if the API KEY provided by the user is activated or not 
            //(in case you quickly want to deactivate specific users)
            // you can also perform an extra check for this
            
            //$existsactive = $this->db->query("SELECT * FROM ".$this->config->item('rest_keys_table')." WHERE '".$this->config->item('rest_key_column')."' = '".$key."' ");

            //$existsactive = $this->db->query("SELECT * FROM keys");
            
            // Using the Query builder method. This will only work if you have a column named activated in the api_key table.
            //If you also want to add this as a config item replace the get('activated') with $this->config->item('rest_key_activated_column').
            //$existsactive = $this->rest->db->where($this->config->item('rest_key_column'), $key)->get('activated')->result();
            //$isactive = $existsactive->result();
            
            if ( ! ($row = $this->rest->db->where($this->config->item('rest_key_column'), $key)->get($this->config->item('rest_keys_table'))->row() ) || $isactive[0]->api_key_activated == 'no')
            {
                return FALSE;
            }
            

            //$this->rest->key = $row->{$this->config->item('rest_key_column')};
            //
            //isset($row->user_id) && $this->rest->user_id = $row->user_id;
            //isset($row->level) && $this->rest->level = $row->level;
            //isset($row->ignore_limits) && $this->rest->ignore_limits = $row->ignore_limits;
            //
            //$this->_apiuser = $row;
            //
            ///*
            // * If "is private key" is enabled, compare the ip address with the list
            // * of valid ip addresses stored in the database
            // */
            //if (empty($row->is_private_key) === FALSE)
            //{
            //    // Check for a list of valid ip addresses
            //    if (isset($row->ip_addresses))
            //    {
            //        // multiple ip addresses must be separated using a comma, explode and loop
            //        $list_ip_addresses = explode(',', $row->ip_addresses);
            //        $found_address = FALSE;
            //
            //        foreach ($list_ip_addresses as $ip_address)
            //        {
            //            if ($this->input->ip_address() === trim($ip_address))
            //            {
            //                // there is a match, set the the value to TRUE and break out of the loop
            //                $found_address = TRUE;
            //                break;
            //            }
            //        }
            //
            //        return $found_address;
            //    }
            //    else
            //    {
            //        // There should be at least one IP address for this private key
            //        return FALSE;
            //    }
            //}
            //
            //return TRUE;
        }

        // No key has been sent
        return FALSE;
    }
```

**Comment by shyambabu2109** [comment]
Replace the function 

protected function _detect_api_key()
    {
        // Get the api key name variable set in the rest config file
        $api_key_variable = $this->config->item('rest_key_name');

        // Work out the name of the SERVER entry based on config
        $key_name = 'HTTP_' . strtoupper(str_replace('-', '_', $api_key_variable));

        $this->rest->key = NULL;
        $this->rest->level = NULL;
        $this->rest->user_id = NULL;
        $this->rest->ignore_limits = FALSE;

        // Find the key from server or arguments
        if (($key = isset($this->_args[$api_key_variable]) ? $this->_args[$api_key_variable] : $this->input->server($key_name)))
        {
            //if you have a field to check if the API KEY provided by the user is activated or not 
            //(in case you quickly want to deactivate specific users)
            // you can also perform an extra check for this
            
            //$existsactive = $this->db->query("SELECT api_key_activated FROM api_keys WHERE api_key = '".$key."' ");
            // Using the Query builder method. This will only work if you have a column named activated in the api_key table.
            //If you also want to add this as a config item replace the get('activated') with $this->config->item('rest_key_activated_column').
            //$existsactive = $this->rest->db->where($this->config->item('rest_key_column'), $key)->get('activated')->result();
            //$isactive = $existsactive->result();
            if ( ! ($row = $this->rest->db->where($this->config->item('rest_key_column'), $key)->get($this->config->item('rest_keys_table'))->row() ) || $isactive[0]->api_key_activated == 'no' )
            {
                return FALSE;
            }

            $this->rest->key = $row->{$this->config->item('rest_key_column')};

            isset($row->user_id) && $this->rest->user_id = $row->user_id;
            isset($row->level) && $this->rest->level = $row->level;
            isset($row->ignore_limits) && $this->rest->ignore_limits = $row->ignore_limits;

            $this->_apiuser = $row;

            /*
             * If "is private key" is enabled, compare the ip address with the list
             * of valid ip addresses stored in the database
             */
            if (empty($row->is_private_key) === FALSE)
            {
                // Check for a list of valid ip addresses
                if (isset($row->ip_addresses))
                {
                    // multiple ip addresses must be separated using a comma, explode and loop
                    $list_ip_addresses = explode(',', $row->ip_addresses);
                    $found_address = FALSE;

                    foreach ($list_ip_addresses as $ip_address)
                    {
                        if ($this->input->ip_address() === trim($ip_address))
                        {
                            // there is a match, set the the value to TRUE and break out of the loop
                            $found_address = TRUE;
                            break;
                        }
                    }

                    return $found_address;
                }
                else
                {
                    // There should be at least one IP address for this private key
                    return FALSE;
                }
            }

            return TRUE;
        }

        // No key has been sent
        return FALSE;
    }

**Comment by ndstyle** [comment]
Thanks! Now works! Thank you so much for your support @lokenthapa @teabrg @unlangchan @shyambabu2109

**Comment by shyambabu2109** [comment]
If you don't need the code for "is private key"
Just replace the function with the following one

protected function _detect_api_key()
    {
        // Get the api key name variable set in the rest config file
        $api_key_variable = $this->config->item('rest_key_name');
        // Work out the name of the SERVER entry based on config
        $key_name = 'HTTP_' . strtoupper(str_replace('-', '_', $api_key_variable));
        $this->rest->key = NULL;
        $this->rest->level = NULL;
        $this->rest->user_id = NULL;
        $this->rest->ignore_limits = FALSE;

        // Find the key from server or arguments
        if (($key = isset($this->_args[$api_key_variable]) ? $this->_args[$api_key_variable] : $this->input->server($key_name)))
        {
            //if you have a field to check if the API KEY provided by the user is activated or not 
            //(in case you quickly want to deactivate specific users)
            // you can also perform an extra check for this

            //$existsactive = $this->db->query("SELECT * FROM ".$this->config->item('rest_keys_table')." WHERE '".$this->config->item('rest_key_column')."' = '".$key."' ");

            //$existsactive = $this->db->query("SELECT * FROM keys");

            // Using the Query builder method. This will only work if you have a column named activated in the api_key table.
            //If you also want to add this as a config item replace the get('activated') with $this->config->item('rest_key_activated_column').
            //$existsactive = $this->rest->db->where($this->config->item('rest_key_column'), $key)->get('activated')->result();
            //$isactive = $existsactive->result();

            if ( ! ($row = $this->rest->db->where($this->config->item('rest_key_column'), $key)->get($this->config->item('rest_keys_table'))->row() ) || $isactive[0]->api_key_activated == 'no')
            {
                return FALSE;
            }
   $this->rest->key = $row->{$this->config->item('rest_key_column')};

        isset($row->user_id) && $this->rest->user_id = $row->user_id;
        isset($row->level) && $this->rest->level = $row->level;
        isset($row->ignore_limits) && $this->rest->ignore_limits = $row->ignore_limits;

        $this->_apiuser = $row;

          return TRUE;
  }
    // No key has been sent
    return FALSE;
}

**Comment by seedups-gavin** [comment]
I ran into the same issues as @ndstyle on a fresh install today.

The last commit on the REST_Controller library seems a little strange. It adds hard-coded table and column names that aren't referenced from the config file and don't match the default table schemas from config.

It's a little bizarre to have to dig in and make customizations to the library to get it working instead of just using the config file.

**Comment by ndstyle** [comment]
@seedups-gavin You're right!

**Comment by chriskacerguis** [comment]
@seedups-gavin where are you seeing the hard coded things?

**Comment by teabrg** [comment]
Yes well i believe i left commenting when i was doing a pull request on this. It is just a simple addition of a column to the table with ENUM (yes, no) and it works as before. why do we have to make the things so complicated. I also left commenting how to do this as a config item...

**Comment by seedups-gavin** [comment]
@chriskacerguis Line 1006 of REST_Controller library, then line 1009 references a table that doesn't exist ("activated")

**Comment by chriskacerguis** [comment]
@seedups-gavin ok, yep I see what's going on.  I've removed that code entirely.

**Comment by jonathanforsythe** [comment]
Thanks for the fix @chriskacerguis ! I was just battling this issue yesterday and everything is working fine now. 👍🏼

**Comment by renuka-makaju** [comment]
i have same problem  invalid api keys
