### ISSUE TITLE
NO LOGIN

### ISSUE THREAD

**Issue by vishok** [chriskacerguis/codeigniter-restserver#704]
With this settings in my rest.php
$config['rest_auth'] = 'digest'; (but is the same for basic)
$config['rest_valid_logins'] = ['admin' => '1234'];

i cannot login. Is there some modification have i to do in htaccess?

**Comment by chriskacerguis** [comment]
Can you please provide more info?  Code, error logs, server info, etc.

**Comment by vishok** [comment]
Hi Chris 
thanks for your reply

Sure i can give you more information

- attached to this mail my config/rest.php
- the url that reject my request http://tecnelab.org/_hotel/api/v1/clienti (as you can see when i try to login with admin and password 1234 i will redirect to same page)
- http://tecnelab.org/_hotel/info.php (here the server info)

Thanks 

Sound be a problem with .htaccess?

**Comment by chriskacerguis** [comment]
Hello @vishok 

Your attachments didn't come though (they don't come though with email).  You would need to cut and paste your code.  Without seeing your code, I could not tell you the problem.
