### ISSUE TITLE
 500: Internal Server Error

### ISSUE THREAD

**Issue by satanand7** [chriskacerguis/codeigniter-restserver#705]
![git](https://cloud.githubusercontent.com/assets/22170723/18471814/4377e630-79d1-11e6-896c-20839a1676dd.jpg)
When i call the api it get internal server error with no responce.
I have copied all file from library and all folder you have given with same location. but this is not working for me. Please give me the solution. Thank you.

**Comment by chriskacerguis** [comment]
500 error would be coming from Apache (or whatever web server you are using).  What is in your error logs?

**Comment by chriskacerguis** [comment]
no reply.

**Comment by teabrg** [comment]
Could you please share the code of your controller with the method users? It looks like a big url
