### ISSUE TITLE
Returning numbers as strings

### ISSUE THREAD

**Issue by davecoffin** [chriskacerguis/codeigniter-restserver#708]
The $this->response method appears to be parsing the data and assigning the types based on what it thinks the type is. This is creating a problem with zipcodes. For example, if a zipcode is stored as "03820", the API response returns 3820. Is there a way to force the response to be a string?

**Comment by chriskacerguis** [comment]
are you using the latest version?  For a bit, we had JSON_NUMERIC_CHECK enabled, but it is off in the latest version (you can also, just removed that from your copy...just search for it, it's not needed)

**Comment by davecoffin** [comment]
Great thanks. I am using v 3.0.0. Could you confirm that this is the correct change?

Change this in the to_json function in Format.php:

if (empty($callback) === TRUE)
{
    return json_encode($data, JSON_NUMERIC_CHECK);
}

// We only honour a jsonp callback which are valid javascript identifiers
elseif (preg_match('/^[a-z_\$][a-z0-9\$_]*(\.[a-z_\$][a-z0-9\$_]*)*$/i', $callback))
{
    // Return the data as encoded json with a callback
    return $callback.'('.json_encode($data, JSON_NUMERIC_CHECK).');';
}

to this:

if (empty($callback) === TRUE)
{
    return json_encode($data);
}

// We only honour a jsonp callback which are valid javascript identifiers
elseif (preg_match('/^[a-z_\$][a-z0-9\$_]*(\.[a-z_\$][a-z0-9\$_]*)*$/i', $callback))
{
    // Return the data as encoded json with a callback
    return $callback.'('.json_encode($data).');';
}

Thanks!
