### ISSUE TITLE
POST Requests return a 403 error ('The action you have requested is not allowed')

### ISSUE THREAD

**Issue by holymp2006** [chriskacerguis/codeigniter-restserver#709]
hi,
with `'csrf_protection'` turned on in config, POST requests return a 403.

I'm currently excluding my POST method url in `$config['csrf_exclude_uris'] = array('api/register');`, to get my POST requests to work.

Can there be a more elegant solution to this? As my current solution poses me some security issues.

(I intend to use this with a mobile app).

**Comment by chriskacerguis** [comment]
I'm not following when you say "Can there be a more elegant solution to this?"

**Comment by chriskacerguis** [comment]
The option "$config['csrf_exclude_uris']" seems to indicate that you are using the Security class (in CI), and it's not working as expected, I would suggest you log an issue with them.

https://github.com/bcit-ci/CodeIgniter

or look in the forums

http://forum.codeigniter.com
