### ISSUE TITLE
Limit Request by IP

### ISSUE THREAD

**Issue by bobbysiagian** [chriskacerguis/codeigniter-restserver#710]
Hi Chris,

If we already have limit by request per user/key , how can i limit request by IP ?

Thanks,

**Comment by chriskacerguis** [comment]
Hello @bobbysiagian,

At present, there is no way, but that's a great idea and I'll add it to the todo list.

**Comment by chriskacerguis** [comment]
This has been added in via https://github.com/chriskacerguis/codeigniter-restserver/pull/711

**Comment by bobbysiagian** [comment]
Ok, thanks :+1:
