### ISSUE TITLE
REST_Controller::response($data, $http_code, $continue) third parameter does nothing

### ISSUE THREAD

**Issue by AndrasZiegenham** [chriskacerguis/codeigniter-restserver#713]
Currently even if $continue is TRUE it doesn't flush the response until the script finishes.

I've found the original commit from 2 years back (https://github.com/chriskacerguis/codeigniter-restserver/pull/307/commits/c5d1b3fd4df7b0bb050637a8424e1cceea524350) and changed my REST_Controller like that and it works.

**Comment by chriskacerguis** [comment]
Can you submit a PR to change it back to what works?
