### ISSUE TITLE
A fix for index methods

### ISSUE THREAD

**Issue by AmitMY** [chriskacerguis/codeigniter-restserver#716]
If I write a method `index_get($param)`, the only way to access is `controller/index` in a `GET` request

I am not sure if this is intended, or just because I use HMVC (like I guess most user do).

Here is a quick fix for that:
In `_remap`:
After:
`$controller_method = $object_called . '_' . $this->request->method;`
Add

```
 if (!method_exists($this, $controller_method)) {
    $controller_method = "index_" . $this->request->method;
    array_unshift($arguments, $object_called);
}
```

This does not remove the option to access `controller/index/:param`
But allows the normal access way of `controller/:param`

---

Also, when we `call_user_func_array`, there should be a `try:catch`
Something like:

```
try {
    call_user_func_array([$this, $controller_method], $arguments);
} catch (Exception $ex) {
    $this->response_ex($ex);
}
```

Sorry if my explanation is bad. If so, I'll try to explain again

I can't create a pull request in this time, hope you'll add it

**Comment by chriskacerguis** [comment]
I'm not sure I understand what you are saying with the first part.

regarding the call_user_func_array part, sounds reasonable, I'll add it at some point.

**Comment by AmitMY** [comment]
Codeigniter natively supports a method called "index", to which you can access just by stating the controller's name, and not function.
You have index_method (index_get, index_post, index_put), but you have to access using `controller/index`. The first suggestion solves it

**Comment by AmitMY** [comment]
Added in pull request:
https://github.com/chriskacerguis/codeigniter-restserver/pull/726

**Comment by Dekadencee** [comment]
Tested and working, thanks @AmitMY

**Comment by AmitMY** [comment]
Thanks for the merge. 
Closed
