### ISSUE TITLE
PUT error

### ISSUE THREAD

**Issue by vinceurag** [chriskacerguis/codeigniter-restserver#717]
I get this error whenever I try to pass a JSON request body.

`<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">
    <h4>A PHP Error was encountered</h4>
    <p>Severity: Warning</p>
    <p>Message:  array_merge(): Argument #5 is not an array</p>
    <p>Filename: libraries/REST_Controller.php</p>
    <p>Line Number: 501</p>
    <p>Backtrace:</p>
    <p style="margin-left:10px">
			File: /hermes/bosnaweb08a/b1203/ipg.uragbros/urag-co/bci_api/application/libraries/REST_Controller.php
        <br />
			Line: 501
        <br />
			Function: array_merge
    </p>
    <p style="margin-left:10px">
			File: /hermes/bosnaweb08a/b1203/ipg.uragbros/urag-co/bci_api/application/controllers/api/Users.php
        <br />
			Line: 24
        <br />
			Function: __construct
    </p>
    <p style="margin-left:10px">
			File: /hermes/bosnaweb08a/b1203/ipg.uragbros/urag-co/bci_api/index.php
        <br />
			Line: 315
        <br />
			Function: require_once
    </p>
</div>`

Please help. Thanks!

**Comment by chriskacerguis** [comment]
I'm sorry, you haven't given me enough info to help (code samples, input data, etc).
