### ISSUE TITLE
How can I use multiple database?

### ISSUE THREAD

**Issue by vpdeva** [chriskacerguis/codeigniter-restserver#724]

**Comment by bobbysiagian** [comment]
Please make sure you have description before issus something,

You can use usual method in CI, looks like 

$db['default']['hostname'] = "192.168.2.104";
etc...

use $this-db->query('your query');

$db2['default']['hostname'] = "192.168.2.105";
etc...
use $this-db2->query('your query');

**Comment by vpdeva** [comment]
Hi,

Sorry for the late reply. I tried to connect it with mongo and its working fine. 
Now I want to save the response in Mysql but the problem is the rest_controller library is already writing the logs to mysql. I cannot connect another mysql database/table. Do you have any solution for this?

**Comment by bobbysiagian** [comment]
I think, currently this framework only save request logs in DB, not response.

So you need to modify your controller, create new func insert logs in controller,
looks like : $this->db>query('insert sql script for logs');
