### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by faiakak** [chriskacerguis/codeigniter-restserver#725]
What will be the best Client side caching or should i also cache rest queries on rest server side ? please guide ?

**Comment by AmitMY** [comment]
Can't answer on client-side caching, google can probably help on that.

### Using CI, you have several options.
- `db->cache_on()` will cache select queries, so you won't overload your DB
- `$this->output->cache(10)` is a codeigniter method that can cache a method's response for an amount of minutes

**Comment by erayakartuna** [comment]
You should read documentation.You can choose a way to caching rest queries. https://www.codeigniter.com/userguide3/libraries/caching.html
