### ISSUE TITLE
response() is called before _log_request() in _remap() when force_https and rest_enable_logging

### ISSUE THREAD

**Issue by aTanCS** [chriskacerguis/codeigniter-restserver#728]
Hi, 
if force_https and rest_enable_logging are true and request is not https, response() is called in _remap() a the beginning. Response() logs a response code with _log_response_code(), but _log_request() was not called in _remap() so _insert_id is empty. I guess _insert_id should be at least checked before using it.

**Comment by chernglin** [comment]
I was having problems that the response output was overwritten by one another. 

Then I found this:
https://github.com/AndrasZiegenham/codeigniter-restserver/commit/b169903f1406589e5af329b320ee1c18f0899337

This fork have extra param to handle the case that prevent out from overwritten by the one that is called later....

**Comment by chriskacerguis** [comment]
See here https://github.com/chriskacerguis/codeigniter-restserver/issues/790

Closing this, please reopen if you are still having the issues.
