### ISSUE TITLE
Request: Would you consider implementing something like this?

### ISSUE THREAD

**Issue by blaasvaer** [chriskacerguis/codeigniter-restserver#729]
http://coreymaynard.com/blog/creating-a-restful-api-with-php/

So that we can create a single Controller for a complete API, instead of having it scattered around multiple controllers?

**Comment by zhgabor** [comment]
isn't it like that already? have u checked the example?

**Comment by blaasvaer** [comment]
Yes, and that's part of why I thought it was per controller. I see examples online like:

class Books extends REST_Controller ...

And in the example I only see users_get, users_post, users_delete ...

And that made me think that it was just for users ... that was, until I actually tested it, as I thought it to be madness if that was the case. And it turned out I can do users_get, pages_get yadayada.

Great. But documentation could be clearer, though.

If it CAN be misunderstood, it WILL be misunderstood. Kind a like Murphy's Law for code ... : )
