### ISSUE TITLE
Problem with "simple" POST error uknown method

### ISSUE THREAD

**Issue by cheloo24** [chriskacerguis/codeigniter-restserver#730]
I'm using the library and I don't have much problem implementing GET method but when I tried to test a POST method it show me this (this is running in my localhost):
```
{"status":false,"error":"Unknown method"}
```
This is my controller : 
```php
defined('BASEPATH') OR exit('No direct script access allowed');
require (APPPATH . '/libraries/REST_Controller.php');
class Pacientes extends REST_Controller {
	public function __construct(){
		parent::__construct();
		$this->load->model('paciente');
	}
	function test_post($number){
		$data = $this->paciente->add_post($number);
		$this->response($data);
	}
}
```
This is my Model Paciente:

```php
class Paciente extends CI_Model 
	{
		public $aux = 0;
		public function __construct(){
			parent::__construct();
		}
		public function add_post($number){
			$aux= $aux + $number;
			$data = array('status'=> 200,'number'=> $aux);
			return $data;
		}
	}
```

I had the same error when I was implementing GET so I think.. the way I try to acces in URL to add_post() could be the problem.
So this is the URL that I try to acces:
```
http://localhost/ci3/index.php/pacientes/test/number/3/format/json
```
I just want to POST some number and has a response like {status: 200, number:$aux value}

**Comment by coscho** [comment]
post , get , put don’t allow function parameters.
only method id delete($id).

**Comment by wang4142** [comment]
me too! how to use post in restful?

**Comment by wang4142** [comment]
I think your config file, $config['csrf_protection'] = TRUE; modify $config['csrf_protection'] = FALSE; will be ok!

and you can:
`if (isset($_SERVER["REQUEST_URI"]))  {
    if(stripos($_SERVER["REQUEST_URI"],'/api/example') === FALSE) {
        $config['csrf_protection'] = TRUE;
    } else {
        $config['csrf_protection'] = FALSE;
    } 
} else {
    $config['csrf_protection'] = TRUE;
}`

replace  $config['csrf_protection'] = TRUE;

**Comment by rahulonly4u** [comment]
> I think your config file, $config['csrf_protection'] = TRUE; modify $config['csrf_protection'] = FALSE; will be ok!
> 
> and you can:
> 
> ```
> if (isset($_SERVER["REQUEST_URI"]))  {
>     if(stripos($_SERVER["REQUEST_URI"],'/api/example') === FALSE) {
>         $config['csrf_protection'] = TRUE;
>     } else {
>         $config['csrf_protection'] = FALSE;
>     } 
> } else {
>     $config['csrf_protection'] = TRUE;
> }
> ```
> 
> replace $config['csrf_protection'] = TRUE;

OR you can  pass API on "csrf_exclude_urls"  as in CI 3, this feature  available

$config['csrf_protection'] = TRUE;
$config['csrf_token_name'] = 'get_csrf_token_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;
$config['csrf_regenerate'] = TRUE;
--------------$config['csrf_exclude_uris'] = array("api/example");------------
