### ISSUE TITLE
Documentation for Levels

### ISSUE THREAD

**Issue by spreaderman** [chriskacerguis/codeigniter-restserver#731]
Trying to figure out how LEVELS work but cannot see any documentation.  Possible to advise?

**Comment by spreaderman** [comment]
Could someone please document?

**Comment by Tjoosten** [comment]
Feel free to try it

**Comment by spreaderman** [comment]
Why closed?  Did I miss something?

**Comment by awalls** [comment]
+1 for some overview documentation on levels
