### ISSUE TITLE
Can't call a DELETE request via ajax

### ISSUE THREAD

**Issue by kenzaburo** [chriskacerguis/codeigniter-restserver#732]
Hi everyone, 

I'm working on project to build a restful backend base on Codeigniter. 
Unfortunately, I have this issue for days but I don't know how to resolve it. 

I have a Delete api some things like it: 
http://sandbox/lap/index.php/api/users/15
` public function index_delete()
    {
        $id = (int)$this->get('id');
        // Validate the id.
        if ($id <= 0) {
            // Set the response and exit
            $this->response(NULL, REST_Controller::HTTP_BAD_REQUEST); // BAD_REQUEST (400) being the HTTP response code
        }

        $this->load->model("user_model");
        $res = $this->user_model->delete_user_by_id($id);
        if ($res == NON_EXISTED) {
            $message = [
                'status' => FALSE,
                'message' => 'User is not existed'
            ];
            $this->set_response($message, REST_Controller::HTTP_BAD_REQUEST);
        } else if($res == OK) {
            $message = [
                'id' => $id,
                'message' => 'Deleted the user'
            ];

            $this->set_response($message, REST_Controller::HTTP_OK); // NO_CONTENT (204) being the HTTP response code
        }

    }`

In client side, I have an ajax call:
`$.ajax({
            url: BACKEND_URL + api + user.id,
            cache: false,
            type: 'DELETE',
            success: function (result) {
                LOG_2(this.name, fname, result);
                if (result != null) {
                    if (result.hasOwnProperty('status') && result.status == false) {
                        warning(result.message);
                    }
                } else {
                    success("Delete successfully!");
                    this.getUsers();
                }
            }.bind(this),
            error: function (xhr, status, err) {
                this.setState({status: COMP_STATUS.ERROR});
                warning(ERROR_MESSAGE.internal_error);
                console.error(status, err.toString());
            }.bind(this)
        });`

The thing i always got the below error. Even though, I set CORS checking is false in Rest.php configuration.
[![error_delete_request.png](https://s22.postimg.org/uu6gnwsap/error_delete_request.png)](https://postimg.org/image/scupgn8e5/)

**Comment by Jyotie** [comment]
3 things you can do for handling this issue.
1> In ajax call add before success :  crossDomain: true,
2> In your  host file [normally found at : C:\Windows\System32\drivers\etc on windows system] add this:
[your ip]    localhost [remote server path]
ex : 192.168.1.1   localhost http://abcd.com/pcp/
3> add this plugin to chrome browser : 
https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?utm_source=chrome-app-launcher-info-dialog

Hope this will help.
