### ISSUE TITLE
REST_Controller in PHP 5.6.28 authentication failed

### ISSUE THREAD

**Issue by keronconk** [chriskacerguis/codeigniter-restserver#737]
I have used this REST_Controller both in CodeIgniter 2 and 3, and all succeeded, both in localhost and hosting which various version of PHP.

Now, I have problem in 1 hosting which use PHP 5.6.28, the problem is authentication failed, and it shows message not authorized.

Thank you for all help and suggestion

this can answered in stackoverflow.com
http://stackoverflow.com/q/40844403/4772809

**Comment by kazi-shahin** [comment]
I am facing this error:
Fatal error: Class 'Restserver\Libraries\REST_Controller' not found in /var/www/html/rest_interface/application/controllers/Welcome.php on line 5
My controller is:
<?php
use Restserver\Libraries\REST_Controller;
defined('BASEPATH') OR exit('No direct script access allowed');

class Welcome extends REST_Controller {
    public function index()
      {
      $foo = array('fake' => 'data');
          $this->response($foo, REST_Controller::HTTP_OK); // OK (200) being the HTTP response code
      }
}
My OS ubuntu 14.0.4 and LAMP
I am using PHP 7.0.13-1+deb.sury.org~trusty+1 (cli) ( NTS )

I have installed Restfull interface using composer.

**Comment by chriskacerguis** [comment]
@keronconk based on it working locally and not on the hosting server, it sounds like a configuration issue on your hosting provider.  I would compare the Apache confs and php.ini and go from there.

@kazi-shahin please open a new issue.
