### ISSUE TITLE
Parse error: syntax error, unexpected '['

### ISSUE THREAD

**Issue by anggaand123** [chriskacerguis/codeigniter-restserver#738]
Hello
i got this error Parse error: syntax error, unexpected '[' in /var/www/kliksasi.com/application/libraries/REST_Controller.php on line 165

my php version is 5.5.3 is some module required ??
im use ubuntu 12.04
![screenshot from 2016-12-08 12 03 29](https://cloud.githubusercontent.com/assets/13533060/20998182/b9eecbb6-bd3e-11e6-929d-4f6ba3c492f7.png)

**Comment by chriskacerguis** [comment]
the error you posted doesn't indicate a missing lib.  Looks like a syntax issue.
