### ISSUE TITLE
Read Authorization Headers

### ISSUE THREAD

**Issue by geolyth** [chriskacerguis/codeigniter-restserver#740]
Hi,
is there a way to read Authorization Headers?
I need it because for my REST server I provide a custom Authorization Bearer Token...

Thanks in advance,
Fabio

**Comment by nicolaib** [comment]
I implemented a full JWT authentication in this library, and I fetch the header like this:
`$headers = apache_request_headers()['Authorization']`
This function is not supported in all environments. 
There is also a Codeigniter specific implementation of it, which solves that problem but it can only be used inside the controller context:
`$this->input->get_request_header('Authorization');`

If the token is not in the header, then I check if the token is in the URI as it can be sent in a GET request.
