### ISSUE TITLE
Strange GET Results

### ISSUE THREAD

**Issue by estevo-de** [chriskacerguis/codeigniter-restserver#743]
No matter what I do with the file, it shows the same results ie. the one in example.
I've deleted the file and uploaded again and change a number of times but it is not changing. When i change other files in the controllers folder, they changes get reflected. 

Anyone has any idea or has come across this situation?

**Comment by estevo-de** [comment]
Just to add the page seems to show the wrong results when I use the raw URL for example 
mydomain/api/Example/users
mydomain/api/example/users seems to refresh correctly at this time

**Comment by estevo-de** [comment]
Hi all,
in case any one of you guys are using page speed mod (standard settings) then you might encounter this as well. It turned out that page speed was caching the results.
cheers
Ashar

**Comment by AmitMY** [comment]
Glad you found the source of the problem.
So if it isn't relevant anymore, can you please close this issue?
