### ISSUE TITLE
rest_ip_whitelist_enabled is TRUE but my ip still unauthorized

### ISSUE THREAD

**Issue by soundiver** [chriskacerguis/codeigniter-restserver#752]
Hello, I have set the '_rest_ip_whitelist_enabled_' to TRUE and I put my IP address in the '_rest_ip_whitelist_' but if i try to log in the message is { "status": false, "error": "IP unauthorized"}.

I'm sure that the IP is really mine.

If I set the while list to FALSE i can access without problems.

rest_auth is set to 'basic' and I'm working in local...

thank you

**Comment by soundiver** [comment]
...but works on the production server!  This is very good!  

Any suggestion about the local problem?

**Comment by Userlocal2** [comment]
Try to add loggigng of current client ip address in  REST_SERVER::__constructor() in begining, than check ip_whitelist

**Comment by chriskacerguis** [comment]
From what you are saying the issue sounds like a misconfiguration. My guess is that you are not using the correct address.  For example, maybe you put in 127.0.0.1 but it's connecting as ::1 I would suggest you do what @Userlocal2 suggests.
