### ISSUE TITLE
Combine REST with Oauth2

### ISSUE THREAD

**Issue by timyounes** [chriskacerguis/codeigniter-restserver#754]
Hello,

I want to know if it is possible to combine REST with Oauth2 authentication. I am using codeigniter for my API development.

Thanks,
Tim

**Comment by timyounes** [comment]
But can I use Oauth2 for my API authorization?

**Comment by chriskacerguis** [comment]
You can if you set it up that way.

**Comment by timyounes** [comment]
@chriskacerguis In what way I should set up my API REST AND Oauth2?

**Comment by chriskacerguis** [comment]
I'm sorry, I cannot help with that.  You would need to follow the directions in whatever Oauth2 lib you are using.

**Comment by timyounes** [comment]
Thanks @chriskacerguis and @appunnicer13

**Comment by chriskacerguis** [comment]
@timyounes I have had good success with https://oauth2.thephpleague.com FWIW.

**Comment by timyounes** [comment]
Thanks @chriskacerguis .. Did you already try to used https://oauth2.thephpleague.com with REST?

**Comment by chriskacerguis** [comment]
It is not built into this project, but I have integrated it before for work.

**Comment by timyounes** [comment]
Thankk you very much @chriskacerguis  I will try to itegrate it in my project hope that it will success
