### ISSUE TITLE
Method response never terminates script execution

### ISSUE THREAD

**Issue by BlakSneil** [chriskacerguis/codeigniter-restserver#757]
After commit https://github.com/chriskacerguis/codeigniter-restserver/pull/748/commits/c13b5fb1bbd8e8a8a1d53e2a368f7bec4a2549f9, method `response` never terminates script execution.

**Comment by benyaminshoham** [comment]
@chriskacerguis suggests script should not terminate on it's own. I tend to agree. I added validation to _remap and prevented it from calling the endpoint if auth failed. PR is https://github.com/chriskacerguis/codeigniter-restserver/pull/759 . Any feedback is welcome...

**Comment by chriskacerguis** [comment]
See here https://github.com/chriskacerguis/codeigniter-restserver/issues/790

Closing this, please reopen if you are still having the issues.
