### ISSUE TITLE
Fatal error: Class 'Restserver\Libraries\REST_Controller' not found in CodeIgnitor 3.1.2

### ISSUE THREAD

**Issue by ech05** [chriskacerguis/codeigniter-restserver#761]
Went through the documentation still facing the issue,

Fatal error: Class 'Restserver\Libraries\REST_Controller' not found.

in CodeIgnitor 3.1.2.

**Comment by pepegarciag** [comment]
Duplicated of #765

**Comment by chriskacerguis** [comment]
See here https://github.com/chriskacerguis/codeigniter-restserver/issues/790

Closing this, please reopen if you are still having the issues.
