### ISSUE TITLE
Header Keys not working at all

### ISSUE THREAD

**Issue by judemanutd** [chriskacerguis/codeigniter-restserver#764]
I am trying to create my rest api server and i am trying to enable api keys but they problem is that even though i followed the instructions,i am unable to authenticate using any key,ie all request go through even if they don't have the api key header in the request.

This is my current config

rest.php
`$config['rest_keys_table'] = 'keys';`
`$config['rest_enable_keys'] = TRUE;`
`$config['rest_key_column'] = 'api_key';`
`$config['rest_limits_method'] = 'ROUTED_URL';`
`$config['rest_key_name'] = 'X-API-KEY';`

My table was created using the following sql query.

`CREATE TABLE `keys` (
  `id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `api_key` varchar(255) NOT NULL,
  `level` int(2) NOT NULL,
  `ignore_limits` tinyint(1) NOT NULL DEFAULT '0',
  `is_private_key` tinyint(1) NOT NULL DEFAULT '0',
  `ip_addresses` text,
  `date_created` int(11) NOT NULL,
  `api_key_activated` enum('yes','no') NOT NULL DEFAULT 'no'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `keys` (`id`, `user_id`, `api_key`, `level`, `ignore_limits`, `is_private_key`, `ip_addresses`, `date_created`, `api_key_activated`) VALUES
(1, 1, '1234', 10, 0, 0, NULL, 0, 'no'), (1, 1, '12345', 10, 0, 0, NULL, 0, 'yes')`

The problem is that the request goes through no matter what.I have enabled routes in my project,could that be causing a problem?

routes.php
`$route['api/v1/foo/(:any)'] = 'Api_v1/foo/$1';`

Even if the header does not contain an X-API-KEY field,no error is thrown instead the request is completed and data is fetched.

[https://stackoverflow.com/questions/41965609/codeigniter-rest-api-keys-not-working](url)

**Comment by noufalcep** [comment]
I had the similar problem.  I solved the problem using this solution.
https://github.com/chriskacerguis/codeigniter-restserver/issues/753
Solution explained in this question will help you.

**Comment by judemanutd** [comment]
Thank you @noufalcep that did help , it seems like a workaround but is it safe to use in production?

**Comment by mtndewxu** [comment]
Same issue here. That workaround solved it.

**Comment by chriskacerguis** [comment]
See here https://github.com/chriskacerguis/codeigniter-restserver/issues/790

Closing this, please reopen if you are still having the issues.
