### ISSUE TITLE
Class 'REST_Controller' not found

### ISSUE THREAD

**Issue by aanik2007** [chriskacerguis/codeigniter-restserver#765]
Whenever I am extending the class. It is showing Class 'REST_Controller' not found

**Comment by judemanutd** [comment]
`require(APPPATH . 'libraries/REST_Controller.php');
class Db extends \Restserver\Libraries\REST_Controller`

That's how i have done it with my class and it works fine.You need to place the rest_controller in application/libraries

**Comment by fariswidhi** [comment]
only add 
`use Restserver\Libraries\REST_Controller;`

**Comment by mahipal0015** [comment]
Fatal error: Class 'Restserver\Libraries\CI_Controller' not found in D:\Server\htdocs\CodeIgniter\application\libraries\REST_Controller.php on line 18

my REST_Controller class doesn't extend CI_Controller and generate error.

**Comment by farukgaric** [comment]
Hi @mahipal0015 
Just add backslash before CI_Controller.
`abstract class REST_Controller extends \CI_Controller {`

**Comment by ayeen** [comment]
@farukgaric 
after adding \slash An Error Was Encountered
Non-existent class: Rest_controller???

**Comment by BrianDLA** [comment]
I solved this issue.
Only do you have put this two lines in the controller:
use Restserver\Libraries\REST_Controller;
require(APPPATH . 'libraries/REST_Controller.php');

And the file REST_Controller.php, the first line like this:
<?php
namespace Restserver\Libraries;
use CI_Controller;
use Exception;
use stdClass;
require APPPATH . 'libraries/Format.php';

**Comment by utsabshrestha** [comment]
Thanks this worked 👍

**Comment by aasiimweDataCare** [comment]
This worked for me too. Thanks a bunch.

**Comment by SudarmawanAdyS** [comment]
Thanks this worked

**Comment by Ashish123111** [comment]
Thanks BrianDLA 
Its working

**Comment by Ashish123111** [comment]
Solved Completely this 
Error Non-existent class: Format
Thanks BrianDLA
