### ISSUE TITLE
Digest auth always valid

### ISSUE THREAD

**Issue by asystat** [chriskacerguis/codeigniter-restserver#766]
The same as with basic auth...but basic auth was solved with two lines of code 👍 
Is there a workaround this? Could you at lease point out where we should look into?

thanks

**Comment by benyaminshoham** [comment]
There's a bug in REST_Controller, fixed with this PR: https://github.com/chriskacerguis/codeigniter-restserver/pull/759

Until this is merged I created a workaround using a wrapper function for "response" that checks for authorization. I placed it in my base_controller (inherits REST_Controller).

```	# TODO: Remove this solution once the rest-server team will fix the original response method
	public function do_response( $data = null, $http_code = null ) {
		if ( $this->_allow && $this->has_permission ) {
			parent::response( $data, $http_code );
		}
	}
```

**Comment by asystat** [comment]
Hi benyamin,
thanks for your help but I tried your PR and it didn't work...it gives me the following error (and more)
A PHP Error was encountered
Severity: Notice
Message: Undefined index: username
Filename: libraries/REST_Controller.php
Line Number: 2040

**Comment by chriskacerguis** [comment]
See here https://github.com/chriskacerguis/codeigniter-restserver/issues/790

Closing this, please reopen if you are still having the issues.
