### ISSUE TITLE
Any chance of getting a version that is compatible with PHP 5.3?

### ISSUE THREAD

**Issue by schester44** [chriskacerguis/codeigniter-restserver#768]
Really wish I could use this library as is but unfortunately i'm in a position where only php 5.3 is available. Is there a version of this floating around that is compatible, and if so, where can I download it?

**Comment by chriskacerguis** [comment]
You can download one of the 2.x releases.

**Comment by schester44** [comment]
Hey Chris, thats what I was hoping to do. The readme says to grab one from the Downloads tab however there isn't a downloads tab to download from.
