### ISSUE TITLE
Authentication not working on latest build 

### ISSUE THREAD

**Issue by calvin-green** [chriskacerguis/codeigniter-restserver#770]
Authentication on the latest build is definitely not working- ran numerous test cases. 
Build 2.8 is running as it should.

**Comment by MasonFI** [comment]
I tried basic authentication and noticed that it doesn't work for me too.

**Comment by uWayLu** [comment]
AJAX, both of white and blacke IP list, and basic login auth are not working for me.

To make them work, I insert "exit();" into corresponding if statement in the libraries/REST_Controller.php.

The following is the example for IP whitelist.
~~~
        if (in_array($this->input->ip_address(), $whitelist) === FALSE)
        {
            $this->response([
                    $this->config->item('rest_status_field_name') => FALSE,
                    $this->config->item('rest_message_field_name') => $this->lang->line('text_rest_ip_unauthorized')
                ], self::HTTP_UNAUTHORIZED);
            exit();            // Please add this line to ensure progress end after response status code.
        }
~~~

**Comment by kalimerre** [comment]
This commit fix it (at least for me)
https://github.com/chriskacerguis/codeigniter-restserver/commit/54b2b9cf0698811f9fdf3a1f833f94295ef7a955

**Comment by chriskacerguis** [comment]
See here https://github.com/chriskacerguis/codeigniter-restserver/issues/790

Closing this, please reopen if you are still having the issues.
