### ISSUE TITLE
issue with geting  utf-8 characters 

### ISSUE THREAD

**Issue by RazzaghShahidi** [chriskacerguis/codeigniter-restserver#772]
i got bad decoded json data.
my data are in persian and in my web are displayed well but in api getting bad characters.
for example:
i got in api :
`{"manategh":[{"manategh_id":"51","manategh_name":"\u0634\u0644\u0645\u0686\u0647","manategh_picture":"24.jpg","manategh_description":"\u0645\u0648\u0642\u0639\u06cc\u062a \u062c\u063a\u0631\u0627\u0641\u06cc\u0627\u06cc\u06cc \u0634\u0644\u0645\u0686\u0647:\r\n\r\n\u0634\u0644\u0645\u0686\u0647 \u062f\u0631 \u06a9\u0634\u0648\u0631 \u0627\u06cc\u0631\u0627\u0646 \u060c \u0627\u0633\u062a\u0627\u0646 \u062e\u0648\u0632
}]}`

**Comment by RazzaghShahidi** [comment]
i solved it by passing `JSON_UNESCAPED_UNICODE` into `json_encode`  function.

`application\libraries\Format.php` in lines 408 , 415, 422:

**Comment by RazzaghShahidi** [comment]
problem solved just for getting json.
in other formats the issue is remains.

**Comment by cshxxx** [comment]
i have the same problem,ths.

**Comment by mohammed1955** [comment]
@RazzaghShahidi  Work For Me ,So THANKS

**Comment by luckydonald** [comment]
Like 
```php
if ($this->config->item('charset') == 'utf8') {
  json_encode($data, JSON_UNESCAPED_UNICODE)
} else {
  return json_encode($data)
}
```

**Comment by qbingking** [comment]
> i solved it by passing `JSON_UNESCAPED_UNICODE` to `json_encode` function.
> 
> file:
> `application\libraries\Format.php`
> 
> in line 408:
> ` return json_encode($data, JSON_UNESCAPED_UNICODE);`
> line 415:
> `return $callback.'('.json_encode($data, JSON_UNESCAPED_UNICODE).');';`
> line 422:
> `return json_encode($data, JSON_UNESCAPED_UNICODE);`
> 
> and file:
> `application\libraries\REST_Controller.php`
> in line 1123:
> `... === TRUE ? json_encode($this->_args,JSON_UNESCAPED_UNICODE) : ...`

yo man! it work fine, Vietnamese utf-8 wanna say thanks to you <3
