### ISSUE TITLE
How can i use REST_Controller with MY_Controller?

### ISSUE THREAD

**Issue by anonymuos1** [chriskacerguis/codeigniter-restserver#773]
Thank You!

**Comment by valterlima** [comment]
core/MY_Controller.php

class MY_Controller extends REST_Controller {
  ...
}

Yes I'm using right now.

**Comment by anonymuos1** [comment]
MY_Controller already extends CI_Controller...

class MY_Controller extends CI_Controller {
...
}

**Comment by cshxxx** [comment]
Yes
