### ISSUE TITLE
URL Structure

### ISSUE THREAD

**Issue by johnish** [chriskacerguis/codeigniter-restserver#777]
Reading over the install directions and an example write-up at https://code.tutsplus.com/tutorials/working-with-restful-services-in-codeigniter--net-8814

It seems every endpoint is it's own file. I currently have a user.php in application/controllers/ which makes this http://localhost/user/ but I would like to have 
http://localhost/api/user/
http://localhost/api/user/search/email/
http://localhost/api/user/search/phone/

What's the suggested way to create this?

**Comment by valterlima** [comment]
In my project I'm going only 3 levels deep: resource/id/resource or for e.g. user/1234/adresses.

You can override the index_get() method on your controller and inside it handle the sub-resources. e.g.:

file user.php
```
function index_get(){
  // YOUR_URL/api/v1/resource/id/resource2
  $resource2 = $this->uri->segment(5, NULL); 
}
```

**Comment by valterlima** [comment]
But I think you can define custom routes as well.

**Comment by johnish** [comment]
Thank you.

Can you post an example of the user.php file that does user/1234/adresses?

**Comment by valterlima** [comment]
User.php

```
class User extends REST_Controller{
  function index_get(){
    $id = $this->uri->segment(4, NULL); // BASE_URL/api/v1/resource/id
    $res2 = $this->uri->segment(5, NULL);  // BASE_URL/api/v1/resource/id/resource2
    if ($res2) 
       do something with $res2... like getting his adresses
    else if ($id)
      do something with $id, like fetching only this user
    else
      do something... like list all users
  
  }
}
```

**Comment by johnish** [comment]
This is really nice. Thank you.

**Comment by valterlima** [comment]
happy to help! :)
