### ISSUE TITLE
Setting Limits on method per api_key with a valid api_key

### ISSUE THREAD

**Issue by arth1992** [chriskacerguis/codeigniter-restserver#778]
Hi!  there,  Great Library

I am using this library for login purposes. The issue is i had enabled logs and api_key feature in rest config file.

    $config['rest_limits_method'] = 'ROUTED_URL';
    $config['rest_key_name'] = 'X-API-KEY';
   

In my controller file

    $this->methods['login_get'] = array('level' => 1, 'limit' => 10); // 500 requests per hour per user/key

In my routes file 

     $route['api/login'] = 'api/api/login';

Inside my logs table api_key column is always inserted as null, though i can see the X-API-KEY in my header request   i.e
                      
    a:10:{s:5:"email";s:27:"arth.parikh@kumbhdesign.com";s:8:"password";s:8:"admin123";s:4:"Host";s:14:"localhost:8080";s:10:"User-Agent";s:72:"Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0";s:6:"Accept";s:3:"*/*";s:15:"Accept-Language";s:14:"en-US,en;q=0.5";s:15:"Accept-Encoding";s:13:"gzip, deflate";s:9:"X-API-KEY";s:12:"sdfsdfsdfsdf";s:6:"Cookie";s:43:"ci_session=qcfo3pv3gdqhg8agh5bno5cd4ikd8jnr";s:10:"Connection";s:10:"keep-alive";}

Although the api_key is not validated  the request can be accessed. Can you suggest me some changes needed to do in the file?

I am using PHP Version : 5.6 , Codeigniter Version 3.0+  and latest repository of REST Server

**Comment by kalimerre** [comment]
For the 
> api_key is not validated the request can be accessed
part this commit fix it https://github.com/chriskacerguis/codeigniter-restserver/commit/54b2b9cf0698811f9fdf3a1f833f94295ef7a955

Just test it maybe it will fix your other problem also

**Comment by chriskacerguis** [comment]
See here https://github.com/chriskacerguis/codeigniter-restserver/issues/790

Closing this, please reopen if you are still having the issues.
