### ISSUE TITLE
Fetch User Data From API_KEYS

### ISSUE THREAD

**Issue by judemanutd** [chriskacerguis/codeigniter-restserver#781]
I want to enable API_KEYS so the REST_CONTROLLER can verify if the key is valid for a particular user and if it is valid i would like to fetch the userID of that particular user based on the given API_KEY supplied.
Can this be done automatically so the REST_CONTROLLER can fetch the ID and store it in a variable which i can later access in my controllers which extend the REST_CONTROLLER or would i have to manually get the API_KEY from the header and fetch the required data from my db?

**Comment by chriskacerguis** [comment]
How are you passing the userID?

**Comment by judemanutd** [comment]
@chriskacerguis the userID is stored in the db.I am sending a 150 character hash from the front end which i am using as an API KEY.
I have a table called Users which contains the userID and their respective API KEYS.
So when a request comes in with a key i would like the rest server to look at my users table and check if the api key is valid and if it is then give me the equivalent userID for that row.

**Comment by chriskacerguis** [comment]
Ahhh.  Check out these config options:

https://github.com/chriskacerguis/codeigniter-restserver/blob/master/application/config/rest.php#L301

https://github.com/chriskacerguis/codeigniter-restserver/blob/master/application/config/rest.php#L337

If I understand you correctly, that will get you where you need to be.

**Comment by judemanutd** [comment]
@chriskacerguis that would work and it would let in valid request but is there a way i can do something like this.
`$id_user=$this->session->userdata['logged_in']['id_user'];`

So if a request is valid the rest server fetches the entire row from my users table in the db and stores it in a variable which i can access from anywhere in the controller.
