### ISSUE TITLE
Enable API Key

### ISSUE THREAD

**Issue by rezarully** [chriskacerguis/codeigniter-restserver#782]
i have made my config  in API key become like this

$config['rest_enable_keys'] = TRUE;

but when i tried to test it nothing happens

do i need to make another configuration in my project to enable  the API key?

tks

**Comment by chriskacerguis** [comment]
See here https://github.com/chriskacerguis/codeigniter-restserver/issues/790

Closing this, please reopen if you are still having the issues.
