### ISSUE TITLE
Response should exit after first call after using invalid credentials

### ISSUE THREAD

**Issue by Revenkroz** [chriskacerguis/codeigniter-restserver#785]
I had a strange error after using invalid credentials - [it always returns a "secret data"](http://i.imgur.com/t6j4Ifu.png). The investigation of this error led me to `response` function. So, problem was in it - it should have display an error, but instead it just set a variable with this error, and the program continued to work. If you add display function at the end of `response`:
```
{"status":false,"error":"Unauthorized"}

... // error

[{"id":1,"name":"John","email":"john@example.com","fact":"Loves coding"},{"id":2,"name":"Jim","email":"jim@example.com","fact":"Developed on CodeIgniter"},{"id":3,"name":"Jane","email":"jane@example.com","fact":"Lives in the USA","0":{"hobbies":["guitar","cycling"]}}][{"id":1,"name":"John","email":"john@example.com","fact":"Loves coding"},{"id":2,"name":"Jim","email":"jim@example.com","fact":"Developed on CodeIgniter"},{"id":3,"name":"Jane","email":"jane@example.com","fact":"Lives in the USA","0":{"hobbies":["guitar","cycling"]}}]
```

Probably solution is to add this two lines at the end:
```
$this->output->_display();
exit();
```
Something similar was already in previous versions, but it was deleted (probably for a reason):
```
       if($continue){
            echo($output);
            ob_end_flush();
            ob_flush();
            flush();
        }else{
            exit($output);
        }
```

**Comment by lambasoft** [comment]
I'm having a similar issue as well, where if in a function there's more than one call to the `response` function, the last one is only executed. Something like that:

```
    public function login_get() {
        if (1 == 1) {
            $this->response(array("success" => true, "message" => "It Worked"));
        }
        $this->response(array("success" => false, "error" => "Empty Username/Password"));
    }
```

Will always show the last response (Empty Username/Password)

**Comment by kalimerre** [comment]
This commit should do the trick https://github.com/chriskacerguis/codeigniter-restserver/commit/54b2b9cf0698811f9fdf3a1f833f94295ef7a955

**Comment by chriskacerguis** [comment]
See here https://github.com/chriskacerguis/codeigniter-restserver/issues/790

Closing this, please reopen if you are still having the issues.
