### ISSUE TITLE
Another Class 'CI_Format' not found issue

### ISSUE THREAD

**Issue by zipnadarien** [chriskacerguis/codeigniter-restserver#786]
I'm seeing a similar issue as [529](https://github.com/chriskacerguis/codeigniter-restserver/issues/529) and [589](https://github.com/chriskacerguis/codeigniter-restserver/issues/589), have thoroughly researched the problem, but am stuck.

I've been using this REST library for a number of years w/out problems. I need to update php, CI, and this REST library due to a change at my hosting provider. I've tried to create a minimal example to explain what I'm seeing. Here's the scoop:

- I'm running on OSX MAMP (php 7.0.15) and also on Centos at my hosting provider
- I deleted all files for my app
- I downloaded and installed codeigniter-restserver-3.0.0. I did no additional configuration. Everything works as expected including the Rest_server.php and api/Examples.php. That was to show the basic setup is working.
- I modified Welcome.php to include a simple class (from another file as expected). It works fine.
- I modified api/Examples.php to include this same simple class and when I create a new instance of this class, I get the "Fatal error: Class 'CI_Format' not found in ... system/core/Common.php on line 196"

I've tried various options with namespaces, loading as a library vs including as a class, etc. it results in the same problem everywhere.

To simplify figuring this out, Here's how to reproduce the issue in less than 2 minutes - 

1. Install codeigniter-restserver-3.0.0 into wherever your server files reside
2. Copy the Classtwo.php file below into the applications/controllers folder
3. Add the following to the api/Example.php file:
   - "require APPPATH . '/controllers/Classtwo.php';"
   - to the top of users_get method add "$classtwo = new Classtwo();"
4. Replace the current Welcome.php with the file Welcome.php file below.
5. Access the Welcome.php to see the class include work fine
6. Access the api/example/users to see the class include cause the problem

Classtwo.php
`<?php if (!defined('BASEPATH')) exit('No direct script access allowed'); 
class Classtwo extends \CI_Controller {
	function nothing($testin){
		$testout = "The parameter - <p>" . $testin;
        return $testout;
	}
}
`

Welcome.php
`<?php defined('BASEPATH') OR exit('No direct script access allowed');
require APPPATH.'/controllers/Classtwo.php';
class Welcome extends CI_Controller {
   public function index() {
      $classtwo = new Classtwo();
      echo $classtwo->nothing("Welcome");
      echo "<p>php version " . phpversion() . "<p>CodeIgniter version " . CI_VERSION;
   }
}
`

Any idea what's going on and/or how to address it?

**Comment by chriskacerguis** [comment]
See here https://github.com/chriskacerguis/codeigniter-restserver/issues/790

Closing this, please reopen if you are still having the issues.
