### ISSUE TITLE
Session authentication does not end the execution

### ISSUE THREAD

**Issue by cmenet** [chriskacerguis/codeigniter-restserver#788]
If a session variable is configured, the _check_php_session method is executed in the REST_controller.php class.
If the session variable does not exist then a response is executed with the http code 401.
But the response method does not finish execution and continues after the response is sent to the client.

In my case modify the code of the response to end the execution if it receives as self :: HTTP_UNAUTHORIZED parameter but I do not know if this is correct at all.

My response method got this way.

    /**
     * Takes mixed data and optionally a status code, then creates the response
     *
     * @access public
     * @param array|NULL $data Data to output to the user
     * @param int|NULL $http_code HTTP status code
     * running the script; otherwise, exit
     */
    public function response($data = NULL, $http_code = NULL)
    {
		ob_start();
        // If the HTTP status is not NULL, then cast as an integer
        if ($http_code !== NULL)
        {
            // So as to be safe later on in the process
            $http_code = (int) $http_code;
        }

        // Set the output as NULL by default
        $output = NULL;

        // If data is NULL and no HTTP status code provided, then display, error and exit
        if ($data === NULL && $http_code === NULL)
        {
            $http_code = self::HTTP_NOT_FOUND;
        }

        // If data is not NULL and a HTTP status code provided, then continue
        elseif ($data !== NULL)
        {
            // If the format method exists, call and return the output in that format
            if (method_exists($this->format, 'to_' . $this->response->format))
            {
                // Set the format header
                $this->output->set_content_type($this->_supported_formats[$this->response->format], strtolower($this->config->item('charset')));
                $output = $this->format->factory($data)->{'to_' . $this->response->format}();

                // An array must be parsed as a string, so as not to cause an array to string error
                // Json is the most appropriate form for such a data type
                if ($this->response->format === 'array')
                {
                    $output = $this->format->factory($output)->{'to_json'}();
                }
            }
            else
            {
                // If an array or object, then parse as a json, so as to be a 'string'
                if (is_array($data) || is_object($data))
                {
                    $data = $this->format->factory($data)->{'to_json'}();
                }

                // Format is not supported, so output the raw data as a string
                $output = $data;
            }
        }

        // If not greater than zero, then set the HTTP status code as 200 by default
        // Though perhaps 500 should be set instead, for the developer not passing a
        // correct HTTP status code
        $http_code > 0 || $http_code = self::HTTP_OK;

        $this->output->set_status_header($http_code);

        // JC: Log response code only if rest logging enabled
        if ($this->config->item('rest_enable_logging') === TRUE)
        {
            $this->_log_response_code($http_code);
        }

        // Output the data
        $this->output->set_output($output);

        ob_end_flush();

        //If the http_code self::HTTP_UNAUTHORIZED then exit
        if($http_code === self::HTTP_UNAUTHORIZED)
        {
            exit;
        }

        // Otherwise dump the output automatically
    }

**Comment by cmenet** [comment]
Cambie mi codigo, quite el exit del metodo response y agregue un exit en el metodo _check_php_session.
Here is my code, I still do not know if it is completely correct.
    /**
     * Check to see if the user is logged in with a PHP session key
     *
     * @access protected
     * @return void
     */
    protected function _check_php_session()
    {
        // Get the auth_source config item
        $key = $this->config->item('auth_source');

        // If false, then the user isn't logged in
        if ( ! $this->session->userdata($key))
        {
            
            // Display an error response
            $this->response([
                    $this->config->item('rest_status_field_name') => FALSE,
                    $this->config->item('rest_message_field_name') => $this->lang->line('text_rest_unauthorized')
                ], self::HTTP_UNAUTHORIZED);

            exit;

        }
    }

**Comment by chriskacerguis** [comment]
See here https://github.com/chriskacerguis/codeigniter-restserver/issues/790

Closing this, please reopen if you are still having the issues.
