### ISSUE TITLE
Json Resposne null 

### ISSUE THREAD

**Issue by sairamduggi** [chriskacerguis/codeigniter-restserver#789]
Hi chriskacerguis,
I have built my web services using the codeigniter-rest server,

I works well in postman and advanced rest client but when it comes to 
android  it show response code 201 created  but the data cannot be shown in the json resposne
Is the issue is with me or the android part and here is my code
Rest_model
<?php

Class Rest_user_model extends CI_Model
{

    var $CI;

    protected $_table_name = 'users';
    protected $_order_by = 'id desc';
    protected $_timestamps = TRUE;
    
    function __construct()
    {
        parent::__construct();

        $this->CI =& get_instance();
        $this->CI->load->database(); 
        $this->CI->load->helper('url');
    }
    
   function saveuser($data){
	   
   		if(!empty($data)){
   		$this->db->insert('register', $data);
		
   		return $this->db->insert_id();
   		}
   		return 0;
	   
    }
    
   function getUserProfile($employee_id){
    	
		
		$this->db->select('employee_id','password');
		$this->db->from('users');
		$this->db->where('employee_id', $employee_id);
		$query = $this->db->get();
		$results = $query->row_array();
		
		return $results; 
    }
	
	
	function login($employee_id,$password)
    { 
        $this->db->select('password');
        $this->db->where('employee_id', $employee_id); 
        $this->db->where('password', $password);
		$this->db->limit(1);
        $result = $this->db->get('users'); 
        $user = $result->row_array();
        if ($user){
             return $user;
        }else{
            return false;
        }
    }
	
	
	
	public function user_exists($employee_id){
   
        $query = $this->db->query("SELECT employee_id FROM users WHERE employee_id='".$employee_id."'");
        
        if($row = $query->row()){
             return 1;
        }else{
             
			 return 0;
        }
	
    }
	

	 
	
}
users.php
I have placed user's in php in controllers

<?php

defined('BASEPATH') OR exit('No direct script access allowed');
require APPPATH . '/libraries/REST_Controller.php';

class Users extends REST_Controller {

    function __construct()
    {
        parent::__construct();
    }

    public function login_post()
    {
       $employee_id=$this->post('employee_id');
	   $password=$this->post('password');
	   $this->load->model('Rest_user_model');
	   $users_data=$this->Rest_user_model->login($employee_id,$password);
	   if(is_array($users_data) && !empty($users_data))
	   {
        $message = [
            'status' => 'success', 
            'result' => $users_data,
            'message' => 'User found Successfully'
        ];
	   }else
	   {
		 $message = [
            'status' => 'fail', 
             'result' => array(),
            'message' => 'User not found'
        ];  
		   
	   }   
	   
        $this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
    }
    public function register_post()
    {
	$employee_id=$this->post('employee_id');
	$password=$this->post('password');
	$this->load->model('Rest_user_model');
	$users_data=$this->Rest_user_model->user_exists($employee_id);
	if($users_data==1)
	   {
        $message = [
            'status' => 'fail', 
            'result' => array(),
            'message' => 'User already exists'
        ];
	   }else
	   {
	  
	$name=$this->post('name');
	$email=$this->post('email');
	$this->load->model('Rest_user_model');
	$insert_array=array(
	'name'=>$name,
	'employee_id'=>$employee_id,
	'password'=>$password,
	'email'=>$email	
	);
	$users_data=$this->Rest_user_model->saveuser($insert_array);
	
	$message = [
	'status' => 'success', 
	'result' => $users_data,
	'message' => 'User  created'
	];  
		   
	}
	$this->set_response($message, REST_Controller::HTTP_CREATED); 
    }

}
Can you figure out me the issue? as i am new to it
Thanks in advance

**Comment by chriskacerguis** [comment]
can you please format the code in the issue so I can read it?

**Comment by sairamduggi** [comment]
`<?php

Class Rest_user_model extends CI_Model
{

    var $CI;

    protected $_table_name = 'users';
    protected $_order_by = 'id desc';
    protected $_timestamps = TRUE;
    
    function __construct()
    {
        parent::__construct();

        $this->CI =& get_instance();
        $this->CI->load->database(); 
        $this->CI->load->helper('url');
    }
    
   function saveuser($data){
	   
   		if(!empty($data)){
   		$this->db->insert('register', $data);
		
   		return $this->db->insert_id();
   		}
   		return 0;
	   
    }
    
   function getUserProfile($employee_id){
    	
		//$this->db->select('user_id,first_name,email_id,role_id,phone_number,alternate_phno,state,city,file_name,street,building_no,area,country,experience,zip,additional_address,about_me,userr_description,longitude,latitude,is_active');
		$this->db->select('employee_id','password');
		$this->db->from('users');
		$this->db->where('employee_id', $employee_id);
		$query = $this->db->get();
		$results = $query->row_array();
		
		return $results; 
    }
	
	
	function login($employee_id,$password)
    { 
        $this->db->select('password');
        $this->db->where('employee_id', $employee_id); 
        $this->db->where('password', $password);
		$this->db->limit(1);
        $result = $this->db->get('users'); 
        $user = $result->row_array();
        if ($user){
             return $user;
        }else{
            return false;
        }
    }
	
	
	
	public function user_exists($employee_id){
   
        $query = $this->db->query("SELECT employee_id FROM users WHERE employee_id='".$employee_id."'");
        
        if($row = $query->row()){
             return 1;
        }else{
             
			 return 0;
        }
	
    }
	

	 
	
}`

`<?php

defined('BASEPATH') OR exit('No direct script access allowed');
require APPPATH . '/libraries/REST_Controller.php';

class Users extends REST_Controller {

    function __construct()
    {
        parent::__construct();
    }


    public function login_post()
    {
       $employee_id=$this->post('employee_id');
	   $password=$this->post('password');
	   $this->load->model('Rest_user_model');
	   $users_data=$this->Rest_user_model->login($employee_id,$password);
	   if(is_array($users_data) && !empty($users_data))
	   {
        $message = [
            'status' => 'success', 
            'result' => $users_data,
            'message' => 'User found Successfully'
        ];
	   }else
	   {
		 $message = [
            'status' => 'fail', 
             'result' => array(),
            'message' => 'User not found'
        ];  
		   
	   }   
	   
        $this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
    }
    public function register_post()
    {
	$employee_id=$this->post('employee_id');
	$password=$this->post('password');
	$this->load->model('Rest_user_model');
	$users_data=$this->Rest_user_model->user_exists($employee_id);
	if($users_data==1)
	   {
        $message = [
            'status' => 'fail', 
            'result' => array(),
            'message' => 'User already exists'
        ];
	   }else
	   {
	  
	$name=$this->post('name');
	$email=$this->post('email');
	$this->load->model('Rest_user_model');
	$insert_array=array(
	'name'=>$name,
	'employee_id'=>$employee_id,
	'password'=>$password,
	'email'=>$email	
	);
	$users_data=$this->Rest_user_model->saveuser($insert_array);
	
	$message = [
	'status' => 'success', 
	'result' => $users_data,
	'message' => 'User  created'
	];  
		   
	}
	$this->set_response($message, REST_Controller::HTTP_CREATED); 
    }



}
`

**Comment by sairamduggi** [comment]
Still needed more info ?
If so let know which kind of info you require?

**Comment by chriskacerguis** [comment]
Based on the info you provided the issue is not with the REST client, but maybe with Android (maybe the data you are sending??)
