### ISSUE TITLE
Need to add the language file to the install steps

### ISSUE THREAD

**Issue by michaelh99** [chriskacerguis/codeigniter-restserver#792]
Without it, you'll get an untraceable 500 error when you call into the controller.  Even with CI logging turned up to maximum it's impossible to see why.
I had to add log messages to the rest controller until I narrowed it down to the failing call to load the language file.

**Comment by Hanisch-IT** [comment]
Hi @michaelh99,

i tested it that way:

- Create a new codeigniter project
- Copy&Paste the files from this repo in the CI-Project
- Tried the test calls

I got no errors, i think the most languages are included in this library.

**Comment by michaelh99** [comment]
Someone should have slapped me for writing up a crap bug report.
Reading this months later, I'm not sure what the hell I'm talking about other than some file was missing that I had to account for.
Feel free to close this.  Looking at this months later I'd guess the problem was BKAC
