### ISSUE TITLE
application/json request

### ISSUE THREAD

**Issue by soundiver** [chriskacerguis/codeigniter-restserver#793]
Hello, in my app, everything is ok if I send POST call from Soapui in x-www-form-urlencoded (Post QueryString). Result is "TRUE" and response OK.

But, if I select MediaType = "application/json" it doesn't work...  because it skip "if": 

if(($this->post('MYVAR') != NULL)){		
	$result = TRUE;
}else{	
	$result = FALSE;
}

How can I tell to my API controller to read the body of the request?

thank you in advance

**Comment by rudybenedetti** [comment]
Please, close this issue, thank you very much.

**Comment by judemanutd** [comment]
Give this a try
 `$data = json_decode($this->input->raw_input_stream, true);
        $sent_data = $data['MYVAR'];`
