### ISSUE TITLE
Any plans to made it "third_party"?

### ISSUE THREAD

**Issue by sierrafayad** [chriskacerguis/codeigniter-restserver#798]
I sucessfuly implemented that way.
![image](https://cloud.githubusercontent.com/assets/4095810/25819819/d166a57a-33f4-11e7-9009-6941791ece93.png)

**Comment by Romerski** [comment]
Can you tell us how did you do? Thanks.

**Comment by luckydonald** [comment]
@sierrafayad please share it with us.

**Comment by sierrafayad** [comment]
Hi,
The in my project i have implemented a lot of modifications internally including JWT authentication, i will have to download a new fork and add those(because i removed some of the features that this project already have)

To list some of them:
- Response string logging (for debugging purpose (opt formatting)) even on status 500 responses
! [Navicat_2017-08-09_11-10-39] (https://user-images.githubusercontent.com/4095810/29131774-8c6c4aa4-7cf3-11e7-9144-ccf9ea8ebf3b.png)
- JWT Authentication
- Some table schema modification for ease of use. (This may be a breaking change so this better stay off)

I do not remember what else but i know i am way off this repo

**Comment by chriskacerguis** [comment]
@sierrafayad I'd love to get those implemented here.  Any chance for a PR?

**Comment by sierrafayad** [comment]
Sure @chriskacerguis 
I will be forking this and adding those then separate PR for each one

**Comment by chriskacerguis** [comment]
awesome!  Looking forward to getting those merged.

**Comment by sierrafayad** [comment]
Just in case you want to take a look here is the repo where i have modified
https://github.com/sierrafayad/PHP-CI-rest-server

**Comment by sierrafayad** [comment]
opened PR #828
