### ISSUE TITLE
Basic authentication not working

### ISSUE THREAD

**Issue by amosangyongjian** [chriskacerguis/codeigniter-restserver#803]
I am trying to integrate REST services on my site.  So far I was able to successfully call the required data. However, when I wanted to add authorization to it and when I try to access it from Postman I get this error:

{
  "status": false,
  "error": "Unauthorized"
}
If I remove the auth, it works again. Does anyone know if this is a bug or is there something I'm missing?? This is my configuration:

-------------------------------------------------------------------------
| REST Login
|--------------------------------------------------------------------------
|
| Set to specify the REST API requires to be logged in
|
| FALSE     No login required
| 'basic'   Unsecured login
| 'digest'  More secured login
| 'session' Check for a PHP session variable. See 'auth_source' to set the
|           authorization key
|
*/
$config['rest_auth'] = 'basic';

|--------------------------------------------------------------------------
| REST Login Usernames
|--------------------------------------------------------------------------
|
| Array of usernames and passwords for login, if ldap is configured this is ignored
|
*/
$config['rest_valid_logins'] = ['admin' => '1234'];
I can't access it through the url as well. The authentication popup keeps appearing even though I have entered the credentials. Please help

**Comment by sierrafayad** [comment]
Hi @amosangyongjian are you sending Authorization headers?

**Comment by Saquibrizwan** [comment]
I have the same issue I send Authorization headers using postman and i got this error. 

The configuration file ldap.php does not exist.

**Comment by amosangyongjian** [comment]
Hi, I realized that my server is using fastcgi so I had to make some changes to the htaccess and some lines in the controller config

**Comment by Saquibrizwan** [comment]
I solved my issue by changing this
$config['auth_source'] = 'idap'; 
to this
$config['auth_source'] = '';
now basic authentication is working

**Comment by cheimsminator** [comment]
Hi, I'm using this apirest. I add basic authentication ($ config ['rest_auth'] = 'basic';) and when I make a request without authentication this is correct, ie it does not request validation.

**Comment by ccnie** [comment]
basic authentication needs two modification in rest.php
$config['rest_auth'] = 'basic';
$config['auth_source'] = '';

And now you can try your basic auth as follow curl command in shell:
curl -u admin:1234 http://www.sample.com/api/user/1

BTW: user admin has been already defined in rest.php
$config['rest_valid_logins'] = ['admin' => '1234'];

**Comment by ccnie** [comment]
If you want to try digest scheme:
It needs two modification in rest.php
$config['rest_auth'] = 'digest';
$config['auth_source'] = '';

And now you can try your digest auth as follow curl command in shell:
curl --digest -u admin:1234 http://www.sample.com/api/user/1

**Comment by alexyellowcube** [comment]
i am trying used the basic authentication but i always get null from 

$this->input->server('HTTP_AUTHORIZATION')

Look like the authorization header is missing after call the API request.

Here is what i get from my $this->input->server(NULL, TRUE) 

![screenshot 2017-11-14 12 16 42](https://user-images.githubusercontent.com/18346408/32762704-ec013946-c935-11e7-8260-8c5a9c540a31.png)


/** ----------------------------------------------------**/
array(52) {
  ["PATH"]=>
  string(28) "/usr/local/bin:/usr/bin:/bin"
  ["TZ"]=>
  string(16) "America/New_York"
  ["REDIRECT_HANDLER"]=>
  string(28) "application/x-httpd-ea-php56"
  ["REDIRECT_STATUS"]=>
  string(3) "200"
  ["UNIQUE_ID"]=>
  string(27) "WgptO@qXugE7Jia1dy9ppgAAARA"
  ["SCRIPT_URL"]=>
  string(34) "/index.php/api/V1/Example_api/test"
  ["SCRIPT_URI"]=>
  string(59) "https://www.river-app.com/index.php/api/V1/Example_api/test"
  ["HTTPS"]=>
  string(2) "on"
  ["SSL_TLS_SNI"]=>
  string(17) "www.river-app.com"
  ["HTTP_HOST"]=>
  string(17) "www.river-app.com"
  ["HTTP_CONNECTION"]=>
  string(10) "keep-alive"
  ["HTTP_TESTINGABC"]=>
  string(3) "ABC"
  ["HTTP_CACHE_CONTROL"]=>
  string(8) "no-cache"
  ["HTTP_USER_AGENT"]=>
  string(121) "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
  ["HTTP_X_API_KEY"]=>
  string(40) "slrirgm2c5c00s4gk4w8g04c0gkk44cabc1dhj1s"
  ["HTTP_POSTMAN_TOKEN"]=>
  string(36) "797ce37f-64d4-1121-aab7-4574741614c4"
  ["HTTP_ACCEPT"]=>
  string(3) "*/*"
  ["HTTP_ACCEPT_ENCODING"]=>
  string(17) "gzip, deflate, br"
  ["HTTP_ACCEPT_LANGUAGE"]=>
  string(38) "en-US,en;q=0.8,zh-CN;q=0.6,zh-TW;q=0.4"
  ["HTTP_COOKIE"]=>
  string(43) "ci_session=qj4jgsh9js19ivgeh4ir5f1ivbvh9uml"
  ["HTTP_X_HTTPS"]=>
  string(1) "1"
  ["SERVER_SIGNATURE"]=>
  string(0) ""
  ["SERVER_SOFTWARE"]=>
  string(6) "Apache"
  ["SERVER_NAME"]=>
  string(17) "www.river-app.com"
  ["SERVER_ADDR"]=>
  string(14) "67.225.226.183"
  ["SERVER_PORT"]=>
  string(3) "443"
  ["REMOTE_ADDR"]=>
  string(15) "118.200.235.133"
  ["DOCUMENT_ROOT"]=>
  string(26) "/home/riverapp/public_html"
  ["REQUEST_SCHEME"]=>
  string(5) "https"
  ["CONTEXT_PREFIX"]=>
  string(8) "/cgi-sys"
  ["CONTEXT_DOCUMENT_ROOT"]=>
  string(26) "/usr/local/cpanel/cgi-sys/"
  ["SERVER_ADMIN"]=>
  string(23) "webmaster@river-app.com"
  ["SCRIPT_FILENAME"]=>
  string(36) "/home/riverapp/public_html/index.php"
  ["REMOTE_PORT"]=>
  string(5) "62900"
  ["REDIRECT_URL"]=>
  string(34) "/index.php/api/V1/Example_api/test"
  ["GATEWAY_INTERFACE"]=>
  string(7) "CGI/1.1"
  ["SERVER_PROTOCOL"]=>
  string(8) "HTTP/1.1"
  ["REQUEST_METHOD"]=>
  string(3) "GET"
  ["QUERY_STRING"]=>
  string(0) ""
  ["REQUEST_URI"]=>
  string(34) "/index.php/api/V1/Example_api/test"
  ["SCRIPT_NAME"]=>
  string(10) "/index.php"
  ["PATH_INFO"]=>
  string(24) "/api/V1/Example_api/test"
  ["PATH_TRANSLATED"]=>
  string(50) "/home/riverapp/public_html/api/V1/Example_api/test"
  ["ORIG_PATH_INFO"]=>
  string(34) "/index.php/api/V1/Example_api/test"
  ["ORIG_SCRIPT_NAME"]=>
  string(17) "/cgi-sys/ea-php56"
  ["ORIG_SCRIPT_FILENAME"]=>
  string(34) "/usr/local/cpanel/cgi-sys/ea-php56"
  ["ORIG_PATH_TRANSLATED"]=>
  string(60) "/home/riverapp/public_html/index.php/api/V1/Example_api/test"
  ["PHP_SELF"]=>
  string(34) "/index.php/api/V1/Example_api/test"
  ["REQUEST_TIME_FLOAT"]=>
  string(13) "1510632763.87"
  ["REQUEST_TIME"]=>
  string(10) "1510632763"
  ["argv"]=>
  array(0) {
  }
  ["argc"]=>
  string(1) "0"
}

/** ----------------------------------------------------**/
 And i also try modify the .htaccess but none of them are working for me.
/** ----------------------------------------------------**/
My .htaccess

<IfModule mod_rewrite.c>
RewriteEngine On
SetEnvIf Authorization .+ HTTP_AUTHORIZATION=$0
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]


#RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php/$1 [L]

</IfModule>
<IfModule mod_headers.c>
    Header set Access-Control-Allow-Origin "*"
    Header set Access-Control-Allow-Headers: "Authorization"
</IfModule>
<IfModule mod_env.c>
    SetEnv CI_ENV development
</IfModule>
#<IfModule mod_env.c>
#    SetEnv CI_ENV testing
#</IfModule>
#<IfModule mod_env.c>
#    SetEnv CI_ENV production
#</IfModule>
/** ----------------------------------------------------**/

anyone got the idea how to solve this issue.
