### ISSUE TITLE
Custom controller method

### ISSUE THREAD

**Issue by timyounes** [chriskacerguis/codeigniter-restserver#804]
Hello,

How can I specify my custom controller method? I don't want to use index_get, index_post etc.

Thanks in advanced

**Comment by coscho** [comment]
user_get
user_post
user_put
user_delete(id)
users_get

**Comment by timyounes** [comment]
This is the only way to make custom method in my controllers?

**Comment by sierrafayad** [comment]
You mean, using something like aliases?

**Comment by timyounes** [comment]
Yes

**Comment by sierrafayad** [comment]
Then, you have the routes.php file inside application/config/ folder.

`$route['v1/Inventory/Movements/Provider/(:num)/Report']['GET'] = 'v1/cat/Warehouse_movements/movements_provider_report/$1';`

Where: v1/Inventory/Movements/Provider/(:num)/Report is the URI on web browser
And: v1/cat/Warehouse_movements/movements_provider_report/$1 is the alias of /application/controllers/v1/cat/Warehouse_movements.php 
`movements_provider_report ` is the method whom takes 1 argument called `id `and is equal to the value of (:num) on the URI.

I hope this helps

**Comment by timyounes** [comment]
Thanks @sierrafayad

**Comment by sierrafayad** [comment]
I forgot to mention, the method `movements_provider_report` has as a suffix `_get`
