### ISSUE TITLE
Unable to active api key for a particular controller

### ISSUE THREAD

**Issue by sudipt0** [chriskacerguis/codeigniter-restserver#805]
<h1>rest_enable_access</h1>
I want to give access to an API key for a particular controller, so i have activated the API key and 

`$config['rest_enable_access'] = TRUE;`

And I have created all the tables.

after that I have inserted data on the access table using the same API key, now i want that API key to access only a particular controller say 'example', but whenever  have given the example as controller field name, it's showing
`{
  "status": false,
  "error": This API key does not have access to the requested controller"
}`

**Comment by sierrafayad** [comment]
In the table access there is a field called all_access do you have it in "1"?

**Comment by gakyoo** [comment]
I had In the table access, all_access set to 0 and did not work, when I changed to value 1 it worked, but there are things I don't fully understand in the access table and keys table would you please add more documentation on how to use those fields?

**Comment by alzarez** [comment]
If you want to limit the api key for a particular controller you need to set all_access to 0 and set the controller field with your controller. For example: 
controller = /api

**Comment by iyinusa** [comment]
When set all_access to 0, then set your controller field to api/blog. Where the 'api' is the directory your REST client extending REST_Controller is hosted, and the blog is your controller.
