### ISSUE TITLE
Error when use api key

### ISSUE THREAD

**Issue by omid2student** [chriskacerguis/codeigniter-restserver#806]
Hello
I use api key for restful in my project
Api key is correct but it get below error
**This API key does not have enough permissions**
My record is 
id 	key 	       level 	   ignore_limits 	date_created
1 	omid 	10 	           10 	                          0

**Comment by kalimerre** [comment]
Can you add a sample of your controller ? With the level set ? 

Regards,

**Comment by omid2student** [comment]
I add key in table (default level is 0)
My problem is that i dont know what is level
Do you can say to me?
How can i know what is permission?

**Comment by sierrafayad** [comment]
Level is a parameter that should be set on you classes.
if you aren't using it set it to 0.

Take a look in here: https://github.com/chriskacerguis/codeigniter-restserver/blob/development/application/controllers/api/Example.php
you can find how to use them.

**Comment by omid2student** [comment]
Thanks but i dont see level parameter in your example :(

**Comment by sierrafayad** [comment]
Sorry, my bad. inside the constructor you should put something like this ` $this->methods['{method_name}_get']['level'] = 10` but as i said its not necessary if you aren't going to use it, you should justo put 0 in the DB record.

**Comment by kalimerre** [comment]
@sierrafayad is right about 0

If you need an example of level here you got : https://github.com/chriskacerguis/codeigniter-restserver/blob/development/application/controllers/api/Key.php

**Comment by omid2student** [comment]
I need to permission for use it in my project
It is good solution for limit user
