### ISSUE TITLE
Get access to table data using API Key

### ISSUE THREAD

**Issue by judemanutd** [chriskacerguis/codeigniter-restserver#807]
When using API Keys in case the api key in the header matches the api key in 1 of the rows in the table,is it possible to manually fetch the contents of that row or would i have to get the api key from the header and then run the query myself?

**Comment by kalimerre** [comment]
As far as I see you need to run the query to get informations. I will try to check at work tomorrow if I can find something but from what I see you have to run the query

**Comment by judemanutd** [comment]
@kalimerre for now i have fetched the key from the header and i am running a query to get the row which works fine but it would be great if there was an inbuilt function which could do that

**Comment by kalimerre** [comment]
I didn't find any inbuilt function to do that in the library unfortunatly 
Anyway if you have build yours and it works there is no real big problem :)

**Comment by judemanutd** [comment]
@stef686 thanks, will check it out.
