### ISSUE TITLE
Handle PUT request in AJAX FormData Submission

### ISSUE THREAD

**Issue by zerocoolElite** [chriskacerguis/codeigniter-restserver#811]
Hi $this->put() is not working if data is from FormData

example data:
-----------------------------13184788820744
Content-Disposition: form-data; name="system"

{"1":{"systemFullName":"asd","description":"asd"}}
-----------------------------13184788820744
Content-Disposition: form-data; name="TEST_NAME"

{"ASDASD":"asd"}
-----------------------------13184788820744--

**Comment by lyhongpon** [comment]
I get this problem too.

**Comment by fikoborquez** [comment]
Check [this](https://stackoverflow.com/questions/22482860/codeigniter-rest-put-method-not-working-for-form-data).
