### ISSUE TITLE
Form validation not working 

### ISSUE THREAD

**Issue by bismert** [chriskacerguis/codeigniter-restserver#816]
Hi,  everyone I'm  using  this philsturgeon rest server for backend. Now,  when I tested with postman it was working fine but at the real practice when setting up with Nativescript as one of the front end it keeps returning an error which is TypeError : Network request failed: unexpected expected token < at position 3
As a result of debugging I discovered everything was fine with Nativescript side but at the point of validation  where on my codeigniter script $this->forn_validation->run()  caused  it. I don't know what was going wrong. Kindly help me out

**Comment by chriskacerguis** [comment]
Not really enough info to help, but that said, seems like the issue is not with the REST server.
