### ISSUE TITLE
How do I get the request header? 

### ISSUE THREAD

**Issue by narraressan** [chriskacerguis/codeigniter-restserver#817]
Hello, sorry, but I am new to codeigniter and while I am using this lib to setup a REST api, I am a little lost as to how to access the request headers.

function user_post()
    {       
        $res = array('id'=>$this->post('id'), 'data'=>$this->post('data'));
        $this->response(request(), 200);
    }

here I have successfully taken the id and data params of the request but I dont know how to access the request headers. I need to get a specific header from there...

**Comment by pippos44** [comment]
User CI3 Input Class
https://www.codeigniter.com/user_guide/libraries/input.html

$headers = $this->input->request_headers();

**Comment by narraressan** [comment]
oh! there it is, thank you very much sir.
