### ISSUE TITLE
Cache Response Data and Cache Response Headers

### ISSUE THREAD

**Issue by natanfelles** [chriskacerguis/codeigniter-restserver#821]
What about add a default Cache system to the REST Controller?

For example:

Add the cache options in the config `rest.php`, same keys as the default `$this->load->driver('cache', array('adapter' => 'apc', 'backup' => 'file'));` but only load this if is called from a method.

Then the user can add the data to be cached, and the seconds, but in the `REST_Controller` the headers `Cache-Control`, `Expires`, `Last-Modified` and `ETag` be automatically created.

I am started to code here, and this worked nice. What do you think about?

If thinks that can be useful I send the PR. Thanks.

**Comment by chriskacerguis** [comment]
Sure, a PR would be great.

**Comment by magijoylarin** [comment]
Hi any updates on this?
