### ISSUE TITLE
[SOLVED] REST API request does not reply until shell script is done

### ISSUE THREAD

**Issue by datenshi** [chriskacerguis/codeigniter-restserver#822]
Hi All,

we are using this REST API module by Chris Kacerguis. This is the code:

PHP Code:
```
public function getAllInformation_put()
{
     ...
            if (!empty($values['Network'])){
                $partial_response = $partial_response.self::setNetworkParams($values['Network']);
            }

            // Generate final REST response
            $response = '{
                              "status": 200,
                              "message": "PUT '.$partial_response.'successful"
                        }';
            $response_array = json_decode($response, true);
            $this->set_response($response_array, REST_Controller::HTTP_OK); // CREATED (201) being the HTTP response code - Changed to 200
            
            if (!empty($values['Configuration'])){
                shell_exec("/bin/reboot.sh &");
            }
        }
    } 
```

And the problem we find is that the response (set_response) is not immediately sent and it waits for the reboot script to be executed (even we try to run it in the background and it has a sleep of 3 secs)

So sometimes we get network error by response, although the logic is well executed. Because probably the reboot timing and the set_response is too tight. 

Any idea about this issue or how we can try to fix it?

Thanks a lot in advance.

**Comment by fikoborquez** [comment]
Maybe is related to output buffer, because [set_response function](https://github.com/chriskacerguis/codeigniter-restserver/blob/master/application/libraries/REST_Controller.php#L850) uses [response function](https://github.com/chriskacerguis/codeigniter-restserver/blob/master/application/libraries/REST_Controller.php#L761) with the continue parameter setting to true for continue running the script

**Comment by datenshi** [comment]
I found the solution to this issue. Related to the way we execute the shell script. If I redirect both stdout and stderr to /dev/null, then background it, everything works fine. 

Solution found here: [LINK](https://stackoverflow.com/questions/3819398/php-exec-command-or-similar-to-not-wait-for-result)

Thanks @fikoborquez for your suggestion.
