### ISSUE TITLE
inconsistent result with different format

### ISSUE THREAD

**Issue by oktapiana** [chriskacerguis/codeigniter-restserver#825]
i made a web service url with json format, it always return empty, because the model gave empty set.
But when i change the format to xml, it gave the correct result. it only happened to one url, the other are just fine.

**Comment by chriskacerguis** [comment]
could you post some sample code?

**Comment by oktapiana** [comment]
I wrote this in routes :
`$route['api/master/marketing/(:any)/(:num)/(:any)/(:num)(\.)([a-zA-Z0-9_-]+)(.*)'] = 'api/master/marketing/company/$1/pelaku/$2/notelp/$3/prjid/$4/format/$5$6'; 
`

to try this, You can fill pelaku with 0 and notelp with a number from the tm_karyawan table field kry_telp.

I Wrote this in Master controller (in folder api) :
` 	public function marketing_get()
	{ 	
        $jmldata=0;
		$pelaku = (int)$this->get('pelaku');
		$key = $this->get('notelp');
		if ($pelaku!==2) {
			// log_message('error', $key);
	        if ($key === NULL || !$this->_key_exists($key, $pelaku))
	        {
	            // It doesn't appear the key exists
	            $this->response([
	                'status' => FALSE,
	                'message' => 'Nomor telpon '.$key.' tidak terdaftar'
	            ], REST_Controller::HTTP_OK); // HTTP_UNAUTHORIZED (401) being the HTTP response code
	        }
	    } else {
            $this->response([
                'status' => FALSE,
                'message' => 'Prosedur lihat daftar marketing tidak boleh diakses'
            ], REST_Controller::HTTP_OK); // HTTP_UNAUTHORIZED (401) being the HTTP response code	    	
	    }
        $prjid = (int)$this->get('prjid');		
		$data['marketing'] = $this->master_models->marketing($prjid);		
		$jmldata=count($data['marketing']);
		if($jmldata>0) {
			$data['status']=TRUE;
			$data['message']='Data Terkirim';
			$this->set_response($data, REST_Controller::HTTP_OK); // OK (200) being the HTTP response code
		} else {
			$data['status']=FALSE;
			$data['message']='Data tidak ditemukan';
			$this->set_response($data, REST_Controller::HTTP_OK); 
		}
 	}

	private function _key_exists($key, $pelaku)
    {
        $data=$this->master_models->_key_exists($key, $pelaku);
		return $data;
    }
`

I Wrote this in my master_models ($GLOBALS['debe2'] is database connection) :

`    public function _key_exists($key, $pelaku)
    {
        if ($pelaku==0){
	        $data=$GLOBALS['debe2']
	            ->where('kry_telp', $key)
	            ->count_all_results('tm_karyawan') > 0;
        } else {
	        $data=$GLOBALS['debe2']
	            ->where('cus_hp', $key)
	            ->count_all_results('tm_customer') > 0;
        }
		return $data;
    }
`
and this :
`	function marketing($prjid) {

		$posts = array();
		$i=0;
		$GLOBALS['debe2']->select('*');
		$GLOBALS['debe2']->from('tm_karyawan');
		$GLOBALS['debe2']->where('prj_id',$prjid);
		$GLOBALS['debe2']->where('kry_status',1);
		$posts = $GLOBALS['debe2']->get();
		// log_message('error', 'host:'.$GLOBALS['debe2']->hostname.' database:'.$GLOBALS['debe2']->database. ' last_query:'.$GLOBALS['debe2']->last_query());
		// log_message('error', json_encode($posts->result()));
		// log_message('error', 'prj_id:'.$prjid);
		return $posts->result_array();
	}
`

here is my tabel ddl :

`CREATE TABLE `tm_karyawan` (
  `kry_id` bigint(20) NOT NULL,
  `kry_kd` varchar(50) DEFAULT NULL,
  `kry_nm` varchar(50) DEFAULT NULL,
  `kry_jbt` varchar(50) DEFAULT NULL,
  `kry_alm` varchar(200) DEFAULT NULL,
  `kry_telp` varchar(50) DEFAULT NULL,
  `kry_mail` varchar(50) DEFAULT NULL,
  `kry_npwp` varchar(50) DEFAULT NULL,
  `kry_atasan` bigint(20) DEFAULT NULL,
  `kry_add2` varchar(50) DEFAULT NULL,
  `kry_add3` varchar(50) DEFAULT NULL,
  `kry_add4` varchar(50) DEFAULT NULL,
  `kry_add5` varchar(50) DEFAULT NULL,
  `jab_id` bigint(20) DEFAULT NULL,
  `kry_kd_jab` varchar(6) DEFAULT NULL,
  `kry_update` datetime DEFAULT NULL,
  `org_id` bigint(20) DEFAULT NULL,
  `prj_id` bigint(20) DEFAULT NULL,
  `kry_status` smallint(6) DEFAULT NULL,
  `kry_group` varchar(50) DEFAULT NULL,
  `kry_aktif` smallint(6) DEFAULT NULL,
  PRIMARY KEY (`kry_id`),
  KEY `karyawan_idx` (`kry_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT;
`

**Comment by oktapiana** [comment]
Found the problem..
I was using latin1 latin1_swedish_ci to create the database, inserting the values using UTF8, read the data using latin1 latin1_swedish_ci in my CI config.. 
I changed the CI connection charset to UTF8 utf8_general_ci and the results appears as it was expected..

Sorry for giving You an headache for my mistake..
