### ISSUE TITLE
Fatal error in codeigniter 2.x

### ISSUE THREAD

**Issue by sulemankhan1** [chriskacerguis/codeigniter-restserver#826]
Showing the following error when using with codeigniter version 2 is there any way to use it with this version?

`Fatal error: Uncaught exception 'Exception' with message 'REST Server requires CodeIgniter 3.x' in C:\xampp\htdocs\sharmeen_foods\2016-17\application\libraries\REST_Controller.php:612 Stack trace: #0 C:\xampp\htdocs\sharmeen_foods\2016-17\application\libraries\REST_Controller.php(383): REST_Controller->preflight_checks() #1 C:\xampp\htdocs\sharmeen_foods\2016-17\system\core\CodeIgniter.php(615): REST_Controller->__construct() #2 C:\xampp\htdocs\sharmeen_foods\2016-17\index.php(189): require_once('C:\\xampp\\htdocs...') #3 {main} thrown in C:\xampp\htdocs\sharmeen_foods\2016-17\application\libraries\REST_Controller.php on line 612`

**Comment by sulemankhan1** [comment]
updated my question

**Comment by farukgaric** [comment]
Note: for 1.7.x support download v2.2 from Downloads tab

https://github.com/chriskacerguis/codeigniter-restserver/releases/tag/v2.2

**Comment by schester44** [comment]
Try an older version?
https://github.com/chriskacerguis/codeigniter-restserver/releases?after=v2.5
