### ISSUE TITLE
How to install with composer

### ISSUE THREAD

**Issue by sensugaz** [chriskacerguis/codeigniter-restserver#827]
i install library with composer and use the command "use Restserver\Libraries\REST_Controller;" But not found Format , this is message "Unable to load the requested class: Format" 

how to fix it ?

**Comment by Hanisch-IT** [comment]
This package has no namespace and its not possible to include it with composer.

I needed that also so i forked it and created a composer ready package. I Try to update it as often i can.

https://github.com/Hanisch-IT/codeigniter-restserver

**Comment by chriskacerguis** [comment]
@Hanisch-IT would you be willing to do a PR and add the name spacing code here, and then we can avoid confusing users?  (I **think** I saw a PR from you, but at the time CI didn't really have default composer support).

**Comment by Hanisch-IT** [comment]
@chriskacerguis you are right. I will create a PR the next days for the namespaces and some other small changes that are needed for composer.

For ci i used https://github.com/kenjis/codeigniter-composer-installer to install it with composer. Many tools, to use ci like software in 2017 :)

**Comment by sierrafayad** [comment]
i'll be waiting for this.

**Comment by Hanisch-IT** [comment]
Added a PR #832

**Comment by sensugaz** [comment]
Nice ~~
