### ISSUE TITLE
Problem function with CURL and file_get_contents

### ISSUE THREAD

**Issue by lucav90** [chriskacerguis/codeigniter-restserver#834]
Hi,

i have insert on your example.php file another function to create session for a user.

```
        $this->load->library('session');

        $this->load->model('sessions/mdl_sessions');

        /* SESSION STATIC VERSION */
        $session_data = array(
            'user_type' => '1',
            'user_id' => '1',
            'user_name' => 'Luca',
            'user_email' => 'prova@prova.it',
            'user_company' => ''
        );
        
        $this->session->set_userdata($session_data);

```

if i invoke it with browser (ex: http://www.site.it/index.php/api/example/session) works, the session is created and the user is logged.
if i use CURL or file_get_contents not works, the session is not created.

Why this?

I want to call login and sessions functions on my codeigniter project to login and start session.
How can i do this?

**Comment by lucav90** [comment]
You have a solution to solve?

Regards,

**Comment by chriskacerguis** [comment]
Sounds like an issue with your code not the rest code
