### ISSUE TITLE
Profiling in Rest Controller

### ISSUE THREAD

**Issue by zgmunshi** [chriskacerguis/codeigniter-restserver#839]
Hello,

I would like to congratulate you for providing such library to codeigniter community & enriching the power of codeigniter step further,

Coming to my question, as we all Profiling is one of the key feature of codeigniter and it helps a lot in development process but we are unable to use that feature if we are extending controller with REST_CONTROLLER.

Is there any way to use the profiling feature along with your library ? Kindly let us know.

Alternatively i have made changes to the library to work with profiling as follows:
1) Add boolean profiling parameter to config.php
2) Wrote a hook to enable /disable profile through out the application based on config parameter
3) Updated your "response" function in library REST_CONTROLLER.php to echo only received data without processing /adding any of the header's required for API result.

So this works when i enable the profiling and output the queries and benchmarking details for the specific function.

I would have done it a wrong way or might be this would be solution for it.

I request you put your thoughts and suggestions on it & let me know if there is any other way out.

Regards,
Zeeshan.

**Comment by Hanisch-IT** [comment]
Hi @zgmunshi,

feel free to suggest your changes via a pull request. I think its not intended to work with profiling yet.

Regrads

**Comment by zgmunshi** [comment]
Thanks for response @Hanisch-IT , Will do it. May i know why is it not intended ?

**Comment by Hanisch-IT** [comment]
Was not yet necessary i think.
Maybe you are the first one whos working with it and using this library.

**Comment by zgmunshi** [comment]
Ok,i will create the Pull request, kindly check it and do the needful as i think it might be useful for some one in future as it will also make REST library more open with CI framework.

Thanks.

**Comment by zgmunshi** [comment]
#854 PR Created. Can you please review it and merge with master.

Thanks.
Zeeshan.

**Comment by chriskacerguis** [comment]
merged.

**Comment by zgmunshi** [comment]
Should i create different PR for master ?

**Comment by zgmunshi** [comment]
#855 Kindly merge with master

**Comment by williamabbott** [comment]
How to see profiling results?

**Comment by zgmunshi** [comment]
@williamabbott you need to enable profiling to view the profiling result. https://github.com/chriskacerguis/codeigniter-restserver#profiling
