### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jamesaxl** [chriskacerguis/codeigniter-restserver#840]
Hello, thank you very much for this tools.
After a Test I get an error:
Fatal error: Call to a member function factory() on null in /application/libraries/REST_Controller.php on line 857

**Comment by lucasmobi** [comment]
Same here.

**Comment by farukgaric** [comment]
Do you guys use it with composer or without?

**Comment by jamesaxl** [comment]
no, without composer

**Comment by Hanisch-IT** [comment]
I will investigate a bit, give me some time

**Comment by Hanisch-IT** [comment]
Created a PR where i fix that issue #842
