### ISSUE TITLE
Content type issue

### ISSUE THREAD

**Issue by MasonFI** [chriskacerguis/codeigniter-restserver#841]
api.example.com/v1/users?format=csv works
api.example.com/v1/users.csv produces 404 error
api.example.com/v1/users/format/csv produces 404 error

Should they work out of box? It wouldn't matter, but with format=csv parameter the downloaded file is without .csv extension and I haven't found the way to define filename or add .csv to the downloaded filename.

**Comment by Hanisch-IT** [comment]
Hi @MasonFI,

it should work out of the box. I tested it with a clean install and all 3 links worked for me.
Maybe a mod_rewrite problem?

**Comment by MasonFI** [comment]
> server {
>         listen 80;
>         listen [::]:80;
>         server_name api.example.local;
>         return 301 https://$host$request_uri;
> }
> 
> server {
>     listen 443 ssl http2;
>     listen [::]:443 ssl http2;
> 
>     root /var/www/api.example.local/codeigniter/public;
>     index index.php index.html index.htm;
> 
>     server_name api.example.local;
> 
>     ssl_certificate           /etc/nginx/cert.crt;
>     ssl_certificate_key       /etc/nginx/cert.key;
> 
>     ssl on;
>     ssl_session_cache  builtin:1000  shared:SSL:10m;
>     ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
>     ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
>     ssl_prefer_server_ciphers on;
> 
>     location / {
>         try_files $uri $uri/ /index.php?$args;
>     }
> 
>     location ~ \.php$ {
>         try_files $uri =404;
>         fastcgi_split_path_info ^(.+\.php)(/.+)$;
>         fastcgi_pass unix:/var/run/php/php7.1-fpm.sock;
>         fastcgi_index index.php;
>         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
>         include fastcgi_params;
>     }
> 
>     error_log /var/log/nginx/api.example.local.error.log;
>     access_log /var/log/nginx/api.example.local.access.log;
> }

Thats my nginx conf for site. No .htaccess is in use. Can you see the problem with it?

**Comment by Hanisch-IT** [comment]
Please have a look

http://www.farinspace.com/codeigniter-nginx-rewrite-rules/

Its not a issue of this project

**Comment by Hanisch-IT** [comment]
@chriskacerguis, this issue is ready to close, because its not a problem with the restserver.
