### ISSUE TITLE
Improve working with version-tags

### ISSUE THREAD

**Issue by Hanisch-IT** [chriskacerguis/codeigniter-restserver#843]
Hi @chriskacerguis,

i would recommend to work more with the version tags. So its better and easier to work with this package.

Braking Changes: 1.x.x -> 2.x.x
Features: 1.1.x -> 1.2.x
Bugfixes: 1.1.0 -> 1.1.1

So i can for example include this library via composer and can only allow bugfix updates automaticly.

Tell me what you think about this.

Regrads

**Comment by chriskacerguis** [comment]
Yeah, I agree.  Good call with that...you may have to remind me to bump the version :)
