### ISSUE TITLE
Add AUTHORS

### ISSUE THREAD

**Issue by chriskacerguis** [chriskacerguis/codeigniter-restserver#849]
Need to add AUTHORS file to keep track of who has helped out.

@Hanisch-IT would you mind creating this and add yourself as the first person, I really appreciate all your bugfixes!!!

**Comment by Hanisch-IT** [comment]
Hi @chriskacerguis, 

thank you, i realy like to develop a bit within this project :)

What do you have in mind for this file? 
Normaly you write down there your guidelines for contributers (https://help.github.com/articles/setting-guidelines-for-repository-contributors/)
Template like: https://gist.github.com/PurpleBooth/b24679402957c63ec426

Or do you want to name all your contributers in this file?

**Comment by chriskacerguis** [comment]
I guess that CONTRIBUTORS is not the best nomenclatures.  I was thinking something like this:

https://github.com/ManageIQ/manageiq/blob/master/AUTHORS

Where we can give credit to all those who have contributed to this project.

**Comment by chriskacerguis** [comment]
Thanks @Hanisch-IT

**Comment by Hanisch-IT** [comment]
Your welcome mate
