### ISSUE TITLE
Unable to locate the specified class: Session.php

### ISSUE THREAD

**Issue by bakasajoshua** [chriskacerguis/codeigniter-restserver#851]
Just loaded the codeigniter-restserver to an existing project that is using the session class then I get this error. It comes when I autoload the session library.

**Comment by farukgaric** [comment]
Hi @bakasajoshua 

You loaded it with composer?
If yes, then you changed composer_autoload in config.php like this:
`$config['composer_autoload'] = realpath(APPPATH . '../vendor/autoload.php');`
Right?

You loaded your library in config/autoload.php?
If you did as I said and you still have a bug then please give us your directory structure.

**Comment by bakasajoshua** [comment]
I have loaded it in config/autoload.php

**Comment by bakasajoshua** [comment]
Sorry I had loaded in the child class like so (require BASEPATH . 'libraries/REST_Controller.php';) and got the session error.

When I changed to config/autoload.php it gave an error "Cannot instantiate abstract class REST_Controller:

**Comment by farukgaric** [comment]
1. Step
In application/config/config.php set composer_autoload path like this:
{code:php}
$config['composer_autoload'] = realpath(APPPATH . '../vendor/autoload.php');
[code}

2. Step
Load all other codeigniter's libraries in application/config/autoload.php
{code:php}
$autoload['libraries'] = array('database', 'session');
[code}

**Comment by Hanisch-IT** [comment]
The error 

> Cannot instantiate abstract class REST_Controller:

says, you dont extend the class, you try to use it.

Write your own Controller and only extend REST_Controller like:

```php

class My_Rest_Controller extends REST_Controller 
{
...
}
```

**Comment by bakasajoshua** [comment]
I have not used composer

**Comment by farukgaric** [comment]
Ok :)

So, you copied REST_Controller.php and Format.php in application/libraries
and rest.php in application/config?

If yes, then add this on top of your controller:
```php require APPPATH . 'libraries/REST_Controller.php';``` 
After this you can extend REST_Controller and use all features.
```php
class My_Rest_Controller extends REST_Controller 
{
...
}
```

**Comment by bakasajoshua** [comment]
@farukgaric  I have done this and have also autoload the session library that is why am getting the error "Unable to locate the specified class: Session.php". When I do not autoload the session class it works fine.

But I need to autoload the session library for the rest of the application to work.

**Comment by farukgaric** [comment]
Ok. Did you try to load it manually in your controller
```php
$this->load->library('session');
```

**Comment by bakasajoshua** [comment]
@farukgaric Yes I did, when I do, it works but cannot load my other custom libraries.

**Comment by Hanisch-IT** [comment]
@farukgaric this sounds not like a probem with the Restserver. This sounds more like a problem with your codeigniter installation/libraries.

**Comment by bakasajoshua** [comment]
@farukgaric @Hanisch-IT I created my own controller that extends the CI_Controller which is loaded by the entire application apart from the API then I loaded the libraries there and it has worked like a charm :)

**Comment by Hanisch-IT** [comment]
@chriskacerguis, this issue is ready to close :)

**Comment by dbudihartono** [comment]
bagaimana cara mengatasi hal ini? Unable to locate the specified class: Session.php
saya memakai versi 18.10 dan berusaha menambahkan update rilis pasca 2.12 (opensid rbac)
salam..

**Comment by anjaneyulugulla** [comment]
any solution?

**Comment by ib-ganz** [comment]
any solution?

@dbudihartono udah ketemu gan?

**Comment by haniefhan** [comment]
the problem occur because we use CI + HMVC
this is the solution
- open file REST_Controller.php
- change "abstract class REST_Controller extends CI_Controller" to "abstract class REST_Controller extends MX_Controller"
- save the file, done!

@dbudihartono , @ib-ganz , @anjaneyulugulla 
masalah ini terjadi karena menggunakan CI + HMVC
solusinya begini:
- buka file REST_Controller.php
- ubah "abstract class REST_Controller extends CI_Controller" ke "abstract class REST_Controller extends MX_Controller"
- save, selesai!

**Comment by arminamirinasab** [comment]
I have the same problem :(
