### ISSUE TITLE
Error when limit reached

### ISSUE THREAD

**Issue by Midelius** [chriskacerguis/codeigniter-restserver#853]
I have exceeded the allowed limit.

REST_CONTROLLER LINE  748
`if ($this->config->item('rest_enable_limits') && $this->_check_limit($controller_method) === FALSE)`
`{`   
`$response=[$this->config->item('rest_status_field_name') => FALSE, $this->config->item('rest_message_field_name') => $this->lang->line('text_rest_api_key_time_limit')];`
              
  `$this->response($response, self::HTTP_UNAUTHORIZED);`
              
  `$this->is_valid_request = false;`
           ` }`
The method 'response' updates the rtime and the code status on de Table of logs, but I dont have insert before, and  I get and error.  I dont have `$this->_insert_id`

I added   it and i solved it.

` if ($this->config->item('rest_enable_logging') && $log_method)
            {
                $this->_log_request(0);
            }`
 before 
` $this->response($response, self::HTTP_UNAUTHORIZED);`

Thanks

**Comment by Midelius** [comment]
I found this error in another part of code. I Changed 

>_log_response_code

 and 

> log_access_time

`  protected function _log_response_code($http_code)
    {
        
         if ($this->_insert_id=='')
       {
	   	
	   	 $this->_log_request(0);
	   }
        $payload['response_code'] = $http_code;

        return $this->rest->db->update(
            $this->config->item('rest_logs_table'), $payload, [
            'id' => $this->_insert_id
        ]);
    }`

**Comment by Hanisch-IT** [comment]
Hi @Midelius,

may you want to create a pull request with your changes?
