### ISSUE TITLE
Update or remove develop branch

### ISSUE THREAD

**Issue by Hanisch-IT** [chriskacerguis/codeigniter-restserver#857]
Hi @chriskacerguis,

to have a clean develop state you should update the develop branch to the master or you should delete it and create a clean one.

But i dont think that you need a develop branch in this project. For this you have the versioning and currently all the changes are directly merged into master.

If you want to work with a develop branch you should change the workflow a bit
- disallow commits to master
- only allow commits/prs to develop
- only allow branches to be merged, no single commits
- only allow branches to be merged to master, dont allow to merge develop direct into master (or you want to have a deployment day where all the changes in develop will be merged into master)

For example: http://nvie.com/posts/a-successful-git-branching-model/

Regards

**Comment by chriskacerguis** [comment]
agree.  I'll delete it.
