### ISSUE TITLE
Cross Origin Resource Sharing Error in POST Method

### ISSUE THREAD

**Issue by priyaragavan** [chriskacerguis/codeigniter-restserver#861]
I am using this repo for Rest API with X-API-KEY. Using the following code to access the Rest API method,

```
authenticate(user):Observable<any[]>{
let _authenticateUrl = 'http://localhost/w2p_ci_rest_api/index.php/w2p/Authentication_controller/user_authenticate';
    return this._http.post(_authenticateUrl,JSON.stringify(user),{ headers: this.header})
		.map((response:Response)=><any[]>response.json())
		.do(data=>console.log('All: '+ JSON.stringify(data)))
    .catch(this.handleError);
  }
```

And the Rest API method is as follows, 

```
public function user_authenticate_post()
    {
        
        $user_name = $this->post('user_name');
        $user_password = $this->post('user_password');
        if ($user_name != '' && $user_password != '')
        {
            $result = $this->am->userAuthenticate($user_name,$user_password);
 
            if ($result) {
                //store session 
                $user_data = array(    
                        'user_id'     => $result->user_id,
                        'user_name'   => $result->user_name, 
                        'user_phone' => $result->user_phone,                            
                        'user_email'  => $result->user_email,
                        'user_password'=> $result->user_password,
                        'is_logged_in'=> true,
                        'session_id'  =>  random_string('unique')
                     );
                    
                    $this->session->set_userdata('success', "Success Login");
                    $this->session->set_userdata($user_data);                    
                    $this->am->sessin_insert();

                $this->response([
                'status' => TRUE,
                'message' => 'Success',
                'data'   => $result,
                'session'=> $this->session->userdata()
                ], REST_Controller::HTTP_NOT_FOUND); // NOT_FOUND (404) being the HTTP response code
               
            } 
            else {
                 $this->response(array(
                'status'  => FALSE,
                'message' => 'Invalid Credential',
                ));
            }
        }
        else{
            $this->response([
            'status' => FALSE,
            'message' => 'Credential Required! Please Enter.'
            ], REST_Controller::HTTP_NOT_FOUND);
        }
    }
```

When login button triggered, Service Call make an XHR request to the Rest API, but i don't know why the two XHR there in Network tab, one for Option method and one for Post method. The OPTION method success with given URL, but the POST method failed to load the resource with the same  URL of OPTION method.

In rest.php config file i set to as follows,
 
```
$config['check_cors'] = TRUE;
$config['allowed_cors_headers'] = [
  'X-API-KEY',
  'Origin',
  'X-Requested-With',
  'Content-Type',
  'Accept',
  'Access-Control-Request-Method'
];
$config['allow_any_cors_domain'] = TRUE;
```

I got the following result in console, 
![console error](https://user-images.githubusercontent.com/30138058/31822176-70e58736-b5c5-11e7-8a6e-d20a8cfce03c.PNG)

and in Network tab,

Status Code:200 OK
Request Method:OPTIONS ,

![xhr_method_option](https://user-images.githubusercontent.com/30138058/31822212-a14fff46-b5c5-11e7-959f-348c22f12f71.PNG)

and in Network tab,

Status Code:404 Not Found
Request Method:POST 

![xhr_method_post](https://user-images.githubusercontent.com/30138058/31822295-e83e46b0-b5c5-11e7-84f4-ef12b3766ab0.PNG)

Request Method:POST with result, 
![xhr_method_post_with_results](https://user-images.githubusercontent.com/30138058/31822315-f9e30e50-b5c5-11e7-85ad-d9552c48b3d2.PNG)

Anything else is wrong with me?

**Comment by farukgaric** [comment]
If your controller is named Authentication_controller try to rename it to Authentication and then change your url to this:
http://localhost/w2p_ci_rest_api/index.php/w2p/authentication/user_authenticate

Keep in mind, your controller name and filename should be the same and url is with lowercase!

**Comment by priyaragavan** [comment]
Sorry farukgaric, Still i got same results.

**Comment by priyaragavan** [comment]
I forget to tell you something, Please consider the fourth image "POST with result",
Rest API return response with that URL but, Why displays it as error in Network tab.

**Comment by farukgaric** [comment]
```php 
<?php
 $this->response([
                'status' => TRUE,
                'message' => 'Success',
                'data'   => $result,
                'session'=> $this->session->userdata()
                ], REST_Controller::HTTP_NOT_FOUND); // NOT_FOUND (404) being the HTTP response code`

There you need HTTP_OK instead of HTTP_NOT_FOUND

Pay attention to response codes: https://github.com/chriskacerguis/codeigniter-restserver/blob/master/application/libraries/REST_Controller.php#L23

**Comment by priyaragavan** [comment]
Oh, I miss it. Thank you @farukgaric.
