### ISSUE TITLE
How to use $config['rest_auth'] = 'session' ?

### ISSUE THREAD

**Issue by priyaragavan** [chriskacerguis/codeigniter-restserver#862]
In Rest API, its give the following results, while config as $config['rest_auth'] = 'session'  and $config['auth_source'] = 'user_data';

![unauthorized_error](https://user-images.githubusercontent.com/30138058/31852794-f2e77150-b69b-11e7-8eba-991c30696a3b.PNG)

How to maintain session in Restserver API?
Please give some valid suggestion.

**Comment by Hanisch-IT** [comment]
What do you expect with `$config['auth_source'] = 'user_data'`

The config examples gives only `ldap`, `library` and empty.

`session` is useful if you only want to make ajax calls within the same domain.

**Comment by priyaragavan** [comment]
I want a login system for Angular 2 app, so i require session for authenticated user to allow Rest API call.
I have refer many resources, nothing else is solve my problem. In documentation, 
**Note: If 'rest_auth' is set to 'session' then change 'auth_source' to the name of the session variable**
mentioned, so i put the session variable as  follows , **$config['auth_source'] = 'user_data'**  in the rest.php file.

but while checking, it showed as "unauthorized".

How to solve this?

**Comment by Hanisch-IT** [comment]
And you'd set `$_SESSION['user_data']`or `$this->session->userdata("user_data", "...")` before you did the call?

**Comment by farukgaric** [comment]
I see in his latest issue #861 that he don't set key for his session, he just set user data with his user details.
I will recommend using library authentication to perform this or even better JWT instead of session.

**Comment by priyaragavan** [comment]
I think the Rest API, look for the session variable before the authentication. So it gives result as "Unauthorized". Any solutions for this?

**Comment by Hanisch-IT** [comment]
You shouldnt use session to authenticate against the rest api.
You should use library to build your own authentication against the rest api.

If you use session the rest only checks if `$_SESSION['user_data']` is set. There is no validation of user oder password.

**Comment by priyaragavan** [comment]
Am i misunderstood the documentation? Then what does the document coming to tell,

/*
|--------------------------------------------------------------------------
| REST Login
|--------------------------------------------------------------------------
|
| Set to specify the REST API requires to be logged in
|
| FALSE     No login required
| 'basic'   Unsecured login
| 'digest'  More secured login
| 'session' Check for a PHP session variable. See 'auth_source' to set the
|           authorization key
|	
*/
`$config['rest_auth'] = 'session';`

/*
|--------------------------------------------------------------------------
| REST Login Source
|--------------------------------------------------------------------------
|
| Is login required and if so, the user store to use
|
| ''        Use config based users or wildcard testing
| 'ldap'    Use LDAP authentication
| 'library' Use a authentication library
|
| Note: If 'rest_auth' is set to 'session' then change 'auth_source' to the name of the session variable
|
*/
`$config['auth_source'] = 'session_variable';`

**Comment by farukgaric** [comment]
Let's think about your problem:
You want to login to be able to use other endpoints which are secured.
First thing that I get on my mind is to create library for authentication.
In rest.php you should define class and method:
```
$config['auth_library_class'] = '';
$config['auth_library_function'] = '';
```
REST_Controller expect TRUE or FALSE from this method. That means, is your request approved to access your endpoint or not.
I understand that you can't access your authentication endpoint because you are not logged in BUT
In your newly created library and method you can check your request and return TRUE if it is e.g. /auth/login
If url is not your "login url" then check is e.g. JWT token valid and refresh token.
If token is valid, refresh them and return true i is not valid then return FALSE.

To use JWT just load this with composer: https://github.com/firebase/php-jwt
All methods are ready to use.

Simple, isn't?

**Comment by priyaragavan** [comment]
@farukgaric, Thank You for your help and kindness mind.

**Comment by farukgaric** [comment]
P.S. I forget to tell you that you have to set token in response of your login endpoint and store it in locaStorage in your Angular app. In Angular app create interceptor which will provide token on every request. If you google little bit you can find amazing tutorials how to implement JWT with Angular. Good luck!

**Comment by priyaragavan** [comment]
Oh, Yeah. Thank You.
