### ISSUE TITLE
OPTIONS request is true, but the GET request doesn't send

### ISSUE THREAD

**Issue by victorylee** [chriskacerguis/codeigniter-restserver#863]
Thanks for the library.
I add some code in REST_Controller.php,  for deal with the OPTIONS problem
 public function index_options()
    {
        return $this->set_response(null, 200);
    }

OPTIONS request is true, but the GET request doesn't send, I don't know why

**Comment by Hanisch-IT** [comment]
For fixing the CORS problem, add that to your Rest-Controller

```php
class My_Rest_controller extends REST_Controller
{
    public function __construct($config = 'rest')
    {
        parent::__construct($config);

        header('Access-Control-Allow-Origin: *');
        header("Access-Control-Allow-Headers: X-API-KEY, Origin, X-Requested-With, Content-Type, Accept, Access-Control-Request-Method, Authorization");
        header("Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE");
        $method = $_SERVER['REQUEST_METHOD'];
        if ($method == "OPTIONS") {
            die();
        }
    }
}
```

Because you need to react to ALL OPTION requests, not only to index_options.

I will create a PR the next days to include this in the REST_Controller but without the header parts.

**Comment by victorylee** [comment]
Ok, thank you very much.

**Comment by El-Shaarawy** [comment]
Hi @Hanisch-IT , I have enabled CORS in rest.php file in config folder and I added the index_options() to REST_Controller.php and when I curl my API on localhost it always returns method not allowed , although it is working with POSTman and Restlet chrome extensions.

**Comment by NanoDev777** [comment]
@Hanisch-IT implemented your solution and worked without problems, however I only had one method in my controller with the name index_get, now I added another method with the name cities_get when trying these 2 in my aplication frontend with the first method not there problems but the second one throws me an error in console "404 (Not Found) No 'Access-Control-Allow-Origin'", I find it strange a 404 error related to CORS, I have tried both routes of my API with POSTMAN and they work correctly .. Any idea what it could be??? @Hanisch-IT

**Comment by jawad-aziz-farhad** [comment]
I was having a weird issue, get requests were working fine but post request returning error of **Method not allowed.** After debugging the issue I found out that preflight request is causing this issue which is an options request.
Thanks to @Hanisch-IT , I used this and now its working fine.

**Comment by upardhi** [comment]
> For fixing the CORS problem, add that to your Rest-Controller
> 
> ```
> class My_Rest_controller extends REST_Controller
> {
>     public function __construct($config = 'rest')
>     {
>         parent::__construct($config);
> 
>         header('Access-Control-Allow-Origin: *');
>         header("Access-Control-Allow-Headers: X-API-KEY, Origin, X-Requested-With, Content-Type, Accept, Access-Control-Request-Method, Authorization");
>         header("Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE");
>         $method = $_SERVER['REQUEST_METHOD'];
>         if ($method == "OPTIONS") {
>             die();
>         }
>     }
> }
> ```
> 
> Because you need to react to ALL OPTIONS requests, not only to index_options.
> 
> I will create a PR the next days to include this in the REST_Controller but without the header parts.

YOU SAVED MY DAY

**Comment by lsalazarm99** [comment]
This is still a problem. Since my `.htaccess` already has CORS settings, I just had to include this in my constructor:
```php
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    die();
}
```

It's ok, but is it the way it should work? Or is it a workaround?

**Comment by DmitryAdam** [comment]
> For fixing the CORS problem, add that to your Rest-Controller
> 
> ```
> class My_Rest_controller extends REST_Controller
> {
>     public function __construct($config = 'rest')
>     {
>         parent::__construct($config);
> 
>         header('Access-Control-Allow-Origin: *');
>         header("Access-Control-Allow-Headers: X-API-KEY, Origin, X-Requested-With, Content-Type, Accept, Access-Control-Request-Method, Authorization");
>         header("Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE");
>         $method = $_SERVER['REQUEST_METHOD'];
>         if ($method == "OPTIONS") {
>             die();
>         }
>     }
> }
> ```
> 
> Because you need to react to ALL OPTIONS requests, not only to index_options.
> 
> I will create a PR the next days to include this in the REST_Controller but without the header parts.

Hi, Im new in this programming world,
how to include it on the global files, so every controller will have this method
