### ISSUE TITLE
api access using android

### ISSUE THREAD

**Issue by d33pak-s1ngh** [chriskacerguis/codeigniter-restserver#864]
i want to use this rest server api in my codeigniter project where user can access apis from android or iphone or web based application with login credential.
so i need to know following
is there any way to get token based authentication for users to access api?
is there any example available which shows how to access these rest api's in android with user name and password?

**Comment by Hanisch-IT** [comment]
Hi @d33pak-s1ngh, 

yes you can get a token based authentikation. You can customize your authentication with a custom authentication library. 
A other posibility is, that you dont use rest servers authentication processes and create your own.

For example, you can extend the rest server like: https://stackoverflow.com/questions/43406721/token-based-authentication-in-codeigniter-rest-server-library

Or you can use JWT to do it: https://github.com/ParitoshVaidya/CodeIgniter-JWT-Sample

Google a bit and you will find many solutions.
