### ISSUE TITLE
Parsing Error:  syntax error, unexpected '[' in libraries/REST_Controller.php 

### ISSUE THREAD

**Issue by sondauta2** [chriskacerguis/codeigniter-restserver#865]
Hi, how resolve this error?

*********************************************
A PHP Error was encountered
Severity: Parsing Error
Message: syntax error, unexpected '['
Filename: libraries/REST_Controller.php
Line Number: 169
Backtrace:
*********************************************

I use PHP v5.3.19 and can't update.  Other version of REST_Controller.php?

Please!!!!

**Comment by chriskacerguis** [comment]
You would need to use an older version of CI.  The latest PHP required is 5.4

What version of CI are you using?

**Comment by sondauta2** [comment]
I use CI 3.1.4

**Comment by sondauta2** [comment]
Any idea?   wich version of CI is compatible with PHP 5.3.19 .... please

**Comment by chriskacerguis** [comment]
2.2 will work

https://github.com/chriskacerguis/codeigniter-restserver/releases/tag/v2.2
