### ISSUE TITLE
file upload via api

### ISSUE THREAD

**Issue by sowiso** [chriskacerguis/codeigniter-restserver#868]
Hello,

we have a case where we want to allow users to upload files via the api.
Is this at all possible with the current restserver? If not, do you have any ideas on how to do this?

thanks

**Comment by Hanisch-IT** [comment]
Hi,

It should work with post, you can access the `$_FILE` variable in `your file_upload_post()` function in the rest controller.
You can also upload files via Raw data (like base64 encoded).


Regards

**Comment by sowiso** [comment]
Thanks, I've got it going now!
