### ISSUE TITLE
Encountered a fatal error when performing data migration!

### ISSUE THREAD

**Issue by xiaowei-vip** [chriskacerguis/codeigniter-restserver#875]
CI:3.1.6
PHP:7.2

```
Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'VARCHAR() NOT NULL UNIQUE, `level` INT(2) NOT NULL, `ignore_limits` TINYINT(1)' at line 4

CREATE TABLE `www_` ( `id` INT(11) NOT NULL AUTO_INCREMENT, `user_id` INT(11) NOT NULL, VARCHAR() NOT NULL UNIQUE, `level` INT(2) NOT NULL, `ignore_limits` TINYINT(1) NOT NULL DEFAULT 0, `is_private_key` TINYINT(1) NOT NULL DEFAULT 0, `ip_addresses` TEXT NULL, `date_created` INT(11) NOT NULL, CONSTRAINT `pk_saas_` PRIMARY KEY(`id`) ) DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci

Filename: migrations/20170706030520_create_table_api_keys.php

Line Number: 54
```

should be config_item can not get to the value？

**Comment by xiaowei-vip** [comment]
After a series of inspections,
I found that the above error is that  not load **config / rest** and **db_helper** at the time of migration.

But also found a new problem,
Part of the statement in the migration file when **dbprefix** is set does not recognize **dbprefix**, cancels **dbprefix** settings everything is fine.

I think there should be corresponding instructions, this can help to other people.

**Comment by chriskacerguis** [comment]
this should address this issue: https://github.com/chriskacerguis/codeigniter-restserver/pull/897
