### ISSUE TITLE
Consuming the API with JavaScript

### ISSUE THREAD

**Issue by kasperpeulen** [chriskacerguis/codeigniter-restserver#876]
I want to allow users that are logged in my codeigniter application to consume the API using javascript ajax calls.

I'm not sure how to set this up. I want by default have the client to provide an API key, but when the user is logged in, in the web interface, I want to skip this step.

Something like this:
https://laravel.com/docs/5.5/passport#consuming-your-api-with-javascript

**Comment by Hanisch-IT** [comment]
Im not sure how we can help you. We dont provide you a full example for authentication. If you want to use rest server only for logged in users you need to authenticate the user. You can set it via session (check of session valid) on the same server or via the request Header.

For example you can use jwt for authentication https://github.com/ParitoshVaidya/CodeIgniter-JWT-Sample
