### ISSUE TITLE
$this->allow Still TRUE when Username/Password are Wrong?

### ISSUE THREAD

**Issue by VikR0001** [chriskacerguis/codeigniter-restserver#877]
With `$config['rest_auth']` set to `basic`, and the wrong password sent, `$this->allow` appears to be still set to 1, with the result that data is returned as if the password were correct.

**Comment by Flor27** [comment]
I have similar problem (authentication handling problem), with followin settings (some are omited) :
`$config['rest_auth'] = 'basic';
$config['allow_auth_and_keys'] = TRUE;
$config['auth_library_class'] = '';
$config['auth_library_function'] = '';
$config['rest_valid_logins'] = [
    'some_user' => 'some password',
    'another_user' => 'another password'
];
$config['rest_enable_keys'] = TRUE;
$config['rest_enable_logging'] = TRUE;`

In logs table, for each REST server access, 2 lines are created as follow (exported here as PHP array) : 
`$logs = array(
	array( // row #0
		'id' => 34,
		'uri' => 'Endpoint/Method',
		'method' => 'get',
		'params' => '{"format":"json","some_parameter":"some_value","Authorization":"Basic [some hash]","User-Agent":"[some user agent]","Host":"[some hostname]","Accept":"*\\/*","X-API-KEY":"[my API key]","Connection":"close"}',
		'api_key' => '',
		'ip_address' => '[an IP address]',
		'time' => 1520263477,
		'rtime' => NULL,
		'authorized' => '0',
		'response_code' => 403,
	),
	array( // row #1
		'id' => 35,
		'uri' => 'Endpoint/Method',
		'method' => 'get',
		'params' => '{"format":"json","some_parameter":"some_value","Authorization":"Basic [some hash]","User-Agent":"[some user agent]","Host":"[some hostname]","Accept":"*\\/*","X-API-KEY":"[my API key]","Connection":"close"}',
		'api_key' => '',
		'ip_address' => '[an IP address]',
		'time' => 1520263477,
		'rtime' => 0.068604,
		'authorized' => '1',
		'response_code' => 200,
	),
);`

Same result any time (403 then 200 response in logs table).
I got one line (200) only if I put $config['rest_enable_keys'] = FALSE; in rest.php

**Comment by Flor27** [comment]
Also, any API KEY I'm providing thru rest client will allow access, whatever it matches the ones in rest_server_api_keys table.

**Comment by chriskacerguis** [comment]
I think that I have fixed this.  Please give it a try and if it is still not working please add a new issue.
