### ISSUE TITLE
Inappropriate property and method naming conventions. 

### ISSUE THREAD

**Issue by axelcho** [chriskacerguis/codeigniter-restserver#880]
It looks like you are using a protected property 'response', and a public method 'response' in the same class. Same with 'request'. 

It makes codebase confusing. 

Renaming them would not be that difficult. 

Also, naming a property/method with such common terms can lead to unexpected problems. We are using http (or other scheme) request and response everywhere.

**Comment by chriskacerguis** [comment]
I look forward to your PR ;)

**Comment by chriskacerguis** [comment]
No response.  Closing.
