### ISSUE TITLE
Including the library?

### ISSUE THREAD

**Issue by davecoffin** [chriskacerguis/codeigniter-restserver#883]
Hey there, I've used this on other projects but on a recent project I did a composer install and I'm not sure how to include it. In my other projects I do 
`require APPPATH . '/libraries/REST_Controller.php';`
But theres no such file in libraries after a composer install. I thought autoload would take care of it all, but REST_Controller is not available from a controller I create.

**Comment by llKoull** [comment]
hey!

same problem here :S

**Comment by davecoffin** [comment]
No I haven't I ended up just copying REST_Controller.php from the libraries folder from another project.

**Comment by farukgaric** [comment]
We discussed here:
https://github.com/chriskacerguis/codeigniter-restserver/issues/859
