### ISSUE TITLE
What is use of limit method?

### ISSUE THREAD

**Issue by iranappo** [chriskacerguis/codeigniter-restserver#884]
Hello
I saw limit method with $this->method['name']['limit'] = 12;
What is it?
Limit each user for method?or limit all user to this method?
Example if i set it to 5,this is means that only 5 user can use this method
Thanks

**Comment by Hanisch-IT** [comment]
You can limitate how many calls a IP_ADDRESS / API_KEY / METHOD_NAME / ROUTED_URL can do a request in a specified time interval, default 1 hour.
You can specify it in the config `rest_limits_method`

**Comment by iranappo** [comment]
Please excuse me i got confused
We limit a user or limit a function for all user?
Sorry

**Comment by Hanisch-IT** [comment]
You can limit several things

You can limit the numer of calls per hour for an ip (all methods)
Or
You can limit the count of requests for a special call (all ips)
Or
You can limit the count of calls for an api key

**Comment by iranappo** [comment]
@Hanisch-IT Thank you so much
