### ISSUE TITLE
Unable to set response code 

### ISSUE THREAD

**Issue by sachinsha** [chriskacerguis/codeigniter-restserver#885]
When i upload the project at unix hosting server. It gives  http code 200 in response. plz tell how i can set the response code. i tried this $this->response(null,201);

**Comment by Hanisch-IT** [comment]
That should be all the magic. Check the http header for the code. Should be 201

**Comment by Shoury17** [comment]
#Hanisch-IT ,
we tried lot but everytime its return 200 status code, but the surprise thing is that when the error occurs in the code then same 200 status code comes instead of 500.
there is any possiblity that is from hosting side because at localhost its work fine

**Comment by Hanisch-IT** [comment]
Mh sorry, i could not help you. In my rest api the header code is set correct.

Can you give a full code sample?

**Comment by chriskacerguis** [comment]
No response from @Shoury17
