### ISSUE TITLE
auth_override

### ISSUE THREAD

**Issue by ashtonsmith** [chriskacerguis/codeigniter-restserver#888]
Hi.
First of all, Great work on this, it's significantly reduced our workload.

Just a question about the auth_override options. we are using session based auth, and I've used the auth_override option to allow access to the login endpoint without authentication as per below, and this works perfectly.
$config['auth_override_class_method']['login']['*'] = 'none';

for other controllers, we are using( as mentioned) session based auth as per below
$config['rest_auth'] = 'session';
and setting the auth source to the session variable "authorized' as per the below:
$config['auth_source'] = 'authorized';

my issue is, I would like to be able to restrict an entire controller "/admin" to be limited to administrators, and I was thinking of a way to be able to use similar functionality to the auth_override.
Is there current functionality to allow checking a different session variable with the auth_override?

If not, ill just put something in the constructor, but this would be tidier if its there.

Thanks

**Comment by MikeDaniel18** [comment]
I too am interested in this. Currently I'm parsing the digest info and finding out which user is logged in, but this is a far from ideal situation.
