### ISSUE TITLE
Rest Server on php 5.2.9

### ISSUE THREAD

**Issue by 50l3r** [chriskacerguis/codeigniter-restserver#889]
I guys

I have a problem. I need to run codeigniter-restserver on PHP 5.2.9 and i have some copatibility errors like CONST.

There's a version with php 5.2 compatibility?

**Comment by Hanisch-IT** [comment]
You should not run php 5.2, it is not maintained any more

http://php.net/supported-versions.php.

You can check older releases for php 5.2 support but they will not support codeigniter 3 i think.

https://github.com/chriskacerguis/codeigniter-restserver/releases/tag/2.6.1 that is a release for php 5.2 but its very old (like php 5.2).

**Comment by 50l3r** [comment]
It's a headache but i need to do it because i share server with older apps that i do not maintain.

i try 2.5 but 2.6 works well.

**Comment by chriskacerguis** [comment]
Sorry, I can't in good conscience support a PHP version that doesn't get security updates.
