### ISSUE TITLE
Call another function inside a rest function

### ISSUE THREAD

**Issue by jkkenzie** [chriskacerguis/codeigniter-restserver#894]
Say i have a function POST and a function call within it like this:
`public function create_post(){
    #call function x e.g.
    $this->nowCreateit()
}`

Is it good practice to create a private function within the same class without _get, _post or _put ends, so that additional executions are outside the main functions?

**Comment by Hanisch-IT** [comment]
Yes you can do that - it depends on how you code, if you have a src structure its maybe better to call the service which is responsible for the rest. 
But if you working without those rules you can create private methods in your rest controller, its a regular practice.
