### ISSUE TITLE
 Error with RestServer CI routes, does not call the corresponding function

### ISSUE THREAD

**Issue by YulianD** [chriskacerguis/codeigniter-restserver#896]
**Hello cordial greeting**, the problem is this:
I have the controller **Modulos**

    `<?php
    defined('BASEPATH') OR exit('No direct script access allowed');

    /** @noinspection PhpIncludeInspection */
    require APPPATH . 'libraries/REST_Controller.php';
    class Modulos extends REST_Controller {

        function __construct()
        {
            parent::__construct();
        }

        public function index_post()
        {
        $this->response("Hello from index", 200);
        }

        public function save_post()
        {
            $this->response("Hello from save", 200);
        }
    }`
And I have the post routes for the respective controller functions
    `$route['api/modulos']['POST'] = 'api/Modulos/index_post';`
    `$route['api/modulos.save']['POST'] = 'api/Modulos/save_post';`

but what happens is that the route `modulos.save` is sent to the function `index_post` and is not returning the one that I have assigned it is `save_post`, in fact I do not recognize any other function that I assigned always return me index_post.
![captura](https://user-images.githubusercontent.com/11492518/36518729-acda77dc-1755-11e8-985d-9e9c868cd619.PNG)

**I appreciate your help**

**Comment by MeekLogic** [comment]
There is built-in HTTP method validation.

So just remove the routes and use `backend/api/modulos/save`
