### ISSUE TITLE
Project maintaining

### ISSUE THREAD

**Issue by Hanisch-IT** [chriskacerguis/codeigniter-restserver#898]
Hi @chriskacerguis,

i dont want to bother you but i feel that you dont have currently the time to maintain this project alone.
Long open PR / Not closed/answered issues / ...
Maybe you will take my helping hand as a colleborater and i will try to do my best helping you with this repo. 

I would not like it to see it die.

Regards

**Comment by chriskacerguis** [comment]
Hi @Hanisch-IT,

It's no bother at all.  I appreciate the concern, but I am not sure that it is warranted at this time :)

Chris
