### ISSUE TITLE
force data type do export

### ISSUE THREAD

**Issue by fcodebue** [chriskacerguis/codeigniter-restserver#899]
I need to enforce data type during set_REsponse for some fields...
For example I have a number but RestAPI client need it  be a string
how I can proceed?

**Comment by MasonFI** [comment]
Can you provide example code where your data is being genererated before setting the response?

**Comment by chriskacerguis** [comment]
no response, closing.
Hello,

I haven't seen a response, so I'm going to close this ticket.  Please feel free to respond and I will re-open :)

Chris
