### ISSUE TITLE
Failing to update response time error

### ISSUE THREAD

**Issue by gakyoo** [chriskacerguis/codeigniter-restserver#900]
Query error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '016963958740234

WHERE `id` = 4116' at line 1 - Invalid query: UPDATE `logs` SET `rtime` = 0,016963958740234
WHERE `id` = 4116

**Comment by chriskacerguis** [comment]
Could you please provide a bit more context / information?  Just coping the error, doesn't really help much.

**Comment by chriskacerguis** [comment]
No response.  Closing.
