### ISSUE TITLE
Rest Server Installation

### ISSUE THREAD

**Issue by sidbenac** [chriskacerguis/codeigniter-restserver#901]
Did the install through Composer by following the readme.md

used example provided with books

got error REST_Controller not found

added use Restserver\Libraries\REST_Controller;

got missing rest.php file,

created the rest.php file and got the error :

Unable to load the requested class: Format

looks like the composer installation doesn't work correctly through CI,

I will fall back to manual installation and not using composer, unless I am missing something here

Thx

**Comment by syrys** [comment]
I can second this. are there any updates/solutions?

You can simply recreate this by just downloading the base codeigniter package, then using composer to install this chriskacerguis/codeigniter-restserver, then create a basic controller and attempt to run it. 

First you get the `REST_Controller not found` issue, then if you use `extends \Restserver\Libraries\REST_Controller` on your controller, you get `missing rest.php file` error, then if you copy over the `config/rest.php.sample` into your config folder, then you get the following error (no obvious solution):

```
An Error Was Encountered
Unable to load the requested class: Format
```

Any ideas?

**Comment by Hanisch-IT** [comment]
Can you paste the head of your code of the class which extends the REST_Controller?

**Comment by chriskacerguis** [comment]
no response.

**Comment by cinder92** [comment]
same issue here

**Comment by KyeBuff** [comment]
Added the restserver files manually in the end - https://www.roytuts.com/setup-restful-service-with-codeigniter/
