### ISSUE TITLE
Stress testing limits

### ISSUE THREAD

**Issue by samueleastdev** [chriskacerguis/codeigniter-restserver#902]
Hi All,

I am using the api and running into some issues when stress testing.

If I set the limits config to true and the run a stress test of say 100 concurrent connections and then check the limits table it is inserting up to 20 duplicate entries.

Not sure if this is due to the speed they are added the issue is here.
~~~
$limit = $this->methods[$controller_method]['limit'];
        $time_limit = (isset($this->methods[$controller_method]['time']) ? $this->methods[$controller_method]['time'] : 3600); // 3600 = 60 * 60
        // Get data about a keys' usage and limit to one row
        $result = $this->rest->db
            ->where('uri', $limited_uri)
            ->where('api_key', $api_key)
            ->get($this->config->item('rest_limits_table'))
            ->row();

        // No calls have been made for this key
        if ($result === NULL)
        {
            // Create a new row for the following key
            $this->rest->db->insert($this->config->item('rest_limits_table'), [
                'uri' => $limited_uri,
                'api_key' =>$api_key,
                'count' => 1,
                'hour_started' => time()
            ]);
        }
~~~

On a really high loaded api this causes the issue with tables locking anyone else having issues?

**Comment by chriskacerguis** [comment]
Honestly, I haven't put things under stress testing.  I can take a loo, what tools are you using to stress test?  Could you outline your setup?

**Comment by samueleastdev** [comment]
Hi @chriskacerguis,

Sure if you install siege 

~~~
brew install siege
~~~

Then run on your api
~~~
siege -c100 -d10 -t5M http://example.com/test/endpoint
~~~

Thanks

**Comment by searchy2** [comment]
PHP 7 only supports 252 requests per second from the commonly quoted benchmark test. 
MySQL shouldn't be the bottleneck here given enough memory. 
I wonder if it's the CodeIgniter overhead itself or some combination of session initialization and server connection limits. Any updates on this?

**Comment by searchy2** [comment]
I performed a basic GET call that returned a string with no DB calls or any other computations. Here are the response time.


Pure PHP Response Times
![pure php response times](https://user-images.githubusercontent.com/19896174/53142971-a64ef800-355b-11e9-8b9d-c687271e88cf.png)


CI Rest Server Response Times
![ci response times](https://user-images.githubusercontent.com/19896174/53142976-abac4280-355b-11e9-9a7c-283788e0a17a.png)

**Comment by searchy2** [comment]
Some quick analysis: 

- The time to first response was around 550ms for both.
- Once the DNS connection was established, the subsequent response time was 250ms for both (not show in pictures)
- The Pure PHP server is faster than CI Rest Server.
- The CI Rest Server's response time hovers above 250ms and does not speed up significantly. 

Unanswered Questions:
- Does CI or the REST server cause the extra 150ms of overhead.
- Why is the time to first response the same for both servers but subsequent requests are faster for the Pure PHP server? Could CI be loading the entire framework with every request?

**Comment by searchy2** [comment]
Here is a better breakdown where I take out the first response time. From these requests, it is apparent that the server slows down as more requests are made.

Pure PHP Response Times
![pure php response times subsequent](https://user-images.githubusercontent.com/19896174/53144244-190ea200-3561-11e9-8c18-e77330e1bc50.png)

CI Rest Server Response Times
![ci response times subsequent](https://user-images.githubusercontent.com/19896174/53144247-1b70fc00-3561-11e9-9fd8-495e91dfb57f.png)

**Comment by searchy2** [comment]
Does response time logging include network request time, CI setup time, or just Rest Server time? #981

**Comment by searchy2** [comment]
Request Per Second stress testing. 

Pure PHP RPS:
_125 RPS_
![pure php request per second 125](https://user-images.githubusercontent.com/19896174/53219832-3d34b680-3627-11e9-8c7f-0ef7ce9587e2.png)

_110 RPS_
![pure php request per second 110](https://user-images.githubusercontent.com/19896174/53219836-3efe7a00-3627-11e9-9f2a-a628dc26fb69.png)

CI RPS:
_125 RPS_
![ci request per second 110](https://user-images.githubusercontent.com/19896174/53219855-50478680-3627-11e9-9d9e-ee5112118234.png)

_110 RPS_
![ci request per second 125](https://user-images.githubusercontent.com/19896174/53219852-4d4c9600-3627-11e9-940d-f3f015be1727.png)

Some analysis:
- Both servers start failing and dropping requests between 110 to 125 requests per second. 
- CI does not appear to be causing enough overhead to throttle the requests and present a bottleneck.

**Comment by searchy2** [comment]
Ran some new tests today and reran some old tests for interesting results. 

Today's new test is making a database query on each request. This tests the overhead added of making a database call.

Pure PHP Database Response Times:
![pure php response times database query](https://user-images.githubusercontent.com/19896174/53618041-5d2c2300-3baf-11e9-92fe-08ac3bbdfe0d.png)

CI Database Response Times:
![ci response times database query](https://user-images.githubusercontent.com/19896174/53618051-64ebc780-3baf-11e9-8199-2867e01f173c.png)

- Pure PHP is slightly but consistently faster than CI. Not by much though which suggests that CodeIgniter's benefits greatly outweigh the performance costs. 
- The CI configuration does not autoload libraries and is a clean installation. This benchmark test should be run with every library that is autoloaded to monitor the performance hit of autoloading additional libraries.

Now, for some interesting results from rerunning network response test. These tests are the same as the ones above but it seems that today the servers are faster. 

Pure PHP Response Times:
![pure php response times 2](https://user-images.githubusercontent.com/19896174/53618239-18ed5280-3bb0-11e9-94d5-130fefd9d1fb.png)

CI Rest Server Response Times:
![ci response times 2](https://user-images.githubusercontent.com/19896174/53618248-27d40500-3bb0-11e9-9aea-5824a3ccd347.png)

- Previously, I did not configure CI correctly so the response times are much faster here. 
- Pure PHP is still consistently faster than CI, but again, not by much.
- Requests without database queries are faster as expected but only by a few milliseconds.

**Comment by searchy2** [comment]
My takeaway is that a clean CI installation is almost as fast as Pure PHP. The overheaded added by the CI framework is a few milliseconds which is negligible. 

Monitoring the performance of a CI app is important as the application grows more complex over time. There is no good way to perform comparables with a Pure PHP implementation for a complex app because reimplementing a CI app in Pure PHP is infeasible. The best way to monitor performance seems to be establishing a baseline here and tracking the overhead added with each new library/feature. 

I'm very happy with the preliminary results!
