### ISSUE TITLE
Cant get $_GET params with http://example.com/books?id=1

### ISSUE THREAD

**Issue by naivestarter** [chriskacerguis/codeigniter-restserver#905]
$_GET or $this->get('id') does not contain any values.

**Comment by chriskacerguis** [comment]
That's not really a RESTful call.

you would want something like:

https://example.com/books/1

(then you would need a route setup accordingly)

**Comment by naivestarter** [comment]
Oh.. but i was looking at other issue about get not working and you had mentioned this method so.. anyways thanks .. i didn't know that.
