### ISSUE TITLE
Auth key only works when header is uppercase

### ISSUE THREAD

**Issue by jerbob92** [chriskacerguis/codeigniter-restserver#906]
A lot of HTTP clients (for example in Go) canonicalizes the headers, so X-API-KEY becomes X-Api-Key.
This breaks implementing API's which use this library, as it only supports the header in the upper-case format. The http specification says that headers should be handled case insensitive.

**Comment by chriskacerguis** [comment]
Have you tired to change the key name in the config?

https://github.com/chriskacerguis/codeigniter-restserver/blob/master/application/config/rest.php#L380

**Comment by jerbob92** [comment]
Changing it in the config works, but then X-API-KEY doesn't work anymore.
Fact is that HTTP headers should be handled case insensitive, so X-API-KEY should work, but also X-Api-Key and x-api-key regardless of whether the header configured is uppercase/lowercase/camelcase.
