### ISSUE TITLE
Didn't show syntax error

### ISSUE THREAD

**Issue by iranappo** [chriskacerguis/codeigniter-restserver#907]
Hello
I use your library
It is very good
But when if exist error in database or syntax or any things,this library return Internal Server Error only
while i write wrong php command

**Comment by Hanisch-IT** [comment]
Thats not a problem of the library.

Turn on your 
```php
error_reporting(E_ALL);
ini_set("display_errors", 1);
```

in your index.php

**Comment by iranappo** [comment]
Oh yes Thank you
Also thank for library,it is very complete please support it always ❤️
