### ISSUE TITLE
My PHP version is 5.3.6, which version should I use?

### ISSUE THREAD

**Issue by ChasLui** [chriskacerguis/codeigniter-restserver#908]
Because the PHP version on the company server is 5.3.6, there is no way to change it, so I want to know which version of codeigniter-restserver can I use?

**Comment by Hanisch-IT** [comment]
You can check it by yourself.
Open the readme.md in every release and you will see the requirements.

I think you should use: https://github.com/chriskacerguis/codeigniter-restserver/releases/tag/2.6.1

And you shoudl tell your company, that is a high risk to use php 5.3 anymore.
