### ISSUE TITLE
Running REST Server Tests yield "404"

### ISSUE THREAD

**Issue by anta40** [chriskacerguis/codeigniter-restserver#909]
A client asked me to implement REST API for his Android app using CI. I think codeigniter-restserver might be useful for this. So I downloaded this package and uploaded it into 2 servers (not actual IPs though, disguised for privacy reason):

1. 123.100.77.10/ci-server (my dev server)
2. 99.40.143.100/ci-server (production server)

The only difference is so far **$config['base_url']** value (in _application/config/config.php_). In my dev server, its **http://123.100.77.10/ci-server**, and on the production server: **http://123.100.77.10/ci-server**

There is no issue running the REST server tests on mine. For example, running test #4 (User 1 - defaulting to JSON (users/1)) yields 

> {"id":1,"name":"John","email":"john@example.com","fact":"Loves coding"}

But all tests on the production server yield:

> 404 Page Not Found
> The page you requested was not found.

I think there are setting issues on the dev server, but don't know exactly what they area.

**Comment by Hanisch-IT** [comment]
Seems like there is mod_rewrite is missing.

Try to open the url on the server ex.

http://.../ci-server/somestring

You should get a response like "method not found".
If not, try the same with index.php

http://.../ci-server/index.php/somestring

**Comment by gadaica3** [comment]
I got same issue with production server.
Just GET methods can be found.
PUT/POST/DELETE throw error method is not found.

Regards,
Ga

**Comment by gadaica3** [comment]
Did you solve it @Hanisch-IT @anta40 ?

I got response:
`{
	"status": false,
	"error": "Unknown method."
}`
