### ISSUE TITLE
JSON encoding error

### ISSUE THREAD

**Issue by ElwoodBermuda** [chriskacerguis/codeigniter-restserver#910]
If passing in an invalid non-UTF8 string into the parsing it is returning a blank page.
I think that the issue is in the Format library for the function to_json
line 423 is:
return json_encode($data, JSON_UNESCAPED_UNICODE);
If the data isn't a utf-8 string then it will return nothing and  json_last_error_msg() has "Malformed UTF-8 characters, possibly incorrectly encoded" in it.

**Comment by Hanisch-IT** [comment]
Solution: Dont pass non UTF8

You can not expect, that the library is auto detecting the encoding, because its nearly impossible.

**Comment by ElwoodBermuda** [comment]
I agree with the solution. I'm grabbing the data from a database and was surprised that there was this issue.
What I think is a problem is that it returns nothing back and I would expect that it would check to see if there was an error that is available and present that as a problem.
