### ISSUE TITLE
Class 'Restserver\Libraries\REST_Controller'

### ISSUE THREAD

**Issue by S-Masoud-Emamian** [chriskacerguis/codeigniter-restserver#912]
I want to use Rest api,I'm using `chriskacerguis/codeigniter-restserver`:

	"require": {
		"php": ">=5.3.7",
		"chriskacerguis/codeigniter-restserver": "^3.0"
	},

I got this error:

       Fatal error: Class 'Restserver\Libraries\REST_Controller' not found 

my class:

    <?php
      namespace Restserver\Libraries;
      use Restserver\Libraries\REST_Controller;

       class Api extends REST_Controller {
	
	     public function __construct(){
		     parent::__construct();
	}
		

	public function user_get()
    {

        $users = [
            'id' => 100, // Automatically generated by the model
            'name' => $this->post('name'),
            'email' => $this->post('email'),
            'message' => 'Added a resource'
        ];

        $this->response($users, REST_Controller::HTTP_OK);
    }
		
	
}

    +controllers
       +Api
          Api.php

**Comment by S-Masoud-Emamian** [comment]
I got this error output:

     Fatal error: Class 'REST_Controller' not found in C:\xampp\htdocs\shadyab\application\controllers\Api\Api.php on line 3

my class:

```
<?php
namespace Restserver\Libraries;
class Api extends \REST_Controller {
	
	public function __construct(){
		parent::__construct();
	}
		


	public function user_get()
    {

        $users = [
            'id' => 100, // Automatically generated by the model
            'name' => $this->post('name'),
            'email' => $this->post('email'),
            'message' => 'Added a resource'
        ];

        $this->response($users, REST_Controller::HTTP_OK);
    }
		
	
}
```

**Comment by luckydonald** [comment]
Just remove `use Restserver\Libraries\REST_Controller`.
This seem to have happened somewhere between `3.0.0` and `3.0.3`.

**Comment by anuragyadav8949** [comment]
@Hanisch-IT  
Hey i have used the same thing(namespace) but it shows the error
" Class 'Restserver\Libraries\CI_Controller' not found in"

Could plz tell me about what is Restserver is
my lib struct is 
+app
  +libraries
    ->Rest_Controller.php

**Comment by Hanisch-IT** [comment]
Hi @anuragyadav8949,

how did you include the Codeigniter_Restserver? Did you copy&paste the files to your library folder or did you install it via composer?

**Comment by anuragyadav8949** [comment]
@Hanisch-IT 
Copy Paste two files from  the github
"format.php  ,  Rext_controller.php"

Thanks for response :)

**Comment by anuragyadav8949** [comment]
Hey 
I resolved the error
by adding line in Rest_controller => "use CI_Controller;"
in my controller => use Restserver\Libraries\REST_Controller;

Now Again error occured is => "Class 'Restserver\Libraries\Format' not found in libraries\REST_controller.php "

U can direct message me on my mail 
anurag.yadav8949@gmail.com

Waiting for reply:)

**Comment by etranger-park** [comment]
I have same problems and solve it!
add 
require APPPATH . 'libraries/Format.php';
in REST_Controller.php

**Comment by atukilham** [comment]
i got another error after upgrade:

`An Error Was Encountered`
`Non-existent class: Format`

I try add `use Restserver\Libraries\Format;` in REST_Controller.php, like this : 

`namespace Restserver\Libraries;`
`use Exception;`
`use stdClass;`
`use Restserver\Libraries\Format;`

But still error, please help.

**Comment by adhimasprayogie** [comment]
Help me please!

I got this error 

> Fatal error: Class 'REST_Controller' not found in C:\xampp\htdocs\rest_server\application\controllers\Itp.php on line 5

and this is my code
`<?php

namespace Restserver\Libraries;

class itp extends \REST_Controller {
    function __construct() {
        parent:: __construct();
    }`

**Comment by farukgaric** [comment]
Just remove \ "backslash" before REST_Controller

**Comment by azmiadhani** [comment]
> I have same problems and solve it!
> add
> require APPPATH . 'libraries/Format.php';
> in REST_Controller.php

Thanks a alot

**Comment by sidiqfatkhul9** [comment]
An uncaught Exception was encountered
Type: Error

Message: Class 'Restserver\Libraries\Format' not found

Filename: C:\xampp\htdocs\pegawai\rest_ci\application\libraries\REST_Controller.php

Line Number: 853

Backtrace:

File: C:\xampp\htdocs\pegawai\rest_ci\application\libraries\REST_Controller.php
Line: 737
Function: response

File: C:\xampp\htdocs\pegawai\rest_ci\index.php
Line: 315
Function: require_once

**Comment by didiwahyudi12** [comment]
I got this error:
Fatal error: Class 'REST_Controller' not found in D:\XAMPP\htdocs\restCI\application\controllers\TestApi.php on line 6

my class:
<?php

  namespace Restserver\Libraries;
  

   class TestApi extends \REST_Controller {

     public function __construct(){
	     parent::__construct();
	 }

	public function index_get(){
	
	    $response['status']=200;
	    $response['error']=false;
	    $response['message']='Hai from response';
	    
	    $this->response($response);
	}

	public function user_get(){
	    $response['status']=200;
	    $response['error']=false;
	    $response['user']['username']='erthru';
	    $response['user']['email']='ersaka96@gmail.com';
	    $response['user']['detail']['full_name']='Suprianto D';
	    $response['user']['detail']['position']='Developer';
	    $response['user']['detail']['specialize']='Android,IOS,WEB,Desktop';
	    $this->response($response);
	}
	
}
?>

**Comment by dikaheni** [comment]
how do i redirect resfull api I want after input_post () page will be redirected
`public function loginsi_post(){
        $username = $this->post('username');
        $password = $this->post('password');
        $data = [];
        $data['username'] = $username;
        $data['password'] = $password;
        if ($this->model_app->insert('jajal', $data) > 0) {
            $this->response([
                'message' => 'data berhasil disimpan',
                'data'    => $data
            ], REST_Controller::HTTP_CREATED);
        }else{
            $this->response([
                'message' => 'data gagal disimpan'
            ], REST_Controller::HTTP_CREATED);
        }
    **redirect('main/home'); -> is not working**
    }`
