### ISSUE TITLE
Download/Upload files

### ISSUE THREAD

**Issue by dmonteirosouza** [chriskacerguis/codeigniter-restserver#914]
It's possible, upload or download files with this one?
If yes, have a example? 
Thank you!

**Comment by luckydonald** [comment]
Download is just `echo $data_of_file;`, upload can use the usual GET/POST variables, see https://www.codeigniter.com/userguide3/libraries/file_uploading.html

**Comment by Hanisch-IT** [comment]
The download should have the correct headers as well

**Comment by dmonteirosouza** [comment]
Got it. I used Header to Download and to upload, Just a post.

**Comment by luckydonald** [comment]
You should probably use the `output` class:
```php
$CI->output->set_header('Content-Type: application/octet-stream')
```

This changes not much in your code, but allow [Unit tests](https://github.com/kenjis/ci-phpunit-test) later.
