### ISSUE TITLE
Test code or tested code did not (only) close its own output buffers

### ISSUE THREAD

**Issue by luckydonald** [chriskacerguis/codeigniter-restserver#915]
This is in release `3.0.3` via composer.

Problem is the `ob_start()` not being closed in [REST_Controller.php](https://github.com/chriskacerguis/codeigniter-restserver/blob/3a5ba0dffdebd24cc215ef714b72208c88304203/application/libraries/REST_Controller.php#L884-L886). This fails in unittests.
My proposed fix is:
```diff
        if ($continue === FALSE) {
            // Display the data and exit execution
+            ob_end_flush();
            $this->output->_display();
            exit;
        } else {
            ob_end_flush();
        }
```

**Comment by luckydonald** [comment]
Looks still relevant for the current code.

**Comment by Hanisch-IT** [comment]
Hi @luckydonald,

your PR is very welcome :)

**Comment by luckydonald** [comment]
The [current version](https://github.com/chriskacerguis/codeigniter-restserver/blob/2c1c621ca79ff91a4a3f5bbe1c7aa6748b56ad27/application/libraries/REST_Controller.php#L888) in the repo the indention seem to be butchered up a little, should I touch that as well?

**Comment by Hanisch-IT** [comment]
if you can improve it, it would be great.

**Comment by maxpaynestory** [comment]
exit; has to go as well, without it unit tests fail.
