### ISSUE TITLE
form validation doesn't update $this->post()

### ISSUE THREAD

**Issue by ingcvillegas** [chriskacerguis/codeigniter-restserver#917]
i'm doing a callback validation, where the input value has to be modified, the problem is that when i get the value after validations $this->post('text') the value stays without changes

//before validations
echo $this->post('text');
//result: foo

//adding rule
$this->form_validation->set_rules('text', 'Name', 'trim|required|callback_strip_word_html|is_unique[table.field]');

 //the rule
public function strip_word_html($text) {
        ......
        //returning the new value 
        return 'bar';
}

//after run validations
echo $this->post('text');
//result: foo

//when its suposed to be:
//result: bar

i've seen that you use _post_args
$this->_post_args = $_POST;
and then only returns
$this->_post_args[$key]
so i guess i need to modify _post_args[$key] but it is protected, and i want it to do it the rigth way, so tell me if im doing something wrong

**Comment by Hanisch-IT** [comment]
Hi @ingcvillegas,

i dont know if the form validation is the right tool to validate the REST Request Parameters.

If you realy want to use it, you are very welcome to create a pull request with the changes which are required to use form_validation.

For me the form_validation is only for "form validation" and not for REST request validation.
