### ISSUE TITLE
how to setting api over ssl/https

### ISSUE THREAD

**Issue by arlakay** [chriskacerguis/codeigniter-restserver#918]
hi, i want ask how to config this framework over ssl/https.
cause i publish api on http://xxxxxx.com working fine.
but after change on server to activate ssl and my address change to https://xxxxxx.com. and i got problem cant get response from my api. 
please need help.

**Comment by chriskacerguis** [comment]
This seems like it might be an issue with your web server config (possibly different paths for http and https).  However, you didn't provide any errors or logs, so I can't really help.  I'm going to close this ticket.  If you have more info, please feel free to reply.
