### ISSUE TITLE
Ignoring api key for ip whitelist or domain

### ISSUE THREAD

**Issue by nabrih** [chriskacerguis/codeigniter-restserver#920]
how to ignoring api key checking and enable key for other origin ?

**Comment by chriskacerguis** [comment]
> ignoring api key checking

You can disable it in the config.php file

https://github.com/chriskacerguis/codeigniter-restserver/blob/master/application/config/rest.php#L327

> enable key for other origin

I'm sorry, I'm not sure what you mean by that.
