### ISSUE TITLE
How to get paramaters passed by headers in PHP method

### ISSUE THREAD

**Issue by being-samrat** [chriskacerguis/codeigniter-restserver#921]

**Comment by kateile** [comment]
If you face no problems try getallheaders();

otherwise use this function custom function
`function get_headers()
{
    $headers = [];
    foreach ($_SERVER as $name => $value) {
        if (substr($name, 0, 5) == 'HTTP_') {
            $headers[str_replace(' ', '-', strtolower(str_replace('_', ' ', substr($name, 5))))] = $value;
        }
    }
    return $headers;
}`

references https://stackoverflow.com/questions/41427359/phpunit-getallheaders-not-work/41428728
