### ISSUE TITLE
auth_override from session to digest-library?

### ISSUE THREAD

**Issue by krstns** [chriskacerguis/codeigniter-restserver#927]
Hello

I would like to use rest_auth session for all of my APIs except for login which I would like to handle using digest authentication handled by my library.

Unfortunately, when the override is detected, the handling is limited to selecting the right function based on the rest_auth. However, it does not override the auth_source at all. This makes the whole thing very limited.

The easiest way to tackle this limitation would be an introduction of a new config variable, something along the line of 'rest_auth_session_variable'.

**Comment by chriskacerguis** [comment]
PR's are welcome ;)
