### ISSUE TITLE
Show php error in restful

### ISSUE THREAD

**Issue by iranappo** [chriskacerguis/codeigniter-restserver#928]
Hi
Thank you for your service
I have problem in this library
If my code had error in php code or database,restful server return only restful's error and i cannot see php error
How do i can see it?

**Comment by farukgaric** [comment]
What about logs?

**Comment by iranappo** [comment]
@farukgaric how do i get log or enable it?

**Comment by farukgaric** [comment]
https://www.codeigniter.com/user_guide/general/errors.html

**Comment by iranappo** [comment]
Oh no i know what is it
My problem is use restful
Actually when i use restful server,i cannot see some errors
