### ISSUE TITLE
Large Dataset 

### ISSUE THREAD

**Issue by rpatel-rnits** [chriskacerguis/codeigniter-restserver#929]
What is the limit on how much data we can get via a call?  So I am trying to get around 10k records, but when I make the the call to the service, it does not work.  When I limit the call to the top 4k records, it works perfectly fine.  So is there a limit on how much data I can get?

I am not getting an error as well.  No data is getting retrieved.  I read older posts on large databases and commenting out this in the REST_Controller.php file: header('Content-Length: ' . strlen($output));, but I can't seem to find this anywhere in the latest version?

Thanks in advanced for your help.

**Comment by chriskacerguis** [comment]
This would be determined by the web server (Apache, Nginx, etc), not the code here.

**Comment by rpatel-rnits** [comment]
What setting would that?  Sorry just a beginner with this kind of things.

**Comment by rpatel-rnits** [comment]
Its all set.  Figured out the setting.  It was the execute time setting in php.
