### ISSUE TITLE
Response doesn't terminate API call

### ISSUE THREAD

**Issue by jorgenocedal** [chriskacerguis/codeigniter-restserver#931]
I was using an old version, but after update codeigniter-restserver I had problem using $this->response() function.

Here is an example:

`<?php

defined('BASEPATH') OR exit('No direct script access allowed');

require APPPATH . '/../vendor/autoload.php';
use Restserver\Libraries\REST_Controller;

class Welcome extends REST_Controller {

    function __construct() {
        parent::__construct();
    }

    public function version_get() {

        $this->response(['error' => 'error'], REST_Controller::HTTP_BAD_REQUEST);

        $this->response(['mensaje' => 'hi'], REST_Controller::HTTP_OK);
    }

}
`

Response should be {"error":"error"} but {"mensajes":"hi"} is displayed.

**Comment by luckydonald** [comment]
The current version has a flag to continue or not.

To quote the file:
```php
/**
     * Takes mixed data and optionally a status code, then creates the response
     *
     * @access public
     * @param array|NULL $data Data to output to the user
     * @param int|NULL $http_code HTTP status code
     * @param bool $continue TRUE to flush the response to the client and continue
     * running the script; otherwise, exit
     */
    public function response($data = NULL, $http_code = NULL, $continue = FALSE)
```

So setting the last argument to `false` should resolve that.
```php
$this->response(['error' => 'error'], REST_Controller::HTTP_BAD_REQUEST, false);

**Comment by jorgenocedal** [comment]
Oh, Thank you very much!
