### ISSUE TITLE
How to run it in production?

### ISSUE THREAD

**Issue by luisxxor** [chriskacerguis/codeigniter-restserver#938]
Hello! I'm making a project that have a front-end with vue, handling the routes with vue-router, and i decided to use codeigniter 3 to the backend, but i only need a backend to certain operations with the database, then i decided to use this package to create a restful api with codeigniter, i have created some methods in a controller, I have tested them with postman running the server with bin\server.sh, but i run a development server for the front with webpack executing   >npm run dev   that makes that the backend runs in localhost:8000 and the frontend in localhost:8080, the question is how to run the backend in production, so i can turn vue into production and test all.

**Comment by codeamancoder** [comment]
Hello @luisxxor 
you must enable CORS support first in case of sending requests to different url from your Vue client app.
it is in config/rest.php $config['allow_any_cors_domain'] = true;
