### ISSUE TITLE
Its Showing Error while use REST_Controller

### ISSUE THREAD

**Issue by vijendra0152** [chriskacerguis/codeigniter-restserver#940]
I am getting error while I am using REST_Controller 
Non-existent class: Format

I load Fomat class in REST_Controller still getting same error.
My REST_Controller looks like.

`<?php

namespace Restserver\Libraries;

require_once APPPATH . '/libraries/Format.php';

use CI_Controller;
use Exception;
use stdClass;
class REST_Controller extends CI_Controller { `

Please Help me.

**Comment by aalissonfl** [comment]
Same here!

**Comment by huetran01** [comment]
I did  followings steps to solve the issue: 

Step 1 :  add  to  composer.json in  the project the line : 

"chriskacerguis/codeigniter-restserver": "^3.0"  

step 2:  composer update 

Step 3 :  

+ **cp** /directory/to/yourproject/vendor/chriskacerguis/codeigniter-restserver/application/libraries/Format.php **to**  /directory/to/yourproject/application/libraries
 
+ **cp** /directory/to/yourproject/vendor/chriskacerguis/codeigniter-restserver/application/config/rest.php  **to**  /directory/to/yourproject/application/config/

Step 4 :  Add to index.php 

include_once './vendor/autoload.php';
require_once BASEPATH.'core/CodeIgniter.php'; 

Step 5:  Use class 

<?php defined('BASEPATH') OR exit('No direct script access allowed');

use Restserver\Libraries\REST_Controller;

class Api extends REST_Controller {  
                                           ...........
}

?>

Maybe there are many ways to solve  but you can try the above steps.  That worked for me.
