### ISSUE TITLE
join 2 table 

### ISSUE THREAD

**Issue by tnfaid** [chriskacerguis/codeigniter-restserver#942]
and I'm so confused how to make a join from 2 table in here... can anyone help me?

in here I have 
table CMS_NewsImage(NewsID, ImageName) 
table CMS_News(NewsID, NewsTitle, PostDate)

**Comment by impactcolor** [comment]
Reasonable question no?

**Comment by impactcolor** [comment]
I think the question is using this library how would one execute a query like so "SELECT * FROM citys LEFT JOIN comments ON comments.city=citys.city WHERE citys.id=$id";

**Comment by chriskacerguis** [comment]
So, this is really a general question that would be better asked on https://forum.codeigniter.com or https://stackoverflow.com

**Comment by impactcolor** [comment]
Does the rest controller dictate these options?  select, from and get?
```
    $templates_data = $this->db->select('dr_template_relational.template_id, dr_report_templates.id')
                                ->from('dr_template_relational')
                                ->get()
                                ->result_array();
```

**Comment by impactcolor** [comment]
Ok so for newbies like myself this is related to codeigniter and not the actual rest.  Here is the link:
https://www.codeigniter.com/userguide3/database/query_builder.html
