### ISSUE TITLE
White listing not working

### ISSUE THREAD

**Issue by alexhobday** [chriskacerguis/codeigniter-restserver#943]
Hi all,

I would like to just enable whitelisting and not authentication, ie no login required. 

According to the comments in rest.php I simply update this line to TRUE:

`$config['rest_ip_whitelist_enabled'] = TRUE;`

AND leave this as false: 

`$config['rest_auth'] = FALSE;`

However I'm getting the following error: 

`{"status":false,"error":"IP unauthorized"}`

In terms of whitelisting IP addresses, I've tested this locally using my localhost (127.0.0.1) address and my remote server address. Neither is working.

Help would be appreciated.

**Comment by codeamancoder** [comment]
Hello @alexhobday 
did you add IP list here "$config['rest_ip_whitelist'] = ''" as comma separated ?

**Comment by alexhobday** [comment]
HI @codeamancoder, thanks for your response, this repo doesn't seem too active.

THis is what I have:

`$config['rest_ip_whitelist_enabled'] = TRUE;`

`$config['rest_ip_whitelist'] = 'xxx.xxx.xxx.xxx';`

I'm still getting a Status Code: 401 Unauthorized response.

**Comment by chriskacerguis** [comment]
Can you please post the headers from the request?
