### ISSUE TITLE
session_start() error in __construct function

### ISSUE THREAD

**Issue by Haseebfayyaz** [chriskacerguis/codeigniter-restserver#948]
<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">
    <h4>A PHP Error was encountered</h4>
    <p>Severity: Warning</p>
    <p>Message:  session_start(): Cannot send session cookie - headers already sent by (output started at /public_html/application`enter code here`/controllers/api/Users.php:192)</p>
    <p>Filename: Session/Session.php</p>
    <p>Line Number: 143</p>
    <p>Backtrace:</p>
    <p style="margin-left:10px">
            File: public_html/application/libraries/REST_Controller.php
        <br />
            Line: 397
        <br />
            Function: __construct
    </p>
    <p style="margin-left:10px">
    /public_html/application/controllers/api/Users.php
        <br />
            Line: 14
        <br />
            Function: __construct
    </p>
    <p style="margin-left:10px">
            File: /public_html/index.php
        <br />
            Line: 315
        <br />
            Function: require_once
    </p>
</div>

**Comment by chriskacerguis** [comment]
Something seem to be throwing an error, but there really isn't enough in this issue to help diagnose.  Seems to indicate this is a local issue not a library one.
