### ISSUE TITLE
axios post data not working for me

### ISSUE THREAD

**Issue by kushanz** [chriskacerguis/codeigniter-restserver#949]
I'm using codeigniter rest api with vue and axios. when it open by console request headers have no post data and json output username password required

axios method
`
          var url = 'http://localhost/rest/user/login';
          var postdata = {username:this.user.username};
        axios.post(url, 
    this.user, 
    { headers: {
      'Content-type': 'application/x-www-form-urlencoded',
      }
    }).then((response) => {
     console.log(response)
 });`
![image](https://user-images.githubusercontent.com/18259456/44997832-c2bba000-afce-11e8-9e5d-0670939f6ce7.png)

**Comment by eckelarsson** [comment]
Post data is not included in the axios post request?

axios.post(url, this.user ...
axios.post(url, **postdata** ...

**Comment by chriskacerguis** [comment]
Using CURL from the command line, what do you see?

**Comment by chriskacerguis** [comment]
No response.  Closing.
