### ISSUE TITLE
Can't access to multipart form request parameters

### ISSUE THREAD

**Issue by holic-cl** [chriskacerguis/codeigniter-restserver#950]
Hi,
I am trying to access to multipart form request parameters without success. I am trying to do:
```
$request = (array) $this->post()
```
But the returned array is empty.
Another post methods like urlencoded or json requests are working without problems.

Is this a CodeIgniter Issue?.

Thanks

**Comment by codeamancoder** [comment]
have you tried $this->_args ? if you are uploading a file, you can get file info from $_FILES.

**Comment by holic-cl** [comment]
Finally i used urlencoded to make it work. Didn't know $this->_args method, i will try it to see if this work.

Thanks for answer!.
