### ISSUE TITLE
installing

### ISSUE THREAD

**Issue by Cipa** [chriskacerguis/codeigniter-restserver#951]
Hi,

1. I can't see a development version, as specified in the docs
2. when installing with composer all codeigniter files are installed, any way I can only install what is needed in a vendor folder? See attached image for a lot more files than needed installed

<img width="457" alt="screen shot 2018-09-17 at 10 38 22 am" src="https://user-images.githubusercontent.com/293377/45639828-df8fb300-ba65-11e8-9d06-b21d8a0db26e.png">

**Comment by chriskacerguis** [comment]
1.  It's in the works.
2. you can delete out what you don't need.
