### ISSUE TITLE
Uncaught Error: Call to a member function item() on null in REST_Controller.php:627

### ISSUE THREAD

**Issue by cnakh** [chriskacerguis/codeigniter-restserver#952]
The library is very nice.

I test on PHP 5.6 works fine.
But now move to production server with PHP 7.1.22 it got error as below:

`Uncaught Error: Call to a member function item() on null in /var/www/html/application/libraries/REST_Controller.php:627`

**Comment by cnakh** [comment]
Hi,

I'm not sure, because it error from original library class.

**Comment by cnakh** [comment]
Instead of download from release, download directly the latest version solved my problem.
Thanks everybody.

**Comment by widiu7omo** [comment]
Hi, which version do you use to solve your problem? I get the same issue here.

**Comment by cnakh** [comment]
@widiu7omo You can go to `https://github.com/chriskacerguis/codeigniter-restserver` and click `Clone or download`. It is the latest source code.

**Comment by valjar** [comment]
I got exactly the same problem on all 3 versions, but only in pre flight request. I have this class publicApi. I'm developing my application with VueJs, which means i have to kill/die option request, but somehow my code is not working (still figuring out why), so OPTIONS request get's executed and throws error like yours.

```
require APPPATH . '/libraries/REST_Controller.php';

/**
 * Class PublicApi
 */
class PublicApi extends REST_Controller {

    /**
     * PublicApiController constructor.
     */
    public function __construct() {
        $this->setHeaders();
        $this->killDevPreFlightRequest();
        parent::__construct();
    }

    /**
     * Set headers
     */
    private function setHeaders() {
        if (ENVIRONMENT === 'dev') {
            header('Access-Control-Allow-Origin: *');
        } else if (ENVIRONMENT === 'staging') {
            header('Access-Control-Allow-Origin: https://test.myApp.com');
        }
        if (ENVIRONMENT === 'production') {
            header('Access-Control-Allow-Origin: https://myApp.com');
        }
        header("Content-type: application/json");
        header("Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Access-Control-Request-Method, Authorization, Token, App-version");
        header("Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE");
    }

    /**
     * Kill options request on development
     */
    private function killDevPreFlightRequest() {
        // resolve options request because of development which is done on localhost:8080
        if (ENVIRONMENT == 'dev') {
            if ($_SERVER['REQUEST_METHOD'] === "OPTIONS") {
                die();
            }
        }
    }
}
```

After preflight request "normal" get request get executed and works as it should

**Comment by valjar** [comment]
If I commented out content of __destruct method in REST_Controller.php:627, then everything is working again...

```
public function __destruct()
    {
        // Log the loading time to the log table
        /*
        if ($this->config->item('rest_enable_logging') === TRUE)
        {
            // Get the current timestamp
            $this->_end_rtime = microtime(TRUE);

            $this->_log_access_time();
        }
        */
    }
```

So the question is why $this->config is NULL only in __destruct method?

**Comment by chriskacerguis** [comment]
This no longer should be an issue in the latest release.  If you are still having issues (once updated to the latest code), can you please open a new issue?
