### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by akshilshah** [chriskacerguis/codeigniter-restserver#953]
I am using rest server for the api and all the response are working perfect.
 The current response from database is 
`{
    "status": true,
    "returnmessage": "",
    "stddiv": [
        {
            "id": "6",
            "standard": "1",
            "division": "A"
        },
        {
            "id": "7",
            "standard": "1",
            "division": "B"
        },]
}`
I want to modify the response like this
`{
    "status": true,
    "returnmessage": "",
    "standard": [
        "name": "1",
          {
            "id": "6",
            "division": "A"
        },
        {
            "id": "7",
            "division": "B"
        },
  "name": "2",
          {
            "id": "8",
            "division": "A"
        },
        {
            "id": "9",
            "division": "B"
        },
]
}`

**Comment by Tpojka** [comment]
You are owner of that response meaning you should make structure that best feet your needs before you pass it to `$this->response($response, $status)` method in controller's method code. 
When everything is working perfect don't open issue ticket with no reason. Use Stackoverflow or forums for getting that kind of problems solved.
