### ISSUE TITLE
404 page not found in production server

### ISSUE THREAD

**Issue by fetro431** [chriskacerguis/codeigniter-restserver#957]
I know there's someone else probably already asking about this problem, but I can't figure out how to solve it.

I implemented the Rest API using XAMPP, and everything works just fine (works perfect also with postman).

But the problem came when I uploaded the same application to our production server. There were no problems using the default controller (welcome page appeared). But when I run the API controller, then 404 page not found page came out. 

I already check the routes in config and routes, everything seems to be correct.

Here's my server specification:
OS: CentOS linux
PHP version: 5.6.30

A few lines of the API controller:

`<?php
defined('BASEPATH') OR exit('No direct script access allowed');

require APPPATH.'/libraries/REST_Controller.php';

use Restserver\Libraries\REST_Controller;

class Api extends REST_Controller
{

       public function __construct() {
               parent::__construct();
               $this->load->model('user_model');

       }
       `
Any suggestions would be highly appreciated.

Thank you

**Comment by sudik** [comment]
Try to rename your model file from user_model.php to User_model.php

**Comment by Thedijje** [comment]
Try using another controller without REST API in it, I believe that there issue with your .htaccess configuration.
You can try using API controller using URL `/index.php/api/your_method_name` if this works fine, please use the code in your `.htaccess` file to route your request over `index.php` in URL.
Let me know
```
RewriteEngine On


RewriteCond %{REQUEST_FILENAME} !-f 
RewriteCond %{REQUEST_FILENAME} !-d 

RewriteRule ^(.*)$ index.php?/$1 [L]
```
Above code works fine in htaccess to get clean URL.
