### ISSUE TITLE
large API gives 500 error

### ISSUE THREAD

**Issue by Pattoow** [chriskacerguis/codeigniter-restserver#959]
Hiya,

I am using this module for our API server. However large data sets (base64 encoded file transfers) gives a 500 error.

The reason because of this is line 1247 in de REST_CONTROLLER.php file

``'params' => $this->_args ? ($this->config->item('rest_logs_json_params') === TRUE ? json_encode($this->_args) : serialize($this->_args)) : NULL,``

"Mysql server as gone away" is the error because of the large data file send to the mysql server. I changed the line to NULL as default, though the string is not logged then it will allow large datasets then.

**Comment by Thedijje** [comment]
This "Mysql server has gone away" erupts when some timeout issue occur with SQL operations, you can try checking error log of CodeIgniter, which you can find at `application_path/logs/log-your-date.php`

If you can't find log there, enable Codeigniter logging in `config/config.php` by setting a the log_threshold value to 1 at least, 2-3 will give the more accurate result.
Let us know your conclusion so we can further go ahead on it.

**Comment by chriskacerguis** [comment]
My guess is that something is that the web server is timing out:

https://dev.mysql.com/doc/refman/8.0/en/gone-away.html

Perhaps the look here: http://php.net/manual/en/function.set-time-limit.php

**Comment by Viiclovish** [comment]
Yeah the error is thrown because the server is timeout but the incoming data from the webservice I have created are such large data files (base64 encoded files) that this error erupts the moment I send something to the webservice.

The only way to not getting this message was to remove the logging of the arguments in total to the database.
