### ISSUE TITLE
Parse error: unexpected 'class' (T_CLASS)

### ISSUE THREAD

**Issue by dkodson23** [chriskacerguis/codeigniter-restserver#962]
Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /home/etanopvt/public_html/securexxxfric_pay/application/libraries/REST_Controller.php on line 849

**Comment by rudiadriian** [comment]
Hi

I'm testing the library

When testing the page, I get the following error  log:
please help me

Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in D:\Project\rest-pns\application\libraries\REST_Controller.php on line 835
