### ISSUE TITLE
Getting 500 error in 3.0.4

### ISSUE THREAD

**Issue by chan51** [chriskacerguis/codeigniter-restserver#976]
Hi Chris,

I'm getting a 500 error in postman while calling any CRUD verbs.

CI 3.0.4
REST: latest master
MAMP on localhost (mac)

My CI is working fine, all pages and code is working fine. But when I'm trying to call api methods, it's throwing 500 Internal server error. No message or error log coming in console.

I'm seriously new to REST/APIs, so any help would be greatly appreciated.

**Comment by chriskacerguis** [comment]
Sorry, I'm not sure what to tell you.  500 indicates the server is throwing an error, but I would need to see logs.  Perhaps turn up the logging in MAMP / PHP?
