### ISSUE TITLE
basic and digest authentication

### ISSUE THREAD

**Issue by liauer** [chriskacerguis/codeigniter-restserver#977]
Hi,
$config['rest_auth'] = 'basic'; runs well
but when it is changed to
$config['rest_auth'] = 'digest'; you get this screen

&lt;div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;"&gt;
&lt;h4&gt;A PHP Error was encountered&lt;/h4&gt;
&lt;p&gt;Severity: Notice&lt;/p&gt;
&lt;p&gt;Message:  Undefined variable: username&lt;/p&gt;
&lt;p&gt;Filename: libraries/REST_Controller.php&lt;/p&gt;
&lt;p&gt;Line Number: 2111&lt;/p&gt;
Backtrace:
			&lt;p&gt; style="margin-left:10px">
			File: /home/ubuntu/workspace/ci/application/libraries/REST_Controller.php<br />
			Line: 2111<br />
			Function: _error_handler			</p>

			<p style="margin-left:10px">
			File: /home/ubuntu/workspace/ci/application/libraries/REST_Controller.php<br />
			Line: 592<br />
			Function: _prepare_digest_auth			</p>

			<p style="margin-left:10px">
			File: /home/ubuntu/workspace/ci/application/controllers/Movies.php<br />
			Line: 11<br />
			Function: __construct			</p>

			<p style="margin-left:10px">
			File: /home/ubuntu/workspace/ci/index.php<br />
			Line: 315<br />
			Function: require_once			</p>

</div>{"status":false,"error":"Invalid credentials"}

I have also the previous version of REST_Controller.php. This basic/digest authentication runs well with it. Digest authentication started not to run after "buxfix a month ago".

Why just use the older version? I am a teacher and my students download the latest version which in this case will not run properly.

**Comment by quick88** [comment]
hi..
i got also the same error..but if i add 
--  $username = $this->_check_login($digest['username'], TRUE); --
from the previous one i can run again..
so is that effect to the new one? or i just wrong to add that script?
please need help..

**Comment by liauer** [comment]
Hi,
where did you add that line of code? Would you please tell the line number or take screen image of the lines?

**Comment by quick88** [comment]
hi liauer,
you can see the previous one, and you can find where the line of code..just insert 
![code username](https://user-images.githubusercontent.com/47584187/52757174-686f4280-3036-11e9-8c31-0fcb18ae793e.png)

**Comment by ardimardiana** [comment]
https://github.com/chriskacerguis/codeigniter-restserver/pull/319#discussion_r13581980

i try to use this library while using digest auth. still return error.

from this lib, return $HA1;

$valid_response = md5($digest['username'].':'.$digest['nonce'].':'.$digest['nc'].':'.$digest['cnonce'].':'.$digest['qop'].':'.$md5);
while $digest['response'] sent by user?
where return $HA1 used in REST_Controller?
