### ISSUE TITLE
Need Full Structure

### ISSUE THREAD

**Issue by bsandy999** [chriskacerguis/codeigniter-restserver#979]
Hello @chriskacerguis,
      I have cloned your code base and running directly through the browser. Can you tell me the basic flow to follow?
     Where are the other files/folders structure like system folder, index.php?
What are the basic things to consider while implementing your updated code into CodeIgniter ?

**Comment by chriskacerguis** [comment]
Hi!

They are not included, you will need to download CI 3.x and drop the files in place.

As for basic things to consider, not sure what you mean.
