### ISSUE TITLE
Invalid api key for get data with CI andREST Server

### ISSUE THREAD

**Issue by adityadees** [chriskacerguis/codeigniter-restserver#980]
My problem is i dont know where must i put api key. I can do it if I test on postman, but on my code i cannot. maybe someone can help me?

If i using postman i can get all data 
![image](https://user-images.githubusercontent.com/37553901/52729848-962f9980-2fec-11e9-8fa6-8e5784a61ebf.png)
But i got error if i try on my php, if i dont use require apikey i can get all data. 
![image](https://user-images.githubusercontent.com/37553901/52729868-9f206b00-2fec-11e9-97a1-88fe9ddb494e.png)

this is my script
```
<?php
defined('BASEPATH') OR exit('No direct script allowed');
class Kontak extends MY_Controller{
    var $api = "";

    function __construct(){
        parent::__construct();
        $this->api = $this->config->item('api');
    }

    function index(){
		$this->curl->header('auth-apikey', '123456');
        $data['dataKontak'] = json_decode($this->curl->simple_get($this->api.'/kontak&auth-apikey=[123456]'));
        $this->load->view('kontak/list', $data);
    }

```

**Comment by pranavipalavarapu** [comment]
how can we generate api will please help me

**Comment by adityadees** [comment]
generate api?

**Comment by chriskacerguis** [comment]
So, from what I see (as far as CI RestServer is working).  I would take a look at this article, perhaps it can help:

https://weichie.com/blog/curl-api-calls-with-php/
