### ISSUE TITLE
What does the response time measure?

### ISSUE THREAD

**Issue by searchy2** [chriskacerguis/codeigniter-restserver#981]
When `rest_enable_logging` enabled is set to TRUE, what does the `rtime` measure?

**Comment by chriskacerguis** [comment]
Hello,

`rtime` is how long the request takes.  

Take a look here:

https://github.com/chriskacerguis/codeigniter-restserver/blob/f3ba7d76cb14c11602f72b432926a17b8ff7c590/application/libraries/REST_Controller.php#L2224

**Comment by searchy2** [comment]
Hi Chris,

Thanks for the response. I did do my homework and look through the code. So the request time is the entire time it takes the rest library to process the request? Does it include setting up CodeIgniter and the database?
It looks like the time includes the time it takes to query the database but not setup CI.
Thanks for the help!

**Comment by searchy2** [comment]
I'm trying to pinpoint the amount of time it takes because I'd like to figure out the overhead CI adds to a REST request vs simple PHP.
