### ISSUE TITLE
Rest Server 4.0 Status [UPDATE 2]

### ISSUE THREAD

**Issue by chriskacerguis** [chriskacerguis/codeigniter-restserver#982]
I don't really keep a blog or twitter, so I'll make this issue and pin it.  I wanted to update everyone on 4.0, my thoughts, and a few general notes.  I'm not really a "blogger", so I'm just jotting down some notes in bulleted form.

**[Update 11/01/2019]:** For a variety of reasons, I've got the beta code at a new repo https://github.com/chriskacerguis/ci-restserver it is also available at Packagist.

[Update 11/10/2019]: Code has shown to be quite stable, so I've tagged this as 3.1 and released it at https://github.com/chriskacerguis/codeigniter-restserverit is also available at Packagist.

-------

- I have just updated the development branch, and have re-included a base CI install.  I've gone back and forth on this but I've settled on including it moving forward.  **Note: Please DO NOT use the development branch right now...it totally doesn't work.**

- Over the last year or so, the amount of contributions has been GREAT.  I'm so happy that a lot of people are finding this library helpful.  That said, for a few reasons (which I will get into in a few bullets down), there has been code rot, a few sections of over complicated code, and bugs have snuck in.  This is pretty much my fault; and I apologies for letting the users of this lib down.

- I want to get "back to basics" with the 4.0.0 release.  So, there is going to be a LOT of cleaning; and some of the more complicated code sections will be TEMPORARILY removed; most have to do with authentication.  I'm constantly seeing bugs on these, and I really want to fix them...or even better...provide a few basic methods and then allow for a "plugin" type system (it *kinda* exists now, but I want to flesh it out).  The library cannot be everything to everyone, that just makes it hard (if not impossible) to maintain.  So, I want to follow standard practices for the "included" things and allow it to be expandable for everything else.

- Further library updates; a few have commented about me disappearing at times and the status of this.  So, as much as I don't like to discuss my personal life, I feel that in this case (for a few reasons) I want do.  The short version is that, like many developers I developed an anxiety disorder, and then when I was working a VERY stressful job, it "evolved" into full blow Panic Disorder; and for almost 2 years, 1 - 2 times per week, it sent me to the emergency room; both for not knowing what was going on...and the stress got so bad it caused episodes of aFib and SVT.  It crippled me, and I couldn't devote "extra time" to spend on this project (which made me VERY sad).  I'm on medication, I have a great doctor, and I am in therapy.  Things are better, and I am FULLY committed to this library. 

- Format.php has to go.  For the most part CI has a majority of these methods implemented, and really for an API we should be returning xml, JSON, or plain text.  So, a lot of those other things just need to go (looking at you html table). 

Well, I hope this helps people know where things are.  I hope to have 4.0.0 in an alpha state in the next few weeks.  I will keep this updated with progress.

**Comment by chriskacerguis** [comment]
[Update]: I did not mean to lock this issue.  Sorry about that.

**Comment by yudikondo** [comment]
HI @chriskacerguis im using this library and you make an great work. Count on us!

**Comment by searchy2** [comment]
Hi Chris, thank you for sharing details about your personal situation and remaining committed to this library. 
CodeIgniter 4 will hopefully be released this year so it's great we'll have a REST library ready. 
My biggest concern right now is performance and CodeIgniter seems add significant overhead but that's probably out of your control.
I'll be doing some performance benchmarks in the short term to help.

**Comment by chriskacerguis** [comment]
@searchy2 Yeah, that's one of the things that I am trying to work on with regards to the new 4.0 of the REST server.  I think that we have added too much, and it has become bloated.  For example, I think having the API key auth system is good, but I would like to see other auth systems as "drivers" for the library so they are added as needed vs. putting them in the lib itself.

**Comment by hudi1212** [comment]
hi chris, im using this library, but i have problem. The message : Class Example cannot extend from trait Restserver\Libraries\REST_Controller

**Comment by sierrafayad** [comment]
Please @hudi1212 open a new issue for that.

**Comment by cristaken** [comment]
Hi Guys,
Your work on this was excellent, it's a really great work.
Just one note, if you could do a tutorial o recient guide for newbies it would be great for massive use of this librarie.
Again, thank you for your work.

**Comment by luckydonald** [comment]
Regarding `Format.php`, getting custom code to work without overwriting your files was a pain in the past.
We have special requirements for the xml (basically indication the type of variable (int, str, bool,...) additionaly as attribute), which needs to be implemented.

Maybe we can find a good system for extending that with custom format and parse methods?

**Comment by Bliksempie** [comment]
Hi Chris. Thanks for your hard work on this. Any idea on whether you will do a CI 4 version of this? Or if not, any idea on what I can use as a base?

**Comment by chriskacerguis** [comment]
@Bliksempie to be honest, I don't know.  CI4 has REST resource handling built in (https://codeigniter.com/user_guide/incoming/restful.html) so I'm not sure the need of this lib anymore.  Thoughts?

**Comment by Bliksempie** [comment]
@chriskacerguis - in my opinion, a reduced layer of this could still be very useful, as I fail to see any tutorials that include authentication/token features, making me wonder (I have not investigated CI4 source yet for this) if it is present. If this is indeed present, and I am just not referencing the right tutorials, your comment makes perfect sense - why build this if already present in CI4 in full scope?
