### ISSUE TITLE
throw an Error in a future version of PHP

### ISSUE THREAD

**Issue by adityadees** [chriskacerguis/codeigniter-restserver#984]
why i got notice like this? 
![image](https://user-images.githubusercontent.com/37553901/53353652-cf0a2f80-3957-11e9-9ca6-0536faa5b6f2.png)
can u help me?

**Comment by Sveeeeeen** [comment]
Your line 113 should looks like this:

> $config['rest_auth'] = 'basic';

Right now your line looks like this:

> $config['rest_auth'] = basic;

**Comment by adityadees** [comment]
ok thanks working fine
