### ISSUE TITLE
Can i retrieve value of GET form data ? 

### ISSUE THREAD

**Issue by faisalbudiman** [chriskacerguis/codeigniter-restserver#987]
i'm testing api url with postman, then fill the form-data :

- the key is 'id'
- and the value is 5

i try this one :
`$data = $this->get('id');
        $this->response(array('id'=>$data));`

but the result still NULL
`{
    "id": null
}`

please help me

**Comment by ttquoccuong** [comment]
@faisalbudiman can you show up your client code?

**Comment by ttquoccuong** [comment]
@faisalbudiman you should try $this->input->get('id')
