### ISSUE TITLE
Parse error: syntax error

### ISSUE THREAD

**Issue by jchiheb** [chriskacerguis/codeigniter-restserver#989]
A PHP Error was encountered
Severity: Parsing Error

Message: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'

Filename: libraries/REST_Controller.php

Line Number: 835

Backtrace:

--------------------------------------------
my code -> REST_controller.php 
-------------------------------------------

        	// If data is not NULL and a HTTP status code provided, then continue
        	elseif ($data !== NULL)
        	{
            	// If the format method exists, call and return the output in that format
            	if (method_exists(Format::class, 'to_' . $this->response->format))
            	{
                	// Set the format header
                	$this->output->set_content_type($this->_supported_formats[$this->response->format], strtolower($this->config->item('charset')));
                	$output = Format::factory($data)->{'to_' . $this->response->format}();

                	// An array must be parsed as a string, so as not to cause an array to string error
                	// Json is the most appropriate form for such a data type
                	if ($this->response->format === 'array')
                	{
                    	$output = Format::factory($output)->{'to_json'}();
                	}
            	}
            	else
            	{
                	// If an array or object, then parse as a json, so as to be a 'string'
                	if (is_array($data) || is_object($data))
                	{
                    	$data = Format::factory($data)->{'to_json'}();
                	}

                	// Format is not supported, so output the raw data as a string
                	$output = $data;
            	}
        	}

[application.zip](https://github.com/chriskacerguis/codeigniter-restserver/files/3030990/application.zip)

**Comment by chriskacerguis** [comment]
Please try with the latest code and let me know if you are still having issues.
