### ISSUE TITLE
Make the Digest Authentication working

### ISSUE THREAD

**Issue by hongjones** [chriskacerguis/codeigniter-restserver#995]
In codeigniter-restserver/application/libraries/REST_Controller.php, the function _prepare_digest_auth(), update the line:

 $valid_response = md5($digest['username'].':'.$digest['nonce'].':'.$digest['nc'].':'.$digest['cnonce'].':'.$digest['qop'].':'.$md5);

to:
 $valid_response = md5($this->_check_login($digest['username'], TRUE).':'.$digest['nonce'].':'.$digest['nc'].':'.$digest['cnonce'].':'.$digest['qop'].':'.$md5);

because: with RFC 2069, the client encrypts the user name and password as follows.

response = MD5( HA1 : nonce:noncecount:cnonce:qop  : HA2)
where:
HA1 = MD5( username : realm : password)
HA2 = MD5( method : digestURI)

**Comment by chriskacerguis** [comment]
Feel free to submit a PR.
