### ISSUE TITLE
index_delete($id) "Unknown method."

### ISSUE THREAD

**Issue by KilianSillero** [chriskacerguis/codeigniter-restserver#998]
CodeIgniter Version: 2.2.6

```
class clientes extends Api{ // Api extends REST_Controller 
    public function index_delete($id)
    {
	$this->response([
		'returned from delete:' => $id,
	]);
    }
}
```
And I call this from Postman as a DELETE to this URL
`http://localhost/api/clientes/1`

But this returns me:
`{
    "status": false,
    "error": "Unknown method."
}`

And if I remove the "1" from the URL like this
`http://localhost/api/clientes`

It returns a php error saying:
Missing argument 1 for clientes::index_delete()

How can I call this method?
I now have `$this->delete('id');` and works but I want to pass the id in the URL

**Comment by chriskacerguis** [comment]
Closing.  Dup of https://github.com/chriskacerguis/codeigniter-restserver/issues/978
